This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file ./D3_7_0_fc3.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file D3_7_0_fc3.acn....done (23 entries accepted, 0 rejected).
Sorting entries....done (99 comparisons).
Generating output file D3_7_0_fc3.acr....done (24 lines written, 0 warnings).
Output written in D3_7_0_fc3.acr.
Transcript written in D3_7_0_fc3.alg.
