/* $*************** KCG Version 6.1.3 (build i6) ****************
** Command: s2c613 -config S:/SDVAL_RAMS/Förderprojekte/openETCS/modeling/model/Scade/System/ObuFunctions/ManageLocationRelatedInformation/MLRI_Integration/KCG\kcg_s2c_config.txt
** Generation date: 2014-12-12T12:03:54
*************************************************************$ */

#include "kcg_consts.h"

/* BG_Types_Pkg::cEmptyHeader */
const MLRI__TelegramHeader_T_BG_Types_Pkg MLRI__cEmptyHeader_BG_Types_Pkg = {
  MLRI__Q_UPDOWN_Down_link_telegram,
  MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
  MLRI__Q_MEDIA_Balise, MLRI__N_PIG_I_am_the_1st,
  MLRI__N_TOTAL_1_balise_in_the_group, MLRI__M_DUP_No_duplicates, 0, 0, 0,
  MLRI__Q_LINK_Unlinked };

/* BG_Types_Pkg::cEmptyBGMessage */
const MLRI__BG_Message_T_BG_Types_Pkg MLRI__cEmptyBGMessage_BG_Types_Pkg = {
  kcg_false, { { kcg_false, kcg_false, { MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_PIG_I_am_the_1st,
        MLRI__N_TOTAL_1_balise_in_the_group, MLRI__M_DUP_No_duplicates, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { { kcg_false, 0, MLRI__Q_DIR_Reverse,
            MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 } } } }, { kcg_false, kcg_false,
      { MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_PIG_I_am_the_1st,
        MLRI__N_TOTAL_1_balise_in_the_group, MLRI__M_DUP_No_duplicates, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { { kcg_false, 0, MLRI__Q_DIR_Reverse,
            MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 } } } }, { kcg_false, kcg_false,
      { MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_PIG_I_am_the_1st,
        MLRI__N_TOTAL_1_balise_in_the_group, MLRI__M_DUP_No_duplicates, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { { kcg_false, 0, MLRI__Q_DIR_Reverse,
            MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 } } } }, { kcg_false, kcg_false,
      { MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_PIG_I_am_the_1st,
        MLRI__N_TOTAL_1_balise_in_the_group, MLRI__M_DUP_No_duplicates, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { { kcg_false, 0, MLRI__Q_DIR_Reverse,
            MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 } } } }, { kcg_false, kcg_false,
      { MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_PIG_I_am_the_1st,
        MLRI__N_TOTAL_1_balise_in_the_group, MLRI__M_DUP_No_duplicates, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { { kcg_false, 0, MLRI__Q_DIR_Reverse,
            MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 } } } }, { kcg_false, kcg_false,
      { MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_PIG_I_am_the_1st,
        MLRI__N_TOTAL_1_balise_in_the_group, MLRI__M_DUP_No_duplicates, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { { kcg_false, 0, MLRI__Q_DIR_Reverse,
            MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 } } } }, { kcg_false, kcg_false,
      { MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_PIG_I_am_the_1st,
        MLRI__N_TOTAL_1_balise_in_the_group, MLRI__M_DUP_No_duplicates, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { { kcg_false, 0, MLRI__Q_DIR_Reverse,
            MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 } } } }, { kcg_false, kcg_false,
      { MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_PIG_I_am_the_1st,
        MLRI__N_TOTAL_1_balise_in_the_group, MLRI__M_DUP_No_duplicates, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { { kcg_false, 0, MLRI__Q_DIR_Reverse,
            MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
            MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
            MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
            0, 0,
            MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
            MLRI__Q_LINKREACTION_Train_trip, 0 } } } } }, 0, { { kcg_false, 0, {
        0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
      MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 } } };

/* BG_Types_Pkg::cAddInfo */
const MLRI__AdditionalInformation_T_BG_Types_Pkg MLRI__cAddInfo_BG_Types_Pkg = {
  { { kcg_false, 0, MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
      MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
      0, 0,
      MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
      MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse,
      MLRI__Q_SCALE_10_cm_scale, 0,
      MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
      0, 0,
      MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
      MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse,
      MLRI__Q_SCALE_10_cm_scale, 0,
      MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
      0, 0,
      MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
      MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse,
      MLRI__Q_SCALE_10_cm_scale, 0,
      MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
      0, 0,
      MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
      MLRI__Q_LINKREACTION_Train_trip, 0 } } };

/* CheckBGConsistency_Pkg::NoLinkedBG */
const MLRI__LinkedBG_T_BG_Types_Pkg MLRI__NoLinkedBG_CheckBGConsistency_Pkg = {
  kcg_false, 0, MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
  MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
  0, 0,
  MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
  MLRI__Q_LINKREACTION_Train_trip, 0 };

/* ProvidePositionReport_Pkg::cTrainPosition */
const MLRI__trainPosition_T_TrainPosition_Types_Pck MLRI__cTrainPosition_ProvidePositionReport_Pkg = {
  kcg_false, 0, kcg_false, kcg_false, { 0, 0, 0 }, 0, 0, 0, { kcg_false, 0, 0,
    MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, { 0, 0, 0 }, { 0,
        0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale,
        0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, {
          0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
        MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
        MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
      MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } }, { kcg_false, 0, 0,
    MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, { 0, 0, 0 }, { 0,
        0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale,
        0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, {
          0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
        MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
        MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
      MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } },
  MLRI__Q_DLRBG_Reverse, MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse,
  kcg_false };

/* BuildBGMessage_Pkg::cemptyStore */
const MLRI__TelegramStore_T_BuildBGMessage_Pkg MLRI__cemptyStore_BuildBGMessage_Pkg = {
  kcg_false, { kcg_false, kcg_false, { MLRI__Q_UPDOWN_Down_link_telegram,
      MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
      MLRI__Q_MEDIA_Balise, MLRI__N_PIG_I_am_the_1st,
      MLRI__N_TOTAL_1_balise_in_the_group, MLRI__M_DUP_No_duplicates, 0, 0, 0,
      MLRI__Q_LINK_Unlinked }, { { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } } } }, { { kcg_false, 0, { 0, 0,
        0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
      MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 } } };

/* BG_Types_Pkg::cemptyHeaderArray */
const MLRI__TelegramArray_T_BG_Types_Pkg MLRI__cemptyHeaderArray_BG_Types_Pkg = {
  { kcg_false, kcg_false, { MLRI__Q_UPDOWN_Down_link_telegram,
      MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
      MLRI__Q_MEDIA_Balise, MLRI__N_PIG_I_am_the_1st,
      MLRI__N_TOTAL_1_balise_in_the_group, MLRI__M_DUP_No_duplicates, 0, 0, 0,
      MLRI__Q_LINK_Unlinked }, { { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } } } }, { kcg_false, kcg_false, {
      MLRI__Q_UPDOWN_Down_link_telegram,
      MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
      MLRI__Q_MEDIA_Balise, MLRI__N_PIG_I_am_the_1st,
      MLRI__N_TOTAL_1_balise_in_the_group, MLRI__M_DUP_No_duplicates, 0, 0, 0,
      MLRI__Q_LINK_Unlinked }, { { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } } } }, { kcg_false, kcg_false, {
      MLRI__Q_UPDOWN_Down_link_telegram,
      MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
      MLRI__Q_MEDIA_Balise, MLRI__N_PIG_I_am_the_1st,
      MLRI__N_TOTAL_1_balise_in_the_group, MLRI__M_DUP_No_duplicates, 0, 0, 0,
      MLRI__Q_LINK_Unlinked }, { { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } } } }, { kcg_false, kcg_false, {
      MLRI__Q_UPDOWN_Down_link_telegram,
      MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
      MLRI__Q_MEDIA_Balise, MLRI__N_PIG_I_am_the_1st,
      MLRI__N_TOTAL_1_balise_in_the_group, MLRI__M_DUP_No_duplicates, 0, 0, 0,
      MLRI__Q_LINK_Unlinked }, { { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } } } }, { kcg_false, kcg_false, {
      MLRI__Q_UPDOWN_Down_link_telegram,
      MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
      MLRI__Q_MEDIA_Balise, MLRI__N_PIG_I_am_the_1st,
      MLRI__N_TOTAL_1_balise_in_the_group, MLRI__M_DUP_No_duplicates, 0, 0, 0,
      MLRI__Q_LINK_Unlinked }, { { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } } } }, { kcg_false, kcg_false, {
      MLRI__Q_UPDOWN_Down_link_telegram,
      MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
      MLRI__Q_MEDIA_Balise, MLRI__N_PIG_I_am_the_1st,
      MLRI__N_TOTAL_1_balise_in_the_group, MLRI__M_DUP_No_duplicates, 0, 0, 0,
      MLRI__Q_LINK_Unlinked }, { { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } } } }, { kcg_false, kcg_false, {
      MLRI__Q_UPDOWN_Down_link_telegram,
      MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
      MLRI__Q_MEDIA_Balise, MLRI__N_PIG_I_am_the_1st,
      MLRI__N_TOTAL_1_balise_in_the_group, MLRI__M_DUP_No_duplicates, 0, 0, 0,
      MLRI__Q_LINK_Unlinked }, { { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } } } }, { kcg_false, kcg_false, {
      MLRI__Q_UPDOWN_Down_link_telegram,
      MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
      MLRI__Q_MEDIA_Balise, MLRI__N_PIG_I_am_the_1st,
      MLRI__N_TOTAL_1_balise_in_the_group, MLRI__M_DUP_No_duplicates, 0, 0, 0,
      MLRI__Q_LINK_Unlinked }, { { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } } } } };

/* BuildBGMessage_Pkg::cCollectorInit */
const MLRI__BGCollector_T_BuildBGMessage_Pkg MLRI__cCollectorInit_BuildBGMessage_Pkg = {
  kcg_false, kcg_false, 0, 0, { { kcg_false, 0, { 0, 0, 0 }, 0, 0,
      MLRI__noMotion_Obu_BasicTypes_Pkg,
      MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 } }, { { kcg_false,
      0, { 0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
      MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 } }, 0, 0 };

/* BG_Types_Pkg::cMaxDistanceBalisesInGroup */
const MLRI__OdometryLocations_T_Obu_BasicTypes_Pkg MLRI__cMaxDistanceBalisesInGroup_BG_Types_Pkg = {
  1200, 1200, 1200 };

/* CheckBGConsistency_Pkg::NoStoredBG */
const MLRI__positionedBG_T_TrainPosition_Types_Pck MLRI__NoStoredBG_CheckBGConsistency_Pkg = {
  kcg_false, 0, 0, MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, {
      0, 0, 0 }, { 0, 0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse,
      MLRI__Q_SCALE_10_cm_scale, 0,
      MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
      0, 0,
      MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
      MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, { 0,
        0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
      MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
      MLRI__Q_UPDOWN_Down_link_telegram,
      MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
      MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
      MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
        MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
        MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
        MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
        MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
    MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } };

/* CheckBGConsistency_Pkg::NoPassedBG */
const MLRI__passedBG_T_BG_Types_Pkg MLRI__NoPassedBG_CheckBGConsistency_Pkg = {
  kcg_false, { kcg_false, 0, { 0, 0, 0 }, 0, 0,
    MLRI__noMotion_Obu_BasicTypes_Pkg,
    MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
    MLRI__Q_UPDOWN_Down_link_telegram,
    MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
    MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
    MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
      MLRI__Q_SCALE_10_cm_scale, 0,
      MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
      0, 0,
      MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
      MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse,
      MLRI__Q_SCALE_10_cm_scale, 0,
      MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
      0, 0,
      MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
      MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse,
      MLRI__Q_SCALE_10_cm_scale, 0,
      MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
      0, 0,
      MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
      MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse,
      MLRI__Q_SCALE_10_cm_scale, 0,
      MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
      0, 0,
      MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
      MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
  MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse };

/* CheckBGConsistency_Pkg::InConsistentTelegram1 */
const MLRI__Telegram_T_BG_Types_Pkg MLRI__InConsistentTelegram1_CheckBGConsistency_Pkg = {
  kcg_false, kcg_false, { MLRI__Q_UPDOWN_Down_link_telegram,
    MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
    MLRI__Q_MEDIA_Balise, MLRI__N_PIG_I_am_the_1st,
    MLRI__N_TOTAL_1_balise_in_the_group, MLRI__M_DUP_No_duplicates, 0, 0, 0,
    MLRI__Q_LINK_Unlinked }, { { { kcg_false, 0, MLRI__Q_DIR_Reverse,
        MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
        MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
        MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
        MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } } } };

/* BG_Types_Pkg::cemptyPosition */
const MLRI__centerOfBalisePosition_T_BG_Types_Pkg MLRI__cemptyPosition_BG_Types_Pkg = {
  { kcg_false, 0, { 0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
    MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 } };

/* BG_Types_Pkg::cEmpty_BaliseTlg */
const MLRI__Telegram_T_BG_Types_Pkg MLRI__cEmpty_BaliseTlg_BG_Types_Pkg = {
  kcg_false, kcg_false, { MLRI__Q_UPDOWN_Down_link_telegram,
    MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
    MLRI__Q_MEDIA_Balise, MLRI__N_PIG_I_am_the_1st,
    MLRI__N_TOTAL_1_balise_in_the_group, MLRI__M_DUP_No_duplicates, 0, 0, 0,
    MLRI__Q_LINK_Unlinked }, { { { kcg_false, 0, MLRI__Q_DIR_Reverse,
        MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
        MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
        MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
        MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } } } };

/* BG_Types_Pkg::cEmptyPassedBG */
const MLRI__passedBG_T_BG_Types_Pkg MLRI__cEmptyPassedBG_BG_Types_Pkg = {
  kcg_false, { kcg_false, 0, { 0, 0, 0 }, 0, 0,
    MLRI__noMotion_Obu_BasicTypes_Pkg,
    MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
    MLRI__Q_UPDOWN_Down_link_telegram,
    MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
    MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
    MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
      MLRI__Q_SCALE_10_cm_scale, 0,
      MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
      0, 0,
      MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
      MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse,
      MLRI__Q_SCALE_10_cm_scale, 0,
      MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
      0, 0,
      MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
      MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse,
      MLRI__Q_SCALE_10_cm_scale, 0,
      MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
      0, 0,
      MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
      MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse,
      MLRI__Q_SCALE_10_cm_scale, 0,
      MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
      0, 0,
      MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
      MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
  MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse };

/* TrainPosition_Integration_Pkg::cNoTrainPosInfo */
const MLRI__trainPositionInfo_T_TrainPosition_Types_Pck MLRI__cNoTrainPosInfo_TrainPosition_Integration_Pkg = {
  kcg_false, 0, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { kcg_false, 0, 0,
    MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, { 0, 0, 0 }, { 0,
        0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale,
        0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, {
          0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
        MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
        MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
      MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } }, { kcg_false, 0, 0,
    MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, { 0, 0, 0 }, { 0,
        0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale,
        0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, {
          0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
        MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
        MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
      MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } }, 0 };

/* CalculateTrainPosition_Pkg::cNoPositionErrors */
const MLRI__positionErrors_T_TrainPosition_Types_Pck MLRI__cNoPositionErrors_CalculateTrainPosition_Pkg = {
  kcg_false, kcg_false, kcg_false, kcg_false, kcg_false, kcg_false };

/* CalculateTrainPosition_Pkg::BG_relocation_Pkg::cNoRefPrevBGs */
const MLRI__refBGs_T_CalculateTrainPosition_Pkg_BG_relocation_Pkg MLRI__cNoRefPrevBGs_CalculateTrainPosition_Pkg_BG_relocation_Pkg = {
  { kcg_false, 0, 0, MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, {
        0, 0, 0 }, { 0, 0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse,
        MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, {
          0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
        MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
        MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
      MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } }, { kcg_false, 0, 0,
    MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, { 0, 0, 0 }, { 0,
        0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale,
        0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, {
          0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
        MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
        MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
      MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } }, { kcg_false, 0, 0,
    MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, { 0, 0, 0 }, { 0,
        0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale,
        0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, {
          0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
        MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
        MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
      MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } }, kcg_false, { 0, 0,
    0 } };

/* CalculateTrainPosition_Pkg::BG_relocation_Pkg::cNoLinkedBG_index */
const MLRI__linkedBG_index_T_CalculateTrainPosition_Pkg_BG_relocation_Pkg MLRI__cNoLinkedBG_index_CalculateTrainPosition_Pkg_BG_relocation_Pkg = {
  MLRI__noValidIndex_CalculateTrainPosition_Pkg_gp_functions_Pkg, - 1,
  MLRI__noValidIndex_CalculateTrainPosition_Pkg_gp_functions_Pkg };

/* CalculateTrainPosition_Pkg::cNoPassedBG */
const MLRI__passedBG_T_BG_Types_Pkg MLRI__cNoPassedBG_CalculateTrainPosition_Pkg = {
  kcg_false, { kcg_false, 0, { 0, 0, 0 }, 0, 0,
    MLRI__noMotion_Obu_BasicTypes_Pkg,
    MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
    MLRI__Q_UPDOWN_Down_link_telegram,
    MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
    MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
    MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
      MLRI__Q_SCALE_10_cm_scale, 0,
      MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
      0, 0,
      MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
      MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse,
      MLRI__Q_SCALE_10_cm_scale, 0,
      MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
      0, 0,
      MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
      MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse,
      MLRI__Q_SCALE_10_cm_scale, 0,
      MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
      0, 0,
      MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
      MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse,
      MLRI__Q_SCALE_10_cm_scale, 0,
      MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
      0, 0,
      MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
      MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
  MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse };

/* Obu_BasicTypes_Pkg::cLocWithInAcc_0 */
const MLRI__LocWithInAcc_T_Obu_BasicTypes_Pkg MLRI__cLocWithInAcc_0_Obu_BasicTypes_Pkg = {
  0, 0, 0 };

/* CalculateTrainPosition_Pkg::cNoInfoFromLinking */
const MLRI__infoFromLinking_T_TrainPosition_Types_Pck MLRI__cNoInfoFromLinking_CalculateTrainPosition_Pkg = {
  kcg_false, 0, 0, { 0, 0, 0 }, { 0, 0, 0 }, { kcg_false, 0,
    MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
    MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
    0, 0,
    MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
    MLRI__Q_LINKREACTION_Train_trip, 0 } };

/* CalculateTrainPosition_Pkg::Pos_Pkg::cOdometryStartVal */
const MLRI__odometry_T_Obu_BasicTypes_Pkg MLRI__cOdometryStartVal_CalculateTrainPosition_Pkg_Pos_Pkg = {
  kcg_false, 0, { 0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
  MLRI__unknownDirection_Obu_BasicTypes_Pkg };

/* Obu_BasicTypes_Pkg::cOdometryInitialValue */
const MLRI__OdometryLocations_T_Obu_BasicTypes_Pkg MLRI__cOdometryInitialValue_Obu_BasicTypes_Pkg = {
  0, 0, 0 };

/* CalculateTrainPosition_Pkg::BG_utilities_Pkg::cEmptyPositionedBG */
const MLRI__positionedBG_T_TrainPosition_Types_Pck MLRI__cEmptyPositionedBG_CalculateTrainPosition_Pkg_BG_utilities_Pkg = {
  kcg_false, 0, 0, MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, {
      0, 0, 0 }, { 0, 0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse,
      MLRI__Q_SCALE_10_cm_scale, 0,
      MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
      0, 0,
      MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
      MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, { 0,
        0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
      MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
      MLRI__Q_UPDOWN_Down_link_telegram,
      MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
      MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
      MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
        MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
        MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
        MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
        MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
    MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } };

/* CalculateTrainPosition_Pkg::cNoPositionedBG */
const MLRI__positionedBG_T_TrainPosition_Types_Pck MLRI__cNoPositionedBG_CalculateTrainPosition_Pkg = {
  kcg_false, 0, 0, MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, {
      0, 0, 0 }, { 0, 0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse,
      MLRI__Q_SCALE_10_cm_scale, 0,
      MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
      0, 0,
      MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
      MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, { 0,
        0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
      MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
      MLRI__Q_UPDOWN_Down_link_telegram,
      MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
      MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
      MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
        MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
        MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
        MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
        MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
    MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } };

/* CalculateTrainPosition_Pkg::BG_utilities_Pkg::cBGCounters_0 */
const MLRI__BG_counters_T_CalculateTrainPosition_Pkg_BG_utilities_Pkg MLRI__cBGCounters_0_CalculateTrainPosition_Pkg_BG_utilities_Pkg = {
  0, 0, 0, 0, 0, 0 };

/* CalculateTrainPosition_Pkg::BG_utilities_Pkg::cBG_find_0 */
const MLRI__BG_find_T_CalculateTrainPosition_Pkg_BG_utilities_Pkg MLRI__cBG_find_0_CalculateTrainPosition_Pkg_BG_utilities_Pkg = {
  MLRI__cNoValidIndex_CalculateTrainPosition_Pkg, 0, kcg_false };

/* ProvidePositionReport_Pkg::cErrorMessage */
const MLRI__ErrorMessage_T_ProvidePositionReport_Pkg MLRI__cErrorMessage_ProvidePositionReport_Pkg = {
  kcg_false, MLRI__M_ERROR_Balise_group_linking_consistency_error };

/* ProvidePositionReport_Pkg::cTrainPosInfo */
const MLRI__trainPositionInfo_T_TrainPosition_Types_Pck MLRI__cTrainPosInfo_ProvidePositionReport_Pkg = {
  kcg_false, 0, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { kcg_false, 0, 0,
    MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, { 0, 0, 0 }, { 0,
        0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale,
        0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, {
          0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
        MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
        MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
      MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } }, { kcg_false, 0, 0,
    MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, { 0, 0, 0 }, { 0,
        0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale,
        0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, {
          0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
        MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
        MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
      MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } }, 0 };

/* ProvidePositionReport_Pkg::cTrack2TrainStatus */
const MLRI__TrainToTrackStatus_T_BG_Types_Pkg MLRI__cTrack2TrainStatus_ProvidePositionReport_Pkg = {
  MLRI__M_MODE_Full_Supervision, MLRI__M_LEVEL_Level_0, MLRI__M_LEVELTR_Level_0,
  0, MLRI__Q_LENGTH_No_train_integrity_information_available };

/* ProvidePositionReport_Pkg::cPresentxM_LOC */
const MLRI__PresentxMLOC_T_ProvidePositionReport_Pkg MLRI__cPresentxM_LOC_ProvidePositionReport_Pkg = {
  kcg_false, MLRI__M_LOC_Now };

/* ProvidePositionReport_Pkg::cNITER_List */
const MLRI__IterPacket58List_T_ProvidePositionReport_Pkg MLRI__cNITER_List_ProvidePositionReport_Pkg = {
  { 0, MLRI__Q_LGTLOC_Min_safe_rear_end }, { 0,
    MLRI__Q_LGTLOC_Min_safe_rear_end } };

/* ProvidePositionReport_Pkg::cNITER_Pair */
const MLRI__IterPacket58_T_ProvidePositionReport_Pkg MLRI__cNITER_Pair_ProvidePositionReport_Pkg = {
  0, MLRI__Q_LGTLOC_Min_safe_rear_end };

/* ProvidePositionReport_Pkg::cPassedBG */
const MLRI__positionedBG_T_TrainPosition_Types_Pck MLRI__cPassedBG_ProvidePositionReport_Pkg = {
  kcg_false, 0, 0, MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, {
      0, 0, 0 }, { 0, 0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse,
      MLRI__Q_SCALE_10_cm_scale, 0,
      MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
      0, 0,
      MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
      MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, { 0,
        0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
      MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
      MLRI__Q_UPDOWN_Down_link_telegram,
      MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
      MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
      MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
        MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
        MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
        MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
        MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
    MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } };

/* CalculateTrainPosition_Pkg::cTrainPosition_0 */
const MLRI__trainPosition_T_TrainPosition_Types_Pck MLRI__cTrainPosition_0_CalculateTrainPosition_Pkg = {
  kcg_false, 0, kcg_false, kcg_false, { 0, 0, 0 }, 0, 0, 0, { kcg_false, 0, 0,
    MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, { 0, 0, 0 }, { 0,
        0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale,
        0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, {
          0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
        MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
        MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
      MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } }, { kcg_false, 0, 0,
    MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, { 0, 0, 0 }, { 0,
        0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale,
        0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, {
          0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
        MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
        MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
      MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } },
  MLRI__Q_DLRBG_Reverse, MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse,
  kcg_false };

/* CalculateTrainPosition_Pkg::cNoPositionedBGs */
const MLRI__positionedBGs_T_TrainPosition_Types_Pck MLRI__cNoPositionedBGs_CalculateTrainPosition_Pkg = {
  { kcg_false, 0, 0, MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, {
        0, 0, 0 }, { 0, 0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse,
        MLRI__Q_SCALE_10_cm_scale, 0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, {
          0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
        MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
        MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
      MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } }, { kcg_false, 0, 0,
    MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, { 0, 0, 0 }, { 0,
        0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale,
        0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, {
          0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
        MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
        MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
      MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } }, { kcg_false, 0, 0,
    MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, { 0, 0, 0 }, { 0,
        0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale,
        0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, {
          0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
        MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
        MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
      MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } }, { kcg_false, 0, 0,
    MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, { 0, 0, 0 }, { 0,
        0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale,
        0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, {
          0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
        MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
        MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
      MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } }, { kcg_false, 0, 0,
    MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, { 0, 0, 0 }, { 0,
        0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale,
        0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, {
          0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
        MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
        MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
      MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } }, { kcg_false, 0, 0,
    MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, { 0, 0, 0 }, { 0,
        0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale,
        0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, {
          0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
        MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
        MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
      MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } }, { kcg_false, 0, 0,
    MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, { 0, 0, 0 }, { 0,
        0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale,
        0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, {
          0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
        MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
        MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
      MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } }, { kcg_false, 0, 0,
    MLRI__Q_LINK_Unlinked, { 0, 0, 0 }, 0, { kcg_false, 0, 0, { 0, 0, 0 }, { 0,
        0, 0 }, { kcg_false, 0, MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale,
        0,
        MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
        0, 0,
        MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
        MLRI__Q_LINKREACTION_Train_trip, 0 } }, { kcg_false, { kcg_false, 0, {
          0, 0, 0 }, 0, 0, MLRI__noMotion_Obu_BasicTypes_Pkg,
        MLRI__unknownDirection_Obu_BasicTypes_Pkg }, { 0, 0, 0 }, 0, {
        MLRI__Q_UPDOWN_Down_link_telegram,
        MLRI__M_VERSION_Previous_versions_according_to_e_g_EEIG_SRS_and_UIC_A200_SRS,
        MLRI__Q_MEDIA_Balise, MLRI__N_TOTAL_1_balise_in_the_group, 0, 0, 0,
        MLRI__Q_LINK_Unlinked }, { { kcg_false, 0, MLRI__Q_DIR_Reverse,
          MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 }, { kcg_false, 0,
          MLRI__Q_DIR_Reverse, MLRI__Q_SCALE_10_cm_scale, 0,
          MLRI__Q_NEWCOUNTRY_Same_country__or__railway_administration_no_NID_C_follows,
          0, 0,
          MLRI__Q_LINKORIENTATION_The_balise_group_is_seen_by_the_train_in_reverse_direction,
          MLRI__Q_LINKREACTION_Train_trip, 0 } }, kcg_false,
      MLRI__Q_DIRLRBG_Reverse, MLRI__Q_DIRTRAIN_Reverse } } };

/* $*************** KCG Version 6.1.3 (build i6) ****************
** kcg_consts.c
** Generation date: 2014-12-12T12:03:54
*************************************************************$ */

