/*********************************************************
 **
 ** File  aol_color_table.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:26:47
 ** Command line: C:\Program Files (x86)\Esterel Technologies\SCADE R17.2\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sct
 *********************************************************/

#ifndef _AOL_COLOR_TABLE_H
#define _AOL_COLOR_TABLE_H

#include "sgl_types.h"

/* Color table definition */
extern const sgl_color aol_color_table[16UL];

extern SGLint32 aol_color_table_size;

extern SGLint32 aol_color_table_background_index;

#endif /* _AOL_COLOR_TABLE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:26:47
 *********************************************************/

