/*********************************************************
 **
 ** File  aol_B.h
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\B\B.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_B_H
#define _AOL_B_H

#include "sgl_types.h"

#include "aol_CircularSpeedGauge.h"
#include "aol_ModeSymbols.h"

/* Accessors */
#define aol_B_G_TrainSpeed(_C_) (_C_)->TrainSpeed
#define aol_B_S_TrainSpeed(_C_,_V_) (_C_)->TrainSpeed = (_V_)
#define aol_B_G_PointerColor(_C_) (_C_)->PointerColor
#define aol_B_S_PointerColor(_C_,_V_) (_C_)->PointerColor = (_V_)
#define aol_B_G_SpeedDigitOne(_C_) (_C_)->SpeedDigitOne
#define aol_B_S_SpeedDigitOne(_C_,_V_) (_C_)->SpeedDigitOne = (_V_)
#define aol_B_G_SpeedDigitTwo(_C_) (_C_)->SpeedDigitTwo
#define aol_B_S_SpeedDigitTwo(_C_,_V_) (_C_)->SpeedDigitTwo = (_V_)
#define aol_B_G_SpeedDigitThree(_C_) (_C_)->SpeedDigitThree
#define aol_B_S_SpeedDigitThree(_C_,_V_) (_C_)->SpeedDigitThree = (_V_)
#define aol_B_G_Vperm(_C_) (_C_)->Vperm
#define aol_B_S_Vperm(_C_,_V_) (_C_)->Vperm = (_V_)
#define aol_B_G_Vtarget(_C_) (_C_)->Vtarget
#define aol_B_S_Vtarget(_C_,_V_) (_C_)->Vtarget = (_V_)
#define aol_B_G_Vrelease(_C_) (_C_)->Vrelease
#define aol_B_S_Vrelease(_C_,_V_) (_C_)->Vrelease = (_V_)
#define aol_B_G_VpermColor(_C_) (_C_)->VpermColor
#define aol_B_S_VpermColor(_C_,_V_) (_C_)->VpermColor = (_V_)
#define aol_B_G_VtargetColor(_C_) (_C_)->VtargetColor
#define aol_B_S_VtargetColor(_C_,_V_) (_C_)->VtargetColor = (_V_)
#define aol_B_G_VreleaseColor(_C_) (_C_)->VreleaseColor
#define aol_B_S_VreleaseColor(_C_,_V_) (_C_)->VreleaseColor = (_V_)
#define aol_B_G_ModeSymbol(_C_) (_C_)->ModeSymbol
#define aol_B_S_ModeSymbol(_C_,_V_) (_C_)->ModeSymbol = (_V_)
#define aol_B_G_ModeSymbolVisibility(_C_) (_C_)->ModeSymbolVisibility
#define aol_B_S_ModeSymbolVisibility(_C_,_V_) (_C_)->ModeSymbolVisibility = (_V_)
#define aol_B_G_Vtarget_permVisible(_C_) (_C_)->Vtarget_permVisible
#define aol_B_S_Vtarget_permVisible(_C_,_V_) (_C_)->Vtarget_permVisible = (_V_)
#define aol_B_G_Vtarget_permColor(_C_) (_C_)->Vtarget_permColor
#define aol_B_S_Vtarget_permColor(_C_,_V_) (_C_)->Vtarget_permColor = (_V_)
#define aol_B_G_Vinterv(_C_) (_C_)->Vinterv
#define aol_B_S_Vinterv(_C_,_V_) (_C_)->Vinterv = (_V_)
#define aol_B_G_VintervColor(_C_) (_C_)->VintervColor
#define aol_B_S_VintervColor(_C_,_V_) (_C_)->VintervColor = (_V_)
#define aol_B_G_VintervVisible(_C_) (_C_)->VintervVisible
#define aol_B_S_VintervVisible(_C_,_V_) (_C_)->VintervVisible = (_V_)
#define aol_B_G_OverB(_C_) (_C_)->OverB
#define aol_B_S_OverB(_C_,_V_) (_C_)->OverB = (_V_)
#define aol_B_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct aol_typ_B_ {
  /* ------------------------- inputs --------------------------- */
  SGLfloat TrainSpeed;
  SGLint32 PointerColor;
  SGLfloat SpeedDigitOne;
  SGLfloat SpeedDigitTwo;
  SGLfloat SpeedDigitThree;
  SGLfloat Vperm;
  SGLfloat Vtarget;
  SGLfloat Vrelease;
  SGLint32 VpermColor;
  SGLint32 VtargetColor;
  SGLint32 VreleaseColor;
  SGLint32 ModeSymbol;
  SGLbool ModeSymbolVisibility;
  SGLbool Vtarget_permVisible;
  SGLint32 Vtarget_permColor;
  SGLfloat Vinterv;
  SGLint32 VintervColor;
  SGLbool VintervVisible;
  /* ------------------------- outputs -------------------------- */
  SGLbool OverB;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} aol_typ_B;

/* Associated functions */
extern void aol_B_init(aol_typ_B *pContext);
extern void aol_B_predraw(aol_typ_B *pContext);
extern void aol_B_draw(aol_typ_B *pContext, SGLint32 pPriority);

#endif /* _AOL_B_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

