/*********************************************************
 **
 ** File  aol_LevelSymbols.c
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\Symbols\LevelSymbols.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#include "aol_LevelSymbols.h"
#include "aol_imported_functions.h"
#include "sgl.h"


void aol_LevelSymbols_init(aol_typ_LevelSymbols *pContext)
{
  aol_LevelSymbols_S_LevelSymbol(pContext, 0L);

  pContext->_parentPriority = 0L;

}

void aol_LevelSymbols_predraw(aol_typ_LevelSymbols *pContext)
{

}

void aol_LevelSymbols_draw(aol_typ_LevelSymbols *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: conditional_group, Type: conditional, OID: 7cc6aee9-820c-4a0d-b2cd-eca04e4e4039 */
    {
      sglPushMatrixAndTranslate(3.0F, 0.0F);
      switch (aol_LevelSymbols_G_LevelSymbol(pContext)) {

      case 1L:

        /* Object: LE01, Type: container, OID: 42e826ff-4062-4db9-a3dc-3408588dd0db */
        {

          /* Object: Level0, Type: container, OID: 9dc0ab29-ea66-4a28-9062-fbf3fa905c04 */
          {
            sglPushMatrixAndTranslate(-3.0F, 0.0F);

            /* Object: rectangle, Type: rectangle, OID: 8fcb7393-2d7e-4cf1-9cf1-43967c1d920a */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexColori(3L);
              sglIndexHaloColori(-1L);
              sglIndexLineWidthi(1L);
              sglIndexLineStipplei(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINE_LOOP);
              sglVertex2f(-24.0F, -1.0F);
              sglVertex2f(24.0F, -1.0F);
              sglVertex2f(24.0F, -9.0F);
              sglVertex2f(-24.0F, -9.0F);
              sglEnd();
            }

            /* Object: text, Type: text, OID: 51e1a8c4-939b-4dd4-b7bd-8813c1e23f6f */
            {
              static SGLuint8 _lArray0_text[255UL] = {48U};
              sglIndexFontLineWidthi(3L);
              sglIndexFonti(0L);
              sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
              sgluWriteText(0.0F, 6.0F, _lArray0_text, 255L);
            }
            sglPopMatrixAndTranslate();
          }
        }
        break;

      case 2L:

        /* Object: LE02, Type: container, OID: 42c4fd80-71e0-4736-a792-2bc4953b41be */
        {

          /* Object: LevelNTC, Type: container, OID: df6fcb99-e8dc-4161-8e67-cb3753c75e09 */
          {

            /* Object: rectangle_1, Type: rectangle, OID: 4c4267a3-afea-4233-9e85-3cefe51f1cae */
            {
              /* filled object part */
              sglIndexColori(3L);
              sglDisable(SGL_MODULATE);
              sglEnable(SGL_POLYGON_SMOOTH);
              sglTransparency8(255L);
              sglDisable(SGL_TEXTURE_2D);
              sglDisable(SGL_TESSELLATION);
              sglBegin(SGL_POLYGON);
              sglVertex2f(-25.0F, -8.0F);
              sglVertex2f(25.0F, -8.0F);
              sglVertex2f(25.0F, -3.0F);
              sglVertex2f(-25.0F, -3.0F);
              sglEnd();
            }

            /* Object: text_1, Type: text, OID: d3fd3661-66a7-49ef-b003-b95b844953b7 */
            {
              static SGLuint8 _lArray0_text_1[255UL] = {83U,84U,77U,32U,65U,84U,66U};
              sglIndexHaloColori(-1L);
              sglIndexFontLineWidthi(2L);
              sglIndexFonti(13L);
              sglDisable(SGL_LINE_HALOING);
              sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
              sgluWriteText(0.0F, 6.0F, _lArray0_text_1, 255L);
            }
          }
        }
        break;

      case 3L:

        /* Object: LE03, Type: container, OID: 83981ff1-6534-4aeb-ba7c-99dd5a6d0b04 */
        {

          /* Object: Level1IntermittetTransmission, Type: container, OID: 99a98105-080a-43a3-9e7c-10598d31c258 */
          {

            /* Object: group, Type: container, OID: 21c35887-55d1-4327-8381-8cbfab155eb1 */
            {
              sglPushMatrix();
              sglScalef(0.9F, 0.8F);

              /* Object: text_2, Type: text, OID: 0cfa67de-c5a0-4633-97d7-bb65c541acab */
              {
                static SGLuint8 _lArray0_text_2[255UL] = {49U};
                sglIndexColori(3L);
                sglIndexHaloColori(-1L);
                sglIndexFontLineWidthi(3L);
                sglIndexFonti(0L);
                sglDisable(SGL_LINE_HALOING);
                sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                sgluWriteText(0.0F, 6.0F, _lArray0_text_2, 255L);
              }
              sglPopMatrix();
            }

            /* Object: rectangle_2, Type: rectangle, OID: 6ce632b7-a1b4-4a19-a4f3-79d107544c3a */
            {
              /* filled object part */
              sglDisable(SGL_MODULATE);
              sglEnable(SGL_POLYGON_SMOOTH);
              sglTransparency8(255L);
              sglDisable(SGL_TEXTURE_2D);
              sglDisable(SGL_TESSELLATION);
              sglBegin(SGL_POLYGON);
              sglVertex2f(-23.0F, -10.0F);
              sglVertex2f(-16.0F, -10.0F);
              sglVertex2f(-16.0F, -3.0F);
              sglVertex2f(-23.0F, -3.0F);
              sglEnd();
            }

            /* Object: rectangle_3, Type: rectangle, OID: 79aa6ce4-920d-4f8d-97f4-eb75335ede33 */
            {
              /* filled object part */
              sglBegin(SGL_POLYGON);
              sglVertex2f(-10.0F, -10.0F);
              sglVertex2f(-3.0F, -10.0F);
              sglVertex2f(-3.0F, -3.0F);
              sglVertex2f(-10.0F, -3.0F);
              sglEnd();
            }

            /* Object: rectangle_4, Type: rectangle, OID: 6c30e5d3-6800-4296-8466-ac22897008f4 */
            {
              /* filled object part */
              sglBegin(SGL_POLYGON);
              sglVertex2f(3.0F, -10.0F);
              sglVertex2f(10.0F, -10.0F);
              sglVertex2f(10.0F, -3.0F);
              sglVertex2f(3.0F, -3.0F);
              sglEnd();
            }

            /* Object: rectangle_5, Type: rectangle, OID: 2008c0b0-3e4f-4f69-863e-4ebb5be50295 */
            {
              /* filled object part */
              sglBegin(SGL_POLYGON);
              sglVertex2f(16.0F, -10.0F);
              sglVertex2f(23.0F, -10.0F);
              sglVertex2f(23.0F, -3.0F);
              sglVertex2f(16.0F, -3.0F);
              sglEnd();
            }
          }
        }
        break;

      case 4L:

        /* Object: LE04, Type: container, OID: 9843f406-09e9-4d4b-9cc7-644e4f6046b2 */
        {

          /* Object: Level2ContinousTransmission, Type: container, OID: 36b721c0-a19a-490d-a127-d66dcbd74a03 */
          {

            /* Object: rectangle_6, Type: rectangle, OID: e961a1e8-52ca-4671-921f-d97997bc5534 */
            {
              /* filled object part */
              sglIndexColori(3L);
              sglDisable(SGL_MODULATE);
              sglEnable(SGL_POLYGON_SMOOTH);
              sglTransparency8(255L);
              sglDisable(SGL_TEXTURE_2D);
              sglDisable(SGL_TESSELLATION);
              sglBegin(SGL_POLYGON);
              sglVertex2f(-25.0F, -8.0F);
              sglVertex2f(25.0F, -8.0F);
              sglVertex2f(25.0F, -3.0F);
              sglVertex2f(-25.0F, -3.0F);
              sglEnd();
            }

            /* Object: text_3, Type: text, OID: eb820079-6ff7-43f0-b9e5-40df68604063 */
            {
              static SGLuint8 _lArray0_text_3[255UL] = {50U};
              sglIndexHaloColori(-1L);
              sglIndexFontLineWidthi(2L);
              sglIndexFonti(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
              sgluWriteText(0.0F, 6.0F, _lArray0_text_3, 255L);
            }
          }
        }
        break;

      case 5L:

        /* Object: LE05, Type: container, OID: 339f5c61-da63-45de-91d8-69ee981efdbe */
        {

          /* Object: Level3ContiousTransmission, Type: container, OID: 09de918b-48a8-4d87-b71b-f182b77bc43a */
          {

            /* Object: rectangle_7, Type: rectangle, OID: 29a33bdc-eedd-4986-b5e0-a48ba2c22cc8 */
            {
              /* filled object part */
              sglIndexColori(3L);
              sglDisable(SGL_MODULATE);
              sglEnable(SGL_POLYGON_SMOOTH);
              sglTransparency8(255L);
              sglDisable(SGL_TEXTURE_2D);
              sglDisable(SGL_TESSELLATION);
              sglBegin(SGL_POLYGON);
              sglVertex2f(-25.0F, -8.0F);
              sglVertex2f(25.0F, -8.0F);
              sglVertex2f(25.0F, -3.0F);
              sglVertex2f(-25.0F, -3.0F);
              sglEnd();
            }

            /* Object: text_4, Type: text, OID: 00508682-9723-4a4a-a5c3-2e3a26c1206f */
            {
              static SGLuint8 _lArray0_text_4[255UL] = {51U};
              sglIndexHaloColori(-1L);
              sglIndexFontLineWidthi(3L);
              sglIndexFonti(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
              sgluWriteText(0.0F, 6.0F, _lArray0_text_4, 255L);
            }
          }
        }
        break;

      case 6L:

        /* Object: LE06, Type: container, OID: 7526e589-d3b7-4106-8e55-85c59f9f2e08 */
        {

          /* Object: Level0AnnouncementGrey, Type: container, OID: a749f507-08fa-4c50-9602-173801e2a918 */
          {

            /* Object: text_5, Type: text, OID: c2cc40d8-c534-48a3-be81-c44367a4df5f */
            {
              static SGLuint8 _lArray0_text_5[255UL] = {48U};
              sglIndexColori(3L);
              sglIndexHaloColori(-1L);
              sglIndexFontLineWidthi(3L);
              sglIndexFonti(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
              sgluWriteText(21.0F, 6.0F, _lArray0_text_5, 255L);
            }

            /* Object: rectangle_8, Type: rectangle, OID: 081d1344-6b03-406a-ba6a-185df3140e66 */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexLineWidthi(1L);
              sglIndexLineStipplei(0L);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINE_LOOP);
              sglVertex2f(-25.0F, -9.0F);
              sglVertex2f(25.0F, -9.0F);
              sglVertex2f(25.0F, -3.0F);
              sglVertex2f(-25.0F, -3.0F);
              sglEnd();
            }

            /* Object: line, Type: line, OID: 760c535b-ba07-4e48-bdf5-7967ef6bb1ec */
            {
              /* outlined object part */
              sglIndexLineWidthi(3L);
              sglBegin(SGL_LINES);
              sglVertex2f(0.0F, 7.0F);
              sglVertex2f(-25.0F, 7.0F);
              sglEnd();
            }

            /* Object: shape, Type: shape, OID: f21f0dd5-f269-4ece-acfd-d1df5cf970ab */
            {
              /* filled object part */
              sglDisable(SGL_MODULATE);
              sglEnable(SGL_POLYGON_SMOOTH);
              sglDisable(SGL_TESSELLATION);
              sglBegin(SGL_POLYGON);
              sglVertex2f(0.0F, 12.0F);
              sglVertex2f(0.0F, 2.0F);
              sglVertex2f(5.0F, 7.0F);
              sglEnd();
              /* outlined object part */
              sglIndexLineWidthi(0L);
              sglBegin(SGL_LINE_LOOP);
              sglVertex2f(0.0F, 12.0F);
              sglVertex2f(0.0F, 2.0F);
              sglVertex2f(5.0F, 7.0F);
              sglEnd();
            }
          }
        }
        break;

      case 7L:

        /* Object: LE07, Type: container, OID: 79cff450-04cc-45ea-af83-82612b191102 */
        {

          /* Object: Level0AnnouncementYellow, Type: container, OID: ab0a8d57-9a7a-4dc6-853f-65e571498c62 */
          {

            /* Object: text_6, Type: text, OID: 74c1e131-304f-4fa4-80dc-fd518f13c645 */
            {
              static SGLuint8 _lArray0_text_6[255UL] = {48U};
              sglIndexColori(8L);
              sglIndexHaloColori(-1L);
              sglIndexFontLineWidthi(3L);
              sglIndexFonti(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
              sgluWriteText(21.0F, 6.0F, _lArray0_text_6, 255L);
            }

            /* Object: rectangle_9, Type: rectangle, OID: 77f701a8-d8a4-47f1-b67b-f92b8b48df9a */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexLineWidthi(1L);
              sglIndexLineStipplei(0L);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINE_LOOP);
              sglVertex2f(-25.0F, -9.0F);
              sglVertex2f(25.0F, -9.0F);
              sglVertex2f(25.0F, -3.0F);
              sglVertex2f(-25.0F, -3.0F);
              sglEnd();
            }

            /* Object: line_1, Type: line, OID: f853e30e-2312-4c91-8225-6261f3fde029 */
            {
              /* outlined object part */
              sglIndexLineWidthi(3L);
              sglBegin(SGL_LINES);
              sglVertex2f(0.0F, 7.0F);
              sglVertex2f(-25.0F, 7.0F);
              sglEnd();
            }

            /* Object: shape_1, Type: shape, OID: a5d17a19-2e01-4776-a449-82285ba51792 */
            {
              /* filled object part */
              sglDisable(SGL_MODULATE);
              sglEnable(SGL_POLYGON_SMOOTH);
              sglDisable(SGL_TESSELLATION);
              sglBegin(SGL_POLYGON);
              sglVertex2f(0.0F, 12.0F);
              sglVertex2f(0.0F, 2.0F);
              sglVertex2f(5.0F, 7.0F);
              sglEnd();
            }
          }
        }
        break;

      case 8L:

        /* Object: LE08, Type: container, OID: a531f5cf-0452-4930-930d-cfbf111b7b12 */
        {

          /* Object: LevelNTCAnnoncementGrey, Type: container, OID: f18137dc-66bd-42bf-8a5a-943e8de2984f */
          {

            /* Object: line_2, Type: line, OID: afe913cf-e2bf-4b5e-985c-402e335968bb */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexColori(3L);
              sglIndexHaloColori(-1L);
              sglIndexLineWidthi(3L);
              sglIndexLineStipplei(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINES);
              sglVertex2f(-12.0F, 0.0F);
              sglVertex2f(-26.0F, 0.0F);
              sglEnd();
            }

            /* Object: shape_2, Type: shape, OID: 41b2f1d8-4bbc-477f-85f1-5f0d95897e2b */
            {
              /* filled object part */
              sglDisable(SGL_MODULATE);
              sglEnable(SGL_POLYGON_SMOOTH);
              sglDisable(SGL_TESSELLATION);
              sglBegin(SGL_POLYGON);
              sglVertex2f(-15.0F, 5.0F);
              sglVertex2f(-15.0F, -5.0F);
              sglVertex2f(-10.0F, 0.0F);
              sglEnd();
              /* outlined object part */
              sglIndexLineWidthi(0L);
              sglBegin(SGL_LINE_LOOP);
              sglVertex2f(-15.0F, 5.0F);
              sglVertex2f(-15.0F, -5.0F);
              sglVertex2f(-10.0F, 0.0F);
              sglEnd();
            }

            /* Object: text_7, Type: text, OID: e3cee02a-d3d9-4e05-84ce-4e54f5851fff */
            {
              static SGLuint8 _lArray0_text_7[255UL] = {78U,84U,67U};
              sglIndexFontLineWidthi(2L);
              sglIndexFonti(0L);
              sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
              sgluWriteText(7.0F, 0.0F, _lArray0_text_7, 255L);
            }
          }
        }
        break;

      case 9L:

        /* Object: LE09, Type: container, OID: 885b07be-57bc-4575-879c-56dc0d052556 */
        {

          /* Object: LevelNTCAnnoncementYellow, Type: container, OID: 75cdc5ce-5bd0-482f-bfc5-484884b10ccd */
          {

            /* Object: line_3, Type: line, OID: d7531060-bd5f-4b6c-aa9e-8795dba56a2a */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexColori(8L);
              sglIndexHaloColori(-1L);
              sglIndexLineWidthi(3L);
              sglIndexLineStipplei(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINES);
              sglVertex2f(-12.0F, 0.0F);
              sglVertex2f(-26.0F, 0.0F);
              sglEnd();
            }

            /* Object: shape_3, Type: shape, OID: 6b1d1e05-53aa-427d-b4e7-c9534f278319 */
            {
              /* filled object part */
              sglDisable(SGL_MODULATE);
              sglEnable(SGL_POLYGON_SMOOTH);
              sglDisable(SGL_TESSELLATION);
              sglBegin(SGL_POLYGON);
              sglVertex2f(-15.0F, 5.0F);
              sglVertex2f(-15.0F, -5.0F);
              sglVertex2f(-10.0F, 0.0F);
              sglEnd();
              /* outlined object part */
              sglIndexLineWidthi(0L);
              sglBegin(SGL_LINE_LOOP);
              sglVertex2f(-15.0F, 5.0F);
              sglVertex2f(-15.0F, -5.0F);
              sglVertex2f(-10.0F, 0.0F);
              sglEnd();
            }

            /* Object: text_8, Type: text, OID: fcca280c-0040-47cd-9833-109779698044 */
            {
              static SGLuint8 _lArray0_text_8[255UL] = {78U,84U,67U};
              sglIndexFontLineWidthi(2L);
              sglIndexFonti(0L);
              sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
              sgluWriteText(7.0F, 0.0F, _lArray0_text_8, 255L);
            }
          }
        }
        break;

      case 10L:

        /* Object: LE10, Type: container, OID: 7359a549-1d66-48a9-b0cc-7751c0bebadb */
        {

          /* Object: Level1AnnouncementIntermittetGrey, Type: container, OID: e1989f1b-dec3-4654-b52a-1608094a86a8 */
          {

            /* Object: text_9, Type: text, OID: a191bdd0-6631-4d1f-a01b-31af039dc302 */
            {
              static SGLuint8 _lArray0_text_9[255UL] = {49U};
              sglIndexColori(3L);
              sglIndexHaloColori(-1L);
              sglIndexFontLineWidthi(3L);
              sglIndexFonti(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
              sgluWriteText(23.0F, 6.0F, _lArray0_text_9, 255L);
            }

            /* Object: line_4, Type: line, OID: fa51d5a5-cb8b-44d6-b776-7420e90889d2 */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexLineWidthi(3L);
              sglIndexLineStipplei(0L);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINES);
              sglVertex2f(0.0F, 7.0F);
              sglVertex2f(-26.0F, 7.0F);
              sglEnd();
            }

            /* Object: shape_4, Type: shape, OID: b13cf721-6768-4165-b2db-5cab72b8d325 */
            {
              /* filled object part */
              sglDisable(SGL_MODULATE);
              sglEnable(SGL_POLYGON_SMOOTH);
              sglDisable(SGL_TESSELLATION);
              sglBegin(SGL_POLYGON);
              sglVertex2f(0.0F, 12.0F);
              sglVertex2f(0.0F, 2.0F);
              sglVertex2f(5.0F, 7.0F);
              sglEnd();
              /* outlined object part */
              sglIndexLineWidthi(0L);
              sglBegin(SGL_LINE_LOOP);
              sglVertex2f(0.0F, 12.0F);
              sglVertex2f(0.0F, 2.0F);
              sglVertex2f(5.0F, 7.0F);
              sglEnd();
            }

            /* Object: rectangle_10, Type: rectangle, OID: 0963e457-4f99-43be-8aa3-2c2d19add3ec */
            {
              /* filled object part */
              sglBegin(SGL_POLYGON);
              sglVertex2f(-27.0F, -11.0F);
              sglVertex2f(-19.0F, -11.0F);
              sglVertex2f(-19.0F, -3.0F);
              sglVertex2f(-27.0F, -3.0F);
              sglEnd();
            }

            /* Object: rectangle_11, Type: rectangle, OID: 039bf9c1-62ed-4b27-8025-1cb261fbaa56 */
            {
              /* filled object part */
              sglBegin(SGL_POLYGON);
              sglVertex2f(-12.0F, -11.0F);
              sglVertex2f(-4.0F, -11.0F);
              sglVertex2f(-4.0F, -3.0F);
              sglVertex2f(-12.0F, -3.0F);
              sglEnd();
            }

            /* Object: rectangle_12, Type: rectangle, OID: f6a617d0-7c13-448a-bf1b-f5df42983abc */
            {
              /* filled object part */
              sglBegin(SGL_POLYGON);
              sglVertex2f(4.0F, -11.0F);
              sglVertex2f(12.0F, -11.0F);
              sglVertex2f(12.0F, -3.0F);
              sglVertex2f(4.0F, -3.0F);
              sglEnd();
            }

            /* Object: rectangle_13, Type: rectangle, OID: 78f967f4-d579-49ab-92af-75b49e19a9d6 */
            {
              /* filled object part */
              sglBegin(SGL_POLYGON);
              sglVertex2f(19.0F, -11.0F);
              sglVertex2f(27.0F, -11.0F);
              sglVertex2f(27.0F, -3.0F);
              sglVertex2f(19.0F, -3.0F);
              sglEnd();
            }
          }
        }
        break;

      case 11L:

        /* Object: LE11, Type: container, OID: a18ddd78-70a1-459a-b19e-8db2c44a4104 */
        {

          /* Object: Level1AnnouncementIntermittetYellow, Type: container, OID: 7b19d19f-9fb0-4d3b-9b44-0dbca9e91f37 */
          {

            /* Object: text_10, Type: text, OID: 5d2094a1-9d62-4ef6-8955-340fe51d9edf */
            {
              static SGLuint8 _lArray0_text_10[255UL] = {49U};
              sglIndexColori(8L);
              sglIndexHaloColori(-1L);
              sglIndexFontLineWidthi(3L);
              sglIndexFonti(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
              sgluWriteText(23.0F, 6.0F, _lArray0_text_10, 255L);
            }

            /* Object: line_5, Type: line, OID: 390c85a1-5b8b-492f-a2fc-99442ac29d05 */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexLineWidthi(3L);
              sglIndexLineStipplei(0L);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINES);
              sglVertex2f(0.0F, 7.0F);
              sglVertex2f(-26.0F, 7.0F);
              sglEnd();
            }

            /* Object: shape_5, Type: shape, OID: cb057f89-c064-4878-a660-e58f5f3cb770 */
            {
              /* filled object part */
              sglDisable(SGL_MODULATE);
              sglEnable(SGL_POLYGON_SMOOTH);
              sglDisable(SGL_TESSELLATION);
              sglBegin(SGL_POLYGON);
              sglVertex2f(0.0F, 12.0F);
              sglVertex2f(0.0F, 2.0F);
              sglVertex2f(5.0F, 7.0F);
              sglEnd();
              /* outlined object part */
              sglIndexLineWidthi(0L);
              sglBegin(SGL_LINE_LOOP);
              sglVertex2f(0.0F, 12.0F);
              sglVertex2f(0.0F, 2.0F);
              sglVertex2f(5.0F, 7.0F);
              sglEnd();
            }

            /* Object: rectangle_14, Type: rectangle, OID: 1569c2a8-3151-47d8-9f1f-450cc2515b11 */
            {
              /* filled object part */
              sglBegin(SGL_POLYGON);
              sglVertex2f(-27.0F, -11.0F);
              sglVertex2f(-19.0F, -11.0F);
              sglVertex2f(-19.0F, -3.0F);
              sglVertex2f(-27.0F, -3.0F);
              sglEnd();
            }

            /* Object: rectangle_15, Type: rectangle, OID: aa569da0-3f65-4d58-a329-e5f66b6b5ccb */
            {
              /* filled object part */
              sglBegin(SGL_POLYGON);
              sglVertex2f(-12.0F, -11.0F);
              sglVertex2f(-4.0F, -11.0F);
              sglVertex2f(-4.0F, -3.0F);
              sglVertex2f(-12.0F, -3.0F);
              sglEnd();
            }

            /* Object: rectangle_16, Type: rectangle, OID: 23186932-a1ac-4232-895a-25ee416aa8b0 */
            {
              /* filled object part */
              sglBegin(SGL_POLYGON);
              sglVertex2f(4.0F, -11.0F);
              sglVertex2f(12.0F, -11.0F);
              sglVertex2f(12.0F, -3.0F);
              sglVertex2f(4.0F, -3.0F);
              sglEnd();
            }

            /* Object: rectangle_17, Type: rectangle, OID: 59094759-da34-4db0-b7f6-68301d589ca2 */
            {
              /* filled object part */
              sglBegin(SGL_POLYGON);
              sglVertex2f(19.0F, -11.0F);
              sglVertex2f(27.0F, -11.0F);
              sglVertex2f(27.0F, -3.0F);
              sglVertex2f(19.0F, -3.0F);
              sglEnd();
            }
          }
        }
        break;

      case 12L:

        /* Object: LE12, Type: container, OID: 75884d05-adc6-4eb4-a504-74aac5ba58c2 */
        {

          /* Object: Level2AnnouncementContinousGrey, Type: container, OID: 98f553b2-9205-4828-90a5-89c3fba498ed */
          {

            /* Object: text_11, Type: text, OID: c9e42d07-38cb-4568-b2f9-7668c446e622 */
            {
              static SGLuint8 _lArray0_text_11[255UL] = {50U};
              sglIndexColori(3L);
              sglIndexHaloColori(-1L);
              sglIndexFontLineWidthi(3L);
              sglIndexFonti(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
              sgluWriteText(23.0F, 6.0F, _lArray0_text_11, 255L);
            }

            /* Object: line_6, Type: line, OID: 9ced4f6d-f8b9-4860-90a3-4c62c6760cc8 */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexLineWidthi(3L);
              sglIndexLineStipplei(0L);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINES);
              sglVertex2f(0.0F, 7.0F);
              sglVertex2f(-26.0F, 7.0F);
              sglEnd();
            }

            /* Object: shape_6, Type: shape, OID: 4454366d-123d-4365-bc97-2d915e51054f */
            {
              /* filled object part */
              sglDisable(SGL_MODULATE);
              sglEnable(SGL_POLYGON_SMOOTH);
              sglDisable(SGL_TESSELLATION);
              sglBegin(SGL_POLYGON);
              sglVertex2f(0.0F, 12.0F);
              sglVertex2f(0.0F, 2.0F);
              sglVertex2f(5.0F, 7.0F);
              sglEnd();
              /* outlined object part */
              sglIndexLineWidthi(0L);
              sglBegin(SGL_LINE_LOOP);
              sglVertex2f(0.0F, 12.0F);
              sglVertex2f(0.0F, 2.0F);
              sglVertex2f(5.0F, 7.0F);
              sglEnd();
            }

            /* Object: rectangle_18, Type: rectangle, OID: 46dfba5d-4615-4d2c-8dc3-45b5ca41f87b */
            {
              /* filled object part */
              sglBegin(SGL_POLYGON);
              sglVertex2f(-27.0F, -11.0F);
              sglVertex2f(27.0F, -11.0F);
              sglVertex2f(27.0F, -3.0F);
              sglVertex2f(-27.0F, -3.0F);
              sglEnd();
            }
          }
        }
        break;

      case 13L:

        /* Object: LE13, Type: container, OID: 82485349-77b4-4c9d-9ef4-5623c9b791f8 */
        {

          /* Object: Level2AnnouncementContinousYellow, Type: container, OID: 39dd142e-9a03-43a8-8a54-146d795df513 */
          {

            /* Object: text_12, Type: text, OID: 04c56fb5-4de0-43a1-a8f2-d8bc8f4ea7e4 */
            {
              static SGLuint8 _lArray0_text_12[255UL] = {50U};
              sglIndexColori(8L);
              sglIndexHaloColori(-1L);
              sglIndexFontLineWidthi(3L);
              sglIndexFonti(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
              sgluWriteText(23.0F, 6.0F, _lArray0_text_12, 255L);
            }

            /* Object: line_7, Type: line, OID: dfb8de0b-bbab-4d59-beb1-53dfd0ba8ec3 */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexLineWidthi(3L);
              sglIndexLineStipplei(0L);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINES);
              sglVertex2f(0.0F, 7.0F);
              sglVertex2f(-26.0F, 7.0F);
              sglEnd();
            }

            /* Object: shape_7, Type: shape, OID: 82cec311-8890-4870-96b3-19bb1218136a */
            {
              /* filled object part */
              sglDisable(SGL_MODULATE);
              sglEnable(SGL_POLYGON_SMOOTH);
              sglDisable(SGL_TESSELLATION);
              sglBegin(SGL_POLYGON);
              sglVertex2f(0.0F, 12.0F);
              sglVertex2f(0.0F, 2.0F);
              sglVertex2f(5.0F, 7.0F);
              sglEnd();
              /* outlined object part */
              sglIndexLineWidthi(0L);
              sglBegin(SGL_LINE_LOOP);
              sglVertex2f(0.0F, 12.0F);
              sglVertex2f(0.0F, 2.0F);
              sglVertex2f(5.0F, 7.0F);
              sglEnd();
            }

            /* Object: rectangle_19, Type: rectangle, OID: f682a1ba-ccb3-47b8-9b61-f8ffd236b4e9 */
            {
              /* filled object part */
              sglBegin(SGL_POLYGON);
              sglVertex2f(-27.0F, -11.0F);
              sglVertex2f(27.0F, -11.0F);
              sglVertex2f(27.0F, -3.0F);
              sglVertex2f(-27.0F, -3.0F);
              sglEnd();
              /* outlined object part */
              sglBegin(SGL_LINE_LOOP);
              sglVertex2f(-27.0F, -11.0F);
              sglVertex2f(27.0F, -11.0F);
              sglVertex2f(27.0F, -3.0F);
              sglVertex2f(-27.0F, -3.0F);
              sglEnd();
            }
          }
        }
        break;

      case 14L:

        /* Object: LE14, Type: container, OID: 534192c8-da46-4945-86bb-25df0acefbe7 */
        {

          /* Object: Level3AnnouncementContinousGrey, Type: container, OID: 103ec01c-bf5e-496e-81d0-cfb7dc815306 */
          {

            /* Object: text_13, Type: text, OID: 807cd8b5-36c8-4aba-9271-32583926aa73 */
            {
              static SGLuint8 _lArray0_text_13[255UL] = {51U};
              sglIndexColori(3L);
              sglIndexHaloColori(-1L);
              sglIndexFontLineWidthi(3L);
              sglIndexFonti(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
              sgluWriteText(23.0F, 6.0F, _lArray0_text_13, 255L);
            }

            /* Object: line_8, Type: line, OID: ce307e05-9570-4489-b155-a0d37b91ef46 */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexLineWidthi(3L);
              sglIndexLineStipplei(0L);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINES);
              sglVertex2f(0.0F, 7.0F);
              sglVertex2f(-26.0F, 7.0F);
              sglEnd();
            }

            /* Object: shape_8, Type: shape, OID: 0ede9330-1c72-4ccf-8251-df34bd318f44 */
            {
              /* filled object part */
              sglDisable(SGL_MODULATE);
              sglEnable(SGL_POLYGON_SMOOTH);
              sglDisable(SGL_TESSELLATION);
              sglBegin(SGL_POLYGON);
              sglVertex2f(0.0F, 12.0F);
              sglVertex2f(0.0F, 2.0F);
              sglVertex2f(5.0F, 7.0F);
              sglEnd();
              /* outlined object part */
              sglIndexLineWidthi(0L);
              sglBegin(SGL_LINE_LOOP);
              sglVertex2f(0.0F, 12.0F);
              sglVertex2f(0.0F, 2.0F);
              sglVertex2f(5.0F, 7.0F);
              sglEnd();
            }

            /* Object: rectangle_20, Type: rectangle, OID: 9e2b3f42-607c-4938-98cd-4c7b7e234c59 */
            {
              /* filled object part */
              sglBegin(SGL_POLYGON);
              sglVertex2f(-27.0F, -11.0F);
              sglVertex2f(27.0F, -11.0F);
              sglVertex2f(27.0F, -3.0F);
              sglVertex2f(-27.0F, -3.0F);
              sglEnd();
            }
          }
        }
        break;

      case 15L:

        /* Object: LE15, Type: container, OID: eb425bb7-ea6d-4140-8f5b-3d1a59b02765 */
        {

          /* Object: Level3AnnouncementContinousYellow, Type: container, OID: e35d4f50-9b62-41a5-bcac-c7067737af7f */
          {

            /* Object: text_14, Type: text, OID: b7e239c2-0372-4d54-af70-438a0b4a4b81 */
            {
              static SGLuint8 _lArray0_text_14[255UL] = {51U};
              sglIndexColori(8L);
              sglIndexHaloColori(-1L);
              sglIndexFontLineWidthi(3L);
              sglIndexFonti(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
              sgluWriteText(23.0F, 6.0F, _lArray0_text_14, 255L);
            }

            /* Object: line_9, Type: line, OID: 041108f9-e8a0-41df-9089-30002003d3c5 */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexLineWidthi(3L);
              sglIndexLineStipplei(0L);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINES);
              sglVertex2f(0.0F, 7.0F);
              sglVertex2f(-26.0F, 7.0F);
              sglEnd();
            }

            /* Object: shape_9, Type: shape, OID: 99993b81-0e64-4149-8e3f-2011df9133d9 */
            {
              /* filled object part */
              sglDisable(SGL_MODULATE);
              sglEnable(SGL_POLYGON_SMOOTH);
              sglDisable(SGL_TESSELLATION);
              sglBegin(SGL_POLYGON);
              sglVertex2f(0.0F, 12.0F);
              sglVertex2f(0.0F, 2.0F);
              sglVertex2f(5.0F, 7.0F);
              sglEnd();
              /* outlined object part */
              sglIndexLineWidthi(0L);
              sglBegin(SGL_LINE_LOOP);
              sglVertex2f(0.0F, 12.0F);
              sglVertex2f(0.0F, 2.0F);
              sglVertex2f(5.0F, 7.0F);
              sglEnd();
            }

            /* Object: rectangle_21, Type: rectangle, OID: 7a803461-dde0-46de-84f6-c51b99bc4b81 */
            {
              /* filled object part */
              sglBegin(SGL_POLYGON);
              sglVertex2f(-27.0F, -11.0F);
              sglVertex2f(27.0F, -11.0F);
              sglVertex2f(27.0F, -3.0F);
              sglVertex2f(-27.0F, -3.0F);
              sglEnd();
              /* outlined object part */
              sglBegin(SGL_LINE_LOOP);
              sglVertex2f(-27.0F, -11.0F);
              sglVertex2f(27.0F, -11.0F);
              sglVertex2f(27.0F, -3.0F);
              sglVertex2f(-27.0F, -3.0F);
              sglEnd();
            }
          }
        }
        break;

      case 16L:

        /* Object: LE02_old, Type: container, OID: 8ed3d956-ecf0-4020-9f62-13cb8090671d */
        {

          /* Object: LevelNTC_1, Type: container, OID: 166d572e-624f-494f-b2f1-f48f9e736a55 */
          {

            /* Object: text_15, Type: text, OID: a77f64d2-e0ac-4acd-b098-14563b3360fb */
            {
              static SGLuint8 _lArray0_text_15[255UL] = {78U,84U,67U};
              sglIndexColori(3L);
              sglIndexHaloColori(-1L);
              sglIndexFontLineWidthi(2L);
              sglIndexFonti(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
              sgluWriteText(0.0F, 0.0F, _lArray0_text_15, 255L);
            }
          }
        }
        break;

      default:
        /* Do nothing */
        break;
      }
      sglPopMatrixAndTranslate();
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

