/*********************************************************
 **
 ** File  aol_button.c
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\MainMenu\Button\button.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:24
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#include "aol_button.h"
#include "aol_imported_functions.h"
#include "sgl.h"


void aol_button_init(aol_typ_button *pContext)
{
  aol_button_S_ButtonIndex(pContext, 0L);
  aol_button_S_enableIndex(pContext, 0L);
  aol_button_S_MousePressed(pContext, SGL_FALSE);
  aol_button_S_onButton(pContext, SGL_FALSE);

  pContext->_parentPriority = 0L;

}

void aol_button_predraw(aol_typ_button *pContext)
{

}

void aol_button_draw(aol_typ_button *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: ButtonMenu, Type: container, OID: 7f3f7a99-c315-4f7b-983a-88950d4d164e */
    {
      sglPushMatrixAndTranslate(153.0F, -125.0F);

      /* Object: rectangle, Type: rectangle, OID: d2fb6480-5a38-4216-b6b3-ee908042df4e */
      {
        /* filled object part */
        sglIndexColori(6L);
        sglDisable(SGL_MODULATE);
        sglEnable(SGL_POLYGON_SMOOTH);
        sglTransparency8(255L);
        sglDisable(SGL_TEXTURE_2D);
        sglDisable(SGL_TESSELLATION);
        sglBegin(SGL_POLYGON);
        sglVertex2f(-153.0F, 175.0F);
        sglVertex2f(0.0F, 175.0F);
        sglVertex2f(0.0F, 125.0F);
        sglVertex2f(-153.0F, 125.0F);
        sglEnd();
        /* outlined object part */
        sglIndexHaloColori(-1L);
        sglIndexLineWidthi(0L);
        sglIndexLineStipplei(0L);
        sglDisable(SGL_LINE_HALOING);
        sglSetLineCaps(SGL_ROUNDED_CAPS);
        sglBegin(SGL_LINE_LOOP);
        sglVertex2f(-153.0F, 175.0F);
        sglVertex2f(0.0F, 175.0F);
        sglVertex2f(0.0F, 125.0F);
        sglVertex2f(-153.0F, 125.0F);
        sglEnd();
      }

      /* Object: conditional_group, Type: conditional, OID: db43f6be-05ae-4d1b-aac1-7ddb6bb80456 */
      {
        switch (aol_button_G_ButtonIndex(pContext)) {

        case 2L:

          /* Object: DriverID, Type: conditional, OID: 38d0fbca-602f-4aa9-bb73-ebd403984dd0 */
          {
            switch (aol_button_G_enableIndex(pContext)) {

            case 1L:

              /* Object: Enable_2, Type: container, OID: fcbec593-53fc-4c22-b627-678f1964c331 */
              {

                /* Object: Enable_3, Type: text, OID: a989bf60-285b-4cbf-974b-696083d5abf3 */
                {
                  static SGLuint8 _lArray0_Enable_3[255UL] = {68U,114U,105U,118U,101U,114U,32U,73U,68U};
                  sglIndexColori(1L);
                  sglIndexFontLineWidthi(2L);
                  sglIndexFonti(5L);
                  sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                  sgluWriteText(-79.0F, 150.0F, _lArray0_Enable_3, 255L);
                }

                /* Object: LT_outer_lines_2, Type: line, OID: adfa668f-2f8c-4ed6-8646-b2a9e72f6487 */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_STRAIGHT_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(-153.0F, 175.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: LT_inner_lines_2, Type: line, OID: dd059abd-0e3e-497d-bf3d-2b1b6fa5e343 */
                {
                  if (SGLbool_not(aol_button_G_MousePressed(pContext))) {
                    /* outlined object part */
                    sglIndexColori(7L);
                    sglBegin(SGL_LINE_STRIP);
                    sglVertex2f(-152.0F, 126.0F);
                    sglVertex2f(-152.0F, 174.0F);
                    sglVertex2f(-1.0F, 174.0F);
                    sglEnd();
                  }
                }

                /* Object: RB_inner_lines_2, Type: line, OID: 33a11bf1-bb29-4da2-a2e1-4752e41394db */
                {
                  if (SGLbool_not(aol_button_G_MousePressed(pContext))) {
                    /* outlined object part */
                    sglIndexColori(2L);
                    sglSetLineCaps(SGL_ROUNDED_CAPS);
                    sglBegin(SGL_LINE_STRIP);
                    sglVertex2f(-152.0F, 126.0F);
                    sglVertex2f(-1.0F, 126.0F);
                    sglVertex2f(-1.0F, 174.0F);
                    sglEnd();
                  }
                }

                /* Object: RB_outer_lines_2, Type: line, OID: 15c48767-e02b-4594-951f-e72316ab4dc7 */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglSetLineCaps(SGL_ROUNDED_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(0.0F, 125.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: rectangle_area_1, Type: rectangleArea, OID: 0451d8e2-182c-4866-826a-5855f3baad7f */
                {
                  SGLfloat _lX = 0.0F;
                  SGLfloat _lY = 0.0F;
                  aol_locate(-1L, &_lX, &_lY);
                  aol_button_G_onButton(pContext) = sglRectangleActiveAreaGetStatus(_lX, _lY, -153.0F, 175.0F, 0.0F, 125.0F);
                }
              }
              break;

            case 2L:

              /* Object: Disable_2, Type: container, OID: c2b99f58-d90e-4e22-b30d-599858b9fd2b */
              {

                /* Object: Disable_3, Type: text, OID: 8522ee38-934d-44f4-b337-42f8f0a6497e */
                {
                  static SGLuint8 _lArray0_Disable_3[255UL] = {68U,114U,105U,118U,101U,114U,32U,73U,68U};
                  sglIndexColori(5L);
                  sglIndexFontLineWidthi(2L);
                  sglIndexFonti(5L);
                  sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                  sgluWriteText(-79.0F, 150.0F, _lArray0_Disable_3, 255L);
                }

                /* Object: LT_outer_lines_3, Type: line, OID: cbb45994-9e91-4a81-a7dc-8e6606110638 */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_STRAIGHT_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(-153.0F, 175.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: LT_inner_lines_3, Type: line, OID: ad267b5e-b079-4c7c-b511-dd4c0d1d45f2 */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-152.0F, 126.0F);
                  sglVertex2f(-152.0F, 174.0F);
                  sglVertex2f(-1.0F, 174.0F);
                  sglEnd();
                }

                /* Object: RB_inner_lines_3, Type: line, OID: f1f436f9-3bbb-45f8-92eb-795dd03e9cef */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_ROUNDED_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-152.0F, 126.0F);
                  sglVertex2f(-1.0F, 126.0F);
                  sglVertex2f(-1.0F, 174.0F);
                  sglEnd();
                }

                /* Object: RB_outer_lines_3, Type: line, OID: 0d1d9e2e-1a1d-4871-95d6-b208df69d519 */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(0.0F, 125.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }
              }
              break;

            default:
              /* Do nothing */
              break;
            }
          }
          break;

        case 3L:

          /* Object: TrainData, Type: conditional, OID: c2310e40-6324-4e8a-a979-920a369eb908 */
          {
            switch (aol_button_G_enableIndex(pContext)) {

            case 1L:

              /* Object: Enable_4, Type: container, OID: 19573247-29ef-44e6-a9c8-8830275c4ec7 */
              {

                /* Object: Enable_5, Type: text, OID: 063d85d7-756b-4a73-b559-525b711543da */
                {
                  static SGLuint8 _lArray0_Enable_5[255UL] = {84U,114U,97U,105U,110U,32U,100U,97U,116U,97U};
                  sglIndexColori(1L);
                  sglIndexFontLineWidthi(2L);
                  sglIndexFonti(5L);
                  sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                  sgluWriteText(-79.0F, 150.0F, _lArray0_Enable_5, 255L);
                }

                /* Object: LT_outer_lines_4, Type: line, OID: 7c1cf912-3dc1-4603-a90d-30257a9d2149 */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_STRAIGHT_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(-153.0F, 175.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: LT_inner_lines_4, Type: line, OID: ce6eb789-0a27-4d7f-8788-2e25d594290a */
                {
                  if (SGLbool_not(aol_button_G_MousePressed(pContext))) {
                    /* outlined object part */
                    sglIndexColori(7L);
                    sglBegin(SGL_LINE_STRIP);
                    sglVertex2f(-152.0F, 126.0F);
                    sglVertex2f(-152.0F, 174.0F);
                    sglVertex2f(-1.0F, 174.0F);
                    sglEnd();
                  }
                }

                /* Object: RB_inner_lines_4, Type: line, OID: df299ea6-d238-4ee5-883b-2d95b4556dbb */
                {
                  if (SGLbool_not(aol_button_G_MousePressed(pContext))) {
                    /* outlined object part */
                    sglIndexColori(2L);
                    sglSetLineCaps(SGL_ROUNDED_CAPS);
                    sglBegin(SGL_LINE_STRIP);
                    sglVertex2f(-152.0F, 126.0F);
                    sglVertex2f(-1.0F, 126.0F);
                    sglVertex2f(-1.0F, 174.0F);
                    sglEnd();
                  }
                }

                /* Object: RB_outer_lines_4, Type: line, OID: d9ceccfd-af31-429b-aaf2-fb7191ed1c60 */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglSetLineCaps(SGL_ROUNDED_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(0.0F, 125.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: rectangle_area_2, Type: rectangleArea, OID: 061a7a3e-b7e2-4b9a-b602-7d1f29efd6fe */
                {
                  SGLfloat _lX = 0.0F;
                  SGLfloat _lY = 0.0F;
                  aol_locate(-1L, &_lX, &_lY);
                  aol_button_G_onButton(pContext) = sglRectangleActiveAreaGetStatus(_lX, _lY, -153.0F, 175.0F, 0.0F, 125.0F);
                }
              }
              break;

            case 2L:

              /* Object: Disable_4, Type: container, OID: 87036c45-ea4c-47a7-b53b-67e79ba1621c */
              {

                /* Object: Disable_5, Type: text, OID: 0f144f50-7cb7-49d0-b339-285387ccb76f */
                {
                  static SGLuint8 _lArray0_Disable_5[255UL] = {84U,114U,97U,105U,110U,32U,100U,97U,116U,97U};
                  sglIndexColori(5L);
                  sglIndexFontLineWidthi(2L);
                  sglIndexFonti(5L);
                  sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                  sgluWriteText(-79.0F, 150.0F, _lArray0_Disable_5, 255L);
                }

                /* Object: LT_outer_lines_5, Type: line, OID: 309135d4-0cf3-49ab-bd31-5e8f3dba590c */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_STRAIGHT_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(-153.0F, 175.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: LT_inner_lines_5, Type: line, OID: c4b5b98b-9ba3-42af-8dd9-06f4527bb67d */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-152.0F, 126.0F);
                  sglVertex2f(-152.0F, 174.0F);
                  sglVertex2f(-1.0F, 174.0F);
                  sglEnd();
                }

                /* Object: RB_inner_lines_5, Type: line, OID: 79b6f368-8819-4112-bff2-b2cc5e593409 */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_ROUNDED_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-152.0F, 126.0F);
                  sglVertex2f(-1.0F, 126.0F);
                  sglVertex2f(-1.0F, 174.0F);
                  sglEnd();
                }

                /* Object: RB_outer_lines_5, Type: line, OID: dc2e9f6e-8986-4689-842f-4379966400f0 */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(0.0F, 125.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }
              }
              break;

            default:
              /* Do nothing */
              break;
            }
          }
          break;

        case 4L:

          /* Object: Level, Type: conditional, OID: 6d7b6dd4-a7d3-47b7-99fa-e117cc9a5119 */
          {
            switch (aol_button_G_enableIndex(pContext)) {

            case 1L:

              /* Object: Enable_6, Type: container, OID: 64e25d82-156c-4b46-a19b-48644b31617a */
              {

                /* Object: Enable_7, Type: text, OID: f2a6b54e-13aa-42f2-a036-2763680987be */
                {
                  static SGLuint8 _lArray0_Enable_7[255UL] = {76U,101U,118U,101U,108U};
                  sglIndexColori(1L);
                  sglIndexFontLineWidthi(2L);
                  sglIndexFonti(5L);
                  sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                  sgluWriteText(-79.0F, 150.0F, _lArray0_Enable_7, 255L);
                }

                /* Object: LT_outer_lines_6, Type: line, OID: 2cafb07d-07a1-49ac-a8d8-6cb45b6460b4 */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_STRAIGHT_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(-153.0F, 175.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: LT_inner_lines_6, Type: line, OID: 140ea015-791b-4a62-842b-d0f55d6a4ba4 */
                {
                  if (SGLbool_not(aol_button_G_MousePressed(pContext))) {
                    /* outlined object part */
                    sglIndexColori(7L);
                    sglBegin(SGL_LINE_STRIP);
                    sglVertex2f(-152.0F, 126.0F);
                    sglVertex2f(-152.0F, 174.0F);
                    sglVertex2f(-1.0F, 174.0F);
                    sglEnd();
                  }
                }

                /* Object: RB_inner_lines_6, Type: line, OID: 96407c74-7f40-4cc4-b0dd-e4b7434dbb2c */
                {
                  if (SGLbool_not(aol_button_G_MousePressed(pContext))) {
                    /* outlined object part */
                    sglIndexColori(2L);
                    sglSetLineCaps(SGL_ROUNDED_CAPS);
                    sglBegin(SGL_LINE_STRIP);
                    sglVertex2f(-152.0F, 126.0F);
                    sglVertex2f(-1.0F, 126.0F);
                    sglVertex2f(-1.0F, 174.0F);
                    sglEnd();
                  }
                }

                /* Object: RB_outer_lines_6, Type: line, OID: b93bec8b-95b9-4b8f-82a3-0fd76ac402c5 */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglSetLineCaps(SGL_ROUNDED_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(0.0F, 125.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: rectangle_area_3, Type: rectangleArea, OID: 0ca56c7d-f254-4441-86ff-c8d84faaee3e */
                {
                  SGLfloat _lX = 0.0F;
                  SGLfloat _lY = 0.0F;
                  aol_locate(-1L, &_lX, &_lY);
                  aol_button_G_onButton(pContext) = sglRectangleActiveAreaGetStatus(_lX, _lY, -153.0F, 175.0F, 0.0F, 125.0F);
                }
              }
              break;

            case 2L:

              /* Object: Disable_6, Type: container, OID: a7adf62e-8e78-44c2-a78f-9010d8b9ebf2 */
              {

                /* Object: Disable_7, Type: text, OID: 7ca46403-1d32-41b5-a14f-1ec55def953a */
                {
                  static SGLuint8 _lArray0_Disable_7[255UL] = {76U,101U,118U,101U,108U};
                  sglIndexColori(5L);
                  sglIndexFontLineWidthi(2L);
                  sglIndexFonti(5L);
                  sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                  sgluWriteText(-79.0F, 150.0F, _lArray0_Disable_7, 255L);
                }

                /* Object: LT_outer_lines_7, Type: line, OID: 23acd77a-54e5-476b-9717-3d9cf6c46d0d */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_STRAIGHT_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(-153.0F, 175.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: LT_inner_lines_7, Type: line, OID: 89733b60-a64c-4562-84b0-c89a2c188e38 */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-152.0F, 126.0F);
                  sglVertex2f(-152.0F, 174.0F);
                  sglVertex2f(-1.0F, 174.0F);
                  sglEnd();
                }

                /* Object: RB_inner_lines_7, Type: line, OID: 8cc2a353-fe44-4fbe-b034-49755a382465 */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_ROUNDED_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-152.0F, 126.0F);
                  sglVertex2f(-1.0F, 126.0F);
                  sglVertex2f(-1.0F, 174.0F);
                  sglEnd();
                }

                /* Object: RB_outer_lines_7, Type: line, OID: 4b757740-a1f1-4caa-bd00-cccfbaaf5f29 */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(0.0F, 125.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }
              }
              break;

            default:
              /* Do nothing */
              break;
            }
          }
          break;

        case 6L:

          /* Object: Shunting, Type: conditional, OID: 9b4335dc-5725-4be9-ae92-c780a759f315 */
          {
            switch (aol_button_G_enableIndex(pContext)) {

            case 1L:

              /* Object: Enable_8, Type: container, OID: 9d3a37c6-db47-478f-a100-e904bb0a6eea */
              {

                /* Object: Enable_9, Type: text, OID: 084a3f97-b29b-4d05-9bb8-ae5749bfc8a4 */
                {
                  static SGLuint8 _lArray0_Enable_9[255UL] = {83U,104U,117U,110U,116U,105U,110U,103U};
                  sglIndexColori(1L);
                  sglIndexFontLineWidthi(2L);
                  sglIndexFonti(5L);
                  sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                  sgluWriteText(-79.0F, 150.0F, _lArray0_Enable_9, 255L);
                }

                /* Object: LT_outer_lines_8, Type: line, OID: f3a95e40-c2bd-47c1-9fac-25c491427ea4 */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_STRAIGHT_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(-153.0F, 175.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: LT_inner_lines_8, Type: line, OID: 9c9eccc0-dcf6-44f3-b641-8ecb7a3e6a49 */
                {
                  if (SGLbool_not(aol_button_G_MousePressed(pContext))) {
                    /* outlined object part */
                    sglIndexColori(7L);
                    sglBegin(SGL_LINE_STRIP);
                    sglVertex2f(-152.0F, 126.0F);
                    sglVertex2f(-152.0F, 174.0F);
                    sglVertex2f(-1.0F, 174.0F);
                    sglEnd();
                  }
                }

                /* Object: RB_inner_lines_8, Type: line, OID: d848fd72-d729-4183-9bbc-bf591372a4e4 */
                {
                  if (SGLbool_not(aol_button_G_MousePressed(pContext))) {
                    /* outlined object part */
                    sglIndexColori(2L);
                    sglSetLineCaps(SGL_ROUNDED_CAPS);
                    sglBegin(SGL_LINE_STRIP);
                    sglVertex2f(-152.0F, 126.0F);
                    sglVertex2f(-1.0F, 126.0F);
                    sglVertex2f(-1.0F, 174.0F);
                    sglEnd();
                  }
                }

                /* Object: RB_outer_lines_8, Type: line, OID: 7538e8d2-327c-4fa9-a188-a6955db059dd */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglSetLineCaps(SGL_ROUNDED_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(0.0F, 125.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: rectangle_area_4, Type: rectangleArea, OID: a6370a1e-9734-480b-99a0-fc50b950ab0f */
                {
                  SGLfloat _lX = 0.0F;
                  SGLfloat _lY = 0.0F;
                  aol_locate(-1L, &_lX, &_lY);
                  aol_button_G_onButton(pContext) = sglRectangleActiveAreaGetStatus(_lX, _lY, -153.0F, 175.0F, 0.0F, 125.0F);
                }
              }
              break;

            case 2L:

              /* Object: Disable_8, Type: container, OID: 0fb2c13f-bb08-4f7b-90ff-47f36851696b */
              {

                /* Object: Disable_9, Type: text, OID: 72b6e1c5-0fc8-46c6-8b78-f8fef40ffaa8 */
                {
                  static SGLuint8 _lArray0_Disable_9[255UL] = {83U,104U,117U,110U,116U,105U,110U,103U};
                  sglIndexColori(5L);
                  sglIndexFontLineWidthi(2L);
                  sglIndexFonti(5L);
                  sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                  sgluWriteText(-79.0F, 150.0F, _lArray0_Disable_9, 255L);
                }

                /* Object: LT_outer_lines_9, Type: line, OID: afcd46c8-fcf5-4222-9446-911fdb7707f4 */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_STRAIGHT_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(-153.0F, 175.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: LT_inner_lines_9, Type: line, OID: 2b03c34f-12fe-4f68-b086-019dd2556454 */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-152.0F, 126.0F);
                  sglVertex2f(-152.0F, 174.0F);
                  sglVertex2f(-1.0F, 174.0F);
                  sglEnd();
                }

                /* Object: RB_inner_lines_9, Type: line, OID: cfe8dbab-5b8a-4635-a870-53eb1efd96e1 */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_ROUNDED_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-152.0F, 126.0F);
                  sglVertex2f(-1.0F, 126.0F);
                  sglVertex2f(-1.0F, 174.0F);
                  sglEnd();
                }

                /* Object: RB_outer_lines_9, Type: line, OID: 71c1aa4b-5b30-4dce-938b-224bf8b58d9b */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(0.0F, 125.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }
              }
              break;

            default:
              /* Do nothing */
              break;
            }
          }
          break;

        case 7L:

          /* Object: NonLeading, Type: conditional, OID: 231bceb8-4de1-41aa-8cb8-cbbfda6dcc0b */
          {
            switch (aol_button_G_enableIndex(pContext)) {

            case 1L:

              /* Object: Enable_10, Type: container, OID: b2bb6a97-afc4-4780-b083-44c7ca7b5de3 */
              {

                /* Object: Enable_11, Type: text, OID: ed73b685-0895-48c6-86ad-95becbd579b8 */
                {
                  static SGLuint8 _lArray0_Enable_11[255UL] = {78U,111U,110U,45U,76U,101U,97U,100U,105U,110U,103U};
                  sglIndexColori(1L);
                  sglIndexFontLineWidthi(2L);
                  sglIndexFonti(5L);
                  sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                  sgluWriteText(-79.0F, 150.0F, _lArray0_Enable_11, 255L);
                }

                /* Object: LT_outer_lines_10, Type: line, OID: c26b8d36-5865-4fb3-8bc8-2dabc3b5c574 */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_STRAIGHT_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(-153.0F, 175.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: LT_inner_lines_10, Type: line, OID: ba3637d2-31c0-461b-9126-0770131b234d */
                {
                  if (SGLbool_not(aol_button_G_MousePressed(pContext))) {
                    /* outlined object part */
                    sglIndexColori(7L);
                    sglBegin(SGL_LINE_STRIP);
                    sglVertex2f(-152.0F, 126.0F);
                    sglVertex2f(-152.0F, 174.0F);
                    sglVertex2f(-1.0F, 174.0F);
                    sglEnd();
                  }
                }

                /* Object: RB_inner_lines_10, Type: line, OID: f416bf3d-b187-4b41-89ec-e10832e9ca80 */
                {
                  if (SGLbool_not(aol_button_G_MousePressed(pContext))) {
                    /* outlined object part */
                    sglIndexColori(2L);
                    sglSetLineCaps(SGL_ROUNDED_CAPS);
                    sglBegin(SGL_LINE_STRIP);
                    sglVertex2f(-152.0F, 126.0F);
                    sglVertex2f(-1.0F, 126.0F);
                    sglVertex2f(-1.0F, 174.0F);
                    sglEnd();
                  }
                }

                /* Object: RB_outer_lines_10, Type: line, OID: ac001221-ece2-447b-93c5-81b21a0d4faf */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglSetLineCaps(SGL_ROUNDED_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(0.0F, 125.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: rectangle_area_5, Type: rectangleArea, OID: 990f82f0-7423-4c54-ac50-9de9f859a184 */
                {
                  SGLfloat _lX = 0.0F;
                  SGLfloat _lY = 0.0F;
                  aol_locate(-1L, &_lX, &_lY);
                  aol_button_G_onButton(pContext) = sglRectangleActiveAreaGetStatus(_lX, _lY, -153.0F, 175.0F, 0.0F, 125.0F);
                }
              }
              break;

            case 2L:

              /* Object: Disable_10, Type: container, OID: 417098e6-8b71-4882-abaa-4a0e5f87f898 */
              {

                /* Object: Disable_11, Type: text, OID: fdc0c194-6733-4037-9289-b320100ee281 */
                {
                  static SGLuint8 _lArray0_Disable_11[255UL] = {78U,111U,110U,45U,76U,101U,97U,100U,105U,110U,103U};
                  sglIndexColori(5L);
                  sglIndexFontLineWidthi(2L);
                  sglIndexFonti(5L);
                  sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                  sgluWriteText(-79.0F, 150.0F, _lArray0_Disable_11, 255L);
                }

                /* Object: LT_outer_lines_11, Type: line, OID: f1af2f68-97e9-4461-a464-783fc50adef9 */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_STRAIGHT_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(-153.0F, 175.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: LT_inner_lines_11, Type: line, OID: 0d941a65-6b79-436c-b4bf-e97dae3083a7 */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-152.0F, 126.0F);
                  sglVertex2f(-152.0F, 174.0F);
                  sglVertex2f(-1.0F, 174.0F);
                  sglEnd();
                }

                /* Object: RB_inner_lines_11, Type: line, OID: e6ca4b69-c668-4ed7-baf8-0284df058802 */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_ROUNDED_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-152.0F, 126.0F);
                  sglVertex2f(-1.0F, 126.0F);
                  sglVertex2f(-1.0F, 174.0F);
                  sglEnd();
                }

                /* Object: RB_outer_lines_11, Type: line, OID: 8addd70f-3c72-4998-ad25-512da1a02603 */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(0.0F, 125.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }
              }
              break;

            default:
              /* Do nothing */
              break;
            }
          }
          break;

        case 8L:

          /* Object: MShunting, Type: conditional, OID: 08fbedf6-97c9-4d13-8470-428750e1ed2d */
          {
            switch (aol_button_G_enableIndex(pContext)) {

            case 1L:

              /* Object: Enable_12, Type: container, OID: 26b15d3f-bcab-47a0-9a41-00433be21c22 */
              {

                /* Object: Enable_13, Type: text, OID: 33653385-c962-404b-9b67-308aa9d7e553 */
                {
                  static SGLuint8 _lArray0_Enable_13[255UL] = {77U,97U,105U,110U,116U,97U,105U,110U,32U,83U,46U};
                  sglIndexColori(1L);
                  sglIndexFontLineWidthi(2L);
                  sglIndexFonti(5L);
                  sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                  sgluWriteText(-79.0F, 150.0F, _lArray0_Enable_13, 255L);
                }

                /* Object: LT_outer_lines_12, Type: line, OID: 5b3f0afb-8e04-4203-9205-efae5e1ef2f1 */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_STRAIGHT_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(-153.0F, 175.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: LT_inner_lines_12, Type: line, OID: 77b3f19e-9618-43c5-a9df-a10273fe6b56 */
                {
                  if (SGLbool_not(aol_button_G_MousePressed(pContext))) {
                    /* outlined object part */
                    sglIndexColori(7L);
                    sglBegin(SGL_LINE_STRIP);
                    sglVertex2f(-152.0F, 126.0F);
                    sglVertex2f(-152.0F, 174.0F);
                    sglVertex2f(-1.0F, 174.0F);
                    sglEnd();
                  }
                }

                /* Object: RB_inner_lines_12, Type: line, OID: ed95b24f-d3d3-43f8-8c78-31419d6afad3 */
                {
                  if (SGLbool_not(aol_button_G_MousePressed(pContext))) {
                    /* outlined object part */
                    sglIndexColori(2L);
                    sglSetLineCaps(SGL_ROUNDED_CAPS);
                    sglBegin(SGL_LINE_STRIP);
                    sglVertex2f(-152.0F, 126.0F);
                    sglVertex2f(-1.0F, 126.0F);
                    sglVertex2f(-1.0F, 174.0F);
                    sglEnd();
                  }
                }

                /* Object: RB_outer_lines_12, Type: line, OID: 32d19011-d076-4dcd-93fb-43b9b2315ed3 */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglSetLineCaps(SGL_ROUNDED_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(0.0F, 125.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: rectangle_area_6, Type: rectangleArea, OID: 9ec2b4d3-945d-434d-91af-ecd42e124453 */
                {
                  SGLfloat _lX = 0.0F;
                  SGLfloat _lY = 0.0F;
                  aol_locate(-1L, &_lX, &_lY);
                  aol_button_G_onButton(pContext) = sglRectangleActiveAreaGetStatus(_lX, _lY, -153.0F, 175.0F, 0.0F, 125.0F);
                }
              }
              break;

            case 2L:

              /* Object: Disable_12, Type: container, OID: 4e894337-0462-4bbf-8e2a-ca92a66d0382 */
              {

                /* Object: Disable_13, Type: text, OID: e3234a6f-89f2-4cab-9006-9bf746add543 */
                {
                  static SGLuint8 _lArray0_Disable_13[255UL] = {77U,97U,105U,110U,116U,97U,105U,110U,32U,83U,46U};
                  sglIndexColori(5L);
                  sglIndexFontLineWidthi(2L);
                  sglIndexFonti(5L);
                  sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                  sgluWriteText(-79.0F, 150.0F, _lArray0_Disable_13, 255L);
                }

                /* Object: LT_outer_lines_13, Type: line, OID: 30afd0f5-35c7-441a-a9b1-84185535f7f2 */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_STRAIGHT_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(-153.0F, 175.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: LT_inner_lines_13, Type: line, OID: 80ef8089-5864-4e6d-ba5a-6af120dc11c9 */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-152.0F, 126.0F);
                  sglVertex2f(-152.0F, 174.0F);
                  sglVertex2f(-1.0F, 174.0F);
                  sglEnd();
                }

                /* Object: RB_inner_lines_13, Type: line, OID: 67cadce0-fab1-46d5-a66c-ee3d21280e63 */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_ROUNDED_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-152.0F, 126.0F);
                  sglVertex2f(-1.0F, 126.0F);
                  sglVertex2f(-1.0F, 174.0F);
                  sglEnd();
                }

                /* Object: RB_outer_lines_13, Type: line, OID: d50dc34e-be82-4442-95db-34d547e9403e */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(0.0F, 125.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }
              }
              break;

            default:
              /* Do nothing */
              break;
            }
          }
          break;

        case 9L:

          /* Object: TRNumber, Type: conditional, OID: 1184f665-4853-48f1-be93-c17156bbf424 */
          {
            switch (aol_button_G_enableIndex(pContext)) {

            case 1L:

              /* Object: Enable_14, Type: container, OID: f2cfb221-c40c-43a0-8528-a3568b3175fd */
              {

                /* Object: Enable_15, Type: richText, OID: 8c649d5f-cab5-498f-a4f8-95f2086329d7 */
                {
                  static SGLuint8 _lArray0_Enable_15[255UL] = {84U,114U,97U,105U,110U,32U,114U,117U,110U,110U,105U,110U,103U,13U,10U,110U,117U,109U,98U,101U,114U};
                  sglIndexColori(1L);
                  sglIndexFontLineWidthi(2L);
                  sglIndexFonti(5L);
                  sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                  sgluWriteRichText(-79.0F, 150.0F, _lArray0_Enable_15, 255L);
                }

                /* Object: LT_outer_lines_14, Type: line, OID: 809199ce-e66e-47ca-82ac-0cc2ca13dd50 */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_STRAIGHT_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(-153.0F, 175.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: LT_inner_lines_14, Type: line, OID: db5141a4-446f-4faf-9e45-81b1fcd3cddf */
                {
                  if (SGLbool_not(aol_button_G_MousePressed(pContext))) {
                    /* outlined object part */
                    sglIndexColori(7L);
                    sglBegin(SGL_LINE_STRIP);
                    sglVertex2f(-152.0F, 126.0F);
                    sglVertex2f(-152.0F, 174.0F);
                    sglVertex2f(-1.0F, 174.0F);
                    sglEnd();
                  }
                }

                /* Object: RB_inner_lines_14, Type: line, OID: 6041fc21-7d22-44ba-ab1e-95733ba7f519 */
                {
                  if (SGLbool_not(aol_button_G_MousePressed(pContext))) {
                    /* outlined object part */
                    sglIndexColori(2L);
                    sglSetLineCaps(SGL_ROUNDED_CAPS);
                    sglBegin(SGL_LINE_STRIP);
                    sglVertex2f(-152.0F, 126.0F);
                    sglVertex2f(-1.0F, 126.0F);
                    sglVertex2f(-1.0F, 174.0F);
                    sglEnd();
                  }
                }

                /* Object: RB_outer_lines_14, Type: line, OID: 631be377-db6d-4d34-977a-72cd43ed58e9 */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglSetLineCaps(SGL_ROUNDED_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(0.0F, 125.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: rectangle_area_7, Type: rectangleArea, OID: ab129a86-0851-4437-9711-8898b773490b */
                {
                  SGLfloat _lX = 0.0F;
                  SGLfloat _lY = 0.0F;
                  aol_locate(-1L, &_lX, &_lY);
                  aol_button_G_onButton(pContext) = sglRectangleActiveAreaGetStatus(_lX, _lY, -153.0F, 175.0F, 0.0F, 125.0F);
                }
              }
              break;

            case 2L:

              /* Object: Disable_14, Type: container, OID: 5ab0e3c6-3eb4-4f70-94fc-df49ef08999a */
              {

                /* Object: Disable_15, Type: richText, OID: 1ded5ef5-e385-4157-8b78-2aeb2a0fdcad */
                {
                  static SGLuint8 _lArray0_Disable_15[255UL] = {84U,114U,97U,105U,110U,32U,114U,117U,110U,110U,105U,110U,103U,13U,10U,110U,117U,109U,98U,101U,114U};
                  sglIndexColori(5L);
                  sglIndexFontLineWidthi(2L);
                  sglIndexFonti(5L);
                  sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                  sgluWriteRichText(-79.0F, 150.0F, _lArray0_Disable_15, 255L);
                }

                /* Object: LT_outer_lines_15, Type: line, OID: 0d4f5cac-3cfc-4d90-b041-6e0d2c519d23 */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_STRAIGHT_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(-153.0F, 175.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: LT_inner_lines_15, Type: line, OID: c05180e1-8d3d-491b-b3b0-259c2dc00ff1 */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-152.0F, 126.0F);
                  sglVertex2f(-152.0F, 174.0F);
                  sglVertex2f(-1.0F, 174.0F);
                  sglEnd();
                }

                /* Object: RB_inner_lines_15, Type: line, OID: 3b544d8c-59c7-430a-83f7-8a2052c9e2aa */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_ROUNDED_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-152.0F, 126.0F);
                  sglVertex2f(-1.0F, 126.0F);
                  sglVertex2f(-1.0F, 174.0F);
                  sglEnd();
                }

                /* Object: RB_outer_lines_15, Type: line, OID: fd0534dc-2347-4e1b-858c-fe67e2a9cb67 */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(0.0F, 125.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }
              }
              break;

            default:
              /* Do nothing */
              break;
            }
          }
          break;

        default:
        /* case 1L */

          /* Object: start, Type: conditional, OID: 04aa44aa-fed6-4fe5-92b0-d24a414c1bf4 */
          {
            switch (aol_button_G_enableIndex(pContext)) {

            case 1L:

              /* Object: Enable, Type: container, OID: c0e39516-ff6e-49c2-b640-3b08c0c3f511 */
              {

                /* Object: Enable_1, Type: text, OID: 5885d547-d03f-4b05-ba25-52a4d5036cbf */
                {
                  static SGLuint8 _lArray0_Enable_1[255UL] = {83U,116U,97U,114U,116U};
                  sglIndexColori(1L);
                  sglIndexFontLineWidthi(2L);
                  sglIndexFonti(5L);
                  sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                  sgluWriteText(-79.0F, 150.0F, _lArray0_Enable_1, 255L);
                }

                /* Object: LT_outer_lines, Type: line, OID: 3ec8e048-1770-4a15-88af-5f6250e964f1 */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_STRAIGHT_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(-153.0F, 175.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: LT_inner_lines, Type: line, OID: 608b792e-7fb8-4f78-8a48-200545e1e9cc */
                {
                  if (SGLbool_not(aol_button_G_MousePressed(pContext))) {
                    /* outlined object part */
                    sglIndexColori(7L);
                    sglBegin(SGL_LINE_STRIP);
                    sglVertex2f(-152.0F, 126.0F);
                    sglVertex2f(-152.0F, 174.0F);
                    sglVertex2f(-1.0F, 174.0F);
                    sglEnd();
                  }
                }

                /* Object: RB_inner_lines, Type: line, OID: e6558247-7733-46c9-b3f5-3e4a88fb5a09 */
                {
                  if (SGLbool_not(aol_button_G_MousePressed(pContext))) {
                    /* outlined object part */
                    sglIndexColori(2L);
                    sglSetLineCaps(SGL_ROUNDED_CAPS);
                    sglBegin(SGL_LINE_STRIP);
                    sglVertex2f(-152.0F, 126.0F);
                    sglVertex2f(-1.0F, 126.0F);
                    sglVertex2f(-1.0F, 174.0F);
                    sglEnd();
                  }
                }

                /* Object: RB_outer_lines, Type: line, OID: e2c30352-df79-4f7b-bcf0-9e3576fbdf07 */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglSetLineCaps(SGL_ROUNDED_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(0.0F, 125.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: rectangle_area, Type: rectangleArea, OID: 6334105a-deee-4a4b-80ec-41ea297d6af7 */
                {
                  SGLfloat _lX = 0.0F;
                  SGLfloat _lY = 0.0F;
                  aol_locate(-1L, &_lX, &_lY);
                  aol_button_G_onButton(pContext) = sglRectangleActiveAreaGetStatus(_lX, _lY, -153.0F, 175.0F, 0.0F, 125.0F);
                }
              }
              break;

            case 2L:

              /* Object: Disable, Type: container, OID: 7f3cc6f3-46a2-475f-9a14-22ab115f0486 */
              {

                /* Object: Disable_1, Type: text, OID: ed747174-f6ce-47e7-9bfa-44a751d6b117 */
                {
                  static SGLuint8 _lArray0_Disable_1[255UL] = {83U,116U,97U,114U,116U};
                  sglIndexColori(5L);
                  sglIndexFontLineWidthi(2L);
                  sglIndexFonti(5L);
                  sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                  sgluWriteText(-79.0F, 150.0F, _lArray0_Disable_1, 255L);
                }

                /* Object: LT_outer_lines_1, Type: line, OID: 25d74602-967f-44c4-8b78-c36274d8a494 */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_STRAIGHT_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(-153.0F, 175.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }

                /* Object: LT_inner_lines_1, Type: line, OID: 5ca930a9-3095-4799-99a9-793789b3137d */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-152.0F, 126.0F);
                  sglVertex2f(-152.0F, 174.0F);
                  sglVertex2f(-1.0F, 174.0F);
                  sglEnd();
                }

                /* Object: RB_inner_lines_1, Type: line, OID: 1dfb718b-a48b-4601-8956-7bae23b08fb0 */
                {
                  /* outlined object part */
                  sglIndexColori(2L);
                  sglSetLineCaps(SGL_ROUNDED_CAPS);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-152.0F, 126.0F);
                  sglVertex2f(-1.0F, 126.0F);
                  sglVertex2f(-1.0F, 174.0F);
                  sglEnd();
                }

                /* Object: RB_outer_lines_1, Type: line, OID: d052607f-053f-4d09-b632-7209ce794969 */
                {
                  /* outlined object part */
                  sglIndexColori(7L);
                  sglBegin(SGL_LINE_STRIP);
                  sglVertex2f(-153.0F, 125.0F);
                  sglVertex2f(0.0F, 125.0F);
                  sglVertex2f(0.0F, 175.0F);
                  sglEnd();
                }
              }
              break;

            default:
              /* Do nothing */
              break;
            }
          }
          break;
        }
      }
      sglPopMatrixAndTranslate();
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:24
 *********************************************************/

