/*********************************************************
 **
 ** File  aol_PASP.c
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\PASP\PASP.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#include "aol_PASP.h"
#include "aol_imported_functions.h"
#include "sgl.h"


void aol_PASP_init(aol_typ_PASP *pContext)
{
  aol_PASP_S_BreakPointPosition(pContext, 0.0F);
  aol_PASP_S_Speed(pContext, 0.0F);

  pContext->_parentPriority = 0L;

}

void aol_PASP_predraw(aol_typ_PASP *pContext)
{

}

void aol_PASP_draw(aol_typ_PASP *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: D7, Type: container, OID: 2b171669-4c66-4890-8d40-42b08f2658aa */
    {

      /* Object: translation_filter, Type: filterTranslate, OID: e463d54d-be22-4ca3-a3ae-79c9b5eb6572 */
      {
#define FunctionalToValueX_translation_filter(pFunctional) (SGLfloat_le((pFunctional), 0.0F) ? 0.0F : (SGLfloat_ge((pFunctional), 4.0F) ? 93.0F : SGLfloat_mul((pFunctional), 23.25F)))
#define FunctionalToValueY_translation_filter(pFunctional) 0.0F

        /* Object: rectangle, Type: rectangle, OID: e55fd6d8-b301-44ba-8d86-f5d66d7242f0 */
        {
          if ((SGLfloat_eq(aol_PASP_G_Speed(pContext), 0.0F) ? SGL_FALSE : SGL_TRUE)) {
            /* filled object part */
            sglIndexColori(12L);
            sglDisable(SGL_MODULATE);
            sglEnable(SGL_POLYGON_SMOOTH);
            sglTransparency8(255L);
            sglDisable(SGL_TEXTURE_2D);
            sglDisable(SGL_TESSELLATION);
            sglBegin(SGL_POLYGON);
            sglVertex2f(FunctionalToValueX_translation_filter(aol_PASP_G_Speed(pContext)), FunctionalToValueY_translation_filter(aol_PASP_G_Speed(pContext)));
            sglVertex2f(1.0F, FunctionalToValueY_translation_filter(aol_PASP_G_Speed(pContext)));
            sglVertex2f(1.0F, aol_PASP_G_BreakPointPosition(pContext));
            sglVertex2f(FunctionalToValueX_translation_filter(aol_PASP_G_Speed(pContext)), aol_PASP_G_BreakPointPosition(pContext));
            sglEnd();
          }
        }
#undef FunctionalToValueX_translation_filter
#undef FunctionalToValueY_translation_filter
      }
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

