/*********************************************************
 **
 ** File  aol_color_table.c
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:26:47
 ** Command line: C:\Program Files (x86)\Esterel Technologies\SCADE R17.2\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sct
 *********************************************************/

#include "aol_color_table.h"

/* Color table definition */
const sgl_color aol_color_table[16UL] = 
{
{ 1.F,              0.501960784314F,  0.741176470588F,  1.F              }, /*     0 : Spare */
{ 1.F,              1.F,              1.F,              1.F              }, /*     1 : white */
{ 0.F,              0.F,              0.F,              1.F              }, /*     2 : black */
{ 0.764705882353F,  0.764705882353F,  0.764705882353F,  1.F              }, /*     3 : grey */
{ 0.588235294118F,  0.588235294118F,  0.588235294118F,  1.F              }, /*     4 : medium grey */
{ 0.333333333333F,  0.333333333333F,  0.333333333333F,  1.F              }, /*     5 : dark grey */
{ 0.0117647058824F, 0.0666666666667F, 0.133333333333F,  1.F              }, /*     6 : dark blue */
{ 0.0313725490196F, 0.0941176470588F, 0.223529411765F,  1.F              }, /*     7 : shadow */
{ 0.874509803922F,  0.874509803922F,  0.F,              1.F              }, /*     8 : yellow */
{ 0.917647058824F,  0.56862745098F,   0.F,              1.F              }, /*     9 : orange */
{ 0.749019607843F,  0.F,              0.0078431372549F, 1.F              }, /*    10 : red */
{ 0.129411764706F,  0.192156862745F,  0.290196078431F,  1.F              }, /*    11 : PASP dark */
{ 0.160784313725F,  0.290196078431F,  0.419607843137F,  1.F              }, /*    12 : PASP light */
{ 1.F,              0.501960784314F,  0.741176470588F,  1.F              }, /*    13 : Spare */
{ 1.F,              0.501960784314F,  0.741176470588F,  1.F              }, /*    14 : Spare */
{ 1.F,              0.501960784314F,  0.741176470588F,  1.F              }  /*    15 : Spare */
};

SGLint32 aol_color_table_size = 16UL;

SGLint32 aol_color_table_background_index = 6L;

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:26:47
 *********************************************************/

