/*********************************************************
 **
 ** File  aol_kcg_user_macros.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:25
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_KCG_USER_MACROS_H
#define _AOL_KCG_USER_MACROS_H

#include "sgl_types.h"

#define kcg_bool SGLbool
#define kcg_char SGLuint8
#define kcg_int SGLint32
#define kcg_real SGLfloat

#include "./user_macros.h"

#endif /* _AOL_KCG_USER_MACROS_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:25
 *********************************************************/
