/*********************************************************
 **
 ** File  aol_F.h
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\F\F.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:24
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_F_H
#define _AOL_F_H

#include "sgl_types.h"


/* Accessors */
#define aol_F_G_ButtonPressed(_C_) (_C_)->ButtonPressed
#define aol_F_S_ButtonPressed(_C_,_V_) (_C_)->ButtonPressed = (_V_)
#define aol_F_G_onMainButton(_C_) (_C_)->onMainButton
#define aol_F_S_onMainButton(_C_,_V_) (_C_)->onMainButton = (_V_)
#define aol_F_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct aol_typ_F_ {
  /* ------------------------- inputs --------------------------- */
  SGLbool ButtonPressed;
  /* ------------------------- outputs -------------------------- */
  SGLbool onMainButton;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} aol_typ_F;

/* Associated functions */
extern void aol_F_init(aol_typ_F *pContext);
extern void aol_F_predraw(aol_typ_F *pContext);
extern void aol_F_draw(aol_typ_F *pContext, SGLint32 pPriority);

#endif /* _AOL_F_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:24
 *********************************************************/

