/*********************************************************
 **
 ** File  aol_indicatorMarker.h
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\indicatorMarker.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_INDICATORMARKER_H
#define _AOL_INDICATORMARKER_H

#include "sgl_types.h"


/* Accessors */
#define aol_indicatorMarker_G_distanceIndicationPoint(_C_) (_C_)->distanceIndicationPoint
#define aol_indicatorMarker_S_distanceIndicationPoint(_C_,_V_) (_C_)->distanceIndicationPoint = (_V_)
#define aol_indicatorMarker_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct aol_typ_indicatorMarker_ {
  /* ------------------------- inputs --------------------------- */
  SGLfloat distanceIndicationPoint;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} aol_typ_indicatorMarker;

/* Associated functions */
extern void aol_indicatorMarker_init(aol_typ_indicatorMarker *pContext);
extern void aol_indicatorMarker_predraw(aol_typ_indicatorMarker *pContext);
extern void aol_indicatorMarker_draw(aol_typ_indicatorMarker *pContext, SGLint32 pPriority);

#endif /* _AOL_INDICATORMARKER_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

