/*********************************************************
 **
 ** File  aol_Y.h
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\Y\Y.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:24
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_Y_H
#define _AOL_Y_H

#include "sgl_types.h"


/* Accessors */
#define aol_Y_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct aol_typ_Y_ {
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} aol_typ_Y;

/* Associated functions */
extern void aol_Y_init(aol_typ_Y *pContext);
extern void aol_Y_predraw(aol_typ_Y *pContext);
extern void aol_Y_draw(aol_typ_Y *pContext, SGLint32 pPriority);

#endif /* _AOL_Y_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:24
 *********************************************************/

