/*********************************************************
 **
 ** File  aol_A.c
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\A\A.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#include "aol_A.h"
#include "aol_imported_functions.h"
#include "sgl.h"


void aol_A_init(aol_typ_A *pContext)
{
  aol_A_S_DistanceToTarget(pContext, 0.0F);
  aol_A_S_DistanceToTargetVisiblityDigital(pContext, SGL_TRUE);
  aol_A_S_InterpolatedDistanceToTarget(pContext, 0.0F);
  aol_A_S_DistToTargetBarVisibility(pContext, SGL_FALSE);
  aol_A_S_OverA(pContext, SGL_FALSE);

  pContext->_parentPriority = 0L;

}

void aol_A_predraw(aol_typ_A *pContext)
{

}

void aol_A_draw(aol_typ_A *pContext, SGLint32 pPriority)
{
  SGLuint32 _lParentMasks = sglGetActiveMasks();
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: A, Type: container, OID: 7ab1f45c-fa3d-429e-9a24-0966cd072f79 */
    {

      /* Object: A1, Type: container, OID: 2b20693a-ed3d-4475-b1be-c511cd8fc4cd */
      {

        /* Object: A1_1, Type: rectangle, OID: 46f0f3ac-4c9b-48a4-a070-8ee0dd0a59f7 */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglDisable(SGL_MODULATE);
          sglEnable(SGL_POLYGON_SMOOTH);
          sglTransparency8(255L);
          sglDisable(SGL_TEXTURE_2D);
          sglDisable(SGL_TESSELLATION);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-27.0F, 96.0F);
          sglVertex2f(27.0F, 96.0F);
          sglVertex2f(27.0F, 150.0F);
          sglVertex2f(-27.0F, 150.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglIndexHaloColori(-1L);
          sglIndexLineWidthi(0L);
          sglIndexLineStipplei(0L);
          sglDisable(SGL_LINE_HALOING);
          sglSetLineCaps(SGL_ROUNDED_CAPS);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-27.0F, 96.0F);
          sglVertex2f(27.0F, 96.0F);
          sglVertex2f(27.0F, 150.0F);
          sglVertex2f(-27.0F, 150.0F);
          sglEnd();
        }

        /* Object: line, Type: line, OID: 87bf0468-23ef-4877-9697-b5206d9056f7 */
        {
          /* outlined object part */
          sglIndexColori(2L);
          sglBegin(SGL_LINE_STRIP);
          sglVertex2f(-27.0F, 96.0F);
          sglVertex2f(-27.0F, 150.0F);
          sglVertex2f(27.0F, 150.0F);
          sglEnd();
        }
      }

      /* Object: A2, Type: container, OID: 03acb8fc-c594-4315-8435-1216ee89334b */
      {

        /* Object: A2_1, Type: rectangle, OID: ba5fa3f1-8e84-447e-beab-569eb1328717 */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-27.0F, 95.0F);
          sglVertex2f(27.0F, 95.0F);
          sglVertex2f(27.0F, 65.0F);
          sglVertex2f(-27.0F, 65.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-27.0F, 95.0F);
          sglVertex2f(27.0F, 95.0F);
          sglVertex2f(27.0F, 65.0F);
          sglVertex2f(-27.0F, 65.0F);
          sglEnd();
        }

        /* Object: line_1, Type: line, OID: 06898ba4-a008-4bc5-bcbe-63d3bda11284 */
        {
          /* outlined object part */
          sglIndexColori(2L);
          sglSetLineCaps(SGL_STRAIGHT_CAPS);
          sglBegin(SGL_LINE_STRIP);
          sglVertex2f(-27.0F, 65.0F);
          sglVertex2f(-27.0F, 95.0F);
          sglVertex2f(27.0F, 95.0F);
          sglEnd();
        }

        /* Object: DistanceToTargetDigital, Type: bifont, OID: 212f66a9-7da4-4073-a0dc-a74a0bb3ab7a */
        {
          if (aol_A_G_DistanceToTargetVisiblityDigital(pContext)) {
            sglIndexColori(3L);
            sglIndexFontLineWidthi(2L);
            sglIndexFonti(0L);
            sglSetTextAlignment(SGL_ALIGN_RIGHT, SGL_ALIGN_MIDDLE);
            sglSetSecondFontAttributes(3L, 0L, 2L);
            {
              sgl_numeric_format _lFormat;
              _lFormat.l_integralPart = 5L;
              _lFormat.l_fractionalPart = 0L;
              _lFormat.l_secondFontPos = 0L;
              _lFormat.b_separator = 46U;
              _lFormat.b_leadingZeros = SGL_FALSE;
              _lFormat.l_displaySign = SGL_SIGN_NEVER;
              sgluWriteFloat(23.0F, 80.0F, SGLfloat_mul((SGLfloat)(SGLint32)SGLfloat_div(SGLfloat_add(aol_A_G_DistanceToTarget(pContext), 5.0F), 10.0F), 10.0F), &_lFormat);
            }
          }
        }
      }

      /* Object: A3, Type: container, OID: 108996ed-c7be-404d-b6ef-abf8b044f977 */
      {

        /* Object: A3_1, Type: rectangle, OID: 8bf89e58-0bac-4ed8-9927-0a64745030bf */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-27.0F, 66.0F);
          sglVertex2f(27.0F, 66.0F);
          sglVertex2f(27.0F, -125.0F);
          sglVertex2f(-27.0F, -125.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglSetLineCaps(SGL_ROUNDED_CAPS);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-27.0F, 66.0F);
          sglVertex2f(27.0F, 66.0F);
          sglVertex2f(27.0F, -125.0F);
          sglVertex2f(-27.0F, -125.0F);
          sglEnd();
        }

        /* Object: line_2, Type: line, OID: 8115d86c-50e2-4338-aed8-f26a4b2986d3 */
        {
          /* outlined object part */
          sglIndexColori(2L);
          sglBegin(SGL_LINE_STRIP);
          sglVertex2f(-27.0F, -125.0F);
          sglVertex2f(-27.0F, 66.0F);
          sglVertex2f(27.0F, 66.0F);
          sglEnd();
        }

        /* Object: DistanceToTargetBar, Type: referenceContainer, OID: 150532c3-94a9-4174-95ab-05f53ff99d4c */
        {
          if (aol_A_G_DistToTargetBarVisibility(pContext)) {
            sglPushMatrixAndTranslate(0.0F, -33.0F);
            {
              aol_typ_DistanceToTargetBar _lSubContextVar;
              aol_typ_DistanceToTargetBar *_lSubContext = &_lSubContextVar;
              aol_DistanceToTargetBar_init(_lSubContext);
              aol_DistanceToTargetBar_S_DistanceToTargetBarVisible(_lSubContext, aol_A_G_DistanceToTargetVisiblityDigital(pContext));
              aol_DistanceToTargetBar_S_InterpolatedDistanceToTarget(_lSubContext, aol_A_G_InterpolatedDistanceToTarget(pContext));
              _lSubContext->_parentPriority = pContext->_parentPriority;
              aol_DistanceToTargetBar_draw(_lSubContext, pPriority);
            }
            sglPopMatrixAndTranslate();
          }
        }
      }

      /* Object: A4, Type: container, OID: 7ccccd5d-9426-41a2-9faf-7ef38861b0d2 */
      {

        /* Object: A4_1, Type: rectangle, OID: 108976f0-5d3d-4e25-bb97-b3852ce3d2c2 */
        {
          sglSetActiveMasks(_lParentMasks);
          /* filled object part */
          sglIndexColori(6L);
          sglDisable(SGL_MODULATE);
          sglEnable(SGL_POLYGON_SMOOTH);
          sglTransparency8(255L);
          sglDisable(SGL_TEXTURE_2D);
          sglDisable(SGL_TESSELLATION);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-27.0F, -125.0F);
          sglVertex2f(27.0F, -125.0F);
          sglVertex2f(27.0F, -150.0F);
          sglVertex2f(-27.0F, -150.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglIndexHaloColori(-1L);
          sglIndexLineWidthi(0L);
          sglIndexLineStipplei(0L);
          sglDisable(SGL_LINE_HALOING);
          sglSetLineCaps(SGL_ROUNDED_CAPS);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-27.0F, -125.0F);
          sglVertex2f(27.0F, -125.0F);
          sglVertex2f(27.0F, -150.0F);
          sglVertex2f(-27.0F, -150.0F);
          sglEnd();
        }

        /* Object: line_3, Type: line, OID: d4993daf-076e-441f-bf90-7574608e34e5 */
        {
          /* outlined object part */
          sglIndexColori(2L);
          sglBegin(SGL_LINE_STRIP);
          sglVertex2f(-27.0F, -150.0F);
          sglVertex2f(-27.0F, -125.0F);
          sglVertex2f(26.0F, -125.5F);
          sglEnd();
        }
      }

      /* Object: rectangle_area, Type: rectangleArea, OID: 556d42aa-d332-49a4-aa34-717eb5ec5355 */
      {
        SGLfloat _lX = 0.0F;
        SGLfloat _lY = 0.0F;
        aol_locate(-1L, &_lX, &_lY);
        aol_A_G_OverA(pContext) = sglRectangleActiveAreaGetStatus(_lX, _lY, -27.0F, 150.0F, 27.0F, -150.0F);
      }
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

