/*********************************************************
 **
 ** File  aol_G.c
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\G\G.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:24
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#include "aol_G.h"
#include "aol_imported_functions.h"
#include "sgl.h"


void aol_G_init(aol_typ_G *pContext)
{
  {
    static SGLfloat _lArray0[4UL] = {0.0F,0.0F,0.0F,0.0F};
    aol_G_S_localTimeArray(pContext, _lArray0);
  }

  pContext->_parentPriority = 0L;

}

void aol_G_predraw(aol_typ_G *pContext)
{

}

void aol_G_draw(aol_typ_G *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: G, Type: container, OID: 672b461a-a068-4def-a984-78eeb8665d83 */
    {
      sglPushMatrixAndTranslate(0.0F, -1.0F);

      /* Object: G1, Type: container, OID: ba513de4-c76f-4255-a727-6a6d51f9bcd0 */
      {
        sglPushMatrixAndTranslate(0.0F, 0.5F);

        /* Object: G1_1, Type: rectangle, OID: 3c9c43b3-010b-4dda-866a-6b44c2821726 */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglDisable(SGL_MODULATE);
          sglEnable(SGL_POLYGON_SMOOTH);
          sglTransparency8(255L);
          sglDisable(SGL_TEXTURE_2D);
          sglDisable(SGL_TESSELLATION);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglVertex2f(-74.0F, 25.0F);
          sglVertex2f(-123.0F, 25.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglIndexHaloColori(-1L);
          sglIndexLineWidthi(0L);
          sglIndexLineStipplei(0L);
          sglDisable(SGL_LINE_HALOING);
          sglSetLineCaps(SGL_ROUNDED_CAPS);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglVertex2f(-74.0F, 25.0F);
          sglVertex2f(-123.0F, 25.0F);
          sglEnd();
        }

        /* Object: line, Type: line, OID: 75be6965-75a7-44ad-be44-63e659972027 */
        {
          /* outlined object part */
          sglIndexColori(2L);
          sglBegin(SGL_LINE_STRIP);
          sglVertex2f(-123.0F, 25.0F);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglEnd();
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: G2, Type: container, OID: 37735ff1-ef48-4131-a70d-2c61714ade56 */
      {
        sglPushMatrixAndTranslate(0.0F, -49.5F);

        /* Object: G1_2, Type: rectangle, OID: ac8052a4-c4fd-4431-b310-5d3415bd7e04 */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglVertex2f(-74.0F, 25.0F);
          sglVertex2f(-123.0F, 25.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglVertex2f(-74.0F, 25.0F);
          sglVertex2f(-123.0F, 25.0F);
          sglEnd();
        }

        /* Object: line_1, Type: line, OID: 58b3c7ac-b0cd-4507-b53a-aad11947cc14 */
        {
          /* outlined object part */
          sglIndexColori(2L);
          sglBegin(SGL_LINE_STRIP);
          sglVertex2f(-123.0F, 25.0F);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglEnd();
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: G3, Type: container, OID: dceaefc1-6936-491d-b259-f39fa66bf8e4 */
      {
        sglPushMatrixAndTranslate(49.0F, 0.5F);

        /* Object: G1_3, Type: rectangle, OID: 22704cd6-517c-41ed-a4f9-cc03cc280603 */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglVertex2f(-74.0F, 25.0F);
          sglVertex2f(-123.0F, 25.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglVertex2f(-74.0F, 25.0F);
          sglVertex2f(-123.0F, 25.0F);
          sglEnd();
        }

        /* Object: line_2, Type: line, OID: ccfe97f8-a8ab-4965-af1b-d282f6b1cdc7 */
        {
          /* outlined object part */
          sglIndexColori(2L);
          sglBegin(SGL_LINE_STRIP);
          sglVertex2f(-123.0F, 25.0F);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglEnd();
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: G4, Type: container, OID: b7c956b9-75bb-4ad9-889c-a6ff6563d272 */
      {
        sglPushMatrixAndTranslate(49.0F, -49.5F);

        /* Object: G1_4, Type: rectangle, OID: 9c0f071d-d52a-4204-ab7a-7d85293be1ef */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglVertex2f(-74.0F, 25.0F);
          sglVertex2f(-123.0F, 25.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglVertex2f(-74.0F, 25.0F);
          sglVertex2f(-123.0F, 25.0F);
          sglEnd();
        }

        /* Object: line_3, Type: line, OID: e147fe1b-1467-473b-9513-9c1915db34c5 */
        {
          /* outlined object part */
          sglIndexColori(2L);
          sglBegin(SGL_LINE_STRIP);
          sglVertex2f(-123.0F, 25.0F);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglEnd();
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: G5, Type: container, OID: ef2464e4-1d82-49fb-b59e-033fc6add354 */
      {
        sglPushMatrixAndTranslate(98.0F, 0.5F);

        /* Object: G1_5, Type: rectangle, OID: 62d79c97-b2c3-4d31-868b-4ba98db09b7f */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglVertex2f(-74.0F, 25.0F);
          sglVertex2f(-123.0F, 25.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglVertex2f(-74.0F, 25.0F);
          sglVertex2f(-123.0F, 25.0F);
          sglEnd();
        }

        /* Object: line_4, Type: line, OID: 87e90a48-d817-4e8b-ae26-8d61744a30c1 */
        {
          /* outlined object part */
          sglIndexColori(2L);
          sglBegin(SGL_LINE_STRIP);
          sglVertex2f(-123.0F, 25.0F);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglEnd();
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: G6, Type: container, OID: 732d230c-839f-45c0-9e9d-3c993ca3cadb */
      {
        sglPushMatrixAndTranslate(98.0F, -49.5F);

        /* Object: G1_6, Type: rectangle, OID: 3789907a-c91d-4c19-89ec-b2bc066d4fa4 */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglVertex2f(-74.0F, 25.0F);
          sglVertex2f(-123.0F, 25.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglVertex2f(-74.0F, 25.0F);
          sglVertex2f(-123.0F, 25.0F);
          sglEnd();
        }

        /* Object: line_5, Type: line, OID: d2099b20-a66e-420e-acc1-9feb6d198069 */
        {
          /* outlined object part */
          sglIndexColori(2L);
          sglBegin(SGL_LINE_STRIP);
          sglVertex2f(-123.0F, 25.0F);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglEnd();
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: G7, Type: container, OID: 5d53b411-c7e9-42f6-ba3c-0e876296aa8c */
      {
        sglPushMatrixAndTranslate(147.0F, 0.5F);

        /* Object: G1_7, Type: rectangle, OID: 9e175ae0-faf7-4c14-a9d7-e1390092751a */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglVertex2f(-74.0F, 25.0F);
          sglVertex2f(-123.0F, 25.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglVertex2f(-74.0F, 25.0F);
          sglVertex2f(-123.0F, 25.0F);
          sglEnd();
        }

        /* Object: line_6, Type: line, OID: 416ebf53-4646-4855-b278-a0b6fd2e3e21 */
        {
          /* outlined object part */
          sglIndexColori(2L);
          sglBegin(SGL_LINE_STRIP);
          sglVertex2f(-123.0F, 25.0F);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglEnd();
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: G8, Type: container, OID: 8c5c5235-ca50-4295-ac39-52b5265c80a5 */
      {
        sglPushMatrixAndTranslate(147.0F, -49.5F);

        /* Object: G1_8, Type: rectangle, OID: 082560de-acb9-4735-9c75-6a094c720459 */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglVertex2f(-74.0F, 25.0F);
          sglVertex2f(-123.0F, 25.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglVertex2f(-74.0F, 25.0F);
          sglVertex2f(-123.0F, 25.0F);
          sglEnd();
        }

        /* Object: line_7, Type: line, OID: 6d53a4b5-4fe1-49d1-8920-7e8943916225 */
        {
          /* outlined object part */
          sglIndexColori(2L);
          sglBegin(SGL_LINE_STRIP);
          sglVertex2f(-123.0F, 25.0F);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglEnd();
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: G9, Type: container, OID: e68eae12-e9db-454b-8673-a462b248b477 */
      {
        sglPushMatrixAndTranslate(196.0F, 0.5F);

        /* Object: G1_9, Type: rectangle, OID: 94cc7dca-0000-4865-ac8b-7b4571eb27a4 */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglVertex2f(-74.0F, 25.0F);
          sglVertex2f(-123.0F, 25.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglVertex2f(-74.0F, 25.0F);
          sglVertex2f(-123.0F, 25.0F);
          sglEnd();
        }

        /* Object: line_8, Type: line, OID: 0d8af006-589a-45d9-95c3-2f27a300b813 */
        {
          /* outlined object part */
          sglIndexColori(2L);
          sglBegin(SGL_LINE_STRIP);
          sglVertex2f(-123.0F, 25.0F);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglEnd();
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: G10, Type: container, OID: da27c175-c05b-4445-9d4d-bc7fc3d1af21 */
      {
        sglPushMatrixAndTranslate(196.0F, -49.5F);

        /* Object: G1_10, Type: rectangle, OID: d812b2e9-9faf-49f6-a84c-8b27e9440c21 */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglVertex2f(-74.0F, 25.0F);
          sglVertex2f(-123.0F, 25.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglVertex2f(-74.0F, 25.0F);
          sglVertex2f(-123.0F, 25.0F);
          sglEnd();
        }

        /* Object: line_9, Type: line, OID: 857aa56e-5696-4327-8932-a6c8bed87a2b */
        {
          /* outlined object part */
          sglIndexColori(2L);
          sglBegin(SGL_LINE_STRIP);
          sglVertex2f(-123.0F, 25.0F);
          sglVertex2f(-123.0F, 75.0F);
          sglVertex2f(-74.0F, 75.0F);
          sglEnd();
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: G11, Type: container, OID: b0adaa82-44c7-4b5b-92a8-da603e4ad7cc */
      {
        sglPushMatrixAndTranslate(0.0F, 0.5F);

        /* Object: G11_1, Type: rectangle, OID: 6b890b16-40f5-415f-9e1f-ae1e9bd8de8b */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-123.0F, -25.0F);
          sglVertex2f(-60.0F, -25.0F);
          sglVertex2f(-60.0F, -75.0F);
          sglVertex2f(-123.0F, -75.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-123.0F, -25.0F);
          sglVertex2f(-60.0F, -25.0F);
          sglVertex2f(-60.0F, -75.0F);
          sglVertex2f(-123.0F, -75.0F);
          sglEnd();
        }

        /* Object: line_10, Type: line, OID: 6eeef273-9202-4e0a-8664-8618d5d091ae */
        {
          /* outlined object part */
          sglIndexColori(2L);
          sglBegin(SGL_LINE_STRIP);
          sglVertex2f(-123.0F, -75.0F);
          sglVertex2f(-123.0F, -25.0F);
          sglVertex2f(-60.0F, -25.0F);
          sglEnd();
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: G12, Type: container, OID: 0b8f81d6-25a7-462a-a2a3-41e23a7b2cc2 */
      {
        sglPushMatrixAndTranslate(0.0F, 0.5F);

        /* Object: G12_1, Type: rectangle, OID: c6d72b61-d6d4-4216-9623-04cecdac3a69 */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-60.0F, -25.0F);
          sglVertex2f(60.0F, -25.0F);
          sglVertex2f(60.0F, -75.0F);
          sglVertex2f(-60.0F, -75.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-60.0F, -25.0F);
          sglVertex2f(60.0F, -25.0F);
          sglVertex2f(60.0F, -75.0F);
          sglVertex2f(-60.0F, -75.0F);
          sglEnd();
        }

        /* Object: line_11, Type: line, OID: 158932ad-c8f6-423e-9db0-069e6421890e */
        {
          /* outlined object part */
          sglIndexColori(2L);
          sglBegin(SGL_LINE_STRIP);
          sglVertex2f(-60.0F, -75.0F);
          sglVertex2f(-60.0F, -25.0F);
          sglVertex2f(60.0F, -25.0F);
          sglEnd();
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: G13, Type: container, OID: c3ceb9d0-549e-4abe-bc0b-7b51339c9832 */
      {
        sglPushMatrixAndTranslate(0.0F, 0.5F);

        /* Object: G13_1, Type: rectangle, OID: d9e7c5b8-0987-446c-82ba-00c73fdb0841 */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(60.0F, -25.0F);
          sglVertex2f(123.0F, -25.0F);
          sglVertex2f(123.0F, -75.0F);
          sglVertex2f(60.0F, -75.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(60.0F, -25.0F);
          sglVertex2f(123.0F, -25.0F);
          sglVertex2f(123.0F, -75.0F);
          sglVertex2f(60.0F, -75.0F);
          sglEnd();
        }

        /* Object: line_12, Type: line, OID: e1f0cc1a-2ce8-4fc7-b26d-ed00d33622e0 */
        {
          /* outlined object part */
          sglIndexColori(2L);
          sglBegin(SGL_LINE_STRIP);
          sglVertex2f(60.0F, -75.0F);
          sglVertex2f(60.0F, -25.0F);
          sglVertex2f(123.0F, -25.0F);
          sglEnd();
        }

        /* Object: time, Type: container, OID: 3debc9a3-9056-4285-8c3d-f70e6ce0249e */
        {
          sglPushMatrixAndTranslate(171.5F, -83.5F);

          /* Object: hh, Type: bifont, OID: d779aa71-0357-438c-9da7-53fd522146ec */
          {
            sglIndexColori(1L);
            sglIndexFontLineWidthi(2L);
            sglIndexFonti(13L);
            sglSetTextAlignment(SGL_ALIGN_LEFT, SGL_ALIGN_BOTTOM);
            sglSetSecondFontAttributes(1L, 0L, 2L);
            {
              sgl_numeric_format _lFormat;
              _lFormat.l_integralPart = 2L;
              _lFormat.l_fractionalPart = 0L;
              _lFormat.l_secondFontPos = 0L;
              _lFormat.b_separator = 46U;
              _lFormat.b_leadingZeros = SGL_TRUE;
              _lFormat.l_displaySign = SGL_SIGN_NEVER;
              sgluWriteFloat(-110.0F, 33.0F, (aol_G_G_localTimeArray(pContext))[3], &_lFormat);
            }
          }

          /* Object: text, Type: text, OID: 34d72599-7e3b-4ee3-8448-7754a63f4f82 */
          {
            static SGLuint8 _lArray0_text[255UL] = {58U};
            sgluWriteText(-94.0F, 33.0F, _lArray0_text, 255L);
          }

          /* Object: mm, Type: bifont, OID: 154ba4b6-a434-4529-bbc2-f51494b62d37 */
          {
            sgl_numeric_format _lFormat;
            _lFormat.l_integralPart = 2L;
            _lFormat.l_fractionalPart = 0L;
            _lFormat.l_secondFontPos = 0L;
            _lFormat.b_separator = 46U;
            _lFormat.b_leadingZeros = SGL_TRUE;
            _lFormat.l_displaySign = SGL_SIGN_NEVER;
            sgluWriteFloat(-88.0F, 33.0F, (aol_G_G_localTimeArray(pContext))[2], &_lFormat);
          }

          /* Object: text_1, Type: text, OID: e8fca98c-de6b-4d3d-8587-5486ec07d990 */
          {
            static SGLuint8 _lArray0_text_1[255UL] = {58U};
            sgluWriteText(-72.25F, 33.0F, _lArray0_text_1, 255L);
          }

          /* Object: ss, Type: bifont, OID: 8b650749-6a98-4ae1-b290-1d0fcd8f64cb */
          {
            sgl_numeric_format _lFormat;
            _lFormat.l_integralPart = 2L;
            _lFormat.l_fractionalPart = 0L;
            _lFormat.l_secondFontPos = 0L;
            _lFormat.b_separator = 46U;
            _lFormat.b_leadingZeros = SGL_TRUE;
            _lFormat.l_displaySign = SGL_SIGN_NEVER;
            sgluWriteFloat(-67.25F, 33.25F, (aol_G_G_localTimeArray(pContext))[1], &_lFormat);
          }
          sglPopMatrixAndTranslate();
        }
        sglPopMatrixAndTranslate();
      }
      sglPopMatrixAndTranslate();
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:24
 *********************************************************/

