/*********************************************************
 **
 ** File  aol_keypad.h
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\Keypad\keypad.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:24
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_KEYPAD_H
#define _AOL_KEYPAD_H

#include "sgl_types.h"
#include "kcg_assign.h"


/* Accessors */
#define aol_keypad_G_keytype(_C_) (_C_)->keytype
#define aol_keypad_S_keytype(_C_,_V_) (_C_)->keytype = (_V_)
#define aol_keypad_G_ArrayLevelIndex(_C_) (*(_C_)->ArrayLevelIndex)
#define aol_keypad_S_ArrayLevelIndex(_C_,_V_) (_C_)->ArrayLevelIndex = &(_V_)
#define aol_keypad_G_ButtonPressed(_C_) (_C_)->ButtonPressed
#define aol_keypad_S_ButtonPressed(_C_,_V_) (_C_)->ButtonPressed = (_V_)
#define aol_keypad_G_keyarray(_C_) (_C_)->keyarray
#define aol_keypad_S_keyarray(_C_,_V_) kcg_assign((_C_)->keyarray, (_V_), sizeof(SGLbool [12UL]))
#define aol_keypad_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct aol_typ_keypad_ {
  /* ------------------------- inputs --------------------------- */
  SGLint32 keytype;
  SGLint32 (*ArrayLevelIndex)[12UL];
  SGLbool ButtonPressed;
  /* ------------------------- outputs -------------------------- */
  SGLbool keyarray[12UL];
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} aol_typ_keypad;

/* Associated functions */
extern void aol_keypad_init(aol_typ_keypad *pContext);
extern void aol_keypad_predraw(aol_typ_keypad *pContext);
extern void aol_keypad_draw(aol_typ_keypad *pContext, SGLint32 pPriority);

#endif /* _AOL_KEYPAD_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:24
 *********************************************************/

