/*********************************************************
 **
 ** File  aol_StatusSymbols.h
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\Symbols\StatusSymbols.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_STATUSSYMBOLS_H
#define _AOL_STATUSSYMBOLS_H

#include "sgl_types.h"


/* Accessors */
#define aol_StatusSymbols_G_StatusSymbol(_C_) (_C_)->StatusSymbol
#define aol_StatusSymbols_S_StatusSymbol(_C_,_V_) (_C_)->StatusSymbol = (_V_)
#define aol_StatusSymbols_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct aol_typ_StatusSymbols_ {
  /* ------------------------- inputs --------------------------- */
  SGLint32 StatusSymbol;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} aol_typ_StatusSymbols;

/* Associated functions */
extern void aol_StatusSymbols_init(aol_typ_StatusSymbols *pContext);
extern void aol_StatusSymbols_predraw(aol_typ_StatusSymbols *pContext);
extern void aol_StatusSymbols_draw(aol_typ_StatusSymbols *pContext, SGLint32 pPriority);

#endif /* _AOL_STATUSSYMBOLS_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

