/*********************************************************
 **
 ** File  aol_CircularSpeedGauge.c
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\CircularSpeedGauge\CircularSpeedGauge.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#include "aol_CircularSpeedGauge.h"
#include "aol_imported_functions.h"
#include "sgl.h"


void aol_CircularSpeedGauge_init(aol_typ_CircularSpeedGauge *pContext)
{
  aol_CircularSpeedGauge_S_Vperm(pContext, 0.0F);
  aol_CircularSpeedGauge_S_Vtarget(pContext, 0.0F);
  aol_CircularSpeedGauge_S_Vrelease(pContext, 0.0F);
  aol_CircularSpeedGauge_S_VpermVisible(pContext, SGL_TRUE);
  aol_CircularSpeedGauge_S_VtargetVisible(pContext, SGL_TRUE);
  aol_CircularSpeedGauge_S_VreleaseVisible(pContext, SGL_TRUE);
  aol_CircularSpeedGauge_S_VpermColor(pContext, 1L);
  aol_CircularSpeedGauge_S_VtargetColor(pContext, 5L);
  aol_CircularSpeedGauge_S_VreleaseColor(pContext, 4L);
  aol_CircularSpeedGauge_S_Vtarget_permVisible(pContext, SGL_FALSE);
  aol_CircularSpeedGauge_S_Vtarget_permColor(pContext, 1L);
  aol_CircularSpeedGauge_S_Vinterv(pContext, 0.0F);
  aol_CircularSpeedGauge_S_VintervColor(pContext, 9L);
  aol_CircularSpeedGauge_S_VintervVisible(pContext, SGL_FALSE);

  pContext->_parentPriority = 0L;

}

void aol_CircularSpeedGauge_predraw(aol_typ_CircularSpeedGauge *pContext)
{

}

void aol_CircularSpeedGauge_draw(aol_typ_CircularSpeedGauge *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: CircularSpeedGauge, Type: container, OID: 6cdd711d-79ea-47b7-bca0-5a91a4a48940 */
    {

      /* Object: TargetSpeed, Type: container, OID: 1d011d1f-851d-4579-a29c-921da7e04f52 */
      {

        /* Object: rotation_filter, Type: filterRotate, OID: 341aa6f8-6b65-4a26-9b8d-7fb822b2341a */
        {
#define FunctionalToValue_rotation_filter(pFunctional) SGLfloat_mul((pFunctional), -0.976666666667F)

          /* Object: TargetSpeedGauge, Type: crown, OID: 07395eb7-c33a-4420-a7fe-4bc8d1df3f3b */
          {
            if (SGLbool_and(aol_CircularSpeedGauge_G_VtargetVisible(pContext), SGLfloat_gt(aol_CircularSpeedGauge_G_Vtarget(pContext), 0.0F))) {
              if (SGLint32_ge(aol_CircularSpeedGauge_G_VtargetColor(pContext), 0L)) {
                /* filled object part */
                sglIndexColori(aol_CircularSpeedGauge_G_VtargetColor(pContext));
                sglDisable(SGL_MODULATE);
                sglEnable(SGL_POLYGON_SMOOTH);
                sglTransparency8(255L);
                sglDisable(SGL_TEXTURE_2D);
                sgluCrown2f(0.0F, 0.0F, 137.0F, 9.0F, 240.0F, SGLfloat_add(238.0F, FunctionalToValue_rotation_filter((SGLfloat_lt(aol_CircularSpeedGauge_G_Vtarget(pContext), 200.0F) ? aol_CircularSpeedGauge_G_Vtarget(pContext) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(aol_CircularSpeedGauge_G_Vtarget(pContext), 200.0F), 2.0F), 200.0F)))), SGL_TRUE, SGL_CROWN_FILLED);
              }
            }
          }

          /* Object: TargetSpeedHook, Type: crown, OID: 1406461a-a4bf-4816-a1b9-64da2a4b65e1 */
          {
            if (SGLbool_and(aol_CircularSpeedGauge_G_VtargetVisible(pContext), SGLfloat_lt(aol_CircularSpeedGauge_G_Vperm(pContext), aol_CircularSpeedGauge_G_Vtarget(pContext)))) {
              if (SGLint32_ge(aol_CircularSpeedGauge_G_VtargetColor(pContext), 0L)) {
                /* filled object part */
                sglIndexColori(aol_CircularSpeedGauge_G_VtargetColor(pContext));
                sglDisable(SGL_MODULATE);
                sglEnable(SGL_POLYGON_SMOOTH);
                sglTransparency8(255L);
                sglDisable(SGL_TEXTURE_2D);
                sgluCrown2f(0.0F, 0.0F, 137.0F, 20.0F, SGLfloat_add(238.0F, FunctionalToValue_rotation_filter((SGLfloat_lt(aol_CircularSpeedGauge_G_Vtarget(pContext), 200.0F) ? aol_CircularSpeedGauge_G_Vtarget(pContext) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(aol_CircularSpeedGauge_G_Vtarget(pContext), 200.0F), 2.0F), 200.0F)))), SGLfloat_add(236.0F, FunctionalToValue_rotation_filter((SGLfloat_lt(aol_CircularSpeedGauge_G_Vtarget(pContext), 200.0F) ? aol_CircularSpeedGauge_G_Vtarget(pContext) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(aol_CircularSpeedGauge_G_Vtarget(pContext), 200.0F), 2.0F), 200.0F)))), SGL_TRUE, SGL_CROWN_FILLED);
              }
            }
          }
#undef FunctionalToValue_rotation_filter
        }
      }

      /* Object: PermittedSpeed, Type: container, OID: 4e6f3b27-9072-4a63-b405-88f3b0e0167c */
      {

        /* Object: rotation_filter_1, Type: filterRotate, OID: 277a7f58-5491-4b9f-ad86-76a3de843ecf */
        {
#define FunctionalToValue_rotation_filter_1(pFunctional) SGLfloat_mul((pFunctional), -0.976666666667F)

          /* Object: PermittedSpeedGauge, Type: crown, OID: ac75bc42-fb0b-407c-a77d-65ca5eff0434 */
          {
            if (SGLbool_and(aol_CircularSpeedGauge_G_VpermVisible(pContext), SGLfloat_gt(aol_CircularSpeedGauge_G_Vperm(pContext), 0.0F))) {
              if (SGLint32_ge(aol_CircularSpeedGauge_G_VpermColor(pContext), 0L)) {
                /* filled object part */
                sglIndexColori(aol_CircularSpeedGauge_G_VpermColor(pContext));
                sglDisable(SGL_MODULATE);
                sglEnable(SGL_POLYGON_SMOOTH);
                sglTransparency8(255L);
                sglDisable(SGL_TEXTURE_2D);
                sgluCrown2f(0.0F, 0.0F, 137.0F, 9.0F, 240.0F, SGLfloat_add(236.0F, FunctionalToValue_rotation_filter_1((SGLfloat_lt(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F) ? aol_CircularSpeedGauge_G_Vperm(pContext) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F), 2.0F), 200.0F)))), SGL_TRUE, SGL_CROWN_FILLED);
              }
            }
          }

          /* Object: PermittedSpeedHook, Type: crown, OID: f3e7627b-d394-4d04-8846-59c51473d897 */
          {
            if (SGLbool_and(aol_CircularSpeedGauge_G_VpermVisible(pContext), SGLfloat_gt(aol_CircularSpeedGauge_G_Vperm(pContext), 0.0F))) {
              if (SGLint32_ge(aol_CircularSpeedGauge_G_VpermColor(pContext), 0L)) {
                /* filled object part */
                sglIndexColori(aol_CircularSpeedGauge_G_VpermColor(pContext));
                sglDisable(SGL_MODULATE);
                sglEnable(SGL_POLYGON_SMOOTH);
                sglTransparency8(255L);
                sglDisable(SGL_TEXTURE_2D);
                sgluCrown2f(0.0F, 0.0F, 137.0F, 20.0F, SGLfloat_add(238.0F, FunctionalToValue_rotation_filter_1((SGLfloat_lt(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F) ? aol_CircularSpeedGauge_G_Vperm(pContext) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F), 2.0F), 200.0F)))), SGLfloat_add(236.0F, FunctionalToValue_rotation_filter_1((SGLfloat_lt(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F) ? aol_CircularSpeedGauge_G_Vperm(pContext) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F), 2.0F), 200.0F)))), SGL_TRUE, SGL_CROWN_FILLED);
              }
            }
          }
#undef FunctionalToValue_rotation_filter_1
        }
      }

      /* Object: Target_Permitted, Type: container, OID: a8c8c11d-3992-4342-8232-dba7c54457f4 */
      {

        /* Object: rotation_filter_2, Type: filterRotate, OID: b373aa24-823d-4590-96c0-990e90c1a1d8 */
        {
#define FunctionalToValue_rotation_filter_2(pFunctional) SGLfloat_mul((pFunctional), -0.976666666667F)

          /* Object: PermittedSpeedGauge_1, Type: crown, OID: 88677fdc-021c-4041-8c00-63bbe3ae1f59 */
          {
            if (SGLbool_and(aol_CircularSpeedGauge_G_Vtarget_permVisible(pContext), SGLfloat_lt(aol_CircularSpeedGauge_G_Vtarget(pContext), aol_CircularSpeedGauge_G_Vperm(pContext)))) {
              if (SGLint32_ge(aol_CircularSpeedGauge_G_Vtarget_permColor(pContext), 0L)) {
                /* filled object part */
                sglIndexColori(aol_CircularSpeedGauge_G_Vtarget_permColor(pContext));
                sglDisable(SGL_MODULATE);
                sglEnable(SGL_POLYGON_SMOOTH);
                sglTransparency8(255L);
                sglDisable(SGL_TEXTURE_2D);
                sgluCrown2f(0.0F, 0.0F, 137.0F, 9.0F, SGLfloat_add(240.0F, FunctionalToValue_rotation_filter_2((SGLfloat_lt(aol_CircularSpeedGauge_G_Vtarget(pContext), 200.0F) ? SGLfloat_add(aol_CircularSpeedGauge_G_Vtarget(pContext), 2.0F) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(aol_CircularSpeedGauge_G_Vtarget(pContext), 200.0F), 2.0F), 202.0F)))), SGLfloat_add(236.0F, FunctionalToValue_rotation_filter_2((SGLfloat_lt(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F) ? aol_CircularSpeedGauge_G_Vperm(pContext) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F), 2.0F), 200.0F)))), SGL_TRUE, SGL_CROWN_FILLED);
                /* outlined object part */
                sglDisable(SGL_TEXTURE_2D);
                sglIndexColori(aol_CircularSpeedGauge_G_Vtarget_permColor(pContext));
                sglIndexHaloColori(-1L);
                sglIndexLineWidthi(1L);
                sglIndexLineStipplei(0L);
                sglDisable(SGL_LINE_HALOING);
                sglSetLineCaps(SGL_ROUNDED_CAPS);
                sglTransparency8(0L);
                sgluCrown2f(0.0F, 0.0F, 137.0F, 9.0F, SGLfloat_add(240.0F, FunctionalToValue_rotation_filter_2((SGLfloat_lt(aol_CircularSpeedGauge_G_Vtarget(pContext), 200.0F) ? SGLfloat_add(aol_CircularSpeedGauge_G_Vtarget(pContext), 2.0F) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(aol_CircularSpeedGauge_G_Vtarget(pContext), 200.0F), 2.0F), 202.0F)))), SGLfloat_add(236.0F, FunctionalToValue_rotation_filter_2((SGLfloat_lt(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F) ? aol_CircularSpeedGauge_G_Vperm(pContext) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F), 2.0F), 200.0F)))), SGL_TRUE, SGL_CROWN_OUTLINE);
              }
            }
          }

          /* Object: PermittedSpeedHook_1, Type: crown, OID: 7daa88a7-e3f8-4bc8-81c6-025ddd85367e */
          {
            if (SGLbool_and(aol_CircularSpeedGauge_G_Vtarget_permVisible(pContext), SGLfloat_lt(aol_CircularSpeedGauge_G_Vtarget(pContext), aol_CircularSpeedGauge_G_Vperm(pContext)))) {
              if (SGLint32_ge(aol_CircularSpeedGauge_G_Vtarget_permColor(pContext), 0L)) {
                /* filled object part */
                sglIndexColori(aol_CircularSpeedGauge_G_Vtarget_permColor(pContext));
                sglDisable(SGL_MODULATE);
                sglEnable(SGL_POLYGON_SMOOTH);
                sglTransparency8(255L);
                sglDisable(SGL_TEXTURE_2D);
                sgluCrown2f(0.0F, 0.0F, 137.0F, 20.0F, SGLfloat_add(238.0F, FunctionalToValue_rotation_filter_2((SGLfloat_lt(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F) ? aol_CircularSpeedGauge_G_Vperm(pContext) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F), 2.0F), 200.0F)))), SGLfloat_add(236.0F, FunctionalToValue_rotation_filter_2((SGLfloat_lt(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F) ? aol_CircularSpeedGauge_G_Vperm(pContext) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F), 2.0F), 200.0F)))), SGL_TRUE, SGL_CROWN_FILLED);
                /* outlined object part */
                sglDisable(SGL_TEXTURE_2D);
                sglIndexColori(aol_CircularSpeedGauge_G_Vtarget_permColor(pContext));
                sglIndexHaloColori(-1L);
                sglIndexLineWidthi(1L);
                sglIndexLineStipplei(0L);
                sglDisable(SGL_LINE_HALOING);
                sglSetLineCaps(SGL_STRAIGHT_CAPS);
                sglTransparency8(0L);
                sgluCrown2f(0.0F, 0.0F, 137.0F, 20.0F, SGLfloat_add(238.0F, FunctionalToValue_rotation_filter_2((SGLfloat_lt(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F) ? aol_CircularSpeedGauge_G_Vperm(pContext) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F), 2.0F), 200.0F)))), SGLfloat_add(236.0F, FunctionalToValue_rotation_filter_2((SGLfloat_lt(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F) ? aol_CircularSpeedGauge_G_Vperm(pContext) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F), 2.0F), 200.0F)))), SGL_TRUE, SGL_CROWN_OUTLINE);
              }
            }
          }
#undef FunctionalToValue_rotation_filter_2
        }
      }

      /* Object: Permitted_Vfloi, Type: container, OID: 1506103f-d90e-4383-bff3-ec8e2807a6bd */
      {

        /* Object: rotation_filter_3, Type: filterRotate, OID: ea191bdf-0747-42ee-9ce0-b574b9f0a42c */
        {
#define FunctionalToValue_rotation_filter_3(pFunctional) SGLfloat_mul((pFunctional), -0.976666666667F)

          /* Object: PermittedSpeedHook_2, Type: crown, OID: 20cf27ee-cecb-4c2a-ac5b-8507d92238b0 */
          {
            if (SGLbool_and(aol_CircularSpeedGauge_G_VintervVisible(pContext), SGLfloat_gt(aol_CircularSpeedGauge_G_Vinterv(pContext), 0.0F))) {
              if (SGLint32_ge(aol_CircularSpeedGauge_G_VintervColor(pContext), 0L)) {
                /* filled object part */
                sglIndexColori(aol_CircularSpeedGauge_G_VintervColor(pContext));
                sglDisable(SGL_MODULATE);
                sglEnable(SGL_POLYGON_SMOOTH);
                sglTransparency8(255L);
                sglDisable(SGL_TEXTURE_2D);
                sgluCrown2f(0.0F, 0.0F, 137.0F, 20.0F, SGLfloat_add(240.0F, FunctionalToValue_rotation_filter_3((SGLfloat_lt(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F) ? SGLfloat_add(aol_CircularSpeedGauge_G_Vperm(pContext), 3.5F) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(SGLfloat_add(aol_CircularSpeedGauge_G_Vperm(pContext), 3.5F), 200.0F), 2.0F), 200.0F)))), SGLfloat_add(236.0F, FunctionalToValue_rotation_filter_3((SGLfloat_lt(aol_CircularSpeedGauge_G_Vinterv(pContext), 200.0F) ? aol_CircularSpeedGauge_G_Vinterv(pContext) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(aol_CircularSpeedGauge_G_Vinterv(pContext), 200.0F), 2.0F), 200.0F)))), SGL_TRUE, SGL_CROWN_FILLED);
                /* outlined object part */
                sglDisable(SGL_TEXTURE_2D);
                sglIndexColori(aol_CircularSpeedGauge_G_VintervColor(pContext));
                sglIndexHaloColori(-1L);
                sglIndexLineWidthi(1L);
                sglIndexLineStipplei(0L);
                sglDisable(SGL_LINE_HALOING);
                sglSetLineCaps(SGL_STRAIGHT_CAPS);
                sglTransparency8(0L);
                sgluCrown2f(0.0F, 0.0F, 137.0F, 20.0F, SGLfloat_add(240.0F, FunctionalToValue_rotation_filter_3((SGLfloat_lt(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F) ? SGLfloat_add(aol_CircularSpeedGauge_G_Vperm(pContext), 3.5F) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(SGLfloat_add(aol_CircularSpeedGauge_G_Vperm(pContext), 3.5F), 200.0F), 2.0F), 200.0F)))), SGLfloat_add(236.0F, FunctionalToValue_rotation_filter_3((SGLfloat_lt(aol_CircularSpeedGauge_G_Vinterv(pContext), 200.0F) ? aol_CircularSpeedGauge_G_Vinterv(pContext) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(aol_CircularSpeedGauge_G_Vinterv(pContext), 200.0F), 2.0F), 200.0F)))), SGL_TRUE, SGL_CROWN_OUTLINE);
              }
            }
          }
#undef FunctionalToValue_rotation_filter_3
        }
      }

      /* Object: ReleaseSpeed, Type: container, OID: 615e55e1-15fb-4233-b5f4-d6437b3d7b44 */
      {

        /* Object: rotation_filter_4, Type: filterRotate, OID: f458551b-dbab-48ea-9ffb-d5c8442d27ce */
        {
#define FunctionalToValue_rotation_filter_4(pFunctional) SGLfloat_mul((pFunctional), -0.976666666667F)

          /* Object: ReleaseSpeedGauge, Type: crown, OID: 53e5b299-b459-4511-829d-b9d72f0b41b3 */
          {
            if (SGLbool_and(aol_CircularSpeedGauge_G_VreleaseVisible(pContext), SGLfloat_gt(aol_CircularSpeedGauge_G_Vrelease(pContext), 0.0F))) {
              if (SGLint32_ge(aol_CircularSpeedGauge_G_VreleaseColor(pContext), 0L)) {
                /* filled object part */
                sglIndexColori(aol_CircularSpeedGauge_G_VreleaseColor(pContext));
                sglDisable(SGL_MODULATE);
                sglEnable(SGL_POLYGON_SMOOTH);
                sglTransparency8(255L);
                sglDisable(SGL_TEXTURE_2D);
                sgluCrown2f(0.0F, 0.0F, 137.0F, 9.0F, 240.0F, SGLfloat_add(238.0F, FunctionalToValue_rotation_filter_4((SGLfloat_lt(aol_CircularSpeedGauge_G_Vrelease(pContext), 200.0F) ? aol_CircularSpeedGauge_G_Vrelease(pContext) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(aol_CircularSpeedGauge_G_Vrelease(pContext), 200.0F), 2.0F), 200.0F)))), SGL_TRUE, SGL_CROWN_FILLED);
                /* outlined object part */
                sglDisable(SGL_TEXTURE_2D);
                sglIndexColori(aol_CircularSpeedGauge_G_VreleaseColor(pContext));
                sglIndexHaloColori(-1L);
                sglIndexLineWidthi(1L);
                sglIndexLineStipplei(0L);
                sglDisable(SGL_LINE_HALOING);
                sglSetLineCaps(SGL_STRAIGHT_CAPS);
                sglTransparency8(0L);
                sgluCrown2f(0.0F, 0.0F, 137.0F, 9.0F, 240.0F, SGLfloat_add(238.0F, FunctionalToValue_rotation_filter_4((SGLfloat_lt(aol_CircularSpeedGauge_G_Vrelease(pContext), 200.0F) ? aol_CircularSpeedGauge_G_Vrelease(pContext) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(aol_CircularSpeedGauge_G_Vrelease(pContext), 200.0F), 2.0F), 200.0F)))), SGL_TRUE, SGL_CROWN_OUTLINE);
              }
            }
          }

          /* Object: PermittedSpeedBorder, Type: crown, OID: c2c7b952-fac5-4e46-9a09-8d2869c0d427 */
          {
            if (SGLbool_and(aol_CircularSpeedGauge_G_VreleaseVisible(pContext), SGLfloat_gt(aol_CircularSpeedGauge_G_Vrelease(pContext), 0.0F))) {
              /* filled object part */
              sglIndexColori(2L);
              sglDisable(SGL_MODULATE);
              sglEnable(SGL_POLYGON_SMOOTH);
              sglTransparency8(255L);
              sglDisable(SGL_TEXTURE_2D);
              sgluCrown2f(0.0F, 0.0F, 132.0F, 1.0F, 240.0F, SGLfloat_add(238.0F, FunctionalToValue_rotation_filter_4((SGLfloat_gt(aol_CircularSpeedGauge_G_Vperm(pContext), aol_CircularSpeedGauge_G_Vrelease(pContext)) ? (SGLfloat_lt(aol_CircularSpeedGauge_G_Vrelease(pContext), 200.0F) ? aol_CircularSpeedGauge_G_Vrelease(pContext) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(aol_CircularSpeedGauge_G_Vrelease(pContext), 200.0F), 2.0F), 200.0F)) : (SGLfloat_lt(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F) ? aol_CircularSpeedGauge_G_Vperm(pContext) : SGLfloat_add(SGLfloat_div(SGLfloat_sub(aol_CircularSpeedGauge_G_Vperm(pContext), 200.0F), 2.0F), 200.0F))))), SGL_TRUE, SGL_CROWN_FILLED);
            }
          }

          /* Object: PermittedSpeedHalfGauge, Type: crown, OID: 8d3ecb35-4477-4bcc-9ba3-af303c0a7720 */
          {
            if (SGLbool_and(aol_CircularSpeedGauge_G_VreleaseVisible(pContext), SGLfloat_gt(aol_CircularSpeedGauge_G_Vrelease(pContext), 0.0F))) {
              if (SGLint32_ge(aol_CircularSpeedGauge_G_Vtarget_permColor(pContext), 0L)) {
                /* filled object part */
                sglIndexColori(aol_CircularSpeedGauge_G_Vtarget_permColor(pContext));
                sglDisable(SGL_MODULATE);
                sglEnable(SGL_POLYGON_SMOOTH);
                sglTransparency8(255L);
                sglDisable(SGL_TEXTURE_2D);
                sgluCrown2f(0.0F, 0.0F, 131.0F, 3.0F, 240.0F, SGLfloat_add(238.0F, FunctionalToValue_rotation_filter_4((SGLfloat_gt(aol_CircularSpeedGauge_G_Vperm(pContext), aol_CircularSpeedGauge_G_Vrelease(pContext)) ? aol_CircularSpeedGauge_G_Vrelease(pContext) : SGLfloat_add(aol_CircularSpeedGauge_G_Vperm(pContext), 2.0F)))), SGL_TRUE, SGL_CROWN_FILLED);
                /* outlined object part */
                sglDisable(SGL_TEXTURE_2D);
                sglIndexColori(aol_CircularSpeedGauge_G_Vtarget_permColor(pContext));
                sglIndexHaloColori(-1L);
                sglIndexLineWidthi(1L);
                sglIndexLineStipplei(0L);
                sglDisable(SGL_LINE_HALOING);
                sglSetLineCaps(SGL_STRAIGHT_CAPS);
                sglTransparency8(0L);
                sgluCrown2f(0.0F, 0.0F, 131.0F, 3.0F, 240.0F, SGLfloat_add(238.0F, FunctionalToValue_rotation_filter_4((SGLfloat_gt(aol_CircularSpeedGauge_G_Vperm(pContext), aol_CircularSpeedGauge_G_Vrelease(pContext)) ? aol_CircularSpeedGauge_G_Vrelease(pContext) : SGLfloat_add(aol_CircularSpeedGauge_G_Vperm(pContext), 2.0F)))), SGL_TRUE, SGL_CROWN_OUTLINE);
              }
            }
          }
#undef FunctionalToValue_rotation_filter_4
        }
      }
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

