/*********************************************************
 **
 ** File  aol_indicatorMarker.c
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\indicatorMarker.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#include "aol_indicatorMarker.h"
#include "aol_imported_functions.h"
#include "sgl.h"


void aol_indicatorMarker_init(aol_typ_indicatorMarker *pContext)
{
  aol_indicatorMarker_S_distanceIndicationPoint(pContext, 0.0F);

  pContext->_parentPriority = 0L;

}

void aol_indicatorMarker_predraw(aol_typ_indicatorMarker *pContext)
{

}

void aol_indicatorMarker_draw(aol_typ_indicatorMarker *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: group, Type: container, OID: 229329a8-35d3-4ef0-9498-21d6699f54c4 */
    {
      sglPushMatrixAndTranslate(0.0F, aol_indicatorMarker_G_distanceIndicationPoint(pContext));

      /* Object: line, Type: line, OID: ebc04bc1-96a0-4ce3-a522-26c490a236a2 */
      {
        /* outlined object part */
        sglDisable(SGL_TEXTURE_2D);
        sglIndexColori(8L);
        sglIndexHaloColori(-1L);
        sglIndexLineWidthi(2L);
        sglIndexLineStipplei(0L);
        sglDisable(SGL_LINE_HALOING);
        sglSetLineCaps(SGL_STRAIGHT_CAPS);
        sglTransparency8(255L);
        sglBegin(SGL_LINES);
        sglVertex2f(93.0F, 0.0F);
        sglVertex2f(1.0F, 0.0F);
        sglEnd();
      }
      sglPopMatrixAndTranslate();
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

