/*********************************************************
 **
 ** File  aol_DistanceToTargetBar.c
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\DistanceToTargetBar\DistanceToTargetBar.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#include "aol_DistanceToTargetBar.h"
#include "aol_imported_functions.h"
#include "sgl.h"


void aol_DistanceToTargetBar_init(aol_typ_DistanceToTargetBar *pContext)
{
  aol_DistanceToTargetBar_S_DistanceToTargetBarVisible(pContext, SGL_FALSE);
  aol_DistanceToTargetBar_S_InterpolatedDistanceToTarget(pContext, 0.0F);

  pContext->_parentPriority = 0L;

}

void aol_DistanceToTargetBar_predraw(aol_typ_DistanceToTargetBar *pContext)
{

}

void aol_DistanceToTargetBar_draw(aol_typ_DistanceToTargetBar *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: DistanceToTargetBar, Type: container, OID: 6c95efdd-ca0c-4b58-b062-8134d966d51d */
    {
      if (aol_DistanceToTargetBar_G_DistanceToTargetBarVisible(pContext)) {

        /* Object: Scale, Type: container, OID: e9954fe1-c720-47ee-93e6-8aa093d0ccd3 */
        {

          /* Object: 0, Type: line, OID: c44214e2-2f34-43a0-88f4-70d08a095564 */
          {
            /* outlined object part */
            sglDisable(SGL_TEXTURE_2D);
            sglIndexColori(3L);
            sglIndexHaloColori(-1L);
            sglIndexLineWidthi(2L);
            sglIndexLineStipplei(0L);
            sglDisable(SGL_LINE_HALOING);
            sglSetLineCaps(SGL_ROUNDED_CAPS);
            sglTransparency8(255L);
            sglBegin(SGL_LINES);
            sglVertex2f(-15.0F, -89.5F);
            sglVertex2f(-2.0F, -89.5F);
            sglEnd();
          }

          /* Object: 100, Type: line, OID: 34ae9319-d2fa-48be-b853-45abae9423b0 */
          {
            /* outlined object part */
            sglIndexLineWidthi(1L);
            sglBegin(SGL_LINES);
            sglVertex2f(-11.0F, -56.5F);
            sglVertex2f(-2.0F, -56.5F);
          }

          /* Object: 200, Type: line, OID: d731a940-299a-4ab9-ada3-c94eb8777d88 */
          {
            /* outlined object part */
            sglVertex2f(-11.0F, -9.5F);
            sglVertex2f(-2.0F, -9.5F);
          }

          /* Object: 300, Type: line, OID: 99c1d01c-c2ad-4c81-8a89-dcbc0861e716 */
          {
            /* outlined object part */
            sglVertex2f(-11.0F, 16.5F);
            sglVertex2f(-2.0F, 16.5F);
          }

          /* Object: 400, Type: line, OID: add83c3b-24a4-449d-a765-99359cfb1495 */
          {
            /* outlined object part */
            sglVertex2f(-11.0F, 36.5F);
            sglVertex2f(-2.0F, 36.5F);
            sglEnd();
          }

          /* Object: 500, Type: line, OID: 2ebd6a3a-c5bc-4b20-8257-d8a6453b53f4 */
          {
            /* outlined object part */
            sglIndexLineWidthi(2L);
            sglBegin(SGL_LINES);
            sglVertex2f(-15.0F, 50.5F);
            sglVertex2f(-2.0F, 50.5F);
            sglEnd();
          }

          /* Object: 600, Type: line, OID: 7b7be73e-1889-4203-b78c-c334322b55d1 */
          {
            /* outlined object part */
            sglIndexLineWidthi(1L);
            sglBegin(SGL_LINES);
            sglVertex2f(-11.0F, 63.5F);
            sglVertex2f(-2.0F, 63.5F);
          }

          /* Object: 700, Type: line, OID: 7754c0ad-3d98-46a3-912d-14fe30b4ffee */
          {
            /* outlined object part */
            sglVertex2f(-11.0F, 73.5F);
            sglVertex2f(-2.0F, 73.5F);
          }

          /* Object: 800, Type: line, OID: 965ecd0c-4530-474d-b83c-b1ec2e90c831 */
          {
            /* outlined object part */
            sglVertex2f(-11.0F, 82.5F);
            sglVertex2f(-2.0F, 82.5F);
          }

          /* Object: 900, Type: line, OID: 8def6f88-205a-410c-a4f9-5e6fb2556b49 */
          {
            /* outlined object part */
            sglVertex2f(-11.0F, 89.5F);
            sglVertex2f(-2.0F, 89.5F);
            sglEnd();
          }

          /* Object: 1000, Type: line, OID: 85a5c1b5-7aab-4088-8848-8a484b34a224 */
          {
            /* outlined object part */
            sglIndexLineWidthi(2L);
            sglBegin(SGL_LINES);
            sglVertex2f(-15.0F, 96.5F);
            sglVertex2f(-2.0F, 96.5F);
            sglEnd();
          }
        }

        /* Object: TargetBar, Type: rectangle, OID: 9d7fed4e-b79c-4ce0-818c-f72b73e3648a */
        {
          /* filled object part */
          sglDisable(SGL_MODULATE);
          sglEnable(SGL_POLYGON_SMOOTH);
          sglDisable(SGL_TESSELLATION);
          sglBegin(SGL_POLYGON);
          sglVertex2f(2.0F, -90.5F);
          sglVertex2f(12.0F, -90.5F);
          sglVertex2f(12.0F, aol_DistanceToTargetBar_G_InterpolatedDistanceToTarget(pContext));
          sglVertex2f(2.0F, aol_DistanceToTargetBar_G_InterpolatedDistanceToTarget(pContext));
          sglEnd();
        }
      }
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

