/*********************************************************
 **
 ** File  aol_line_width_table.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:26:49
 ** Command line: C:\Program Files (x86)\Esterel Technologies\SCADE R17.2\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\line_width_table.swt
 *********************************************************/

#ifndef _AOL_LINE_WIDTH_TABLE_H
#define _AOL_LINE_WIDTH_TABLE_H

#include "sgl_types.h"

/* Line width table definition */
extern const sgl_line_width aol_line_width_table[8UL];

extern SGLint32 aol_line_width_table_size;

#endif /* _AOL_LINE_WIDTH_TABLE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:26:49
 *********************************************************/

