/*********************************************************
 **
 ** File  aol_ValidationWindow.c
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\ValidationWindow\ValidationWindow.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:25
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#include "aol_ValidationWindow.h"
#include "aol_imported_functions.h"
#include "sgl.h"


void aol_ValidationWindow_init(aol_typ_ValidationWindow *pContext)
{
  aol_ValidationWindow_S_trainLenght(pContext, 0.0F);
  aol_ValidationWindow_S_trainBrakePerc(pContext, 0.0F);
  aol_ValidationWindow_S_trainMaxSpeed(pContext, 0.0F);
  aol_ValidationWindow_S_indexTrainCategory(pContext, 0L);
  aol_ValidationWindow_S_trainAirtightIndex(pContext, 0L);
  aol_ValidationWindow_S_trainLoadingGaugeIndex(pContext, 0L);
  aol_ValidationWindow_S_traindataYesNoIndex(pContext, 0L);
  aol_ValidationWindow_S_trainAxleLoad(pContext, 0L);
  aol_ValidationWindow_S_closeTrainDataValidationWindow(pContext, SGL_FALSE);
  aol_ValidationWindow_S_traindataAck(pContext, SGL_FALSE);
  aol_ValidationWindow_S_traindataYesAck(pContext, SGL_FALSE);
  aol_ValidationWindow_S_traindataNoAck(pContext, SGL_FALSE);

  pContext->_parentPriority = 0L;

  aol_closebutton_init(&(pContext->__closebutton__));
}

void aol_ValidationWindow_predraw(aol_typ_ValidationWindow *pContext)
{

  aol_closebutton_predraw(&(pContext->__closebutton__));
}

void aol_ValidationWindow_draw(aol_typ_ValidationWindow *pContext, SGLint32 pPriority)
{
  SGLuint32 _lParentMasks = sglGetActiveMasks();
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: group, Type: container, OID: 75c1bbd1-e03d-4717-9234-a64e75418d8f */
    {

      /* Object: rectangle, Type: rectangle, OID: e3d538fb-388b-4314-89b9-808851110f32 */
      {
        /* filled object part */
        sglIndexColori(6L);
        sglDisable(SGL_MODULATE);
        sglDisable(SGL_POLYGON_SMOOTH);
        sglTransparency8(255L);
        sglDisable(SGL_TEXTURE_2D);
        sglDisable(SGL_TESSELLATION);
        sglBegin(SGL_POLYGON);
        sglVertex2f(-320.0F, 225.0F);
        sglVertex2f(320.0F, 225.0F);
        sglVertex2f(320.0F, -225.0F);
        sglVertex2f(-320.0F, -225.0F);
        sglEnd();
      }

      /* Object: title, Type: container, OID: fdd5c462-ccd5-4c13-82c7-51647675030b */
      {

        /* Object: rectangle_1, Type: rectangle, OID: 693e2f0f-21d5-4aee-a351-497e49b407b6 */
        {
          /* filled object part */
          sglIndexColori(2L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-320.0F, 225.0F);
          sglVertex2f(0.0F, 225.0F);
          sglVertex2f(0.0F, 201.0F);
          sglVertex2f(-320.0F, 201.0F);
          sglEnd();
        }

        /* Object: validateTrainData, Type: text, OID: f4f2c6b7-a19f-4488-804a-cd54515d253b */
        {
          static SGLuint8 _lArray0_validateTrainData[255UL] = {86U,97U,108U,105U,100U,97U,116U,101U,32U,116U,114U,97U,105U,110U,32U,100U,97U,116U,97U};
          sglIndexColori(1L);
          sglIndexHaloColori(-1L);
          sglIndexFontLineWidthi(2L);
          sglIndexFonti(5L);
          sglDisable(SGL_LINE_HALOING);
          sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
          sgluWriteText(-94.0F, 213.0F, _lArray0_validateTrainData, 255L);
        }
      }

      /* Object: inputfield, Type: container, OID: c836b60a-ab8d-4e99-acec-609134936e1a */
      {

        /* Object: rectangle_2, Type: rectangle, OID: dd2d4ef5-903b-4cbd-ab58-2d416aa2b51d */
        {
          /* filled object part */
          sglIndexColori(3L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(0.0F, 225.0F);
          sglVertex2f(320.0F, 225.0F);
          sglVertex2f(320.0F, 175.0F);
          sglVertex2f(0.0F, 175.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(1L);
          sglIndexLineWidthi(0L);
          sglIndexLineStipplei(0L);
          sglSetLineCaps(SGL_ROUNDED_CAPS);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(0.0F, 225.0F);
          sglVertex2f(320.0F, 225.0F);
          sglVertex2f(320.0F, 175.0F);
          sglVertex2f(0.0F, 175.0F);
          sglEnd();
        }

        /* Object: conditional_group, Type: conditional, OID: 140baaf0-3438-4cb3-aee3-5e81b9ed444c */
        {
          sglPushMatrixAndTranslate(-14.0F, 0.0F);
          switch (aol_ValidationWindow_G_traindataYesNoIndex(pContext)) {

          case 2L:

            /* Object: no, Type: text, OID: 9af000ff-b11e-4236-b6b7-69b328643189 */
            {
              static SGLuint8 _lArray0_no[255UL] = {78U,111U};
              sglIndexColori(2L);
              sglSetTextAlignment(SGL_ALIGN_LEFT, SGL_ALIGN_MIDDLE);
              sgluWriteText(27.0F, 200.0F, _lArray0_no, 255L);
            }
            break;

          default:
          /* case 1L */

            /* Object: yes, Type: text, OID: a996e035-e242-4247-b47e-ff06efdd9b36 */
            {
              static SGLuint8 _lArray0_yes[255UL] = {89U,101U,115U};
              sglIndexColori(2L);
              sglSetTextAlignment(SGL_ALIGN_LEFT, SGL_ALIGN_MIDDLE);
              sgluWriteText(27.0F, 200.0F, _lArray0_yes, 255L);
            }
            break;
          }
          sglPopMatrixAndTranslate();
        }

        /* Object: rectangle_area, Type: rectangleArea, OID: 20d38ead-373d-42c5-bf65-444fe7d32021 */
        {
          SGLfloat _lX = 0.0F;
          SGLfloat _lY = 0.0F;
          aol_locate(-1L, &_lX, &_lY);
          aol_ValidationWindow_G_traindataAck(pContext) = sglRectangleActiveAreaGetStatus(_lX, _lY, 0.0F, 225.0F, 320.0F, 175.0F);
        }
      }

      /* Object: closebutton, Type: referenceContainer, OID: 525a9318-da94-4a3e-9ee1-1a4ae9e807c4 */
      {
        sglPushMatrixAndTranslate(0.0F, -225.0F);
        {
          aol_typ_closebutton *_lSubContext = &(pContext->__closebutton__);
          aol_closebutton_S_ModeSymbol(_lSubContext, 25L);
          aol_closebutton_S_isPressed(_lSubContext, SGL_FALSE);
          _lSubContext->_parentPriority = pContext->_parentPriority;
          aol_closebutton_draw(_lSubContext, pPriority);
          aol_ValidationWindow_G_closeTrainDataValidationWindow(pContext) = aol_closebutton_G_onButton(_lSubContext);
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: yes_1, Type: container, OID: c1341dc4-4481-492b-bb0d-f96c7e7b6cad */
      {
        sglPushMatrixAndTranslate(0.0F, -125.0F);

        /* Object: key1, Type: rectangle, OID: 52c10c7f-bf95-4a2a-8897-e61889d6e9d5 */
        {
          sglSetActiveMasks(_lParentMasks);
          /* filled object part */
          sglIndexColori(6L);
          sglDisable(SGL_MODULATE);
          sglEnable(SGL_POLYGON_SMOOTH);
          sglTransparency8(255L);
          sglDisable(SGL_TEXTURE_2D);
          sglDisable(SGL_TESSELLATION);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-0.5F, 50.75F);
          sglVertex2f(102.5F, 50.75F);
          sglVertex2f(102.5F, 0.75F);
          sglVertex2f(-0.5F, 0.75F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglIndexHaloColori(-1L);
          sglIndexLineWidthi(0L);
          sglIndexLineStipplei(0L);
          sglDisable(SGL_LINE_HALOING);
          sglSetLineCaps(SGL_ROUNDED_CAPS);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-0.5F, 50.75F);
          sglVertex2f(102.5F, 50.75F);
          sglVertex2f(102.5F, 0.75F);
          sglVertex2f(-0.5F, 0.75F);
          sglEnd();
        }

        /* Object: text, Type: text, OID: 4200505c-f3e3-426a-8148-d8ca3d3ab0bb */
        {
          static SGLuint8 _lArray0_text[255UL] = {89U,101U,115U};
          sglIndexColori(1L);
          sglIndexFontLineWidthi(2L);
          sglIndexFonti(5L);
          sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
          sgluWriteText(49.5F, 25.75F, _lArray0_text, 255L);
        }

        /* Object: rectangle_area_1, Type: rectangleArea, OID: 027c2f93-1810-43a3-a7ac-ce3ffedfd73f */
        {
          SGLfloat _lX = 0.0F;
          SGLfloat _lY = 0.0F;
          aol_locate(-1L, &_lX, &_lY);
          aol_ValidationWindow_G_traindataYesAck(pContext) = sglRectangleActiveAreaGetStatus(_lX, _lY, 1.25F, 51.0F, 104.25F, 1.0F);
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: no_1, Type: container, OID: 6f1a85a8-013b-4afc-bc02-21411a5ed800 */
      {
        sglPushMatrixAndTranslate(102.0F, -125.0F);

        /* Object: key1_1, Type: rectangle, OID: 4c800855-bbb3-4cf5-81fe-890410aec992 */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-0.5F, 50.75F);
          sglVertex2f(102.5F, 50.75F);
          sglVertex2f(102.5F, 0.75F);
          sglVertex2f(-0.5F, 0.75F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-0.5F, 50.75F);
          sglVertex2f(102.5F, 50.75F);
          sglVertex2f(102.5F, 0.75F);
          sglVertex2f(-0.5F, 0.75F);
          sglEnd();
        }

        /* Object: no_2, Type: text, OID: 0f4ca898-c565-46af-b20d-6011885c8936 */
        {
          static SGLuint8 _lArray0_no_2[255UL] = {78U,111U};
          sglIndexColori(1L);
          sgluWriteText(49.5F, 25.75F, _lArray0_no_2, 255L);
        }

        /* Object: rectangle_area_2, Type: rectangleArea, OID: 7a8e3909-0c49-4f1c-bca3-e1af96ced043 */
        {
          SGLfloat _lX = 0.0F;
          SGLfloat _lY = 0.0F;
          aol_locate(-1L, &_lX, &_lY);
          aol_ValidationWindow_G_traindataNoAck(pContext) = sglRectangleActiveAreaGetStatus(_lX, _lY, 1.25F, 51.0F, 104.25F, 1.0F);
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: labels, Type: container, OID: 201025a0-d8e4-433f-8607-9c2133b9ab11 */
      {

        /* Object: text_1, Type: text, OID: ff253919-6f3d-46b1-a77b-bd5657b4724d */
        {
          static SGLuint8 _lArray0_text_1[255UL] = {84U,114U,97U,105U,110U,32U,99U,97U,116U,101U,103U,111U,114U,121U};
          sglSetTextAlignment(SGL_ALIGN_RIGHT, SGL_ALIGN_MIDDLE);
          sgluWriteText(-138.0F, 105.0F, _lArray0_text_1, 255L);
        }

        /* Object: text_2, Type: text, OID: 33a924b3-a79b-4e97-8dee-313044b8e170 */
        {
          static SGLuint8 _lArray0_text_2[255UL] = {76U,101U,110U,103U,116U,104U,32U,40U,109U,41U};
          sgluWriteText(-138.0F, 85.0F, _lArray0_text_2, 255L);
        }

        /* Object: text_3, Type: text, OID: ad68c1b8-4c86-4a05-bdf8-2205c62e4e16 */
        {
          static SGLuint8 _lArray0_text_3[255UL] = {66U,114U,97U,107U,101U,32U,112U,101U,114U,99U,101U,110U,116U,97U,103U,101U};
          sgluWriteText(-138.0F, 65.0F, _lArray0_text_3, 255L);
        }

        /* Object: text_4, Type: text, OID: 4f1f7c8e-c260-44f5-b688-44cac042c47b */
        {
          static SGLuint8 _lArray0_text_4[255UL] = {77U,97U,120U,32U,115U,112U,101U,101U,100U,32U,40U,75U,109U,47U,104U,41U};
          sgluWriteText(-138.0F, 45.0F, _lArray0_text_4, 255L);
        }

        /* Object: text_5, Type: text, OID: bef0fc51-2cb3-4c7f-a6f7-3052281caebe */
        {
          static SGLuint8 _lArray0_text_5[255UL] = {65U,120U,108U,101U,32U,108U,111U,97U,100U,32U,99U,97U,116U,101U,103U,111U,114U,121U};
          sgluWriteText(-138.0F, 25.0F, _lArray0_text_5, 255L);
        }

        /* Object: text_6, Type: text, OID: 83597ab4-02f2-46d1-8b82-6f28c5f66ce3 */
        {
          static SGLuint8 _lArray0_text_6[255UL] = {65U,105U,114U,116U,105U,103U,104U,116U};
          sgluWriteText(-138.0F, 5.0F, _lArray0_text_6, 255L);
        }

        /* Object: text_7, Type: text, OID: 4e8337e3-94d2-426a-832b-777e168f0a3d */
        {
          static SGLuint8 _lArray0_text_7[255UL] = {76U,111U,97U,100U,105U,110U,103U,32U,103U,97U,117U,103U,101U};
          sgluWriteText(-138.0F, -15.0F, _lArray0_text_7, 255L);
        }
      }

      /* Object: values, Type: container, OID: 374833f8-3837-4b1f-b26e-65c2d65cbe24 */
      {

        /* Object: categorygroup, Type: conditional, OID: 1ed87ccb-ab43-4dd7-b228-2b256daee60f */
        {
          switch (aol_ValidationWindow_G_indexTrainCategory(pContext)) {

          case 1L:

            /* Object: unknown, Type: text, OID: ddbbdb82-0dcd-4e88-a7d8-a752e294e288 */
            {
              static SGLuint8 _lArray0_unknown[10UL] = {85U,110U,107U,110U,111U,119U,110U};
              sglSetTextAlignment(SGL_ALIGN_LEFT, SGL_ALIGN_MIDDLE);
              sgluWriteText(-128.0F, 105.0F, _lArray0_unknown, 10L);
            }
            break;

          case 2L:

            /* Object: PASS, Type: text, OID: 0f50aa20-de31-417c-ae7f-941be8c92e9a */
            {
              static SGLuint8 _lArray0_PASS[10UL] = {80U,65U,83U,83U};
              sglSetTextAlignment(SGL_ALIGN_LEFT, SGL_ALIGN_MIDDLE);
              sgluWriteText(-128.0F, 105.0F, _lArray0_PASS, 10L);
            }
            break;

          case 3L:

            /* Object: FP, Type: text, OID: dd438f4a-8f98-4b45-9797-c8312002291d */
            {
              static SGLuint8 _lArray0_FP[10UL] = {70U,80U};
              sglSetTextAlignment(SGL_ALIGN_LEFT, SGL_ALIGN_MIDDLE);
              sgluWriteText(-128.0F, 105.0F, _lArray0_FP, 10L);
            }
            break;

          case 4L:

            /* Object: FG, Type: text, OID: a2bf777e-98af-4741-84b2-92fb9b770a7e */
            {
              static SGLuint8 _lArray0_FG[10UL] = {70U,71U};
              sglSetTextAlignment(SGL_ALIGN_LEFT, SGL_ALIGN_MIDDLE);
              sgluWriteText(-128.0F, 105.0F, _lArray0_FG, 10L);
            }
            break;

          default:
            /* Do nothing */
            break;
          }
        }

        /* Object: lenght, Type: bifont, OID: 45c6d4e4-93b6-47ef-a231-46d14833041d */
        {
          sglIndexFonti(0L);
          sglSetTextAlignment(SGL_ALIGN_LEFT, SGL_ALIGN_MIDDLE);
          sglSetSecondFontAttributes(1L, 0L, 2L);
          {
            sgl_numeric_format _lFormat;
            _lFormat.l_integralPart = 3L;
            _lFormat.l_fractionalPart = 0L;
            _lFormat.l_secondFontPos = 0L;
            _lFormat.b_separator = 46U;
            _lFormat.b_leadingZeros = SGL_FALSE;
            _lFormat.l_displaySign = SGL_SIGN_NEVER;
            sgluWriteFloat(-128.0F, 85.0F, aol_ValidationWindow_G_trainLenght(pContext), &_lFormat);
          }
        }

        /* Object: brakeperc, Type: bifont, OID: 2667cd0c-b76c-4323-bd8d-fb12e430b0d3 */
        {
          sgl_numeric_format _lFormat;
          _lFormat.l_integralPart = 3L;
          _lFormat.l_fractionalPart = 0L;
          _lFormat.l_secondFontPos = 0L;
          _lFormat.b_separator = 46U;
          _lFormat.b_leadingZeros = SGL_FALSE;
          _lFormat.l_displaySign = SGL_SIGN_NEVER;
          sgluWriteFloat(-128.0F, 65.0F, aol_ValidationWindow_G_trainBrakePerc(pContext), &_lFormat);
        }

        /* Object: maxspeed, Type: bifont, OID: 25f3e98e-9e83-42b1-b5e4-398ca29b1902 */
        {
          sgl_numeric_format _lFormat;
          _lFormat.l_integralPart = 3L;
          _lFormat.l_fractionalPart = 0L;
          _lFormat.l_secondFontPos = 0L;
          _lFormat.b_separator = 46U;
          _lFormat.b_leadingZeros = SGL_FALSE;
          _lFormat.l_displaySign = SGL_SIGN_NEVER;
          sgluWriteFloat(-128.0F, 45.0F, aol_ValidationWindow_G_trainMaxSpeed(pContext), &_lFormat);
        }

        /* Object: axleloadgroup, Type: conditional, OID: 87093a43-10fc-407d-9342-7873d777fb23 */
        {
          switch (aol_ValidationWindow_G_trainAxleLoad(pContext)) {

          case 2L:

            /* Object: text_9, Type: text, OID: 17d0cf24-d1e2-410a-87d5-b9637df55252 */
            {
              static SGLuint8 _lArray0_text_9[10UL] = {72U,83U,49U,55U};
              sglIndexFonti(5L);
              sgluWriteText(-128.0F, 25.0F, _lArray0_text_9, 10L);
            }
            break;

          case 3L:

            /* Object: text_10, Type: text, OID: 51ed3d26-b587-4629-8403-ae40b9040bd1 */
            {
              static SGLuint8 _lArray0_text_10[10UL] = {66U,49U};
              sglIndexFonti(5L);
              sgluWriteText(-128.0F, 25.0F, _lArray0_text_10, 10L);
            }
            break;

          case 4L:

            /* Object: text_11, Type: text, OID: f98c2deb-e261-4abf-ad76-a83d17a2e297 */
            {
              static SGLuint8 _lArray0_text_11[10UL] = {66U,50U};
              sglIndexFonti(5L);
              sgluWriteText(-128.0F, 25.0F, _lArray0_text_11, 10L);
            }
            break;

          case 5L:

            /* Object: text_12, Type: text, OID: a8983ad8-feff-43e0-bf00-e9acce39a681 */
            {
              static SGLuint8 _lArray0_text_12[10UL] = {67U,50U};
              sglIndexFonti(5L);
              sgluWriteText(-128.0F, 25.0F, _lArray0_text_12, 10L);
            }
            break;

          case 6L:

            /* Object: text_13, Type: text, OID: 60301fdd-2f97-424b-be3a-9944f745e6d3 */
            {
              static SGLuint8 _lArray0_text_13[10UL] = {67U,51U};
              sglIndexFonti(5L);
              sgluWriteText(-128.0F, 25.0F, _lArray0_text_13, 10L);
            }
            break;

          case 7L:

            /* Object: text_14, Type: text, OID: 6c9ee9a3-ade2-4046-953f-232583c0b47a */
            {
              static SGLuint8 _lArray0_text_14[10UL] = {67U,52U};
              sglIndexFonti(5L);
              sgluWriteText(-128.0F, 25.0F, _lArray0_text_14, 10L);
            }
            break;

          case 8L:

            /* Object: text_15, Type: text, OID: 8fcc9388-0d32-4ae2-8993-5fdbe01564ed */
            {
              static SGLuint8 _lArray0_text_15[10UL] = {68U,50U};
              sglIndexFonti(5L);
              sgluWriteText(-128.0F, 25.0F, _lArray0_text_15, 10L);
            }
            break;

          case 9L:

            /* Object: text_16, Type: text, OID: f80550c4-447b-4f39-8ec2-0a451b448dbe */
            {
              static SGLuint8 _lArray0_text_16[10UL] = {68U,51U};
              sglIndexFonti(5L);
              sgluWriteText(-128.0F, 25.0F, _lArray0_text_16, 10L);
            }
            break;

          case 10L:

            /* Object: text_17, Type: text, OID: bdacaacd-12a8-4d9b-8ff5-4aaf42053e0c */
            {
              static SGLuint8 _lArray0_text_17[10UL] = {68U,52U};
              sglIndexFonti(5L);
              sgluWriteText(-128.0F, 25.0F, _lArray0_text_17, 10L);
            }
            break;

          case 11L:

            /* Object: text_18, Type: text, OID: f63710be-8e37-4aef-b0a5-f4513c859125 */
            {
              static SGLuint8 _lArray0_text_18[10UL] = {68U,52U,88U,76U};
              sglIndexFonti(5L);
              sgluWriteText(-128.0F, 25.0F, _lArray0_text_18, 10L);
            }
            break;

          case 12L:

            /* Object: text_19, Type: text, OID: 2d63d744-1b48-4b55-901b-0039caa4283b */
            {
              static SGLuint8 _lArray0_text_19[10UL] = {69U,52U};
              sglIndexFonti(5L);
              sgluWriteText(-128.0F, 25.0F, _lArray0_text_19, 10L);
            }
            break;

          case 13L:

            /* Object: text_20, Type: text, OID: 5c7729ec-5f06-4f6a-82f0-76bb9a01043d */
            {
              static SGLuint8 _lArray0_text_20[10UL] = {69U,53U};
              sglIndexFonti(5L);
              sgluWriteText(-128.0F, 25.0F, _lArray0_text_20, 10L);
            }
            break;

          default:
          /* case 1L */

            /* Object: text_8, Type: text, OID: 11abcf5a-44a9-499a-8ec3-c2f4b5ff206c */
            {
              static SGLuint8 _lArray0_text_8[10UL] = {65U};
              sglIndexFonti(5L);
              sgluWriteText(-128.0F, 25.0F, _lArray0_text_8, 10L);
            }
            break;
          }
        }

        /* Object: airtightgroup, Type: conditional, OID: 76fdad18-bb0e-4eaf-91e8-59767ae79f49 */
        {
          switch (aol_ValidationWindow_G_trainAirtightIndex(pContext)) {

          case 2L:

            /* Object: no_3, Type: text, OID: 5c7e8f83-24a8-4d23-b591-41d920e2644d */
            {
              static SGLuint8 _lArray0_no_3[10UL] = {78U,111U};
              sglIndexFonti(5L);
              sgluWriteText(-128.0F, 5.0F, _lArray0_no_3, 10L);
            }
            break;

          default:
          /* case 1L */

            /* Object: yes_2, Type: text, OID: 3b1d45c1-6454-4e7b-a683-1643b8e7ae2b */
            {
              static SGLuint8 _lArray0_yes_2[10UL] = {89U,101U,115U};
              sglIndexFonti(5L);
              sgluWriteText(-128.0F, 5.0F, _lArray0_yes_2, 10L);
            }
            break;
          }
        }

        /* Object: loadinggaugegroup, Type: conditional, OID: 828cbdb6-1270-426d-8d76-320262124f02 */
        {
          switch (aol_ValidationWindow_G_trainLoadingGaugeIndex(pContext)) {

          case 2L:

            /* Object: text_22, Type: text, OID: 35f641c3-d76c-45ad-9424-3e3a3c3a80ea */
            {
              static SGLuint8 _lArray0_text_22[10UL] = {71U,49U};
              sglIndexFonti(5L);
              sgluWriteText(-128.0F, -15.0F, _lArray0_text_22, 10L);
            }
            break;

          case 3L:

            /* Object: text_23, Type: text, OID: 473174da-7352-4762-8c91-19f891af0983 */
            {
              static SGLuint8 _lArray0_text_23[10UL] = {71U,65U};
              sglIndexFonti(5L);
              sgluWriteText(-128.0F, -15.0F, _lArray0_text_23, 10L);
            }
            break;

          case 4L:

            /* Object: text_24, Type: text, OID: 2fdf0d83-24d6-418a-a24f-95fc42d6c363 */
            {
              static SGLuint8 _lArray0_text_24[10UL] = {71U,66U};
              sglIndexFonti(5L);
              sgluWriteText(-128.0F, -15.0F, _lArray0_text_24, 10L);
            }
            break;

          case 5L:

            /* Object: text_25, Type: text, OID: f2645edd-fa69-4b0e-83c4-b934d6bbdbba */
            {
              static SGLuint8 _lArray0_text_25[10UL] = {71U,67U};
              sglIndexFonti(5L);
              sgluWriteText(-128.0F, -15.0F, _lArray0_text_25, 10L);
            }
            break;

          default:
          /* case 1L */

            /* Object: text_21, Type: text, OID: 6d2680c9-188e-4e3b-948e-92eb6230ab1c */
            {
              static SGLuint8 _lArray0_text_21[10UL] = {85U,110U,107U,110U,111U,119U,110U};
              sglIndexFonti(5L);
              sgluWriteText(-128.0F, -15.0F, _lArray0_text_21, 10L);
            }
            break;
          }
        }
      }
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:25
 *********************************************************/

