/*********************************************************
 **
 ** File  aol_mainmenu.c
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\MainMenu\mainmenu.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:24
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#include "aol_mainmenu.h"
#include "aol_imported_functions.h"
#include "sgl.h"


void aol_mainmenu_init(aol_typ_mainmenu *pContext)
{
  {
    static SGLint32 _lArray0[30UL] = {0L};
    aol_mainmenu_S_buttonEnabler(pContext, _lArray0);
  }
  aol_mainmenu_S_closeButtonEnabler(pContext, 26L);
  aol_mainmenu_S_TitleVisibility(pContext, SGL_FALSE);
  aol_mainmenu_S_MousePressed(pContext, SGL_FALSE);
  aol_mainmenu_S_openTrainData(pContext, SGL_FALSE);
  aol_mainmenu_S_closeMainmenu(pContext, SGL_FALSE);
  aol_mainmenu_S_StartRequest(pContext, SGL_FALSE);
  aol_mainmenu_S_openTrainRN(pContext, SGL_FALSE);
  aol_mainmenu_S_openDriverID(pContext, SGL_FALSE);
  aol_mainmenu_S_levelMenu(pContext, SGL_FALSE);
  aol_mainmenu_S_openShunting(pContext, SGL_FALSE);
  aol_mainmenu_S_openNonLeading(pContext, SGL_FALSE);

  pContext->_parentPriority = 0L;

  aol_button_init(&(pContext->__start__));
  aol_button_init(&(pContext->__DriverID__));
  aol_button_init(&(pContext->__traindata__));
  aol_button_init(&(pContext->__level__));
  aol_button_init(&(pContext->__trainRN__));
  aol_button_init(&(pContext->__Shunting__));
  aol_button_init(&(pContext->__nonLeading__));
  aol_button_init(&(pContext->__button__));
  aol_closebutton_init(&(pContext->__closebutton__));
}

void aol_mainmenu_predraw(aol_typ_mainmenu *pContext)
{

  aol_button_predraw(&(pContext->__start__));
  aol_button_predraw(&(pContext->__DriverID__));
  aol_button_predraw(&(pContext->__traindata__));
  aol_button_predraw(&(pContext->__level__));
  aol_button_predraw(&(pContext->__trainRN__));
  aol_button_predraw(&(pContext->__Shunting__));
  aol_button_predraw(&(pContext->__nonLeading__));
  aol_button_predraw(&(pContext->__button__));
  aol_closebutton_predraw(&(pContext->__closebutton__));
}

void aol_mainmenu_draw(aol_typ_mainmenu *pContext, SGLint32 pPriority)
{
  SGLuint32 _lParentMasks = sglGetActiveMasks();
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: Main, Type: container, OID: 5e3e53d3-071a-4fa9-adad-b29c3738a34b */
    {

      /* Object: rectangle, Type: rectangle, OID: b9a5089a-d1a2-4465-b81e-5e3708fd382e */
      {
        /* filled object part */
        sglIndexColori(6L);
        sglDisable(SGL_MODULATE);
        sglDisable(SGL_POLYGON_SMOOTH);
        sglTransparency8(255L);
        sglDisable(SGL_TEXTURE_2D);
        sglDisable(SGL_TESSELLATION);
        sglBegin(SGL_POLYGON);
        sglVertex2f(-153.0F, 225.0F);
        sglVertex2f(153.0F, 225.0F);
        sglVertex2f(153.0F, -225.0F);
        sglVertex2f(-153.0F, -225.0F);
        sglEnd();
      }

      /* Object: title, Type: container, OID: 26263089-a6e6-4e38-92f7-2b8be4bfd56f */
      {

        /* Object: rectangle_1, Type: rectangle, OID: 67c94966-5702-4205-a4bc-2081caab0e5e */
        {
          /* filled object part */
          sglIndexColori(2L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-153.0F, 225.0F);
          sglVertex2f(153.0F, 225.0F);
          sglVertex2f(153.0F, 201.0F);
          sglVertex2f(-153.0F, 201.0F);
          sglEnd();
        }

        /* Object: TitleText, Type: text, OID: 9b7a2d27-74b9-43f3-8c95-eace3ac514de */
        {
          static SGLuint8 _lArray0_TitleText[255UL] = {77U,97U,105U,110U};
          if (aol_mainmenu_G_TitleVisibility(pContext)) {
            sglIndexColori(1L);
            sglIndexHaloColori(-1L);
            sglIndexFontLineWidthi(2L);
            sglIndexFonti(5L);
            sglDisable(SGL_LINE_HALOING);
            sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
            sgluWriteText(-124.5F, 214.0F, _lArray0_TitleText, 255L);
          }
        }
      }

      /* Object: buttons, Type: container, OID: df919f40-7f2e-4630-9e13-5f67f9c3bed8 */
      {

        /* Object: start, Type: referenceContainer, OID: efdc7a2d-066b-421f-9b37-75e83dfa9909 */
        {
          sglPushMatrixAndTranslate(-153.0F, 125.0F);
          {
            aol_typ_button *_lSubContext = &(pContext->__start__);
            aol_button_S_ButtonIndex(_lSubContext, 1L);
            aol_button_S_MousePressed(_lSubContext, SGLbool_and(aol_mainmenu_G_MousePressed(pContext), aol_mainmenu_G_StartRequest(pContext)));
            aol_button_S_enableIndex(_lSubContext, (aol_mainmenu_G_buttonEnabler(pContext))[0]);
            _lSubContext->_parentPriority = pContext->_parentPriority;
            aol_button_draw(_lSubContext, pPriority);
            aol_mainmenu_G_StartRequest(pContext) = aol_button_G_onButton(_lSubContext);
          }
          sglPopMatrixAndTranslate();
        }

        /* Object: DriverID, Type: referenceContainer, OID: 892b3399-bf3b-4af9-852a-f8407c578d16 */
        {
          sglSetActiveMasks(_lParentMasks);
          sglPushMatrixAndTranslate(0.0F, 125.0F);
          {
            aol_typ_button *_lSubContext = &(pContext->__DriverID__);
            aol_button_S_ButtonIndex(_lSubContext, 2L);
            aol_button_S_MousePressed(_lSubContext, SGLbool_and(aol_mainmenu_G_MousePressed(pContext), aol_mainmenu_G_openDriverID(pContext)));
            aol_button_S_enableIndex(_lSubContext, (aol_mainmenu_G_buttonEnabler(pContext))[6]);
            _lSubContext->_parentPriority = pContext->_parentPriority;
            aol_button_draw(_lSubContext, pPriority);
            aol_mainmenu_G_openDriverID(pContext) = aol_button_G_onButton(_lSubContext);
          }
          sglPopMatrixAndTranslate();
        }

        /* Object: traindata, Type: referenceContainer, OID: 1a8e2252-9c6b-4f24-8f5e-fdabddeaac7d */
        {
          sglSetActiveMasks(_lParentMasks);
          sglPushMatrixAndTranslate(-153.0F, 75.0F);
          {
            aol_typ_button *_lSubContext = &(pContext->__traindata__);
            aol_button_S_ButtonIndex(_lSubContext, 3L);
            aol_button_S_MousePressed(_lSubContext, SGLbool_and(aol_mainmenu_G_MousePressed(pContext), aol_mainmenu_G_openTrainData(pContext)));
            aol_button_S_enableIndex(_lSubContext, (aol_mainmenu_G_buttonEnabler(pContext))[10]);
            _lSubContext->_parentPriority = pContext->_parentPriority;
            aol_button_draw(_lSubContext, pPriority);
            aol_mainmenu_G_openTrainData(pContext) = aol_button_G_onButton(_lSubContext);
          }
          sglPopMatrixAndTranslate();
        }

        /* Object: level, Type: referenceContainer, OID: 4e6335c3-c1f3-470a-8117-0053ce8949f7 */
        {
          sglSetActiveMasks(_lParentMasks);
          sglPushMatrixAndTranslate(-153.0F, 25.0F);
          {
            aol_typ_button *_lSubContext = &(pContext->__level__);
            aol_button_S_ButtonIndex(_lSubContext, 4L);
            aol_button_S_MousePressed(_lSubContext, SGLbool_and(aol_mainmenu_G_MousePressed(pContext), aol_mainmenu_G_levelMenu(pContext)));
            aol_button_S_enableIndex(_lSubContext, (aol_mainmenu_G_buttonEnabler(pContext))[8]);
            _lSubContext->_parentPriority = pContext->_parentPriority;
            aol_button_draw(_lSubContext, pPriority);
            aol_mainmenu_G_levelMenu(pContext) = aol_button_G_onButton(_lSubContext);
          }
          sglPopMatrixAndTranslate();
        }

        /* Object: trainRN, Type: referenceContainer, OID: 9ea683f1-cb82-4b4a-8c65-ee1d48093158 */
        {
          sglSetActiveMasks(_lParentMasks);
          sglPushMatrixAndTranslate(0.0F, 25.0F);
          {
            aol_typ_button *_lSubContext = &(pContext->__trainRN__);
            aol_button_S_ButtonIndex(_lSubContext, 9L);
            aol_button_S_MousePressed(_lSubContext, SGLbool_and(aol_mainmenu_G_MousePressed(pContext), aol_mainmenu_G_openTrainRN(pContext)));
            aol_button_S_enableIndex(_lSubContext, (aol_mainmenu_G_buttonEnabler(pContext))[7]);
            _lSubContext->_parentPriority = pContext->_parentPriority;
            aol_button_draw(_lSubContext, pPriority);
            aol_mainmenu_G_openTrainRN(pContext) = aol_button_G_onButton(_lSubContext);
          }
          sglPopMatrixAndTranslate();
        }

        /* Object: Shunting, Type: referenceContainer, OID: 25eaaa83-a5d0-4fae-bd19-a4dd265325cb */
        {
          sglSetActiveMasks(_lParentMasks);
          sglPushMatrixAndTranslate(-153.0F, -25.0F);
          {
            aol_typ_button *_lSubContext = &(pContext->__Shunting__);
            aol_button_S_ButtonIndex(_lSubContext, 6L);
            aol_button_S_MousePressed(_lSubContext, SGLbool_and(aol_mainmenu_G_MousePressed(pContext), aol_mainmenu_G_levelMenu(pContext)));
            aol_button_S_enableIndex(_lSubContext, (aol_mainmenu_G_buttonEnabler(pContext))[1]);
            _lSubContext->_parentPriority = pContext->_parentPriority;
            aol_button_draw(_lSubContext, pPriority);
            aol_mainmenu_G_openShunting(pContext) = aol_button_G_onButton(_lSubContext);
          }
          sglPopMatrixAndTranslate();
        }

        /* Object: nonLeading, Type: referenceContainer, OID: df2627ba-1dd1-4e1f-9cbc-1c0efeec00bf */
        {
          sglSetActiveMasks(_lParentMasks);
          sglPushMatrixAndTranslate(-1.0F, -24.0F);
          {
            aol_typ_button *_lSubContext = &(pContext->__nonLeading__);
            aol_button_S_ButtonIndex(_lSubContext, 7L);
            aol_button_S_MousePressed(_lSubContext, SGLbool_and(aol_mainmenu_G_MousePressed(pContext), aol_mainmenu_G_levelMenu(pContext)));
            aol_button_S_enableIndex(_lSubContext, (aol_mainmenu_G_buttonEnabler(pContext))[3]);
            _lSubContext->_parentPriority = pContext->_parentPriority;
            aol_button_draw(_lSubContext, pPriority);
            aol_mainmenu_G_openNonLeading(pContext) = aol_button_G_onButton(_lSubContext);
          }
          sglPopMatrixAndTranslate();
        }

        /* Object: button, Type: referenceContainer, OID: 8e5b28e1-e533-427d-9405-a1504d3104b0 */
        {
          sglSetActiveMasks(_lParentMasks);
          sglPushMatrixAndTranslate(-153.0F, -75.0F);
          {
            aol_typ_button *_lSubContext = &(pContext->__button__);
            aol_button_S_ButtonIndex(_lSubContext, 8L);
            aol_button_S_MousePressed(_lSubContext, SGL_FALSE);
            aol_button_S_enableIndex(_lSubContext, 2L);
            _lSubContext->_parentPriority = pContext->_parentPriority;
            aol_button_draw(_lSubContext, pPriority);
          }
          sglPopMatrixAndTranslate();
        }

        /* Object: closebutton, Type: referenceContainer, OID: a32e0c5f-6611-4145-a9dc-216a73c27b1e */
        {
          sglSetActiveMasks(_lParentMasks);
          sglPushMatrixAndTranslate(-153.0F, -226.0F);
          {
            aol_typ_closebutton *_lSubContext = &(pContext->__closebutton__);
            aol_closebutton_S_ModeSymbol(_lSubContext, aol_mainmenu_G_closeButtonEnabler(pContext));
            aol_closebutton_S_isPressed(_lSubContext, aol_mainmenu_G_MousePressed(pContext));
            _lSubContext->_parentPriority = pContext->_parentPriority;
            aol_closebutton_draw(_lSubContext, pPriority);
            aol_mainmenu_G_closeMainmenu(pContext) = aol_closebutton_G_onButton(_lSubContext);
          }
          sglPopMatrixAndTranslate();
        }
      }
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:24
 *********************************************************/

