/*********************************************************
 **
 ** File  aol_line_stipple_table.c
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:26:51
 ** Command line: C:\Program Files (x86)\Esterel Technologies\SCADE R17.2\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\line_stipple_table.sst
 *********************************************************/

#include "aol_line_stipple_table.h"

/* Line stipple table definition */
const sgl_linestipple aol_line_stipple_table[5UL] = 
{
{ {   0,   0,   0,   0,   0,   0}, {   0,   0,   0,   0,   0,   0},   1,   0}, /*     0  solid  pattern :  */
{ {  12,  12,   0,   0,   0,   0}, {   1,   0,   0,   0,   0,   0},   0,   2}, /*     1  dashed pattern :  */
{ {   8,   8,   0,   0,   0,   0}, {   1,   0,   0,   0,   0,   0},   0,   2}, /*     2  dashed pattern :  */
{ {   1,   6,   0,   0,   0,   0}, {   1,   0,   0,   0,   0,   0},   0,   2}, /*     3  dashed pattern :  */
{ {   1,   8,   8,   8,   0,   0}, {   1,   0,   1,   0,   0,   0},   0,   4}  /*     4  dashed pattern :  */
};

SGLint32 aol_line_stipple_table_size = 5UL;

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:26:51
 *********************************************************/

