/*********************************************************
 **
 ** File  aol_texture_table.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:26:53
 ** Command line: C:\Program Files (x86)\Esterel Technologies\SCADE R17.2\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\texture_table.stt
 *********************************************************/

#ifndef _AOL_TEXTURE_TABLE_H
#define _AOL_TEXTURE_TABLE_H

#include "sgl_types.h"

/* Textures definition */
#define AOL_TEXTURE_TABLE_SIZE 0

extern void aol_texture_table(void);

#endif /* _AOL_TEXTURE_TABLE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:26:53
 *********************************************************/

