/*********************************************************
 **
 ** File  aol_E.h
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\E\E.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_E_H
#define _AOL_E_H

#include "sgl_types.h"
#include "kcg_assign.h"

#include "aol_StatusSymbols.h"
#include "aol_scroll_button.h"

/* Accessors */
#define aol_E_G_StatusSymbolVisibility(_C_) (_C_)->StatusSymbolVisibility
#define aol_E_S_StatusSymbolVisibility(_C_,_V_) (_C_)->StatusSymbolVisibility = (_V_)
#define aol_E_G_StatusSymnolIndex(_C_) (_C_)->StatusSymnolIndex
#define aol_E_S_StatusSymnolIndex(_C_,_V_) (_C_)->StatusSymnolIndex = (_V_)
#define aol_E_G_ArrayOfMsgIndex(_C_) (*(_C_)->ArrayOfMsgIndex)
#define aol_E_S_ArrayOfMsgIndex(_C_,_V_) (_C_)->ArrayOfMsgIndex = &(_V_)
#define aol_E_G_yellowBorderMsg(_C_) (_C_)->yellowBorderMsg
#define aol_E_S_yellowBorderMsg(_C_,_V_) (_C_)->yellowBorderMsg = (_V_)
#define aol_E_G_SingleMsgAckRequiredVisibility(_C_) (_C_)->SingleMsgAckRequiredVisibility
#define aol_E_S_SingleMsgAckRequiredVisibility(_C_,_V_) (_C_)->SingleMsgAckRequiredVisibility = (_V_)
#define aol_E_G_IndexFixedMsg(_C_) (*(_C_)->IndexFixedMsg)
#define aol_E_S_IndexFixedMsg(_C_,_V_) (_C_)->IndexFixedMsg = &(_V_)
#define aol_E_G_ArrayPlainText(_C_) (*(_C_)->ArrayPlainText)
#define aol_E_S_ArrayPlainText(_C_,_V_) (_C_)->ArrayPlainText = &(_V_)
#define aol_E_G_Array_hh(_C_) (*(_C_)->Array_hh)
#define aol_E_S_Array_hh(_C_,_V_) (_C_)->Array_hh = &(_V_)
#define aol_E_G_Array_mm(_C_) (*(_C_)->Array_mm)
#define aol_E_S_Array_mm(_C_,_V_) (_C_)->Array_mm = &(_V_)
#define aol_E_G_isAuxiliarMsg(_C_) (_C_)->isAuxiliarMsg
#define aol_E_S_isAuxiliarMsg(_C_,_V_) (_C_)->isAuxiliarMsg = (_V_)
#define aol_E_G_scrollUpEnableTypeIndex(_C_) (_C_)->scrollUpEnableTypeIndex
#define aol_E_S_scrollUpEnableTypeIndex(_C_,_V_) (_C_)->scrollUpEnableTypeIndex = (_V_)
#define aol_E_G_scrolUplButtonClicked(_C_) (_C_)->scrolUplButtonClicked
#define aol_E_S_scrolUplButtonClicked(_C_,_V_) (_C_)->scrolUplButtonClicked = (_V_)
#define aol_E_G_scrolDownlButtonClicked(_C_) (_C_)->scrolDownlButtonClicked
#define aol_E_S_scrolDownlButtonClicked(_C_,_V_) (_C_)->scrolDownlButtonClicked = (_V_)
#define aol_E_G_scrollDownEnableTypeIndex(_C_) (_C_)->scrollDownEnableTypeIndex
#define aol_E_S_scrollDownEnableTypeIndex(_C_,_V_) (_C_)->scrollDownEnableTypeIndex = (_V_)
#define aol_E_G_textMsgAck(_C_) (_C_)->textMsgAck
#define aol_E_S_textMsgAck(_C_,_V_) (_C_)->textMsgAck = (_V_)
#define aol_E_G_scrollUp(_C_) (_C_)->scrollUp
#define aol_E_S_scrollUp(_C_,_V_) (_C_)->scrollUp = (_V_)
#define aol_E_G_scrollDown(_C_) (_C_)->scrollDown
#define aol_E_S_scrollDown(_C_,_V_) (_C_)->scrollDown = (_V_)
#define aol_E_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct aol_typ_E_ {
  /* ------------------------- inputs --------------------------- */
  SGLbool StatusSymbolVisibility;
  SGLint32 StatusSymnolIndex;
  SGLint32 (*ArrayOfMsgIndex)[5UL];
  SGLbool yellowBorderMsg;
  SGLbool SingleMsgAckRequiredVisibility;
  SGLint32 (*IndexFixedMsg)[5UL];
  SGLuint8 (*ArrayPlainText)[5UL][30UL];
  SGLfloat (*Array_hh)[5UL];
  SGLfloat (*Array_mm)[5UL];
  SGLbool isAuxiliarMsg;
  SGLint32 scrollUpEnableTypeIndex;
  SGLbool scrolUplButtonClicked;
  SGLbool scrolDownlButtonClicked;
  SGLint32 scrollDownEnableTypeIndex;
  /* ------------------------- outputs -------------------------- */
  SGLbool textMsgAck;
  SGLbool scrollUp;
  SGLbool scrollDown;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} aol_typ_E;

/* Associated functions */
extern void aol_E_init(aol_typ_E *pContext);
extern void aol_E_predraw(aol_typ_E *pContext);
extern void aol_E_draw(aol_typ_E *pContext, SGLint32 pPriority);

#endif /* _AOL_E_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

