/*********************************************************
 **
 ** File  aol_D.h
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\D\D.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

/* Inlined constants:
   GradientVisible=true
 */

#ifndef _AOL_D_H
#define _AOL_D_H

#include "sgl_types.h"
#include "kcg_assign.h"

#include "aol_Gradient.h"
#include "aol_PASP.h"
#include "aol_indicatorMarker.h"
#include "aol_SPDI.h"
#include "aol_NavigationSymbols.h"

/* Accessors */
#define aol_D_G_GradientsValue(_C_) (*(_C_)->GradientsValue)
#define aol_D_S_GradientsValue(_C_,_V_) (_C_)->GradientsValue = &(_V_)
#define aol_D_G_Scale(_C_) (*(_C_)->Scale)
#define aol_D_S_Scale(_C_,_V_) (_C_)->Scale = &(_V_)
#define aol_D_G_GradientsEndInterpolated(_C_) (*(_C_)->GradientsEndInterpolated)
#define aol_D_S_GradientsEndInterpolated(_C_,_V_) (_C_)->GradientsEndInterpolated = &(_V_)
#define aol_D_G_GradientsStartInterpolated(_C_) (*(_C_)->GradientsStartInterpolated)
#define aol_D_S_GradientsStartInterpolated(_C_,_V_) (_C_)->GradientsStartInterpolated = &(_V_)
#define aol_D_G_PASP_BreakPointPositions(_C_) (*(_C_)->PASP_BreakPointPositions)
#define aol_D_S_PASP_BreakPointPositions(_C_,_V_) (_C_)->PASP_BreakPointPositions = &(_V_)
#define aol_D_G_PASP_FilteredSpeeds(_C_) (*(_C_)->PASP_FilteredSpeeds)
#define aol_D_S_PASP_FilteredSpeeds(_C_,_V_) (_C_)->PASP_FilteredSpeeds = &(_V_)
#define aol_D_G_SPDI_SpeedChangeIndex(_C_) (*(_C_)->SPDI_SpeedChangeIndex)
#define aol_D_S_SPDI_SpeedChangeIndex(_C_,_V_) (_C_)->SPDI_SpeedChangeIndex = &(_V_)
#define aol_D_G_SPDI_speedChangePosition(_C_) (*(_C_)->SPDI_speedChangePosition)
#define aol_D_S_SPDI_speedChangePosition(_C_,_V_) (_C_)->SPDI_speedChangePosition = &(_V_)
#define aol_D_G_SPDI_SpeedChangeVisible(_C_) (*(_C_)->SPDI_SpeedChangeVisible)
#define aol_D_S_SPDI_SpeedChangeVisible(_C_,_V_) (_C_)->SPDI_SpeedChangeVisible = &(_V_)
#define aol_D_G_GradientsVisible(_C_) (*(_C_)->GradientsVisible)
#define aol_D_S_GradientsVisible(_C_,_V_) (_C_)->GradientsVisible = &(_V_)
#define aol_D_G_PASP_IndicationMarkaerPosition(_C_) (*(_C_)->PASP_IndicationMarkaerPosition)
#define aol_D_S_PASP_IndicationMarkaerPosition(_C_,_V_) (_C_)->PASP_IndicationMarkaerPosition = &(_V_)
#define aol_D_G_OverD12(_C_) (_C_)->OverD12
#define aol_D_S_OverD12(_C_,_V_) (_C_)->OverD12 = (_V_)
#define aol_D_G_OverD9(_C_) (_C_)->OverD9
#define aol_D_S_OverD9(_C_,_V_) (_C_)->OverD9 = (_V_)
#define aol_D_G_HidePlanningArea(_C_) (_C_)->HidePlanningArea
#define aol_D_S_HidePlanningArea(_C_,_V_) (_C_)->HidePlanningArea = (_V_)
#define aol_D_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct aol_typ_D_ {
  /* ------------------------- inputs --------------------------- */
  SGLfloat (*GradientsValue)[32UL];
  SGLfloat (*Scale)[9UL];
  SGLfloat (*GradientsEndInterpolated)[32UL];
  SGLfloat (*GradientsStartInterpolated)[32UL];
  SGLfloat (*PASP_BreakPointPositions)[4UL];
  SGLfloat (*PASP_FilteredSpeeds)[4UL];
  SGLint32 (*SPDI_SpeedChangeIndex)[10UL];
  SGLfloat (*SPDI_speedChangePosition)[10UL];
  SGLbool (*SPDI_SpeedChangeVisible)[10UL];
  SGLbool (*GradientsVisible)[32UL];
  SGLfloat (*PASP_IndicationMarkaerPosition)[1UL];
  /* ------------------------- outputs -------------------------- */
  SGLbool OverD12;
  SGLbool OverD9;
  SGLbool HidePlanningArea;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} aol_typ_D;

/* Associated functions */
extern void aol_D_init(aol_typ_D *pContext);
extern void aol_D_predraw(aol_typ_D *pContext);
extern void aol_D_draw(aol_typ_D *pContext, SGLint32 pPriority);

#endif /* _AOL_D_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

