/*********************************************************
 **
 ** File  aol_D.c
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\D\D.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

/* Inlined constants:
   GradientVisible=true
 */

#include "aol_D.h"
#include "aol_imported_functions.h"
#include "sgl.h"


void aol_D_init(aol_typ_D *pContext)
{
  {
    static SGLfloat _lArray0[32UL] = {0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F};
    aol_D_S_GradientsValue(pContext, _lArray0);
  }
  {
    static SGLfloat _lArray0[9UL] = {0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F};
    aol_D_S_Scale(pContext, _lArray0);
  }
  {
    static SGLfloat _lArray0[32UL] = {0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F};
    aol_D_S_GradientsEndInterpolated(pContext, _lArray0);
  }
  {
    static SGLfloat _lArray0[32UL] = {0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F};
    aol_D_S_GradientsStartInterpolated(pContext, _lArray0);
  }
  {
    static SGLfloat _lArray0[4UL] = {0.0F,0.0F,0.0F,0.0F};
    aol_D_S_PASP_BreakPointPositions(pContext, _lArray0);
  }
  {
    static SGLfloat _lArray0[4UL] = {0.0F,0.0F,0.0F,0.0F};
    aol_D_S_PASP_FilteredSpeeds(pContext, _lArray0);
  }
  {
    static SGLint32 _lArray0[10UL] = {0L};
    aol_D_S_SPDI_SpeedChangeIndex(pContext, _lArray0);
  }
  {
    static SGLfloat _lArray0[10UL] = {0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F};
    aol_D_S_SPDI_speedChangePosition(pContext, _lArray0);
  }
  {
    static SGLbool _lArray0[10UL] = {SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE};
    aol_D_S_SPDI_SpeedChangeVisible(pContext, _lArray0);
  }
  {
    static SGLbool _lArray0[32UL] = {SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE};
    aol_D_S_GradientsVisible(pContext, _lArray0);
  }
  {
    static SGLfloat _lArray0[1UL] = {0.0F};
    aol_D_S_PASP_IndicationMarkaerPosition(pContext, _lArray0);
  }
  aol_D_S_OverD12(pContext, SGL_FALSE);
  aol_D_S_OverD9(pContext, SGL_FALSE);
  aol_D_S_HidePlanningArea(pContext, SGL_FALSE);

  pContext->_parentPriority = 0L;

}

void aol_D_predraw(aol_typ_D *pContext)
{

}

void aol_D_draw(aol_typ_D *pContext, SGLint32 pPriority)
{
  SGLuint32 _lParentMasks = sglGetActiveMasks();
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: D, Type: container, OID: e665d5c1-d079-4e2e-b78a-b495bd43c7c1 */
    {
      sglPushMatrixAndTranslate(0.0F, 0.5F);

      /* Object: D1, Type: container, OID: f15bca7e-128b-4434-9cb4-0c93b068bdb5 */
      {

        /* Object: D1_1, Type: rectangle, OID: f287c346-054d-4d1f-a73c-9096cc6d33a2 */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglDisable(SGL_MODULATE);
          sglDisable(SGL_POLYGON_SMOOTH);
          sglTransparency8(255L);
          sglDisable(SGL_TEXTURE_2D);
          sglDisable(SGL_TESSELLATION);
          sglBegin(SGL_POLYGON);
          sglVertex2f(0.0F, 285.0F);
          sglVertex2f(40.0F, 285.0F);
          sglVertex2f(40.0F, 15.0F);
          sglVertex2f(0.0F, 15.0F);
          sglEnd();
        }
      }

      /* Object: D2, Type: container, OID: e61aec20-a927-4841-a2dc-f1cb67f8b0eb */
      {

        /* Object: D2_1, Type: rectangle, OID: 0429e043-d888-4fff-bcc3-0d4ae0fd68a4 */
        {
          /* filled object part */
          sglBegin(SGL_POLYGON);
          sglVertex2f(40.0F, 285.0F);
          sglVertex2f(65.0F, 285.0F);
          sglVertex2f(65.0F, 15.0F);
          sglVertex2f(40.0F, 15.0F);
          sglEnd();
        }
      }

      /* Object: D3, Type: container, OID: 65fc0e37-6920-4885-aeff-8b016a1c461c */
      {

        /* Object: D3_1, Type: rectangle, OID: dd3646fe-3d24-4ffd-89ba-e3e465932d7e */
        {
          /* filled object part */
          sglBegin(SGL_POLYGON);
          sglVertex2f(65.0F, 285.0F);
          sglVertex2f(90.0F, 285.0F);
          sglVertex2f(90.0F, 15.0F);
          sglVertex2f(65.0F, 15.0F);
          sglEnd();
        }
      }

      /* Object: D4, Type: container, OID: 58cea04c-d4ed-477c-8558-9091e803e3ea */
      {

        /* Object: D4_1, Type: rectangle, OID: 04fd5d13-6851-4879-b20b-fd6abc453624 */
        {
          /* filled object part */
          sglBegin(SGL_POLYGON);
          sglVertex2f(90.0F, 285.0F);
          sglVertex2f(115.0F, 285.0F);
          sglVertex2f(115.0F, 15.0F);
          sglVertex2f(90.0F, 15.0F);
          sglEnd();
        }
      }

      /* Object: D5, Type: container, OID: 7b3ff7f6-75aa-478e-a9cb-6678e50491d5 */
      {

        /* Object: D5_1, Type: rectangle, OID: e00f464f-7355-40bb-80c6-e3202d47509c */
        {
          /* filled object part */
          sglBegin(SGL_POLYGON);
          sglVertex2f(115.0F, 285.0F);
          sglVertex2f(133.0F, 285.0F);
          sglVertex2f(133.0F, 15.0F);
          sglVertex2f(115.0F, 15.0F);
          sglEnd();
        }

        /* Object: group, Type: container, OID: f556c137-5f70-4ca5-8125-f36424524cef */
        {

          /* Object: Gradient_np, Type: nplicatorContainer, OID: e61ada0c-71ad-42ea-a6c3-bc6471bb38aa */
          {
            SGLuint32 _lInstance;
            for (_lInstance=0UL; _lInstance<=31UL; _lInstance++) {
              if ((aol_D_G_GradientsVisible(pContext))[_lInstance]) {
                sglPushMatrixAndTranslate(115.0F, 15.0F);
                {
                  aol_typ_Gradient _lSubContextVar;
                  aol_typ_Gradient *_lSubContext = &_lSubContextVar;
                  aol_Gradient_init(_lSubContext);
                  aol_Gradient_S_GradientEnd(_lSubContext, (aol_D_G_GradientsEndInterpolated(pContext))[_lInstance]);
                  aol_Gradient_S_GradientStart(_lSubContext, (aol_D_G_GradientsStartInterpolated(pContext))[_lInstance]);
                  aol_Gradient_S_GradientValue(_lSubContext, (aol_D_G_GradientsValue(pContext))[_lInstance]);
                  aol_Gradient_S_GradientVisible(_lSubContext, (aol_D_G_GradientsVisible(pContext))[_lInstance]);
                  _lSubContext->_parentPriority = pContext->_parentPriority;
                  aol_Gradient_draw(_lSubContext, pPriority);
                }
                sglPopMatrixAndTranslate();
              }
            }
          }
        }
      }

      /* Object: D7, Type: container, OID: f41fa6ef-cdb3-4a94-bbc9-cefa6d2bdbeb */
      {

        /* Object: D7_1, Type: rectangle, OID: ebae2615-8b3f-46d5-9d43-9aba5fbd28a2 */
        {
          sglSetActiveMasks(_lParentMasks);
          /* filled object part */
          sglIndexColori(11L);
          sglDisable(SGL_MODULATE);
          sglDisable(SGL_POLYGON_SMOOTH);
          sglTransparency8(255L);
          sglDisable(SGL_TEXTURE_2D);
          sglDisable(SGL_TESSELLATION);
          sglBegin(SGL_POLYGON);
          sglVertex2f(147.0F, 285.0F);
          sglVertex2f(240.0F, 285.0F);
          sglVertex2f(240.0F, 15.0F);
          sglVertex2f(147.0F, 15.0F);
          sglEnd();
        }

        /* Object: PASP_np, Type: nplicatorContainer, OID: fd9b53ff-f0d1-439d-89b1-cc480cab3927 */
        {
          SGLuint32 _lInstance;
          for (_lInstance=0UL; _lInstance<=3UL; _lInstance++) {
            sglPushMatrixAndTranslate(147.0F, 15.0F);
            {
              aol_typ_PASP _lSubContextVar;
              aol_typ_PASP *_lSubContext = &_lSubContextVar;
              aol_PASP_init(_lSubContext);
              aol_PASP_S_BreakPointPosition(_lSubContext, (aol_D_G_PASP_BreakPointPositions(pContext))[_lInstance]);
              aol_PASP_S_Speed(_lSubContext, (aol_D_G_PASP_FilteredSpeeds(pContext))[_lInstance]);
              _lSubContext->_parentPriority = pContext->_parentPriority;
              aol_PASP_draw(_lSubContext, pPriority);
            }
            sglPopMatrixAndTranslate();
          }
        }

        /* Object: indicatorMarker_np, Type: nplicatorContainer, OID: 5cf85e04-464c-4592-9606-4b5b897cb686 */
        {
          /* Instance 0 */
          sglSetActiveMasks(_lParentMasks);
          sglPushMatrixAndTranslate(147.0F, 0.0F);
          {
            aol_typ_indicatorMarker _lSubContextVar;
            aol_typ_indicatorMarker *_lSubContext = &_lSubContextVar;
            aol_indicatorMarker_init(_lSubContext);
            aol_indicatorMarker_S_distanceIndicationPoint(_lSubContext, (aol_D_G_PASP_IndicationMarkaerPosition(pContext))[0UL]);
            _lSubContext->_parentPriority = pContext->_parentPriority;
            aol_indicatorMarker_draw(_lSubContext, pPriority);
          }
          sglPopMatrixAndTranslate();
        }
      }

      /* Object: D6, Type: container, OID: 9bcb211e-8a67-4c8b-b663-9e2d4b491add */
      {

        /* Object: D6_1, Type: rectangle, OID: 940876f7-2c59-46c2-b744-43acd8ab2376 */
        {
          sglSetActiveMasks(_lParentMasks);
          /* filled object part */
          sglIndexColori(6L);
          sglDisable(SGL_MODULATE);
          sglDisable(SGL_POLYGON_SMOOTH);
          sglTransparency8(255L);
          sglDisable(SGL_TEXTURE_2D);
          sglDisable(SGL_TESSELLATION);
          sglBegin(SGL_POLYGON);
          sglVertex2f(133.0F, 285.0F);
          sglVertex2f(147.0F, 285.0F);
          sglVertex2f(147.0F, 15.0F);
          sglVertex2f(133.0F, 15.0F);
          sglEnd();
        }

        /* Object: SPDI_np, Type: nplicatorContainer, OID: f4d76c8b-d9c9-46a1-a93c-0964bc82b882 */
        {
          SGLuint32 _lInstance;
          for (_lInstance=0UL; _lInstance<=9UL; _lInstance++) {
            sglPushMatrixAndTranslate(140.0F, 15.0F);
            {
              aol_typ_SPDI _lSubContextVar;
              aol_typ_SPDI *_lSubContext = &_lSubContextVar;
              aol_SPDI_init(_lSubContext);
              aol_SPDI_S_SPDI_SpeedChange(_lSubContext, (aol_D_G_SPDI_SpeedChangeIndex(pContext))[_lInstance]);
              aol_SPDI_S_SPDI_SpeedChangeVisible(_lSubContext, (aol_D_G_SPDI_SpeedChangeVisible(pContext))[_lInstance]);
              aol_SPDI_S_SPDI_speedChangePosition(_lSubContext, (aol_D_G_SPDI_speedChangePosition(pContext))[_lInstance]);
              _lSubContext->_parentPriority = pContext->_parentPriority;
              aol_SPDI_draw(_lSubContext, pPriority);
            }
            sglPopMatrixAndTranslate();
          }
        }
      }

      /* Object: D8, Type: container, OID: 4e0c8691-fd98-44a0-bb13-5923249f2063 */
      {

        /* Object: D8_1, Type: rectangle, OID: 646f1ae4-7b9b-4161-824d-27f6967f418d */
        {
          sglSetActiveMasks(_lParentMasks);
          /* filled object part */
          sglIndexColori(11L);
          sglDisable(SGL_MODULATE);
          sglDisable(SGL_POLYGON_SMOOTH);
          sglTransparency8(255L);
          sglDisable(SGL_TEXTURE_2D);
          sglDisable(SGL_TESSELLATION);
          sglBegin(SGL_POLYGON);
          sglVertex2f(240.0F, 285.0F);
          sglVertex2f(246.0F, 285.0F);
          sglVertex2f(246.0F, 15.0F);
          sglVertex2f(240.0F, 15.0F);
          sglEnd();
        }
      }

      /* Object: D9, Type: container, OID: 1e4b91d5-b63c-4c3d-88f1-30208e0d65ca */
      {

        /* Object: D9_1, Type: rectangle, OID: 522849ff-9686-4932-9cc4-d00caf16f3a5 */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(0.0F, 15.0F);
          sglVertex2f(40.0F, 15.0F);
          sglVertex2f(40.0F, 0.0F);
          sglVertex2f(0.0F, 0.0F);
          sglEnd();
        }

        /* Object: NavigationSymbols, Type: referenceContainer, OID: 48880454-b185-487d-8f84-267a431a83ca */
        {
          sglPushMatrixAndTranslate(20.0F, 7.5F);
          {
            aol_typ_NavigationSymbols _lSubContextVar;
            aol_typ_NavigationSymbols *_lSubContext = &_lSubContextVar;
            aol_NavigationSymbols_init(_lSubContext);
            aol_NavigationSymbols_S_ModeSymbol(_lSubContext, 3L);
            _lSubContext->_parentPriority = pContext->_parentPriority;
            aol_NavigationSymbols_draw(_lSubContext, pPriority);
          }
          sglPopMatrixAndTranslate();
        }

        /* Object: rectangle_area, Type: rectangleArea, OID: 343a4600-ee41-471e-b3fc-91a02617c3dc */
        {
          SGLfloat _lX = 0.0F;
          SGLfloat _lY = 0.0F;
          aol_locate(-1L, &_lX, &_lY);
          aol_D_G_OverD9(pContext) = sglRectangleActiveAreaGetStatus(_lX, _lY, 0.0F, 15.0F, 40.0F, 0.0F);
        }
      }

      /* Object: D10, Type: container, OID: ab1f8589-c2cb-4ae9-9e70-595dda654414 */
      {

        /* Object: D10_1, Type: rectangle, OID: 0cb3473a-158d-445b-859c-94d557490b04 */
        {
          sglSetActiveMasks(_lParentMasks);
          /* filled object part */
          sglIndexColori(6L);
          sglDisable(SGL_MODULATE);
          sglDisable(SGL_POLYGON_SMOOTH);
          sglTransparency8(255L);
          sglDisable(SGL_TEXTURE_2D);
          sglDisable(SGL_TESSELLATION);
          sglBegin(SGL_POLYGON);
          sglVertex2f(40.0F, 15.0F);
          sglVertex2f(206.0F, 15.0F);
          sglVertex2f(206.0F, 0.0F);
          sglVertex2f(40.0F, 0.0F);
          sglEnd();
        }
      }

      /* Object: D11, Type: container, OID: adbbe04a-d195-4dfe-a4c0-372df01d64ac */
      {

        /* Object: D11_1, Type: rectangle, OID: 2c753a05-1cf2-47e0-8ebe-500bea07579d */
        {
          /* filled object part */
          sglBegin(SGL_POLYGON);
          sglVertex2f(206.0F, 15.0F);
          sglVertex2f(246.0F, 15.0F);
          sglVertex2f(246.0F, 0.0F);
          sglVertex2f(206.0F, 0.0F);
          sglEnd();
        }
      }

      /* Object: D12, Type: container, OID: 2ef3cdbf-65a1-42f6-91c6-87cd497dce6e */
      {

        /* Object: D12_1, Type: rectangle, OID: 8e15f000-1311-4cb5-88ae-5bc2dca05b1f */
        {
          /* filled object part */
          sglBegin(SGL_POLYGON);
          sglVertex2f(0.0F, 300.0F);
          sglVertex2f(40.0F, 300.0F);
          sglVertex2f(40.0F, 285.0F);
          sglVertex2f(0.0F, 285.0F);
          sglEnd();
        }

        /* Object: NavigationSymbols_1, Type: referenceContainer, OID: 1462ecee-a934-47b7-aa41-d4259c3d9cbf */
        {
          sglPushMatrixAndTranslate(20.0F, 292.5F);
          {
            aol_typ_NavigationSymbols _lSubContextVar;
            aol_typ_NavigationSymbols *_lSubContext = &_lSubContextVar;
            aol_NavigationSymbols_init(_lSubContext);
            aol_NavigationSymbols_S_ModeSymbol(_lSubContext, 4L);
            _lSubContext->_parentPriority = pContext->_parentPriority;
            aol_NavigationSymbols_draw(_lSubContext, pPriority);
          }
          sglPopMatrixAndTranslate();
        }

        /* Object: rectangle_area_1, Type: rectangleArea, OID: d5cc41c7-e321-4247-b8f5-7098217bddf1 */
        {
          SGLfloat _lX = 0.0F;
          SGLfloat _lY = 0.0F;
          aol_locate(-1L, &_lX, &_lY);
          aol_D_G_OverD12(pContext) = sglRectangleActiveAreaGetStatus(_lX, _lY, 0.0F, 300.0F, 40.0F, 285.0F);
        }
      }

      /* Object: D13, Type: container, OID: 7c2ec43f-0a40-4906-beab-0e97db20f44d */
      {

        /* Object: D13_1, Type: rectangle, OID: af87b0f2-9eb4-4327-b714-4f968f9615cc */
        {
          sglSetActiveMasks(_lParentMasks);
          /* filled object part */
          sglIndexColori(6L);
          sglDisable(SGL_MODULATE);
          sglDisable(SGL_POLYGON_SMOOTH);
          sglTransparency8(255L);
          sglDisable(SGL_TEXTURE_2D);
          sglDisable(SGL_TESSELLATION);
          sglBegin(SGL_POLYGON);
          sglVertex2f(40.0F, 300.0F);
          sglVertex2f(206.0F, 300.0F);
          sglVertex2f(206.0F, 285.0F);
          sglVertex2f(40.0F, 285.0F);
          sglEnd();
        }
      }

      /* Object: D14, Type: container, OID: e973d11f-f8ae-4004-bd66-ed225616b14c */
      {

        /* Object: D14_1, Type: rectangle, OID: d2392490-3b88-4179-bab0-a552c9301261 */
        {
          /* filled object part */
          sglBegin(SGL_POLYGON);
          sglVertex2f(206.0F, 300.0F);
          sglVertex2f(246.0F, 300.0F);
          sglVertex2f(246.0F, 285.0F);
          sglVertex2f(206.0F, 285.0F);
          sglEnd();
        }

        /* Object: rectangle_area_2, Type: rectangleArea, OID: dab91bdc-89a1-466d-80c2-d9849baf9ee9 */
        {
          SGLfloat _lX = 0.0F;
          SGLfloat _lY = 0.0F;
          aol_locate(-1L, &_lX, &_lY);
          aol_D_G_HidePlanningArea(pContext) = sglRectangleActiveAreaGetStatus(_lX, _lY, 206.0F, 300.0F, 246.0F, 285.0F);
        }

        /* Object: NavigationSymbols_2, Type: referenceContainer, OID: 43c47165-a4e0-44ef-b8ba-05387fdca9e2 */
        {
          sglPushMatrixAndTranslate(229.0F, 292.5F);
          {
            aol_typ_NavigationSymbols _lSubContextVar;
            aol_typ_NavigationSymbols *_lSubContext = &_lSubContextVar;
            aol_NavigationSymbols_init(_lSubContext);
            aol_NavigationSymbols_S_ModeSymbol(_lSubContext, 1L);
            _lSubContext->_parentPriority = pContext->_parentPriority;
            aol_NavigationSymbols_draw(_lSubContext, pPriority);
          }
          sglPopMatrixAndTranslate();
        }
      }

      /* Object: scale, Type: container, OID: c56c04e5-d308-46f6-ac46-0290ec01d034 */
      {

        /* Object: group1, Type: container, OID: 0fafab6d-e2b3-4f57-b3ab-ea3452f52c75 */
        {
          sglPushMatrix();
          sglTranslatef(34.0F, 18.0F);
          sglScalef(0.6F, 0.6F);

          /* Object: zero, Type: text, OID: d19198a5-fd3c-4e34-bee6-0747d2815cfb */
          {
            static SGLuint8 _lArray0_zero[255UL] = {48U};
            sglSetActiveMasks(_lParentMasks);
            sglIndexColori(3L);
            sglIndexHaloColori(-1L);
            sglIndexFontLineWidthi(2L);
            sglIndexFonti(0L);
            sglDisable(SGL_LINE_HALOING);
            sglSetTextAlignment(SGL_ALIGN_RIGHT, SGL_ALIGN_MIDDLE);
            sgluWriteText(0.0F, 0.0F, _lArray0_zero, 255L);
          }
          sglPopMatrix();
        }

        /* Object: group2, Type: container, OID: 59d8681e-aa8f-4f52-9a72-0b946d0e8d7e */
        {
          sglPushMatrix();
          sglTranslatef(34.0F, 151.0F);
          sglScalef(0.6F, 0.6F);

          /* Object: bi_font, Type: bifont, OID: 3bfc108e-a1d5-4fa2-9768-cf122c5c8707 */
          {
            sglSetSecondFontAttributes(3L, 0L, 2L);
            {
              sgl_numeric_format _lFormat;
              _lFormat.l_integralPart = 5L;
              _lFormat.l_fractionalPart = 0L;
              _lFormat.l_secondFontPos = 0L;
              _lFormat.b_separator = 46U;
              _lFormat.b_leadingZeros = SGL_FALSE;
              _lFormat.l_displaySign = SGL_SIGN_NEVER;
              sgluWriteFloat(0.0F, 0.0F, (aol_D_G_Scale(pContext))[5], &_lFormat);
            }
          }
          sglPopMatrix();
        }

        /* Object: group3, Type: container, OID: 0f71754a-e374-41a5-a90b-1478c25fcb82 */
        {
          sglPushMatrix();
          sglTranslatef(34.0F, 194.0F);
          sglScalef(0.6F, 0.6F);

          /* Object: bi_font_1, Type: bifont, OID: 0ae8e9bb-1e28-4415-8bfd-bea6d3040c12 */
          {
            sgl_numeric_format _lFormat;
            _lFormat.l_integralPart = 5L;
            _lFormat.l_fractionalPart = 0L;
            _lFormat.l_secondFontPos = 0L;
            _lFormat.b_separator = 46U;
            _lFormat.b_leadingZeros = SGL_FALSE;
            _lFormat.l_displaySign = SGL_SIGN_NEVER;
            sgluWriteFloat(0.0F, 0.0F, (aol_D_G_Scale(pContext))[6], &_lFormat);
          }
          sglPopMatrix();
        }

        /* Object: group4, Type: container, OID: 14b03785-c2ef-455d-a017-e71f11a66336 */
        {
          sglPushMatrix();
          sglTranslatef(34.0F, 237.0F);
          sglScalef(0.6F, 0.6F);

          /* Object: bi_font_2, Type: bifont, OID: e6a2ef6d-41cc-41b1-98d3-be99d6d5db3e */
          {
            sgl_numeric_format _lFormat;
            _lFormat.l_integralPart = 5L;
            _lFormat.l_fractionalPart = 0L;
            _lFormat.l_secondFontPos = 0L;
            _lFormat.b_separator = 46U;
            _lFormat.b_leadingZeros = SGL_FALSE;
            _lFormat.l_displaySign = SGL_SIGN_NEVER;
            sgluWriteFloat(0.0F, 0.0F, (aol_D_G_Scale(pContext))[7], &_lFormat);
          }
          sglPopMatrix();
        }

        /* Object: group5, Type: container, OID: d5438287-5c40-4811-9abd-bd26b500a038 */
        {
          sglPushMatrix();
          sglTranslatef(34.0F, 280.0F);
          sglScalef(0.6F, 0.6F);

          /* Object: bi_font_3, Type: bifont, OID: 7ecc17ea-61db-4627-aba5-bb409c371155 */
          {
            sgl_numeric_format _lFormat;
            _lFormat.l_integralPart = 5L;
            _lFormat.l_fractionalPart = 0L;
            _lFormat.l_secondFontPos = 0L;
            _lFormat.b_separator = 46U;
            _lFormat.b_leadingZeros = SGL_FALSE;
            _lFormat.l_displaySign = SGL_SIGN_NEVER;
            sgluWriteFloat(0.0F, 0.0F, (aol_D_G_Scale(pContext))[8], &_lFormat);
          }
          sglPopMatrix();
        }

        /* Object: line, Type: line, OID: b5daf0f2-bf70-4e0c-8bf4-ac7fd099ddac */
        {
          /* outlined object part */
          sglDisable(SGL_TEXTURE_2D);
          sglIndexColori(1L);
          sglIndexLineWidthi(4L);
          sglIndexLineStipplei(0L);
          sglSetLineCaps(SGL_STRAIGHT_CAPS);
          sglTransparency8(128L);
          sglBegin(SGL_LINES);
          sglVertex2f(41.0F, 277.0F);
          sglVertex2f(239.0F, 277.0F);
          sglEnd();
        }

        /* Object: line_1, Type: line, OID: 76c9c5cb-44aa-4784-887d-2d3ce1064005 */
        {
          /* outlined object part */
          sglIndexLineWidthi(0L);
          sglBegin(SGL_LINES);
          sglVertex2f(41.0F, 234.0F);
          sglVertex2f(239.0F, 234.0F);
        }

        /* Object: line_2, Type: line, OID: 5c8a3665-8918-410a-a60a-8809ebd7a257 */
        {
          /* outlined object part */
          sglVertex2f(41.0F, 191.0F);
          sglVertex2f(239.0F, 191.0F);
          sglEnd();
        }

        /* Object: line_3, Type: line, OID: b7479b20-5975-48ef-99b3-276c3ffa77cb */
        {
          /* outlined object part */
          sglIndexLineWidthi(4L);
          sglBegin(SGL_LINES);
          sglVertex2f(41.0F, 148.0F);
          sglVertex2f(239.0F, 148.0F);
          sglEnd();
        }

        /* Object: line_4, Type: line, OID: 4f1ee226-ea91-4fc1-99d7-3c914dea023a */
        {
          /* outlined object part */
          sglIndexLineWidthi(0L);
          sglBegin(SGL_LINES);
          sglVertex2f(41.0F, 134.0F);
          sglVertex2f(239.0F, 134.0F);
        }

        /* Object: line_5, Type: line, OID: ee773d83-3af0-48c9-adc4-fd271df1609a */
        {
          /* outlined object part */
          sglVertex2f(41.0F, 116.0F);
          sglVertex2f(239.0F, 116.0F);
        }

        /* Object: line_6, Type: line, OID: e80fee82-36d0-4260-b5de-ce4d2246a12b */
        {
          /* outlined object part */
          sglVertex2f(41.0F, 92.0F);
          sglVertex2f(239.0F, 92.0F);
        }

        /* Object: line_7, Type: line, OID: 5523fe33-3fbc-4673-83d1-18829f1b2fdd */
        {
          /* outlined object part */
          sglVertex2f(41.0F, 48.0F);
          sglVertex2f(239.0F, 48.0F);
          sglEnd();
        }

        /* Object: line_8, Type: line, OID: 515efc34-e7e7-4e61-80b2-5f5f85814547 */
        {
          /* outlined object part */
          sglIndexLineWidthi(4L);
          sglBegin(SGL_LINES);
          sglVertex2f(41.0F, 15.0F);
          sglVertex2f(239.0F, 15.0F);
          sglEnd();
        }
      }
      sglPopMatrixAndTranslate();
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

