/*********************************************************
 **
 ** File  aol_PASP.h
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\PASP\PASP.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_PASP_H
#define _AOL_PASP_H

#include "sgl_types.h"


/* Accessors */
#define aol_PASP_G_BreakPointPosition(_C_) (_C_)->BreakPointPosition
#define aol_PASP_S_BreakPointPosition(_C_,_V_) (_C_)->BreakPointPosition = (_V_)
#define aol_PASP_G_Speed(_C_) (_C_)->Speed
#define aol_PASP_S_Speed(_C_,_V_) (_C_)->Speed = (_V_)
#define aol_PASP_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct aol_typ_PASP_ {
  /* ------------------------- inputs --------------------------- */
  SGLfloat BreakPointPosition;
  SGLfloat Speed;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} aol_typ_PASP;

/* Associated functions */
extern void aol_PASP_init(aol_typ_PASP *pContext);
extern void aol_PASP_predraw(aol_typ_PASP *pContext);
extern void aol_PASP_draw(aol_typ_PASP *pContext, SGLint32 pPriority);

#endif /* _AOL_PASP_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

