/*********************************************************
 **
 ** File  aol_line_stipple_table.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:26:51
 ** Command line: C:\Program Files (x86)\Esterel Technologies\SCADE R17.2\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\line_stipple_table.sst
 *********************************************************/

#ifndef _AOL_LINE_STIPPLE_TABLE_H
#define _AOL_LINE_STIPPLE_TABLE_H

#include "sgl_types.h"

/* Line stipple table definition */
extern const sgl_linestipple aol_line_stipple_table[5UL];

extern SGLint32 aol_line_stipple_table_size;

#endif /* _AOL_LINE_STIPPLE_TABLE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:26:51
 *********************************************************/

