/*********************************************************
 **
 ** File  aol_imported_functions.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:25
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_IMPORTED_FUNCTIONS_H
#define _AOL_IMPORTED_FUNCTIONS_H

#include "sgl_types.h"

/* Imported functions */
extern void aol_locate(SGLint32 pPointer, SGLfloat *pX, SGLfloat *pY);
extern void aol_pointer(SGLint32 pPointer, SGLbool *pPressed, SGLbool *pReleased, SGLint32 *pButton, SGLfloat *pX, SGLfloat *pY, SGLint32 *pModifiers);

#endif /* _AOL_IMPORTED_FUNCTIONS_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:25
 *********************************************************/

