/*********************************************************
 **
 ** File  aol_Gradient.c
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\Gradient\Gradient.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#include "aol_Gradient.h"
#include "aol_imported_functions.h"
#include "sgl.h"


void aol_Gradient_init(aol_typ_Gradient *pContext)
{
  aol_Gradient_S_GradientValue(pContext, 22.0F);
  aol_Gradient_S_GradientVisible(pContext, SGL_TRUE);
  aol_Gradient_S_GradientStart(pContext, 1.0F);
  aol_Gradient_S_GradientEnd(pContext, 100.0F);

  pContext->_parentPriority = 0L;

}

void aol_Gradient_predraw(aol_typ_Gradient *pContext)
{

}

void aol_Gradient_draw(aol_typ_Gradient *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: Gradient, Type: container, OID: fc06cc42-64c4-4723-9f7e-078a2dce5da6 */
    {
      if (aol_Gradient_G_GradientVisible(pContext)) {

        /* Object: rectangle, Type: rectangle, OID: a87d784e-4335-4486-b1a1-551e9ef51ec0 */
        {
          if (SGLint32_ge((SGLfloat_ge(aol_Gradient_G_GradientValue(pContext), 0.0F) ? 3L : 5L), 0L)) {
            /* filled object part */
            sglIndexColori((SGLfloat_ge(aol_Gradient_G_GradientValue(pContext), 0.0F) ? 3L : 5L));
            sglDisable(SGL_MODULATE);
            sglEnable(SGL_POLYGON_SMOOTH);
            sglTransparency8(255L);
            sglDisable(SGL_TEXTURE_2D);
            sglDisable(SGL_TESSELLATION);
            sglBegin(SGL_POLYGON);
            sglVertex2f(1.0F, aol_Gradient_G_GradientStart(pContext));
            sglVertex2f(17.0F, aol_Gradient_G_GradientStart(pContext));
            sglVertex2f(17.0F, aol_Gradient_G_GradientEnd(pContext));
            sglVertex2f(1.0F, aol_Gradient_G_GradientEnd(pContext));
            sglEnd();
          }
        }

        /* Object: group, Type: container, OID: c7a4cc1b-f60c-4610-b42c-7263e6a52523 */
        {
          if ((SGLfloat_gt(SGLfloat_sub(aol_Gradient_G_GradientEnd(pContext), aol_Gradient_G_GradientStart(pContext)), 45.0F) ? SGL_TRUE : SGL_FALSE)) {
            sglPushMatrix();
            sglTranslatef(9.0F, SGLfloat_add(SGLfloat_div(SGLfloat_sub(aol_Gradient_G_GradientEnd(pContext), aol_Gradient_G_GradientStart(pContext)), 2.0F), aol_Gradient_G_GradientStart(pContext)));
            sglScalef(0.7F, 0.7F);

            /* Object: bi_font, Type: bifont, OID: 6fb982e0-c65d-4b88-a7c6-27560a86a5ac */
            {
              if (SGLint32_ge((SGLfloat_ge(aol_Gradient_G_GradientValue(pContext), 0.0F) ? 2L : 1L), 0L)) {
                sglIndexColori((SGLfloat_ge(aol_Gradient_G_GradientValue(pContext), 0.0F) ? 2L : 1L));
                sglIndexHaloColori(-1L);
                sglIndexFontLineWidthi(2L);
                sglIndexFonti(0L);
                sglDisable(SGL_LINE_HALOING);
                sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                sglSetSecondFontAttributes((SGLfloat_ge(aol_Gradient_G_GradientValue(pContext), 0.0F) ? 2L : 1L), 0L, 2L);
                {
                  sgl_numeric_format _lFormat;
                  _lFormat.l_integralPart = 2L;
                  _lFormat.l_fractionalPart = 0L;
                  _lFormat.l_secondFontPos = 0L;
                  _lFormat.b_separator = 46U;
                  _lFormat.b_leadingZeros = SGL_FALSE;
                  _lFormat.l_displaySign = SGL_SIGN_NEVER;
                  sgluWriteFloat(0.0F, 0.0F, aol_Gradient_G_GradientValue(pContext), &_lFormat);
                }
              }
            }
            sglPopMatrix();
          }
        }

        /* Object: text, Type: text, OID: 8149255e-934c-4664-91a1-b6dfd2eb7e99 */
        {
          static SGLuint8 _lArray0_text[1UL] = {45U};
          static SGLuint8 _lArray1_text[1UL] = {43U};
          if ((SGLfloat_gt(SGLfloat_sub(aol_Gradient_G_GradientEnd(pContext), aol_Gradient_G_GradientStart(pContext)), 30.0F) ? SGL_TRUE : SGL_FALSE)) {
            if (SGLint32_ge((SGLfloat_ge(aol_Gradient_G_GradientValue(pContext), 0.0F) ? 2L : 1L), 0L)) {
              sglIndexColori((SGLfloat_ge(aol_Gradient_G_GradientValue(pContext), 0.0F) ? 2L : 1L));
              sglIndexHaloColori(-1L);
              sglIndexFontLineWidthi(2L);
              sglIndexFonti(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
              sgluWriteText(9.0F, SGLfloat_add(aol_Gradient_G_GradientStart(pContext), 10.0F), (SGLfloat_ge(aol_Gradient_G_GradientValue(pContext), 0.0F) ? _lArray1_text : _lArray0_text), 1L);
            }
          }
        }

        /* Object: text_1, Type: text, OID: fa49b6ea-f2bf-4079-9748-09f53db8b4c9 */
        {
          static SGLuint8 _lArray0_text_1[1UL] = {45U};
          static SGLuint8 _lArray1_text_1[1UL] = {43U};
          if ((SGLfloat_gt(SGLfloat_sub(aol_Gradient_G_GradientEnd(pContext), aol_Gradient_G_GradientStart(pContext)), 16.0F) ? SGL_TRUE : SGL_FALSE)) {
            if (SGLint32_ge((SGLfloat_ge(aol_Gradient_G_GradientValue(pContext), 0.0F) ? 2L : 1L), 0L)) {
              sglIndexColori((SGLfloat_ge(aol_Gradient_G_GradientValue(pContext), 0.0F) ? 2L : 1L));
              sglIndexHaloColori(-1L);
              sglIndexFontLineWidthi(2L);
              sglIndexFonti(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
              sgluWriteText(9.0F, SGLfloat_sub(aol_Gradient_G_GradientEnd(pContext), 10.0F), (SGLfloat_ge(aol_Gradient_G_GradientValue(pContext), 0.0F) ? _lArray1_text_1 : _lArray0_text_1), 1L);
            }
          }
        }
      }
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

