/*********************************************************
 **
 ** File  aol_driverid_display.h
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\DriverID_Display\driverid_display.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:24
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_DRIVERID_DISPLAY_H
#define _AOL_DRIVERID_DISPLAY_H

#include "sgl_types.h"
#include "kcg_assign.h"


/* Accessors */
#define aol_driverid_display_G_titlewindow(_C_) (_C_)->titlewindow
#define aol_driverid_display_S_titlewindow(_C_,_V_) (_C_)->titlewindow = (_V_)
#define aol_driverid_display_G_text_digit(_C_) (_C_)->text_digit
#define aol_driverid_display_S_text_digit(_C_,_V_) (_C_)->text_digit = (_V_)
#define aol_driverid_display_G_Ack_area(_C_) (_C_)->Ack_area
#define aol_driverid_display_S_Ack_area(_C_,_V_) (_C_)->Ack_area = (_V_)
#define aol_driverid_display_G_TrainRN_Display(_C_) (*(_C_)->TrainRN_Display)
#define aol_driverid_display_S_TrainRN_Display(_C_,_V_) (_C_)->TrainRN_Display = &(_V_)
#define aol_driverid_display_G_DriverID_Display(_C_) (*(_C_)->DriverID_Display)
#define aol_driverid_display_S_DriverID_Display(_C_,_V_) (_C_)->DriverID_Display = &(_V_)
#define aol_driverid_display_G_LevelIndex(_C_) (_C_)->LevelIndex
#define aol_driverid_display_S_LevelIndex(_C_,_V_) (_C_)->LevelIndex = (_V_)
#define aol_driverid_display_G_ButtonPressed(_C_) (_C_)->ButtonPressed
#define aol_driverid_display_S_ButtonPressed(_C_,_V_) (_C_)->ButtonPressed = (_V_)
#define aol_driverid_display_G_InputFieldAck(_C_) (_C_)->InputFieldAck
#define aol_driverid_display_S_InputFieldAck(_C_,_V_) (_C_)->InputFieldAck = (_V_)
#define aol_driverid_display_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct aol_typ_driverid_display_ {
  /* ------------------------- inputs --------------------------- */
  SGLint32 titlewindow;
  SGLint32 text_digit;
  SGLint32 Ack_area;
  SGLint32 (*TrainRN_Display)[9UL];
  SGLint32 (*DriverID_Display)[9UL];
  SGLint32 LevelIndex;
  SGLbool ButtonPressed;
  /* ------------------------- outputs -------------------------- */
  SGLbool InputFieldAck;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} aol_typ_driverid_display;

/* Associated functions */
extern void aol_driverid_display_init(aol_typ_driverid_display *pContext);
extern void aol_driverid_display_predraw(aol_typ_driverid_display *pContext);
extern void aol_driverid_display_draw(aol_typ_driverid_display *pContext, SGLint32 pPriority);

#endif /* _AOL_DRIVERID_DISPLAY_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:24
 *********************************************************/

