/*********************************************************
 **
 ** File  aol_button.h
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\MainMenu\Button\button.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:24
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_BUTTON_H
#define _AOL_BUTTON_H

#include "sgl_types.h"


/* Accessors */
#define aol_button_G_ButtonIndex(_C_) (_C_)->ButtonIndex
#define aol_button_S_ButtonIndex(_C_,_V_) (_C_)->ButtonIndex = (_V_)
#define aol_button_G_enableIndex(_C_) (_C_)->enableIndex
#define aol_button_S_enableIndex(_C_,_V_) (_C_)->enableIndex = (_V_)
#define aol_button_G_MousePressed(_C_) (_C_)->MousePressed
#define aol_button_S_MousePressed(_C_,_V_) (_C_)->MousePressed = (_V_)
#define aol_button_G_onButton(_C_) (_C_)->onButton
#define aol_button_S_onButton(_C_,_V_) (_C_)->onButton = (_V_)
#define aol_button_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct aol_typ_button_ {
  /* ------------------------- inputs --------------------------- */
  SGLint32 ButtonIndex;
  SGLint32 enableIndex;
  SGLbool MousePressed;
  /* ------------------------- outputs -------------------------- */
  SGLbool onButton;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} aol_typ_button;

/* Associated functions */
extern void aol_button_init(aol_typ_button *pContext);
extern void aol_button_predraw(aol_typ_button *pContext);
extern void aol_button_draw(aol_typ_button *pContext, SGLint32 pPriority);

#endif /* _AOL_BUTTON_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:24
 *********************************************************/

