/*********************************************************
 **
 ** File  aol_font_table.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:05
 ** Command line: C:\Program Files (x86)\Esterel Technologies\SCADE R17.2\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\font_table.sft
 *********************************************************/

#ifndef _AOL_FONT_TABLE_H
#define _AOL_FONT_TABLE_H

#include "glf.h"

/* Fonts definition */

typedef struct
{
  glf_type_font_table_header tr_header;
  glf_type_font tr_fonts_description[15UL];
  glf_type_map_property tr_maps[4UL];
  glf_type_character_bitmap5 tr_characters0[101UL];
  glf_type_character_bitmap5 tr_characters1[101UL];
  glf_type_character_bitmap6 tr_characters2[101UL];
  glf_type_character_bitmap6 tr_characters3[101UL];
  glf_type_character_bitmap7 tr_characters4[101UL];
  glf_type_character_bitmap2 tr_characters5[475UL];
  glf_type_character_bitmap2 tr_characters6[475UL];
  glf_type_character_bitmap2 tr_characters7[475UL];
  glf_type_character_bitmap2 tr_characters8[475UL];
  glf_type_character_bitmap2 tr_characters9[366UL];
  glf_type_character_bitmap2 tr_characters10[366UL];
  glf_type_character_bitmap2 tr_characters11[366UL];
  glf_type_character_bitmap2 tr_characters12[366UL];
  glf_type_character_bitmap2 tr_characters13[896UL];
  glf_type_character_bitmap2 tr_characters14[896UL];
} aol_font_table_type;

extern SGLuint8 aol_font_table_texture0[531060UL];
extern SGLuint8 aol_font_table_texture1[500059UL];
extern SGLuint8 aol_font_table_texture2[521698UL];
extern SGLuint8 aol_font_table_texture3[170025UL];

extern const aol_font_table_type aol_font_table;

#define AOL_FONT_TABLE_SIZE (sizeof(aol_font_table_type))

#endif /* _AOL_FONT_TABLE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:05
 *********************************************************/

