/*********************************************************
 **
 ** File  aol_DMI.c
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:25
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#include "aol_DMI.h"
#include "aol_imported_functions.h"
#include "sgl.h"
#include "kcg_assign.h"


void aol_DMI_init(aol_typ_DMI *pContext)
{
  aol_DMI_S_TrainPosition(pContext, 0.0F);
  aol_DMI_S_DistanceToTarget(pContext, 0.0F);
  aol_DMI_S_DistanceToTargetVisibilityDigital(pContext, SGL_TRUE);
  aol_DMI_S_TrainSpeed(pContext, 0.0F);
  aol_DMI_S_PointerColor(pContext, 1L);
  aol_DMI_S_SpeedDigitOne(pContext, 1.0F);
  aol_DMI_S_SpeedDigitTwo(pContext, 0.0F);
  aol_DMI_S_SpeedDigitThree(pContext, 0.0F);
  aol_DMI_S_Vperm(pContext, 0.0F);
  aol_DMI_S_Vtarget(pContext, 0.0F);
  aol_DMI_S_Vrelease(pContext, 0.0F);
  aol_DMI_S_VpermColor(pContext, 1L);
  aol_DMI_S_VtargetColor(pContext, 5L);
  aol_DMI_S_VreleaseColor(pContext, 8L);
  aol_DMI_S_ModeSymbol(pContext, 11L);
  aol_DMI_S_LevelSymbol(pContext, 3L);
  aol_DMI_S_StatusSymbolBrake(pContext, SGL_FALSE);
  aol_DMI_S_LevelSymbolAnncouncement(pContext, 7L);
  aol_DMI_S_InterpolatedDistanceToTarget(pContext, 0.0F);
  {
    static SGLint32 _lArray0[9UL] = {0L};
    aol_DMI_S_DriverID_Display(pContext, _lArray0);
  }
  {
    static SGLint32 _lArray0[30UL] = {0L};
    aol_DMI_S_buttonEnabler(pContext, _lArray0);
  }
  {
    static SGLbool _lArray0[15UL] = {SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE};
    aol_DMI_S_window_mask(pContext, _lArray0);
  }
  {
    static SGLint32 _lArray0[9UL] = {0L};
    aol_DMI_S_TrainRN_Display(pContext, _lArray0);
  }
  aol_DMI_S_closeButtonEnabler(pContext, 26L);
  aol_DMI_S_LevelSymbolVisibility(pContext, SGL_FALSE);
  aol_DMI_S_StatusSymbolVisibility(pContext, SGL_FALSE);
  aol_DMI_S_DistanceToTargetBarVisibility(pContext, SGL_FALSE);
  aol_DMI_S_RBC_status_symbol(pContext, 3L);
  aol_DMI_S_TrainDataWindowVisibility(pContext, SGL_FALSE);
  aol_DMI_S_ModeSymbolVisibility(pContext, SGL_FALSE);
  {
    static SGLuint8 _lArray0[45UL] = {0U};
    aol_DMI_S_textMsgLine1(pContext, _lArray0);
  }
  aol_DMI_S_traindataValidWinVisibility(pContext, SGL_FALSE);
  aol_DMI_S_trainLenght(pContext, 0.0F);
  aol_DMI_S_trainBrakePerc(pContext, 0.0F);
  aol_DMI_S_trainMaxSpeed(pContext, 0.0F);
  aol_DMI_S_trainAxleLoad(pContext, 0L);
  aol_DMI_S_indexTrainCategory(pContext, 0L);
  aol_DMI_S_trainAirtightIndex(pContext, 0L);
  aol_DMI_S_trainLoadingGaugeIndex(pContext, 0L);
  aol_DMI_S_traindataYesNoIndex(pContext, 0L);
  {
    static SGLint32 _lArray0[5UL] = {0L};
    aol_DMI_S_ArrayOfMsgIndex(pContext, _lArray0);
  }
  aol_DMI_S_textMsgEnable(pContext, SGL_FALSE);
  aol_DMI_S_yellowBorderMsg(pContext, SGL_FALSE);
  aol_DMI_S_closeButtonIndex(pContext, 26L);
  aol_DMI_S_openDesk(pContext, SGL_FALSE);
  aol_DMI_S_ModeSymbolAnnouncement(pContext, 16L);
  aol_DMI_S_iconGroupIndex(pContext, 0L);
  aol_DMI_S_yellowBorderBrakeSymbol(pContext, SGL_FALSE);
  aol_DMI_S_yellowBorderC1Area(pContext, SGL_FALSE);
  aol_DMI_S_translateHourGlass(pContext, 0.0F);
  aol_DMI_S_hourGlassVisibility(pContext, SGL_FALSE);
  aol_DMI_S_Vtarget_permVisible(pContext, SGL_FALSE);
  aol_DMI_S_Vtarget_permColor(pContext, 1L);
  aol_DMI_S_Vinterv(pContext, 0.0F);
  aol_DMI_S_VintervColor(pContext, 9L);
  aol_DMI_S_VintervVisible(pContext, SGL_FALSE);
  aol_DMI_S_levelMenuVisibility(pContext, SGL_FALSE);
  {
    static SGLint32 _lArray0[12UL] = {1L,2L,3L,5L,5L,5L};
    aol_DMI_S_ArrayLevelIndex(pContext, _lArray0);
  }
  aol_DMI_S_LevelIndex(pContext, 1L);
  {
    static SGLuint8 _lArray0[5UL][50UL] = {{0U},{0U},{0U},{0U},{0U}};
    aol_DMI_S_ListMsg(pContext, _lArray0);
  }
  aol_DMI_S_SingleMsgAckRequiredVisibility(pContext, SGL_FALSE);
  {
    static SGLint32 _lArray0[5UL] = {0L};
    aol_DMI_S_IndexFixedMsg(pContext, _lArray0);
  }
  {
    static SGLuint8 _lArray0[5UL][30UL] = {{99U,105U,97U,111U},{99U,105U,97U,111U},{98U,97U,109U,98U,105U,110U,97U},{0U},{0U}};
    aol_DMI_S_PlainText(pContext, _lArray0);
  }
  {
    static SGLfloat _lArray0[5UL] = {18.0F,0.0F,0.0F,0.0F,0.0F};
    aol_DMI_S_Array_hh(pContext, _lArray0);
  }
  {
    static SGLfloat _lArray0[5UL] = {20.0F,0.0F,0.0F,0.0F,0.0F};
    aol_DMI_S_Array_mm(pContext, _lArray0);
  }
  aol_DMI_S_isAuxiliarMsg(pContext, SGL_FALSE);
  {
    static SGLfloat _lArray0[9UL] = {0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F};
    aol_DMI_S_D_Scale(pContext, _lArray0);
  }
  {
    static SGLfloat _lArray0[32UL] = {0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F};
    aol_DMI_S_D_GradientEndInterpolated(pContext, _lArray0);
  }
  {
    static SGLfloat _lArray0[32UL] = {0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F};
    aol_DMI_S_D_GradientsStartInterpolated(pContext, _lArray0);
  }
  {
    static SGLfloat _lArray0[4UL] = {0.0F,0.0F,0.0F,0.0F};
    aol_DMI_S_D_PASP_BreakPointPositions(pContext, _lArray0);
  }
  {
    static SGLfloat _lArray0[4UL] = {0.0F,0.0F,0.0F,0.0F};
    aol_DMI_S_D_PASP_FilteredSpeeds(pContext, _lArray0);
  }
  {
    static SGLint32 _lArray0[10UL] = {0L};
    aol_DMI_S_D_SPID_SpeedChangeIndex(pContext, _lArray0);
  }
  {
    static SGLfloat _lArray0[10UL] = {0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F};
    aol_DMI_S_D_SPDI_speedChangePosition(pContext, _lArray0);
  }
  {
    static SGLbool _lArray0[10UL] = {SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE};
    aol_DMI_S_D_SPDI_SpeedChangeVisible(pContext, _lArray0);
  }
  {
    static SGLbool _lArray0[32UL] = {SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE};
    aol_DMI_S_D_GradientsVisible(pContext, _lArray0);
  }
  aol_DMI_S_PlanningAreaVisibility(pContext, SGL_FALSE);
  {
    static SGLfloat _lArray0[32UL] = {0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F};
    aol_DMI_S_D_GradientsValue(pContext, _lArray0);
  }
  {
    static SGLfloat _lArray0[32UL] = {0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F};
    aol_DMI_S_D_GradientsEndInterpolated(pContext, _lArray0);
  }
  {
    static SGLfloat _lArray0[1UL] = {0.0F};
    aol_DMI_S_D_PASP_IndicationMarkerPosition(pContext, _lArray0);
  }
  aol_DMI_S_undefined(pContext, 0L);
  aol_DMI_S_scrollUpEnableTypeIndex(pContext, 0L);
  aol_DMI_S_scrollDownEnableTypeIndex(pContext, 0L);
  {
    static SGLfloat _lArray0[4UL] = {0.0F,0.0F,0.0F,0.0F};
    aol_DMI_S_localTimeArray(pContext, _lArray0);
  }
  aol_DMI_S_OverA(pContext, SGL_FALSE);
  aol_DMI_S_OverC2(pContext, SGL_FALSE);
  aol_DMI_S_OverC3(pContext, SGL_FALSE);
  aol_DMI_S_OverC4(pContext, SGL_FALSE);
  aol_DMI_S_MousePressed(pContext, SGL_FALSE);
  {
    static SGLbool _lArray0[12UL] = {SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE};
    aol_DMI_S_VisibleGradients(pContext, _lArray0);
  }
  {
    static SGLbool _lArray0[12UL] = {SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE,SGL_FALSE};
    aol_DMI_S_keyarray(pContext, _lArray0);
  }
  aol_DMI_S_confirmTrainData(pContext, SGL_FALSE);
  aol_DMI_S_openTrainData(pContext, SGL_FALSE);
  aol_DMI_S_startRequest(pContext, SGL_FALSE);
  aol_DMI_S_traindataAck(pContext, SGL_FALSE);
  aol_DMI_S_traindataYesAck(pContext, SGL_FALSE);
  aol_DMI_S_traindataNoAck(pContext, SGL_FALSE);
  aol_DMI_S_textMsgAck(pContext, SGL_FALSE);
  aol_DMI_S_openTrainRN(pContext, SGL_FALSE);
  aol_DMI_S_openDriverID(pContext, SGL_FALSE);
  aol_DMI_S_closeButton(pContext, SGL_FALSE);
  aol_DMI_S_BrakeStatusSymbolAck(pContext, SGL_FALSE);
  aol_DMI_S_C1AreaAck(pContext, SGL_FALSE);
  aol_DMI_S_openLevelMenu(pContext, SGL_FALSE);
  aol_DMI_S_InputFieldAck(pContext, SGL_FALSE);
  aol_DMI_S_ButtonPressed(pContext, SGL_FALSE);
  aol_DMI_S_OverD12(pContext, SGL_FALSE);
  aol_DMI_S_OverD9(pContext, SGL_FALSE);
  aol_DMI_S_OpenMainMenu(pContext, SGL_FALSE);
  aol_DMI_S_closeMainMenu(pContext, SGL_FALSE);
  aol_DMI_S_hidePlanningArea(pContext, SGL_FALSE);
  aol_DMI_S_ShowPlanningArea(pContext, SGL_FALSE);
  aol_DMI_S_openShunting(pContext, SGL_FALSE);
  aol_DMI_S_openNonLeading(pContext, SGL_FALSE);
  aol_DMI_S_scrollUp(pContext, SGL_FALSE);
  aol_DMI_S_scrollDown(pContext, SGL_FALSE);
  aol_DMI_S_isPressed(pContext, SGL_FALSE);

  aol_A_init(&(pContext->__A__));
  aol_B_init(&(pContext->__B__));
  aol_C_init(&(pContext->__C__));
  aol_D_init(&(pContext->__D__));
  aol_F_init(&(pContext->__F__));
  aol_driverid_display_init(&(pContext->__driverid_display__));
  aol_keypad_init(&(pContext->__keypad__));
  aol_closebutton_init(&(pContext->__closebutton__));
  aol_driverid_display_init(&(pContext->__trainRN_display__));
  aol_keypad_init(&(pContext->__keypad_1__));
  aol_closebutton_init(&(pContext->__closebutton_1__));
  aol_mainmenu_init(&(pContext->__mainmenu_1__));
  aol_TrainData_init(&(pContext->__TrainData_1__));
  aol_ValidationWindow_init(&(pContext->__ValidationWindow__));
  aol_driverid_display_init(&(pContext->__level_display__));
  aol_keypad_init(&(pContext->__keypad_2__));
  aol_closebutton_init(&(pContext->__closebutton_2__));
  aol_ButtonBehaviour_behavior_init(&(pContext->__ButtonBehaviour__));
}

void aol_DMI_predraw(aol_typ_DMI *pContext)
{
  aol_DMI_S_traindataAck(pContext, SGL_FALSE);
  aol_DMI_S_textMsgAck(pContext, SGL_FALSE);
  aol_DMI_S_BrakeStatusSymbolAck(pContext, SGL_FALSE);
  aol_DMI_S_scrollUp(pContext, SGL_FALSE);
  aol_DMI_S_scrollDown(pContext, SGL_FALSE);

  aol_A_predraw(&(pContext->__A__));
  aol_B_predraw(&(pContext->__B__));
  aol_C_predraw(&(pContext->__C__));
  aol_D_predraw(&(pContext->__D__));
  aol_F_predraw(&(pContext->__F__));
  aol_driverid_display_predraw(&(pContext->__driverid_display__));
  aol_keypad_predraw(&(pContext->__keypad__));
  aol_closebutton_predraw(&(pContext->__closebutton__));
  aol_driverid_display_predraw(&(pContext->__trainRN_display__));
  aol_keypad_predraw(&(pContext->__keypad_1__));
  aol_closebutton_predraw(&(pContext->__closebutton_1__));
  aol_mainmenu_predraw(&(pContext->__mainmenu_1__));
  aol_TrainData_predraw(&(pContext->__TrainData_1__));
  aol_ValidationWindow_predraw(&(pContext->__ValidationWindow__));
  aol_driverid_display_predraw(&(pContext->__level_display__));
  aol_keypad_predraw(&(pContext->__keypad_2__));
  aol_closebutton_predraw(&(pContext->__closebutton_2__));
}

void aol_DMI_draw(aol_typ_DMI *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, 0L)) {

    /* Object: DMI, Type: layer, OID: b407b1a6-e1ce-4242-902a-855eafe548c8 */
    {
      sglPushMatrixAndTranslate(320.0F, 240.0F);

      /* Object: bi_font, Type: bifont, OID: 523dc833-a3f7-4f43-b4a8-889b2b0d0790 */
      {
        sglSetActiveMasks(SGL_NO_MASK);
        sglIndexColori(1L);
        sglIndexHaloColori(-1L);
        sglIndexFontLineWidthi(2L);
        sglIndexFonti(0L);
        sglDisable(SGL_LINE_HALOING);
        sglSetTextAlignment(SGL_ALIGN_LEFT, SGL_ALIGN_BOTTOM);
        sglSetSecondFontAttributes(1L, 0L, 2L);
        {
          sgl_numeric_format _lFormat;
          _lFormat.l_integralPart = 5L;
          _lFormat.l_fractionalPart = 2L;
          _lFormat.l_secondFontPos = 0L;
          _lFormat.b_separator = 46U;
          _lFormat.b_leadingZeros = SGL_FALSE;
          _lFormat.l_displaySign = SGL_SIGN_WHEN_NEGATIVE;
          sgluWriteFloat(85.0F, -145.0F, aol_DMI_G_SpeedDigitOne(pContext), &_lFormat);
        }
      }

      /* Object: A, Type: referenceContainer, OID: 4afe504d-c5e6-4118-807b-e34d0f34d677 */
      {
        sglPushMatrixAndTranslate(-293.0F, 75.0F);
        {
          aol_typ_A *_lSubContext = &(pContext->__A__);
          aol_A_S_DistToTargetBarVisibility(_lSubContext, aol_DMI_G_DistanceToTargetBarVisibility(pContext));
          aol_A_S_DistanceToTarget(_lSubContext, aol_DMI_G_DistanceToTarget(pContext));
          aol_A_S_DistanceToTargetVisiblityDigital(_lSubContext, aol_DMI_G_DistanceToTargetVisibilityDigital(pContext));
          aol_A_S_InterpolatedDistanceToTarget(_lSubContext, aol_DMI_G_InterpolatedDistanceToTarget(pContext));
          _lSubContext->_parentPriority = 0L;
          aol_A_draw(_lSubContext, pPriority);
          aol_DMI_G_OverA(pContext) = aol_A_G_OverA(_lSubContext);
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: B, Type: referenceContainer, OID: 471e76ca-2611-47b2-b471-8d4193726a0f */
      {
        sglSetActiveMasks(SGL_NO_MASK);
        sglPushMatrixAndTranslate(-126.0F, 75.0F);
        {
          aol_typ_B *_lSubContext = &(pContext->__B__);
          aol_B_S_ModeSymbol(_lSubContext, aol_DMI_G_ModeSymbol(pContext));
          aol_B_S_ModeSymbolVisibility(_lSubContext, aol_DMI_G_ModeSymbolVisibility(pContext));
          aol_B_S_PointerColor(_lSubContext, aol_DMI_G_PointerColor(pContext));
          aol_B_S_SpeedDigitOne(_lSubContext, aol_DMI_G_SpeedDigitOne(pContext));
          aol_B_S_SpeedDigitThree(_lSubContext, aol_DMI_G_SpeedDigitThree(pContext));
          aol_B_S_SpeedDigitTwo(_lSubContext, aol_DMI_G_SpeedDigitTwo(pContext));
          aol_B_S_TrainSpeed(_lSubContext, aol_DMI_G_TrainSpeed(pContext));
          aol_B_S_Vinterv(_lSubContext, aol_DMI_G_Vinterv(pContext));
          aol_B_S_VintervColor(_lSubContext, aol_DMI_G_VintervColor(pContext));
          aol_B_S_VintervVisible(_lSubContext, aol_DMI_G_VintervVisible(pContext));
          aol_B_S_Vperm(_lSubContext, aol_DMI_G_Vperm(pContext));
          aol_B_S_VpermColor(_lSubContext, aol_DMI_G_VpermColor(pContext));
          aol_B_S_Vrelease(_lSubContext, aol_DMI_G_Vrelease(pContext));
          aol_B_S_VreleaseColor(_lSubContext, aol_DMI_G_VreleaseColor(pContext));
          aol_B_S_Vtarget(_lSubContext, aol_DMI_G_Vtarget(pContext));
          aol_B_S_VtargetColor(_lSubContext, aol_DMI_G_VtargetColor(pContext));
          aol_B_S_Vtarget_permColor(_lSubContext, aol_DMI_G_Vtarget_permColor(pContext));
          aol_B_S_Vtarget_permVisible(_lSubContext, aol_DMI_G_Vtarget_permVisible(pContext));
          _lSubContext->_parentPriority = 0L;
          aol_B_draw(_lSubContext, pPriority);
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: C, Type: referenceContainer, OID: ad51aef9-5956-4afd-82e2-11e948373973 */
      {
        sglSetActiveMasks(SGL_NO_MASK);
        sglPushMatrixAndTranslate(-153.0F, -100.0F);
        {
          aol_typ_C *_lSubContext = &(pContext->__C__);
          aol_C_S_C1_area_visibility(_lSubContext, SGL_TRUE);
          aol_C_S_LevelSymbol(_lSubContext, aol_DMI_G_LevelSymbol(pContext));
          aol_C_S_LevelSymbolAnncouncement(_lSubContext, aol_DMI_G_LevelSymbolAnncouncement(pContext));
          aol_C_S_LevelSymbolVisibility(_lSubContext, aol_DMI_G_LevelSymbolVisibility(pContext));
          aol_C_S_ModeSymbolAnncouncement(_lSubContext, aol_DMI_G_ModeSymbolAnnouncement(pContext));
          aol_C_S_StatusSymbolBrake(_lSubContext, aol_DMI_G_StatusSymbolBrake(pContext));
          aol_C_S_iconGroupIndex(_lSubContext, aol_DMI_G_iconGroupIndex(pContext));
          aol_C_S_yellowBorderBrakeSymbol(_lSubContext, aol_DMI_G_yellowBorderBrakeSymbol(pContext));
          aol_C_S_yellowBorderC1Area(_lSubContext, aol_DMI_G_yellowBorderC1Area(pContext));
          _lSubContext->_parentPriority = 0L;
          aol_C_draw(_lSubContext, pPriority);
          aol_DMI_G_BrakeStatusSymbolAck(pContext) = aol_C_G_BrakeStatusSymbolAck(_lSubContext);
          aol_DMI_G_C1AreaAck(pContext) = aol_C_G_C1AreaAck(_lSubContext);
          aol_DMI_G_OverC2(pContext) = aol_C_G_OverC2(_lSubContext);
          aol_DMI_G_OverC3(pContext) = aol_C_G_OverC3(_lSubContext);
          aol_DMI_G_OverC4(pContext) = aol_C_G_OverC4(_lSubContext);
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: D, Type: referenceContainer, OID: 8917117e-d291-4c3d-9a5d-502f68d1b40c */
      {
        if (aol_DMI_G_PlanningAreaVisibility(pContext)) {
          sglSetActiveMasks(SGL_NO_MASK);
          sglPushMatrixAndTranslate(13.0F, -77.0F);
          {
            aol_typ_D *_lSubContext = &(pContext->__D__);
            aol_D_S_GradientsEndInterpolated(_lSubContext, aol_DMI_G_D_GradientsEndInterpolated(pContext));
            aol_D_S_GradientsStartInterpolated(_lSubContext, aol_DMI_G_D_GradientsStartInterpolated(pContext));
            aol_D_S_GradientsValue(_lSubContext, aol_DMI_G_D_GradientsValue(pContext));
            aol_D_S_GradientsVisible(_lSubContext, aol_DMI_G_D_GradientsVisible(pContext));
            aol_D_S_PASP_BreakPointPositions(_lSubContext, aol_DMI_G_D_PASP_BreakPointPositions(pContext));
            aol_D_S_PASP_FilteredSpeeds(_lSubContext, aol_DMI_G_D_PASP_FilteredSpeeds(pContext));
            aol_D_S_PASP_IndicationMarkaerPosition(_lSubContext, aol_DMI_G_D_PASP_IndicationMarkerPosition(pContext));
            aol_D_S_SPDI_SpeedChangeIndex(_lSubContext, aol_DMI_G_D_SPID_SpeedChangeIndex(pContext));
            aol_D_S_SPDI_SpeedChangeVisible(_lSubContext, aol_DMI_G_D_SPDI_SpeedChangeVisible(pContext));
            aol_D_S_SPDI_speedChangePosition(_lSubContext, aol_DMI_G_D_SPDI_speedChangePosition(pContext));
            aol_D_S_Scale(_lSubContext, aol_DMI_G_D_Scale(pContext));
            _lSubContext->_parentPriority = 0L;
            aol_D_draw(_lSubContext, pPriority);
            aol_DMI_G_hidePlanningArea(pContext) = aol_D_G_HidePlanningArea(_lSubContext);
            aol_DMI_G_OverD12(pContext) = aol_D_G_OverD12(_lSubContext);
            aol_DMI_G_OverD9(pContext) = aol_D_G_OverD9(_lSubContext);
          }
          sglPopMatrixAndTranslate();
        }
      }

      /* Object: E, Type: referenceContainer, OID: 947f8bb6-c880-4e73-8e30-777bbe8c296e */
      {
        sglPushMatrixAndTranslate(-153.0F, -175.0F);
        {
          aol_typ_E _lSubContextVar;
          aol_typ_E *_lSubContext = &_lSubContextVar;
          aol_E_init(_lSubContext);
          aol_E_S_ArrayOfMsgIndex(_lSubContext, aol_DMI_G_ArrayOfMsgIndex(pContext));
          aol_E_S_ArrayPlainText(_lSubContext, aol_DMI_G_PlainText(pContext));
          aol_E_S_Array_hh(_lSubContext, aol_DMI_G_Array_hh(pContext));
          aol_E_S_Array_mm(_lSubContext, aol_DMI_G_Array_mm(pContext));
          aol_E_S_IndexFixedMsg(_lSubContext, aol_DMI_G_IndexFixedMsg(pContext));
          aol_E_S_SingleMsgAckRequiredVisibility(_lSubContext, aol_DMI_G_SingleMsgAckRequiredVisibility(pContext));
          aol_E_S_StatusSymbolVisibility(_lSubContext, aol_DMI_G_StatusSymbolVisibility(pContext));
          aol_E_S_StatusSymnolIndex(_lSubContext, aol_DMI_G_RBC_status_symbol(pContext));
          aol_E_S_isAuxiliarMsg(_lSubContext, aol_DMI_G_isAuxiliarMsg(pContext));
          aol_E_S_scrolDownlButtonClicked(_lSubContext, SGL_FALSE);
          aol_E_S_scrolUplButtonClicked(_lSubContext, SGL_FALSE);
          aol_E_S_scrollDownEnableTypeIndex(_lSubContext, aol_DMI_G_scrollDownEnableTypeIndex(pContext));
          aol_E_S_scrollUpEnableTypeIndex(_lSubContext, aol_DMI_G_scrollUpEnableTypeIndex(pContext));
          aol_E_S_yellowBorderMsg(_lSubContext, aol_DMI_G_yellowBorderMsg(pContext));
          _lSubContext->_parentPriority = 0L;
          aol_E_draw(_lSubContext, pPriority);
          aol_DMI_G_scrollDown(pContext) = aol_E_G_scrollDown(_lSubContext);
          aol_DMI_G_scrollUp(pContext) = aol_E_G_scrollUp(_lSubContext);
          aol_DMI_G_textMsgAck(pContext) = aol_E_G_textMsgAck(_lSubContext);
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: F, Type: referenceContainer, OID: 392fdd81-aef9-486e-956b-e2c9b46051b2 */
      {
        sglSetActiveMasks(SGL_NO_MASK);
        sglPushMatrixAndTranslate(290.0F, 0.0F);
        {
          aol_typ_F *_lSubContext = &(pContext->__F__);
          aol_F_S_ButtonPressed(_lSubContext, aol_DMI_G_isPressed(pContext));
          _lSubContext->_parentPriority = 0L;
          aol_F_draw(_lSubContext, pPriority);
          aol_DMI_G_OpenMainMenu(pContext) = aol_F_G_onMainButton(_lSubContext);
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: G, Type: referenceContainer, OID: df78d1b7-a8c1-48c4-aae6-31e345876fb5 */
      {
        sglSetActiveMasks(SGL_NO_MASK);
        sglPushMatrixAndTranslate(137.0F, -150.0F);
        {
          aol_typ_G _lSubContextVar;
          aol_typ_G *_lSubContext = &_lSubContextVar;
          aol_G_init(_lSubContext);
          aol_G_S_localTimeArray(_lSubContext, aol_DMI_G_localTimeArray(pContext));
          _lSubContext->_parentPriority = 0L;
          aol_G_draw(_lSubContext, pPriority);
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: Z, Type: referenceContainer, OID: d13c4fd8-cb34-4943-ac15-c24fe13237fe */
      {
        sglSetActiveMasks(SGL_NO_MASK);
        sglPushMatrixAndTranslate(0.0F, 232.5F);
        {
          aol_typ_Z _lSubContextVar;
          aol_typ_Z *_lSubContext = &_lSubContextVar;
          aol_Z_init(_lSubContext);
          _lSubContext->_parentPriority = 0L;
          aol_Z_draw(_lSubContext, pPriority);
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: Y, Type: referenceContainer, OID: 42f215b0-246d-4e9d-b914-4526e9a9b816 */
      {
        sglSetActiveMasks(SGL_NO_MASK);
        sglPushMatrixAndTranslate(-10.0F, -237.5F);
        {
          aol_typ_Y _lSubContextVar;
          aol_typ_Y *_lSubContext = &_lSubContextVar;
          aol_Y_init(_lSubContext);
          _lSubContext->_parentPriority = 0L;
          aol_Y_draw(_lSubContext, pPriority);
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: OnPlanningArea, Type: rectangleArea, OID: 7c31b9a3-a012-4b9b-a3f8-1b4f7ef0c53e */
      {
        if (SGLbool_not(aol_DMI_G_PlanningAreaVisibility(pContext))) {
          {
            SGLfloat _lX = 0.0F;
            SGLfloat _lY = 0.0F;
            aol_locate(-1L, &_lX, &_lY);
            aol_DMI_G_ShowPlanningArea(pContext) = sglRectangleActiveAreaGetStatus(_lX, _lY, 17.0F, 223.0F, 260.0F, -76.0F);
          }
        }
      }

      /* Object: menu, Type: container, OID: 97aca467-3293-4cf3-9af1-27fdbb74a1a1 */
      {
        sglPushMatrixAndTranslate(1.5F, 0.0F);

        /* Object: driverid, Type: container, OID: 67e10159-d85b-4eb1-9dbe-269acd6830c2 */
        {
          if ((aol_DMI_G_window_mask(pContext))[0]) {
            sglPushMatrixAndTranslate(-1.0F, 0.0F);

            /* Object: backgroundMenu, Type: rectangle, OID: 413da1b9-fe4f-4b07-a9d1-f63d133ca562 */
            {
              /* filled object part */
              sglIndexColori(6L);
              sglDisable(SGL_MODULATE);
              sglEnable(SGL_POLYGON_SMOOTH);
              sglTransparency8(255L);
              sglDisable(SGL_TEXTURE_2D);
              sglDisable(SGL_TESSELLATION);
              sglBegin(SGL_POLYGON);
              sglVertex2f(14.0F, 240.0F);
              sglVertex2f(320.0F, 240.0F);
              sglVertex2f(320.0F, -240.0F);
              sglVertex2f(14.0F, -240.0F);
              sglEnd();
            }

            /* Object: driverid_display, Type: referenceContainer, OID: 41ae8c5e-1652-4ec1-b5a4-dcc6c3f648eb */
            {
              static SGLint32 _lArray0_driverid_display[9UL] = {0L};
              sglPushMatrixAndTranslate(169.0F, 126.0F);
              {
                aol_typ_driverid_display *_lSubContext = &(pContext->__driverid_display__);
                aol_driverid_display_S_Ack_area(_lSubContext, 1L);
                aol_driverid_display_S_ButtonPressed(_lSubContext, aol_DMI_G_isPressed(pContext));
                aol_driverid_display_S_DriverID_Display(_lSubContext, aol_DMI_G_DriverID_Display(pContext));
                aol_driverid_display_S_LevelIndex(_lSubContext, 0L);
                aol_driverid_display_S_TrainRN_Display(_lSubContext, _lArray0_driverid_display);
                aol_driverid_display_S_text_digit(_lSubContext, 1L);
                aol_driverid_display_S_titlewindow(_lSubContext, 1L);
                _lSubContext->_parentPriority = 0L;
                aol_driverid_display_draw(_lSubContext, pPriority);
                aol_DMI_G_InputFieldAck(pContext) = aol_driverid_display_G_InputFieldAck(_lSubContext);
              }
              sglPopMatrixAndTranslate();
            }

            /* Object: keypad, Type: referenceContainer, OID: 6d497f2f-0f26-4ea3-9640-1afcd5c22ce1 */
            {
              static SGLint32 _lArray0_keypad[12UL] = {0L};
              sglSetActiveMasks(SGL_NO_MASK);
              sglPushMatrixAndTranslate(169.0F, -75.0F);
              {
                aol_typ_keypad *_lSubContext = &(pContext->__keypad__);
                aol_keypad_S_ArrayLevelIndex(_lSubContext, _lArray0_keypad);
                aol_keypad_S_ButtonPressed(_lSubContext, aol_DMI_G_isPressed(pContext));
                aol_keypad_S_keytype(_lSubContext, 1L);
                _lSubContext->_parentPriority = 0L;
                aol_keypad_draw(_lSubContext, pPriority);
                kcg_assign(aol_DMI_G_keyarray(pContext), aol_keypad_G_keyarray(_lSubContext), sizeof(SGLbool [12UL]));
              }
              sglPopMatrixAndTranslate();
            }

            /* Object: closebutton, Type: referenceContainer, OID: 143c80d0-d2d5-4b65-98fd-f82a3d702c72 */
            {
              sglSetActiveMasks(SGL_NO_MASK);
              sglPushMatrixAndTranslate(16.0F, -226.0F);
              {
                aol_typ_closebutton *_lSubContext = &(pContext->__closebutton__);
                aol_closebutton_S_ModeSymbol(_lSubContext, aol_DMI_G_closeButtonIndex(pContext));
                aol_closebutton_S_isPressed(_lSubContext, SGL_FALSE);
                _lSubContext->_parentPriority = 0L;
                aol_closebutton_draw(_lSubContext, pPriority);
                aol_DMI_G_closeButton(pContext) = aol_closebutton_G_onButton(_lSubContext);
              }
              sglPopMatrixAndTranslate();
            }
            sglPopMatrixAndTranslate();
          }
        }

        /* Object: trainRN, Type: container, OID: 7cf3a8b5-39c3-4c5f-8cfa-e63b3bec7650 */
        {
          if ((aol_DMI_G_window_mask(pContext))[1]) {

            /* Object: backgroundMenu_1, Type: rectangle, OID: 4d724b64-91b6-46fc-96b7-69c665e6cc0d */
            {
              /* filled object part */
              sglIndexColori(6L);
              sglDisable(SGL_MODULATE);
              sglEnable(SGL_POLYGON_SMOOTH);
              sglTransparency8(255L);
              sglDisable(SGL_TEXTURE_2D);
              sglDisable(SGL_TESSELLATION);
              sglBegin(SGL_POLYGON);
              sglVertex2f(14.0F, 240.0F);
              sglVertex2f(320.0F, 240.0F);
              sglVertex2f(320.0F, -240.0F);
              sglVertex2f(14.0F, -240.0F);
              sglEnd();
            }

            /* Object: trainRN_display, Type: referenceContainer, OID: 37686c57-462a-42a5-ab84-215ab6abf725 */
            {
              static SGLint32 _lArray0_trainRN_display[9UL] = {0L};
              sglPushMatrixAndTranslate(169.0F, 126.0F);
              {
                aol_typ_driverid_display *_lSubContext = &(pContext->__trainRN_display__);
                aol_driverid_display_S_Ack_area(_lSubContext, 2L);
                aol_driverid_display_S_ButtonPressed(_lSubContext, aol_DMI_G_isPressed(pContext));
                aol_driverid_display_S_DriverID_Display(_lSubContext, _lArray0_trainRN_display);
                aol_driverid_display_S_LevelIndex(_lSubContext, 0L);
                aol_driverid_display_S_TrainRN_Display(_lSubContext, aol_DMI_G_TrainRN_Display(pContext));
                aol_driverid_display_S_text_digit(_lSubContext, 2L);
                aol_driverid_display_S_titlewindow(_lSubContext, 2L);
                _lSubContext->_parentPriority = 0L;
                aol_driverid_display_draw(_lSubContext, pPriority);
                aol_DMI_G_InputFieldAck(pContext) = aol_driverid_display_G_InputFieldAck(_lSubContext);
              }
              sglPopMatrixAndTranslate();
            }

            /* Object: keypad_1, Type: referenceContainer, OID: 6e18a90d-b734-455a-ad5a-ecb98bed2052 */
            {
              static SGLint32 _lArray0_keypad_1[12UL] = {0L};
              sglSetActiveMasks(SGL_NO_MASK);
              sglPushMatrixAndTranslate(167.0F, -75.0F);
              {
                aol_typ_keypad *_lSubContext = &(pContext->__keypad_1__);
                aol_keypad_S_ArrayLevelIndex(_lSubContext, _lArray0_keypad_1);
                aol_keypad_S_ButtonPressed(_lSubContext, aol_DMI_G_isPressed(pContext));
                aol_keypad_S_keytype(_lSubContext, 2L);
                _lSubContext->_parentPriority = 0L;
                aol_keypad_draw(_lSubContext, pPriority);
                kcg_assign(aol_DMI_G_keyarray(pContext), aol_keypad_G_keyarray(_lSubContext), sizeof(SGLbool [12UL]));
              }
              sglPopMatrixAndTranslate();
            }

            /* Object: closebutton_1, Type: referenceContainer, OID: 5c4f6488-305b-4afb-83a5-bd1fa515e60e */
            {
              sglSetActiveMasks(SGL_NO_MASK);
              sglPushMatrixAndTranslate(14.0F, -226.0F);
              {
                aol_typ_closebutton *_lSubContext = &(pContext->__closebutton_1__);
                aol_closebutton_S_ModeSymbol(_lSubContext, aol_DMI_G_closeButtonIndex(pContext));
                aol_closebutton_S_isPressed(_lSubContext, SGL_FALSE);
                _lSubContext->_parentPriority = 0L;
                aol_closebutton_draw(_lSubContext, pPriority);
                aol_DMI_G_closeButton(pContext) = aol_closebutton_G_onButton(_lSubContext);
              }
              sglPopMatrixAndTranslate();
            }
          }
        }

        /* Object: mainmenu, Type: container, OID: b5e7001d-820b-4917-82d6-929613e63d50 */
        {
          sglPushMatrixAndTranslate(-1.0F, 0.0F);

          /* Object: mainmenu_1, Type: referenceContainer, OID: f264f277-a568-4787-80ba-ff2b246ce435 */
          {
            static SGLint32 _lArray0_mainmenu_1[30UL] = {2L,2L,2L,2L,2L,2L,2L,2L,2L,2L,2L,2L,2L,2L};
            if (SGLbool_or(SGLbool_and((aol_DMI_G_window_mask(pContext))[9], SGLbool_not((aol_DMI_G_window_mask(pContext))[10])), aol_DMI_G_hourGlassVisibility(pContext))) {
              sglPushMatrixAndTranslate(167.0F, 0.0F);
              {
                aol_typ_mainmenu *_lSubContext = &(pContext->__mainmenu_1__);
                aol_mainmenu_S_MousePressed(_lSubContext, aol_DMI_G_isPressed(pContext));
                if (aol_DMI_G_hourGlassVisibility(pContext)) {
                  aol_mainmenu_S_TitleVisibility(_lSubContext, SGL_FALSE);
                  aol_mainmenu_S_buttonEnabler(_lSubContext, _lArray0_mainmenu_1);
                }
                else {
                  aol_mainmenu_S_TitleVisibility(_lSubContext, SGL_TRUE);
                  aol_mainmenu_S_buttonEnabler(_lSubContext, aol_DMI_G_buttonEnabler(pContext));
                }
                aol_mainmenu_S_closeButtonEnabler(_lSubContext, aol_DMI_G_closeButtonEnabler(pContext));
                _lSubContext->_parentPriority = 0L;
                aol_mainmenu_draw(_lSubContext, pPriority);
                aol_DMI_G_startRequest(pContext) = aol_mainmenu_G_StartRequest(_lSubContext);
                aol_DMI_G_closeMainMenu(pContext) = aol_mainmenu_G_closeMainmenu(_lSubContext);
                aol_DMI_G_openLevelMenu(pContext) = aol_mainmenu_G_levelMenu(_lSubContext);
                aol_DMI_G_openDriverID(pContext) = aol_mainmenu_G_openDriverID(_lSubContext);
                aol_DMI_G_openNonLeading(pContext) = aol_mainmenu_G_openNonLeading(_lSubContext);
                aol_DMI_G_openShunting(pContext) = aol_mainmenu_G_openShunting(_lSubContext);
                aol_DMI_G_openTrainData(pContext) = aol_mainmenu_G_openTrainData(_lSubContext);
                aol_DMI_G_openTrainRN(pContext) = aol_mainmenu_G_openTrainRN(_lSubContext);
              }
              sglPopMatrixAndTranslate();
            }
          }

          /* Object: translate_group, Type: functionalTranslate, OID: a18fdf98-f706-47c6-8a20-feb52aff538d */
          {
            if (aol_DMI_G_hourGlassVisibility(pContext)) {
              sglPushMatrixAndTranslate(SGLfloat_add(67.0F, SGLfloat_add(50.005F, SGLfloat_mul(aol_DMI_G_translateHourGlass(pContext), -2.9F))), 0.0F);

              /* Object: StatusSymbols, Type: referenceContainer, OID: 08c4b31b-428a-4fd3-ba26-957aa84b49f3 */
              {
                sglPushMatrixAndTranslate(-4.0F, 213.0F);
                {
                  aol_typ_StatusSymbols _lSubContextVar;
                  aol_typ_StatusSymbols *_lSubContext = &_lSubContextVar;
                  aol_StatusSymbols_init(_lSubContext);
                  aol_StatusSymbols_S_StatusSymbol(_lSubContext, 5L);
                  _lSubContext->_parentPriority = 0L;
                  aol_StatusSymbols_draw(_lSubContext, pPriority);
                }
                sglPopMatrixAndTranslate();
              }
              sglPopMatrixAndTranslate();
            }
          }
          sglPopMatrixAndTranslate();
        }

        /* Object: TrainData, Type: container, OID: c207b452-a418-4564-8654-8d4a36e2946c */
        {
          if (aol_DMI_G_TrainDataWindowVisibility(pContext)) {
            sglPushMatrixAndTranslate(0.0F, -1.0F);

            /* Object: TrainData_1, Type: referenceContainer, OID: eee4ac32-1c8f-4a52-a3a0-86e28f1d1d10 */
            {
              if (aol_DMI_G_TrainDataWindowVisibility(pContext)) {
                {
                  aol_typ_TrainData *_lSubContext = &(pContext->__TrainData_1__);
                  _lSubContext->_parentPriority = 0L;
                  aol_TrainData_draw(_lSubContext, pPriority);
                  aol_DMI_G_closeButton(pContext) = aol_TrainData_G_closeTrainDataWindow(_lSubContext);
                  aol_DMI_G_confirmTrainData(pContext) = aol_TrainData_G_confirmTrainData(_lSubContext);
                }
              }
            }
            sglPopMatrixAndTranslate();
          }
        }

        /* Object: traindataValidation, Type: container, OID: c8bd1545-0042-440a-82b3-fe7672366151 */
        {
          if (aol_DMI_G_traindataValidWinVisibility(pContext)) {
            sglPushMatrixAndTranslate(0.0F, -1.0F);

            /* Object: ValidationWindow, Type: referenceContainer, OID: 5d371136-5e63-4cae-a719-72b505badd8e */
            {
              if (aol_DMI_G_traindataValidWinVisibility(pContext)) {
                {
                  aol_typ_ValidationWindow *_lSubContext = &(pContext->__ValidationWindow__);
                  aol_ValidationWindow_S_indexTrainCategory(_lSubContext, aol_DMI_G_indexTrainCategory(pContext));
                  aol_ValidationWindow_S_trainAirtightIndex(_lSubContext, aol_DMI_G_trainAirtightIndex(pContext));
                  aol_ValidationWindow_S_trainAxleLoad(_lSubContext, aol_DMI_G_trainAxleLoad(pContext));
                  aol_ValidationWindow_S_trainBrakePerc(_lSubContext, aol_DMI_G_trainBrakePerc(pContext));
                  aol_ValidationWindow_S_trainLenght(_lSubContext, aol_DMI_G_trainLenght(pContext));
                  aol_ValidationWindow_S_trainLoadingGaugeIndex(_lSubContext, aol_DMI_G_trainLoadingGaugeIndex(pContext));
                  aol_ValidationWindow_S_trainMaxSpeed(_lSubContext, aol_DMI_G_trainMaxSpeed(pContext));
                  aol_ValidationWindow_S_traindataYesNoIndex(_lSubContext, aol_DMI_G_traindataYesNoIndex(pContext));
                  _lSubContext->_parentPriority = 0L;
                  aol_ValidationWindow_draw(_lSubContext, pPriority);
                  aol_DMI_G_closeButton(pContext) = aol_ValidationWindow_G_closeTrainDataValidationWindow(_lSubContext);
                  aol_DMI_G_traindataAck(pContext) = aol_ValidationWindow_G_traindataAck(_lSubContext);
                  aol_DMI_G_traindataNoAck(pContext) = aol_ValidationWindow_G_traindataNoAck(_lSubContext);
                  aol_DMI_G_traindataYesAck(pContext) = aol_ValidationWindow_G_traindataYesAck(_lSubContext);
                }
              }
            }
            sglPopMatrixAndTranslate();
          }
        }

        /* Object: Level, Type: container, OID: ea621905-4f91-437d-be5f-383939a0d89e */
        {
          if (aol_DMI_G_levelMenuVisibility(pContext)) {
            sglPushMatrixAndTranslate(-1.0F, 0.0F);

            /* Object: backgroundMenu_2, Type: rectangle, OID: 76a88b09-5af0-4fb8-aef7-5f76d210eb09 */
            {
              /* filled object part */
              sglIndexColori(6L);
              sglDisable(SGL_MODULATE);
              sglEnable(SGL_POLYGON_SMOOTH);
              sglTransparency8(255L);
              sglDisable(SGL_TEXTURE_2D);
              sglDisable(SGL_TESSELLATION);
              sglBegin(SGL_POLYGON);
              sglVertex2f(14.0F, 240.0F);
              sglVertex2f(320.0F, 240.0F);
              sglVertex2f(320.0F, -240.0F);
              sglVertex2f(14.0F, -240.0F);
              sglEnd();
            }

            /* Object: level_display, Type: referenceContainer, OID: f7fea089-8c32-4189-9f1f-179f6824fe45 */
            {
              static SGLint32 _lArray0_level_display[9UL] = {0L};
              sglPushMatrixAndTranslate(169.0F, 126.0F);
              {
                aol_typ_driverid_display *_lSubContext = &(pContext->__level_display__);
                aol_driverid_display_S_Ack_area(_lSubContext, 1L);
                aol_driverid_display_S_ButtonPressed(_lSubContext, aol_DMI_G_isPressed(pContext));
                aol_driverid_display_S_DriverID_Display(_lSubContext, _lArray0_level_display);
                aol_driverid_display_S_LevelIndex(_lSubContext, aol_DMI_G_LevelIndex(pContext));
                aol_driverid_display_S_TrainRN_Display(_lSubContext, _lArray0_level_display);
                aol_driverid_display_S_text_digit(_lSubContext, 3L);
                aol_driverid_display_S_titlewindow(_lSubContext, 3L);
                _lSubContext->_parentPriority = 0L;
                aol_driverid_display_draw(_lSubContext, pPriority);
                aol_DMI_G_InputFieldAck(pContext) = aol_driverid_display_G_InputFieldAck(_lSubContext);
              }
              sglPopMatrixAndTranslate();
            }

            /* Object: keypad_2, Type: referenceContainer, OID: a8ad62e5-3ea6-46b6-b2b4-936cae87d71e */
            {
              sglSetActiveMasks(SGL_NO_MASK);
              sglPushMatrixAndTranslate(169.0F, -75.0F);
              {
                aol_typ_keypad *_lSubContext = &(pContext->__keypad_2__);
                aol_keypad_S_ArrayLevelIndex(_lSubContext, aol_DMI_G_ArrayLevelIndex(pContext));
                aol_keypad_S_ButtonPressed(_lSubContext, aol_DMI_G_isPressed(pContext));
                aol_keypad_S_keytype(_lSubContext, 3L);
                _lSubContext->_parentPriority = 0L;
                aol_keypad_draw(_lSubContext, pPriority);
                kcg_assign(aol_DMI_G_keyarray(pContext), aol_keypad_G_keyarray(_lSubContext), sizeof(SGLbool [12UL]));
              }
              sglPopMatrixAndTranslate();
            }

            /* Object: closebutton_2, Type: referenceContainer, OID: a90653f3-5511-4364-9613-3844afd7f196 */
            {
              sglSetActiveMasks(SGL_NO_MASK);
              sglPushMatrixAndTranslate(14.0F, -226.0F);
              {
                aol_typ_closebutton *_lSubContext = &(pContext->__closebutton_2__);
                aol_closebutton_S_ModeSymbol(_lSubContext, aol_DMI_G_closeButtonIndex(pContext));
                aol_closebutton_S_isPressed(_lSubContext, SGL_FALSE);
                _lSubContext->_parentPriority = 0L;
                aol_closebutton_draw(_lSubContext, pPriority);
                aol_DMI_G_closeButton(pContext) = aol_closebutton_G_onButton(_lSubContext);
              }
              sglPopMatrixAndTranslate();
            }
            sglPopMatrixAndTranslate();
          }
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: closeDeskBackground, Type: rectangle, OID: 0dffff0b-e08e-478e-8c06-f5cafb76f8da */
      {
        if (SGLbool_not(aol_DMI_G_openDesk(pContext))) {
          /* filled object part */
          sglIndexColori(2L);
          sglDisable(SGL_MODULATE);
          sglDisable(SGL_POLYGON_SMOOTH);
          sglTransparency8(255L);
          sglDisable(SGL_TEXTURE_2D);
          sglDisable(SGL_TESSELLATION);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-320.0F, 240.0F);
          sglVertex2f(320.0F, 240.0F);
          sglVertex2f(320.0F, -240.0F);
          sglVertex2f(-320.0F, -240.0F);
          sglEnd();
        }
      }

      /* Object: MouseReleased, Type: pointerEvent, OID: d70337e7-31b9-404b-8c25-3496e168ef55 */
      {
        aol_pointer(0L, SGL_NULL, &(aol_DMI_G_MousePressed(pContext)), SGL_NULL, SGL_NULL, SGL_NULL, SGL_NULL);
      }

      /* Object: MousePressed, Type: pointerEvent, OID: b266a919-a2d9-4298-9af4-cba6fd57f664 */
      {
        aol_pointer(0L, &(aol_DMI_G_ButtonPressed(pContext)), SGL_NULL, SGL_NULL, SGL_NULL, SGL_NULL, SGL_NULL);
      }

      /* Object: ButtonBehaviour, Type: behavior, OID: 4cf8a627-6401-4c49-8c19-3f375b37ad7f */
      {
        inC_aol_ButtonBehaviour_behavior _lInContextVar;
        inC_aol_ButtonBehaviour_behavior *_lInContext = &_lInContextVar;
        outC_aol_ButtonBehaviour_behavior *_lOutContext = &(pContext->__ButtonBehaviour__);
        _lInContext->pressed = aol_DMI_G_ButtonPressed(pContext);
        _lInContext->released = aol_DMI_G_MousePressed(pContext);
        aol_ButtonBehaviour_behavior(_lInContext, _lOutContext);
        aol_DMI_G_isPressed(pContext) = _lOutContext->isPressed;
      }
      sglPopMatrixAndTranslate();
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:25
 *********************************************************/

