/*********************************************************
 **
 ** File  aol_CircularSpeedGauge.h
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\CircularSpeedGauge\CircularSpeedGauge.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_CIRCULARSPEEDGAUGE_H
#define _AOL_CIRCULARSPEEDGAUGE_H

#include "sgl_types.h"


/* Accessors */
#define aol_CircularSpeedGauge_G_Vperm(_C_) (_C_)->Vperm
#define aol_CircularSpeedGauge_S_Vperm(_C_,_V_) (_C_)->Vperm = (_V_)
#define aol_CircularSpeedGauge_G_Vtarget(_C_) (_C_)->Vtarget
#define aol_CircularSpeedGauge_S_Vtarget(_C_,_V_) (_C_)->Vtarget = (_V_)
#define aol_CircularSpeedGauge_G_Vrelease(_C_) (_C_)->Vrelease
#define aol_CircularSpeedGauge_S_Vrelease(_C_,_V_) (_C_)->Vrelease = (_V_)
#define aol_CircularSpeedGauge_G_VpermVisible(_C_) (_C_)->VpermVisible
#define aol_CircularSpeedGauge_S_VpermVisible(_C_,_V_) (_C_)->VpermVisible = (_V_)
#define aol_CircularSpeedGauge_G_VtargetVisible(_C_) (_C_)->VtargetVisible
#define aol_CircularSpeedGauge_S_VtargetVisible(_C_,_V_) (_C_)->VtargetVisible = (_V_)
#define aol_CircularSpeedGauge_G_VreleaseVisible(_C_) (_C_)->VreleaseVisible
#define aol_CircularSpeedGauge_S_VreleaseVisible(_C_,_V_) (_C_)->VreleaseVisible = (_V_)
#define aol_CircularSpeedGauge_G_VpermColor(_C_) (_C_)->VpermColor
#define aol_CircularSpeedGauge_S_VpermColor(_C_,_V_) (_C_)->VpermColor = (_V_)
#define aol_CircularSpeedGauge_G_VtargetColor(_C_) (_C_)->VtargetColor
#define aol_CircularSpeedGauge_S_VtargetColor(_C_,_V_) (_C_)->VtargetColor = (_V_)
#define aol_CircularSpeedGauge_G_VreleaseColor(_C_) (_C_)->VreleaseColor
#define aol_CircularSpeedGauge_S_VreleaseColor(_C_,_V_) (_C_)->VreleaseColor = (_V_)
#define aol_CircularSpeedGauge_G_Vtarget_permVisible(_C_) (_C_)->Vtarget_permVisible
#define aol_CircularSpeedGauge_S_Vtarget_permVisible(_C_,_V_) (_C_)->Vtarget_permVisible = (_V_)
#define aol_CircularSpeedGauge_G_Vtarget_permColor(_C_) (_C_)->Vtarget_permColor
#define aol_CircularSpeedGauge_S_Vtarget_permColor(_C_,_V_) (_C_)->Vtarget_permColor = (_V_)
#define aol_CircularSpeedGauge_G_Vinterv(_C_) (_C_)->Vinterv
#define aol_CircularSpeedGauge_S_Vinterv(_C_,_V_) (_C_)->Vinterv = (_V_)
#define aol_CircularSpeedGauge_G_VintervColor(_C_) (_C_)->VintervColor
#define aol_CircularSpeedGauge_S_VintervColor(_C_,_V_) (_C_)->VintervColor = (_V_)
#define aol_CircularSpeedGauge_G_VintervVisible(_C_) (_C_)->VintervVisible
#define aol_CircularSpeedGauge_S_VintervVisible(_C_,_V_) (_C_)->VintervVisible = (_V_)
#define aol_CircularSpeedGauge_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct aol_typ_CircularSpeedGauge_ {
  /* ------------------------- inputs --------------------------- */
  SGLfloat Vperm;
  SGLfloat Vtarget;
  SGLfloat Vrelease;
  SGLbool VpermVisible;
  SGLbool VtargetVisible;
  SGLbool VreleaseVisible;
  SGLint32 VpermColor;
  SGLint32 VtargetColor;
  SGLint32 VreleaseColor;
  SGLbool Vtarget_permVisible;
  SGLint32 Vtarget_permColor;
  SGLfloat Vinterv;
  SGLint32 VintervColor;
  SGLbool VintervVisible;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} aol_typ_CircularSpeedGauge;

/* Associated functions */
extern void aol_CircularSpeedGauge_init(aol_typ_CircularSpeedGauge *pContext);
extern void aol_CircularSpeedGauge_predraw(aol_typ_CircularSpeedGauge *pContext);
extern void aol_CircularSpeedGauge_draw(aol_typ_CircularSpeedGauge *pContext, SGLint32 pPriority);

#endif /* _AOL_CIRCULARSPEEDGAUGE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

