/*********************************************************
 **
 ** File  aol_SPDI.c
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\SPDI\SPDI.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#include "aol_SPDI.h"
#include "aol_imported_functions.h"
#include "sgl.h"


void aol_SPDI_init(aol_typ_SPDI *pContext)
{
  aol_SPDI_S_SPDI_SpeedChangeVisible(pContext, SGL_FALSE);
  aol_SPDI_S_SPDI_SpeedChange(pContext, 0L);
  aol_SPDI_S_SPDI_speedChangePosition(pContext, 0.0F);

  pContext->_parentPriority = 0L;

}

void aol_SPDI_predraw(aol_typ_SPDI *pContext)
{

}

void aol_SPDI_draw(aol_typ_SPDI *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: SpeedChangeSymbol, Type: conditional, OID: dcf679dd-71b6-4618-b5d7-e990eab8e589 */
    {
      if (aol_SPDI_G_SPDI_SpeedChangeVisible(pContext)) {
        sglPushMatrixAndTranslate(0.0F, aol_SPDI_G_SPDI_speedChangePosition(pContext));
        switch (aol_SPDI_G_SPDI_SpeedChange(pContext)) {

        case 1L:

          /* Object: SpeedInc, Type: container, OID: 1a247828-faee-4b3e-96cb-9f3c6b8dca53 */
          {

            /* Object: line, Type: line, OID: d5da9c25-d7bc-4167-9730-48f3b20ec534 */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexColori(3L);
              sglIndexHaloColori(-1L);
              sglIndexLineWidthi(0L);
              sglIndexLineStipplei(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINES);
              sglVertex2f(2.0F, 0.0F);
              sglVertex2f(19.0F, 0.0F);
              sglEnd();
            }

            /* Object: shape, Type: shape, OID: 41ad2341-44c9-4ae6-b48c-888839b2593e */
            {
              /* filled object part */
              sglDisable(SGL_MODULATE);
              sglDisable(SGL_POLYGON_SMOOTH);
              sglDisable(SGL_TESSELLATION);
              sglBegin(SGL_POLYGON);
              sglVertex2f(10.0F, 2.5F);
              sglVertex2f(18.0F, 2.5F);
              sglVertex2f(14.0F, 13.5F);
              sglEnd();
            }
          }
          break;

        case 3L:

          /* Object: SpeedDecZero, Type: container, OID: 57faf27e-b5e2-4346-b4bb-383f7157cb88 */
          {

            /* Object: line_2, Type: line, OID: 731eaa6e-2ea3-4898-9588-90854ff5710d */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexColori(3L);
              sglIndexHaloColori(-1L);
              sglIndexLineWidthi(0L);
              sglIndexLineStipplei(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINES);
              sglVertex2f(2.0F, 0.0F);
              sglVertex2f(19.0F, 0.0F);
              sglEnd();
            }

            /* Object: group, Type: container, OID: 66d8667c-6628-46ea-b1d1-7c010e53c289 */
            {
              sglPushMatrix();
              sglTranslatef(2.062F, -13.25F);
              sglScalef(0.6F, 0.6F);

              /* Object: bi_font, Type: bifont, OID: 08392606-c130-4b81-b242-f05699c9fa17 */
              {
                sglIndexFontLineWidthi(2L);
                sglIndexFonti(0L);
                sglSetTextAlignment(SGL_ALIGN_LEFT, SGL_ALIGN_BOTTOM);
                sglSetSecondFontAttributes(3L, 0L, 0L);
                {
                  sgl_numeric_format _lFormat;
                  _lFormat.l_integralPart = 1L;
                  _lFormat.l_fractionalPart = 0L;
                  _lFormat.l_secondFontPos = 0L;
                  _lFormat.b_separator = 46U;
                  _lFormat.b_leadingZeros = SGL_FALSE;
                  _lFormat.l_displaySign = SGL_SIGN_NEVER;
                  sgluWriteFloat(2.0F, 4.0F, 0.0F, &_lFormat);
                }
              }
              sglPopMatrix();
            }

            /* Object: shape_2, Type: shape, OID: 86590434-787c-45f9-bd72-a6fb70702f93 */
            {
              /* filled object part */
              sglDisable(SGL_MODULATE);
              sglDisable(SGL_POLYGON_SMOOTH);
              sglDisable(SGL_TESSELLATION);
              sglBegin(SGL_POLYGON);
              sglVertex2f(10.0F, -2.5F);
              sglVertex2f(18.0F, -2.5F);
              sglVertex2f(14.0F, -12.5F);
              sglEnd();
            }
          }
          break;

        default:
        /* case 2L */

          /* Object: SpeedDec, Type: container, OID: 8f69cfc7-a015-4768-93e0-82c68f598e39 */
          {

            /* Object: line_1, Type: line, OID: 0fdf4a87-9234-48e8-a77e-6158e10e3383 */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexColori(3L);
              sglIndexHaloColori(-1L);
              sglIndexLineWidthi(0L);
              sglIndexLineStipplei(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINES);
              sglVertex2f(2.0F, 0.0F);
              sglVertex2f(19.0F, 0.0F);
              sglEnd();
            }

            /* Object: shape_1, Type: shape, OID: ced1a39b-b349-44ab-8cf4-458f683dd476 */
            {
              /* filled object part */
              sglDisable(SGL_MODULATE);
              sglDisable(SGL_POLYGON_SMOOTH);
              sglDisable(SGL_TESSELLATION);
              sglBegin(SGL_POLYGON);
              sglVertex2f(10.0F, -2.5F);
              sglVertex2f(18.0F, -2.5F);
              sglVertex2f(14.0F, -12.5F);
              sglEnd();
            }
          }
          break;
        }
        sglPopMatrixAndTranslate();
      }
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

