/*********************************************************
 **
 ** File  aol_F.c
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\F\F.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:24
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#include "aol_F.h"
#include "aol_imported_functions.h"
#include "sgl.h"


void aol_F_init(aol_typ_F *pContext)
{
  aol_F_S_ButtonPressed(pContext, SGL_FALSE);
  aol_F_S_onMainButton(pContext, SGL_FALSE);

  pContext->_parentPriority = 0L;

}

void aol_F_predraw(aol_typ_F *pContext)
{

}

void aol_F_draw(aol_typ_F *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: F, Type: container, OID: 803c8b28-4cf4-4f7c-887c-93d940d88de8 */
    {
      sglPushMatrixAndTranslate(1.0F, 0.0F);

      /* Object: F1, Type: container, OID: e3a79733-2f24-4bcc-b795-778d509c930f */
      {
        sglPushMatrixAndTranslate(0.5F, 0.0F);

        /* Object: F1_1, Type: rectangle, OID: eebc19c5-a195-48a7-a54c-b8e4c1642319 */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglDisable(SGL_MODULATE);
          sglEnable(SGL_POLYGON_SMOOTH);
          sglTransparency8(255L);
          sglDisable(SGL_TEXTURE_2D);
          sglDisable(SGL_TESSELLATION);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-30.0F, 225.0F);
          sglVertex2f(30.0F, 225.0F);
          sglVertex2f(30.0F, 175.0F);
          sglVertex2f(-30.0F, 175.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglIndexHaloColori(-1L);
          sglIndexLineWidthi(0L);
          sglIndexLineStipplei(0L);
          sglDisable(SGL_LINE_HALOING);
          sglSetLineCaps(SGL_ROUNDED_CAPS);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-30.0F, 225.0F);
          sglVertex2f(30.0F, 225.0F);
          sglVertex2f(30.0F, 175.0F);
          sglVertex2f(-30.0F, 175.0F);
          sglEnd();
        }

        /* Object: TL_outerLine, Type: line, OID: a00b44ab-b687-4ae0-b706-ff66532fdcd8 */
        {
          /* outlined object part */
          sglIndexColori(2L);
          sglBegin(SGL_LINE_STRIP);
          sglVertex2f(-30.0F, 175.0F);
          sglVertex2f(-30.0F, 225.0F);
          sglVertex2f(30.0F, 225.0F);
          sglEnd();
        }

        /* Object: TL_innerLine, Type: line, OID: 314771bd-ae14-4dcc-a338-ff558c9ccf58 */
        {
          if (SGLbool_not(SGLbool_and(aol_F_G_ButtonPressed(pContext), aol_F_G_onMainButton(pContext)))) {
            /* outlined object part */
            sglIndexColori(7L);
            sglBegin(SGL_LINE_STRIP);
            sglVertex2f(-29.0F, 176.0F);
            sglVertex2f(-29.0F, 224.0F);
            sglVertex2f(29.0F, 224.0F);
            sglEnd();
          }
        }

        /* Object: BR_innerLine, Type: line, OID: a847e592-a29c-4d0f-8180-6490acfd198b */
        {
          if (SGLbool_not(SGLbool_and(aol_F_G_ButtonPressed(pContext), aol_F_G_onMainButton(pContext)))) {
            /* outlined object part */
            sglIndexColori(2L);
            sglBegin(SGL_LINE_STRIP);
            sglVertex2f(-29.0F, 176.0F);
            sglVertex2f(29.0F, 176.0F);
            sglVertex2f(29.0F, 224.0F);
            sglEnd();
          }
        }

        /* Object: BR_outerLine, Type: line, OID: 9a15c6f7-19e5-4c64-998a-477e2daf7d1b */
        {
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_STRIP);
          sglVertex2f(-30.0F, 175.0F);
          sglVertex2f(30.0F, 175.0F);
          sglVertex2f(30.0F, 225.0F);
          sglEnd();
        }

        /* Object: rectangle_area, Type: rectangleArea, OID: 80d0e475-1e89-483c-8b7b-d8c61648ac6b */
        {
          SGLfloat _lX = 0.0F;
          SGLfloat _lY = 0.0F;
          aol_locate(-1L, &_lX, &_lY);
          aol_F_G_onMainButton(pContext) = sglRectangleActiveAreaGetStatus(_lX, _lY, -30.0F, 225.0F, 30.0F, 175.0F);
        }

        /* Object: text, Type: text, OID: faf7ce73-db85-4bfe-a73b-928b4027dad1 */
        {
          static SGLuint8 _lArray0_text[255UL] = {77U,97U,105U,110U};
          sglIndexColori(1L);
          sglIndexFontLineWidthi(2L);
          sglIndexFonti(5L);
          sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
          sgluWriteText(0.0F, 200.0F, _lArray0_text, 255L);
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: F2, Type: container, OID: 32224ed0-fffb-4052-84a3-0c6ad29e195f */
      {
        sglPushMatrixAndTranslate(0.5F, 0.0F);

        /* Object: F2_1, Type: rectangle, OID: 54edd58e-e659-4bbd-b412-5604d5cf7d65 */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-30.0F, 175.0F);
          sglVertex2f(30.0F, 175.0F);
          sglVertex2f(30.0F, 125.0F);
          sglVertex2f(-30.0F, 125.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-30.0F, 175.0F);
          sglVertex2f(30.0F, 175.0F);
          sglVertex2f(30.0F, 125.0F);
          sglVertex2f(-30.0F, 125.0F);
          sglEnd();
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: F3, Type: container, OID: 9f4cc585-9f25-4e94-8a3c-f2eca8be4e51 */
      {
        sglPushMatrixAndTranslate(0.5F, 0.0F);

        /* Object: F3_1, Type: rectangle, OID: 911663a8-a47c-491a-b29b-28247ab24bbe */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-30.0F, 125.0F);
          sglVertex2f(30.0F, 125.0F);
          sglVertex2f(30.0F, 75.0F);
          sglVertex2f(-30.0F, 75.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-30.0F, 125.0F);
          sglVertex2f(30.0F, 125.0F);
          sglVertex2f(30.0F, 75.0F);
          sglVertex2f(-30.0F, 75.0F);
          sglEnd();
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: F4, Type: container, OID: 2fb66534-4663-470d-b1c2-316aa1b90bc7 */
      {
        sglPushMatrixAndTranslate(0.5F, 0.0F);

        /* Object: F4_1, Type: rectangle, OID: 195b8dca-482f-4170-8320-b8e56abce20c */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-30.0F, 75.0F);
          sglVertex2f(30.0F, 75.0F);
          sglVertex2f(30.0F, 25.0F);
          sglVertex2f(-30.0F, 25.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-30.0F, 75.0F);
          sglVertex2f(30.0F, 75.0F);
          sglVertex2f(30.0F, 25.0F);
          sglVertex2f(-30.0F, 25.0F);
          sglEnd();
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: F5, Type: container, OID: 2cb757e7-2b74-491b-b486-dee29c5519dd */
      {
        sglPushMatrixAndTranslate(0.5F, 0.0F);

        /* Object: F5_1, Type: rectangle, OID: 652650ad-2015-496b-aae2-f9dcfa073d49 */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-30.0F, 25.0F);
          sglVertex2f(30.0F, 25.0F);
          sglVertex2f(30.0F, -25.0F);
          sglVertex2f(-30.0F, -25.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-30.0F, 25.0F);
          sglVertex2f(30.0F, 25.0F);
          sglVertex2f(30.0F, -25.0F);
          sglVertex2f(-30.0F, -25.0F);
          sglEnd();
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: F6, Type: container, OID: 8c261ac2-0768-4aac-a3d6-8cc79149eac5 */
      {
        sglPushMatrixAndTranslate(0.5F, 0.0F);

        /* Object: F6_1, Type: rectangle, OID: 9928e192-1970-4625-bddd-adc721ebacae */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-30.0F, -25.0F);
          sglVertex2f(30.0F, -25.0F);
          sglVertex2f(30.0F, -75.0F);
          sglVertex2f(-30.0F, -75.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-30.0F, -25.0F);
          sglVertex2f(30.0F, -25.0F);
          sglVertex2f(30.0F, -75.0F);
          sglVertex2f(-30.0F, -75.0F);
          sglEnd();
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: F7, Type: container, OID: acc4e52b-e316-4a14-9799-823b8eb3f8d5 */
      {
        sglPushMatrixAndTranslate(0.5F, 0.0F);

        /* Object: F7_1, Type: rectangle, OID: 936a611d-c800-4643-913f-d9012d1dc7af */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-30.0F, -75.0F);
          sglVertex2f(30.0F, -75.0F);
          sglVertex2f(30.0F, -125.0F);
          sglVertex2f(-30.0F, -125.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-30.0F, -75.0F);
          sglVertex2f(30.0F, -75.0F);
          sglVertex2f(30.0F, -125.0F);
          sglVertex2f(-30.0F, -125.0F);
          sglEnd();
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: F8, Type: container, OID: c54543bd-5196-4386-a83e-01eeb2dde783 */
      {
        sglPushMatrixAndTranslate(0.5F, 0.0F);

        /* Object: F8_1, Type: rectangle, OID: 98aba41d-3479-439a-a132-710e5009b09f */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-30.0F, -125.0F);
          sglVertex2f(30.0F, -125.0F);
          sglVertex2f(30.0F, -175.0F);
          sglVertex2f(-30.0F, -175.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-30.0F, -125.0F);
          sglVertex2f(30.0F, -125.0F);
          sglVertex2f(30.0F, -175.0F);
          sglVertex2f(-30.0F, -175.0F);
          sglEnd();
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: F9, Type: container, OID: 30497e0a-bd39-4c31-ba16-6e165d88ce24 */
      {
        sglPushMatrixAndTranslate(0.5F, 0.0F);

        /* Object: F9_1, Type: rectangle, OID: e342b716-7d34-4d9b-8b2d-08981234e11d */
        {
          /* filled object part */
          sglIndexColori(6L);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-30.0F, -175.0F);
          sglVertex2f(30.0F, -175.0F);
          sglVertex2f(30.0F, -225.0F);
          sglVertex2f(-30.0F, -225.0F);
          sglEnd();
          /* outlined object part */
          sglIndexColori(7L);
          sglBegin(SGL_LINE_LOOP);
          sglVertex2f(-30.0F, -175.0F);
          sglVertex2f(30.0F, -175.0F);
          sglVertex2f(30.0F, -225.0F);
          sglVertex2f(-30.0F, -225.0F);
          sglEnd();
        }
        sglPopMatrixAndTranslate();
      }
      sglPopMatrixAndTranslate();
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:24
 *********************************************************/

