/*********************************************************
 **
 ** File  aol_NavigationSymbols.c
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\Symbols\NavigationSymbols.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#include "aol_NavigationSymbols.h"
#include "aol_imported_functions.h"
#include "sgl.h"


void aol_NavigationSymbols_init(aol_typ_NavigationSymbols *pContext)
{
  aol_NavigationSymbols_S_ModeSymbol(pContext, 0L);

  pContext->_parentPriority = 0L;

}

void aol_NavigationSymbols_predraw(aol_typ_NavigationSymbols *pContext)
{

}

void aol_NavigationSymbols_draw(aol_typ_NavigationSymbols *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: conditional_group, Type: conditional, OID: 90a2dd53-0dc6-416a-8223-506203c1d1df */
    {
      sglPushMatrix();
      sglScalef(0.9F, 0.9F);
      switch (aol_NavigationSymbols_G_ModeSymbol(pContext)) {

      case 1L:

        /* Object: NA01, Type: container, OID: 85336733-3ea6-4277-a1fd-a6574c5968ac */
        {

          /* Object: HidePlanningInformation, Type: container, OID: c9e2b64f-d213-4480-989b-3d4d44d2eb78 */
          {
            sglPushMatrixAndTranslate(-3.0F, 0.0F);

            /* Object: rectangle, Type: rectangle, OID: 1b7ecf16-1346-47ae-a7bf-73eb056da97f */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexColori(3L);
              sglIndexHaloColori(-1L);
              sglIndexLineWidthi(1L);
              sglIndexLineStipplei(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINE_LOOP);
              sglVertex2f(-5.0F, 5.0F);
              sglVertex2f(5.0F, 5.0F);
              sglVertex2f(5.0F, -5.0F);
              sglVertex2f(-5.0F, -5.0F);
              sglEnd();
            }
            sglPopMatrixAndTranslate();
          }
        }
        break;

      case 2L:

        /* Object: NA02, Type: container, OID: b093fd02-4f96-4253-af0c-c753e3cd8aef */
        {

          /* Object: rectangle_1, Type: rectangle, OID: 5218d9e8-a73a-42a8-ba36-8d05d8d23893 */
          {
            /* outlined object part */
            sglDisable(SGL_TEXTURE_2D);
            sglIndexColori(3L);
            sglIndexHaloColori(-1L);
            sglIndexLineWidthi(2L);
            sglIndexLineStipplei(0L);
            sglDisable(SGL_LINE_HALOING);
            sglSetLineCaps(SGL_ROUNDED_CAPS);
            sglTransparency8(255L);
            sglBegin(SGL_LINE_LOOP);
            sglVertex2f(-15.0F, 15.0F);
            sglVertex2f(15.0F, 15.0F);
            sglVertex2f(15.0F, -15.0F);
            sglVertex2f(-15.0F, -15.0F);
            sglEnd();
          }
        }
        break;

      case 3L:

        /* Object: NA03, Type: container, OID: e4f6d3ea-f33d-4feb-b424-8cdddf67d0d1 */
        {

          /* Object: ScaleUp, Type: container, OID: f8b34d94-cdfb-4ce8-b09a-6f8247aff3bb */
          {

            /* Object: line, Type: line, OID: 1db4afef-9aa2-4a21-95ef-cf1ee5463a11 */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexColori(3L);
              sglIndexHaloColori(-1L);
              sglIndexLineWidthi(1L);
              sglIndexLineStipplei(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINES);
              sglVertex2f(0.0F, 5.0F);
              sglVertex2f(0.0F, -5.0F);
            }

            /* Object: line_1, Type: line, OID: e0babb3d-3df8-48a8-81fb-ebd2ff03bb5f */
            {
              /* outlined object part */
              sglVertex2f(-5.0F, 0.0F);
              sglVertex2f(5.0F, 0.0F);
              sglEnd();
            }
          }
        }
        break;

      case 4L:

        /* Object: NA04, Type: container, OID: cfb64e97-a9c9-4231-83c7-091109b24f7a */
        {

          /* Object: ScaleDown, Type: container, OID: c818ba8f-53f5-47f7-9adc-6f2951e6fcfa */
          {

            /* Object: line_2, Type: line, OID: 98b8b82d-dcc1-46d3-973d-62eb8139ee64 */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexColori(3L);
              sglIndexHaloColori(-1L);
              sglIndexLineWidthi(1L);
              sglIndexLineStipplei(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINES);
              sglVertex2f(-5.0F, 0.0F);
              sglVertex2f(5.0F, 0.0F);
              sglEnd();
            }
          }
        }
        break;

      case 23L:

        /* Object: NA05, Type: container, OID: ac58b747-454f-4a1c-a567-afeb14134cdd */
        {

          /* Object: ScaleUp_1, Type: container, OID: d6729330-6660-4426-955b-4c31c861ee70 */
          {

            /* Object: line_3, Type: line, OID: ee3e341d-4f4c-4a36-82a0-e14d5a226b30 */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexColori(5L);
              sglIndexHaloColori(-1L);
              sglIndexLineWidthi(1L);
              sglIndexLineStipplei(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINES);
              sglVertex2f(0.0F, 5.0F);
              sglVertex2f(0.0F, -5.0F);
            }

            /* Object: line_4, Type: line, OID: 97d43c95-a1ef-4f7a-987b-08e113806cb1 */
            {
              /* outlined object part */
              sglVertex2f(-5.0F, 0.0F);
              sglVertex2f(5.0F, 0.0F);
              sglEnd();
            }
          }
        }
        break;

      case 24L:

        /* Object: NA06, Type: container, OID: c678d46f-11db-4282-8825-3429261201fb */
        {

          /* Object: ScaleDown_1, Type: container, OID: 72df54ed-5bf4-4788-9890-ea78f13e5eb5 */
          {

            /* Object: line_5, Type: line, OID: 24146c5e-d80f-4e9c-a243-1fbd15e0315e */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexColori(5L);
              sglIndexHaloColori(-1L);
              sglIndexLineWidthi(1L);
              sglIndexLineStipplei(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINES);
              sglVertex2f(-5.0F, 0.0F);
              sglVertex2f(5.0F, 0.0F);
              sglEnd();
            }
          }
        }
        break;

      case 25L:

        /* Object: NA11, Type: container, OID: 2b4d115d-fb94-4c7c-b40f-b8aea29e2281 */
        {

          /* Object: X, Type: container, OID: f0537792-abf0-4d03-9e1e-056b3f106873 */
          {

            /* Object: line_6, Type: line, OID: de2892c7-7fe7-4dfc-a63c-087d4fc6e37b */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexColori(3L);
              sglIndexHaloColori(-1L);
              sglIndexLineWidthi(1L);
              sglIndexLineStipplei(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINES);
              sglVertex2f(-10.0F, 10.0F);
              sglVertex2f(10.0F, -10.0F);
            }

            /* Object: line_7, Type: line, OID: f6a22348-7391-4b10-ba02-6f5d1c8d9826 */
            {
              /* outlined object part */
              sglVertex2f(10.0F, 10.0F);
              sglVertex2f(-10.0F, -10.0F);
              sglEnd();
            }
          }
        }
        break;

      case 26L:

        /* Object: NA12, Type: container, OID: a5b9edd8-2dcb-4512-909b-16e68c6a3ed8 */
        {

          /* Object: X_1, Type: container, OID: 9636afb3-8972-4311-a01e-e63a6b324b09 */
          {

            /* Object: line_8, Type: line, OID: e4238fd1-aec2-4913-9293-1df5b675765a */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexColori(5L);
              sglIndexHaloColori(-1L);
              sglIndexLineWidthi(1L);
              sglIndexLineStipplei(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINES);
              sglVertex2f(-10.0F, 10.0F);
              sglVertex2f(10.0F, -10.0F);
            }

            /* Object: line_9, Type: line, OID: e96f7f03-ff3e-41d1-a43e-8a8fe76d5642 */
            {
              /* outlined object part */
              sglVertex2f(10.0F, 10.0F);
              sglVertex2f(-10.0F, -10.0F);
              sglEnd();
            }
          }
        }
        break;

      default:
        /* Do nothing */
        break;
      }
      sglPopMatrix();
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

