/*********************************************************
 **
 ** File  aol_scroll_button.h
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\scroll_button.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_SCROLL_BUTTON_H
#define _AOL_SCROLL_BUTTON_H

#include "sgl_types.h"


/* Accessors */
#define aol_scroll_button_G_buttonType(_C_) (_C_)->buttonType
#define aol_scroll_button_S_buttonType(_C_,_V_) (_C_)->buttonType = (_V_)
#define aol_scroll_button_G_UpenableType(_C_) (_C_)->UpenableType
#define aol_scroll_button_S_UpenableType(_C_,_V_) (_C_)->UpenableType = (_V_)
#define aol_scroll_button_G_buttonClicked(_C_) (_C_)->buttonClicked
#define aol_scroll_button_S_buttonClicked(_C_,_V_) (_C_)->buttonClicked = (_V_)
#define aol_scroll_button_G_DownenableType(_C_) (_C_)->DownenableType
#define aol_scroll_button_S_DownenableType(_C_,_V_) (_C_)->DownenableType = (_V_)
#define aol_scroll_button_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct aol_typ_scroll_button_ {
  /* ------------------------- inputs --------------------------- */
  SGLint32 buttonType;
  SGLint32 UpenableType;
  SGLbool buttonClicked;
  SGLint32 DownenableType;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} aol_typ_scroll_button;

/* Associated functions */
extern void aol_scroll_button_init(aol_typ_scroll_button *pContext);
extern void aol_scroll_button_predraw(aol_typ_scroll_button *pContext);
extern void aol_scroll_button_draw(aol_typ_scroll_button *pContext, SGLint32 pPriority);

#endif /* _AOL_SCROLL_BUTTON_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

