/*********************************************************
 **
 ** File  aol_QuestionBox.h
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\QuestionBox\QuestionBox.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_QUESTIONBOX_H
#define _AOL_QUESTIONBOX_H

#include "sgl_types.h"


/* Accessors */
#define aol_QuestionBox_G_DriverRequest(_C_) (_C_)->DriverRequest
#define aol_QuestionBox_S_DriverRequest(_C_,_V_) (_C_)->DriverRequest = (_V_)
#define aol_QuestionBox_G_ShowQuestionBox(_C_) (_C_)->ShowQuestionBox
#define aol_QuestionBox_S_ShowQuestionBox(_C_,_V_) (_C_)->ShowQuestionBox = (_V_)
#define aol_QuestionBox_G_YesPressed(_C_) (_C_)->YesPressed
#define aol_QuestionBox_S_YesPressed(_C_,_V_) (_C_)->YesPressed = (_V_)
#define aol_QuestionBox_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct aol_typ_QuestionBox_ {
  /* ------------------------- inputs --------------------------- */
  SGLint32 DriverRequest;
  SGLbool ShowQuestionBox;
  /* ------------------------- outputs -------------------------- */
  SGLbool YesPressed;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} aol_typ_QuestionBox;

/* Associated functions */
extern void aol_QuestionBox_init(aol_typ_QuestionBox *pContext);
extern void aol_QuestionBox_predraw(aol_typ_QuestionBox *pContext);
extern void aol_QuestionBox_draw(aol_typ_QuestionBox *pContext, SGLint32 pPriority);

#endif /* _AOL_QUESTIONBOX_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

