/*********************************************************
 **
 ** File  aol_yesButton.h
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\TrainData\yesButton.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:24
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_YESBUTTON_H
#define _AOL_YESBUTTON_H

#include "sgl_types.h"


/* Accessors */
#define aol_yesButton_G_confirmData(_C_) (_C_)->confirmData
#define aol_yesButton_S_confirmData(_C_,_V_) (_C_)->confirmData = (_V_)
#define aol_yesButton_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct aol_typ_yesButton_ {
  /* ------------------------- outputs -------------------------- */
  SGLbool confirmData;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} aol_typ_yesButton;

/* Associated functions */
extern void aol_yesButton_init(aol_typ_yesButton *pContext);
extern void aol_yesButton_predraw(aol_typ_yesButton *pContext);
extern void aol_yesButton_draw(aol_typ_yesButton *pContext, SGLint32 pPriority);

#endif /* _AOL_YESBUTTON_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:24
 *********************************************************/

