/*********************************************************
 **
 ** File  aol_NavigationSymbols.h
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\Symbols\NavigationSymbols.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_NAVIGATIONSYMBOLS_H
#define _AOL_NAVIGATIONSYMBOLS_H

#include "sgl_types.h"


/* Accessors */
#define aol_NavigationSymbols_G_ModeSymbol(_C_) (_C_)->ModeSymbol
#define aol_NavigationSymbols_S_ModeSymbol(_C_,_V_) (_C_)->ModeSymbol = (_V_)
#define aol_NavigationSymbols_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct aol_typ_NavigationSymbols_ {
  /* ------------------------- inputs --------------------------- */
  SGLint32 ModeSymbol;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} aol_typ_NavigationSymbols;

/* Associated functions */
extern void aol_NavigationSymbols_init(aol_typ_NavigationSymbols *pContext);
extern void aol_NavigationSymbols_predraw(aol_typ_NavigationSymbols *pContext);
extern void aol_NavigationSymbols_draw(aol_typ_NavigationSymbols *pContext, SGLint32 pPriority);

#endif /* _AOL_NAVIGATIONSYMBOLS_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

