/*********************************************************
 **
 ** File  aol_Gradient.h
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\Gradient\Gradient.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_GRADIENT_H
#define _AOL_GRADIENT_H

#include "sgl_types.h"


/* Accessors */
#define aol_Gradient_G_GradientValue(_C_) (_C_)->GradientValue
#define aol_Gradient_S_GradientValue(_C_,_V_) (_C_)->GradientValue = (_V_)
#define aol_Gradient_G_GradientVisible(_C_) (_C_)->GradientVisible
#define aol_Gradient_S_GradientVisible(_C_,_V_) (_C_)->GradientVisible = (_V_)
#define aol_Gradient_G_GradientStart(_C_) (_C_)->GradientStart
#define aol_Gradient_S_GradientStart(_C_,_V_) (_C_)->GradientStart = (_V_)
#define aol_Gradient_G_GradientEnd(_C_) (_C_)->GradientEnd
#define aol_Gradient_S_GradientEnd(_C_,_V_) (_C_)->GradientEnd = (_V_)
#define aol_Gradient_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct aol_typ_Gradient_ {
  /* ------------------------- inputs --------------------------- */
  SGLfloat GradientValue;
  SGLbool GradientVisible;
  SGLfloat GradientStart;
  SGLfloat GradientEnd;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} aol_typ_Gradient;

/* Associated functions */
extern void aol_Gradient_init(aol_typ_Gradient *pContext);
extern void aol_Gradient_predraw(aol_typ_Gradient *pContext);
extern void aol_Gradient_draw(aol_typ_Gradient *pContext, SGLint32 pPriority);

#endif /* _AOL_GRADIENT_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

