/*********************************************************
 **
 ** File  aol_Y.c
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\Y\Y.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:24
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#include "aol_Y.h"
#include "aol_imported_functions.h"
#include "sgl.h"


void aol_Y_init(aol_typ_Y *pContext)
{

  pContext->_parentPriority = 0L;

}

void aol_Y_predraw(aol_typ_Y *pContext)
{

}

void aol_Y_draw(aol_typ_Y *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: Y, Type: container, OID: fec415ad-702c-4111-a5a2-2a9c66cbfee5 */
    {
      sglPushMatrixAndTranslate(0.0F, 0.5F);

      /* Object: Y_1, Type: rectangle, OID: a55a6918-7069-4a95-a2c2-d274ef16f771 */
      {
        /* filled object part */
        sglIndexColori(6L);
        sglDisable(SGL_MODULATE);
        sglEnable(SGL_POLYGON_SMOOTH);
        sglTransparency8(255L);
        sglDisable(SGL_TEXTURE_2D);
        sglDisable(SGL_TESSELLATION);
        sglBegin(SGL_POLYGON);
        sglVertex2f(-320.0F, 7.5F);
        sglVertex2f(320.0F, 7.5F);
        sglVertex2f(320.0F, -7.5F);
        sglVertex2f(-320.0F, -7.5F);
        sglEnd();
        /* outlined object part */
        sglIndexColori(7L);
        sglIndexHaloColori(-1L);
        sglIndexLineWidthi(0L);
        sglIndexLineStipplei(0L);
        sglDisable(SGL_LINE_HALOING);
        sglSetLineCaps(SGL_ROUNDED_CAPS);
        sglBegin(SGL_LINE_LOOP);
        sglVertex2f(-320.0F, 7.5F);
        sglVertex2f(320.0F, 7.5F);
        sglVertex2f(320.0F, -7.5F);
        sglVertex2f(-320.0F, -7.5F);
        sglEnd();
      }
      sglPopMatrixAndTranslate();
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:24
 *********************************************************/

