/*********************************************************
 **
 ** File  aol_kcg_user_macros.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:25
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_KCG_USER_MACROS_H
#define _AOL_KCG_USER_MACROS_H

#include "sgl_types.h"

#ifndef ASSERT_SIZE
#define ASSERT_SIZE(x,y) typedef char x ## _assert_size_t[-1+10*(sizeof(x) == (y))]
#endif

#ifndef kcg_bool
#define kcg_bool SGLbool
#endif

#ifndef kcg_char
#define kcg_char SGLuint8
#endif

#ifndef kcg_int
#define kcg_int SGLint32
#else
/* just making sure, the existing definition is equally sized */
ASSERT_SIZE(kcg_int, 4);
#endif

#ifndef kcg_real
#define kcg_real SGLfloat
#endif

#include "./user_macros.h"

#endif /* _AOL_KCG_USER_MACROS_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:25
 *********************************************************/
