/*********************************************************
 **
 ** File  aol_ModeSymbols.h
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\Symbols\ModeSymbols.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_MODESYMBOLS_H
#define _AOL_MODESYMBOLS_H

#include "sgl_types.h"


/* Accessors */
#define aol_ModeSymbols_G_ModeSymbol(_C_) (_C_)->ModeSymbol
#define aol_ModeSymbols_S_ModeSymbol(_C_,_V_) (_C_)->ModeSymbol = (_V_)
#define aol_ModeSymbols_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct aol_typ_ModeSymbols_ {
  /* ------------------------- inputs --------------------------- */
  SGLint32 ModeSymbol;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} aol_typ_ModeSymbols;

/* Associated functions */
extern void aol_ModeSymbols_init(aol_typ_ModeSymbols *pContext);
extern void aol_ModeSymbols_predraw(aol_typ_ModeSymbols *pContext);
extern void aol_ModeSymbols_draw(aol_typ_ModeSymbols *pContext, SGLint32 pPriority);

#endif /* _AOL_MODESYMBOLS_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

