/*********************************************************
 **
 ** File  aol_ValidationWindow.h
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\ValidationWindow\ValidationWindow.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:25
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_VALIDATIONWINDOW_H
#define _AOL_VALIDATIONWINDOW_H

#include "sgl_types.h"

#include "aol_closebutton.h"

/* Accessors */
#define aol_ValidationWindow_G_trainLenght(_C_) (_C_)->trainLenght
#define aol_ValidationWindow_S_trainLenght(_C_,_V_) (_C_)->trainLenght = (_V_)
#define aol_ValidationWindow_G_trainBrakePerc(_C_) (_C_)->trainBrakePerc
#define aol_ValidationWindow_S_trainBrakePerc(_C_,_V_) (_C_)->trainBrakePerc = (_V_)
#define aol_ValidationWindow_G_trainMaxSpeed(_C_) (_C_)->trainMaxSpeed
#define aol_ValidationWindow_S_trainMaxSpeed(_C_,_V_) (_C_)->trainMaxSpeed = (_V_)
#define aol_ValidationWindow_G_indexTrainCategory(_C_) (_C_)->indexTrainCategory
#define aol_ValidationWindow_S_indexTrainCategory(_C_,_V_) (_C_)->indexTrainCategory = (_V_)
#define aol_ValidationWindow_G_trainAirtightIndex(_C_) (_C_)->trainAirtightIndex
#define aol_ValidationWindow_S_trainAirtightIndex(_C_,_V_) (_C_)->trainAirtightIndex = (_V_)
#define aol_ValidationWindow_G_trainLoadingGaugeIndex(_C_) (_C_)->trainLoadingGaugeIndex
#define aol_ValidationWindow_S_trainLoadingGaugeIndex(_C_,_V_) (_C_)->trainLoadingGaugeIndex = (_V_)
#define aol_ValidationWindow_G_traindataYesNoIndex(_C_) (_C_)->traindataYesNoIndex
#define aol_ValidationWindow_S_traindataYesNoIndex(_C_,_V_) (_C_)->traindataYesNoIndex = (_V_)
#define aol_ValidationWindow_G_trainAxleLoad(_C_) (_C_)->trainAxleLoad
#define aol_ValidationWindow_S_trainAxleLoad(_C_,_V_) (_C_)->trainAxleLoad = (_V_)
#define aol_ValidationWindow_G_closeTrainDataValidationWindow(_C_) (_C_)->closeTrainDataValidationWindow
#define aol_ValidationWindow_S_closeTrainDataValidationWindow(_C_,_V_) (_C_)->closeTrainDataValidationWindow = (_V_)
#define aol_ValidationWindow_G_traindataAck(_C_) (_C_)->traindataAck
#define aol_ValidationWindow_S_traindataAck(_C_,_V_) (_C_)->traindataAck = (_V_)
#define aol_ValidationWindow_G_traindataYesAck(_C_) (_C_)->traindataYesAck
#define aol_ValidationWindow_S_traindataYesAck(_C_,_V_) (_C_)->traindataYesAck = (_V_)
#define aol_ValidationWindow_G_traindataNoAck(_C_) (_C_)->traindataNoAck
#define aol_ValidationWindow_S_traindataNoAck(_C_,_V_) (_C_)->traindataNoAck = (_V_)
#define aol_ValidationWindow_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct aol_typ_ValidationWindow_ {
  /* ------------------------- inputs --------------------------- */
  SGLfloat trainLenght;
  SGLfloat trainBrakePerc;
  SGLfloat trainMaxSpeed;
  SGLint32 indexTrainCategory;
  SGLint32 trainAirtightIndex;
  SGLint32 trainLoadingGaugeIndex;
  SGLint32 traindataYesNoIndex;
  SGLint32 trainAxleLoad;
  /* ------------------------- outputs -------------------------- */
  SGLbool closeTrainDataValidationWindow;
  SGLbool traindataAck;
  SGLbool traindataYesAck;
  SGLbool traindataNoAck;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
  /* ------------------------- subcontexts ---------------------- */
  aol_typ_closebutton __closebutton__;
} aol_typ_ValidationWindow;

/* Associated functions */
extern void aol_ValidationWindow_init(aol_typ_ValidationWindow *pContext);
extern void aol_ValidationWindow_predraw(aol_typ_ValidationWindow *pContext);
extern void aol_ValidationWindow_draw(aol_typ_ValidationWindow *pContext, SGLint32 pPriority);

#endif /* _AOL_VALIDATIONWINDOW_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:25
 *********************************************************/

