/*********************************************************
 **
 ** File  aol_A.h
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\A\A.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:23
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_A_H
#define _AOL_A_H

#include "sgl_types.h"

#include "aol_DistanceToTargetBar.h"

/* Accessors */
#define aol_A_G_DistanceToTarget(_C_) (_C_)->DistanceToTarget
#define aol_A_S_DistanceToTarget(_C_,_V_) (_C_)->DistanceToTarget = (_V_)
#define aol_A_G_DistanceToTargetVisiblityDigital(_C_) (_C_)->DistanceToTargetVisiblityDigital
#define aol_A_S_DistanceToTargetVisiblityDigital(_C_,_V_) (_C_)->DistanceToTargetVisiblityDigital = (_V_)
#define aol_A_G_InterpolatedDistanceToTarget(_C_) (_C_)->InterpolatedDistanceToTarget
#define aol_A_S_InterpolatedDistanceToTarget(_C_,_V_) (_C_)->InterpolatedDistanceToTarget = (_V_)
#define aol_A_G_DistToTargetBarVisibility(_C_) (_C_)->DistToTargetBarVisibility
#define aol_A_S_DistToTargetBarVisibility(_C_,_V_) (_C_)->DistToTargetBarVisibility = (_V_)
#define aol_A_G_OverA(_C_) (_C_)->OverA
#define aol_A_S_OverA(_C_,_V_) (_C_)->OverA = (_V_)
#define aol_A_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct aol_typ_A_ {
  /* ------------------------- inputs --------------------------- */
  SGLfloat DistanceToTarget;
  SGLbool DistanceToTargetVisiblityDigital;
  SGLfloat InterpolatedDistanceToTarget;
  SGLbool DistToTargetBarVisibility;
  /* ------------------------- outputs -------------------------- */
  SGLbool OverA;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} aol_typ_A;

/* Associated functions */
extern void aol_A_init(aol_typ_A *pContext);
extern void aol_A_predraw(aol_typ_A *pContext);
extern void aol_A_draw(aol_typ_A *pContext, SGLint32 pPriority);

#endif /* _AOL_A_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:23
 *********************************************************/

