/*********************************************************
 **
 ** File  aol_Z.c
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\Z\Z.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:24
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#include "aol_Z.h"
#include "aol_imported_functions.h"
#include "sgl.h"


void aol_Z_init(aol_typ_Z *pContext)
{

  pContext->_parentPriority = 0L;

}

void aol_Z_predraw(aol_typ_Z *pContext)
{

}

void aol_Z_draw(aol_typ_Z *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: Z, Type: container, OID: c947f15d-f368-4c13-969e-ebece6264025 */
    {

      /* Object: Z_1, Type: rectangle, OID: 980fb4b4-422a-4243-83ef-94efdddbb3b6 */
      {
        /* filled object part */
        sglIndexColori(6L);
        sglDisable(SGL_MODULATE);
        sglEnable(SGL_POLYGON_SMOOTH);
        sglTransparency8(255L);
        sglDisable(SGL_TEXTURE_2D);
        sglDisable(SGL_TESSELLATION);
        sglBegin(SGL_POLYGON);
        sglVertex2f(-320.0F, 7.0F);
        sglVertex2f(320.0F, 7.0F);
        sglVertex2f(320.0F, -7.0F);
        sglVertex2f(-320.0F, -7.0F);
        sglEnd();
      }
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:24
 *********************************************************/

