/*********************************************************
 **
 ** File  aol_G.h
 **
 ** Specification File:  P:\modeling\model\Scade\System\DMI_Control\SCADE Display\Widgets\G\G.ogfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3 (build i10)
 **
 ** Date of generation: 2017-05-30T13:27:24
 ** Command line: ScadeDisplayKCG.exe -outdir P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI_Code P:\modeling\model\Scade\System\DMI_Control\SCADE Display\DMI.sgfx
 *********************************************************/

#ifndef _AOL_G_H
#define _AOL_G_H

#include "sgl_types.h"
#include "kcg_assign.h"


/* Accessors */
#define aol_G_G_localTimeArray(_C_) (*(_C_)->localTimeArray)
#define aol_G_S_localTimeArray(_C_,_V_) (_C_)->localTimeArray = &(_V_)
#define aol_G_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct aol_typ_G_ {
  /* ------------------------- inputs --------------------------- */
  SGLfloat (*localTimeArray)[4UL];
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} aol_typ_G;

/* Associated functions */
extern void aol_G_init(aol_typ_G *pContext);
extern void aol_G_predraw(aol_typ_G *pContext);
extern void aol_G_draw(aol_typ_G *pContext, SGLint32 pPriority);

#endif /* _AOL_G_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-05-30T13:27:24
 *********************************************************/

