/* Generated by SCADE Display */

/* ============================================================================
   (C) 2017 ESTEREL TECHNOLOGIES SAS.  ALL RIGHTS RESERVED
    This source file may be used and distributed without restriction provided
    that this copyright statement is not removed from the file and that any
    derivative work contains this copyright notice.
   Warranty
   ESTEREL TECHNOLOGIES SAS makes no warranty of any kind with regard to the
   use of this Software, either expressed or implied, including, but not
   limited to the fitness for a particular purpose.
 =========================================================================== */

#include "target_configuration.h"

SGLulong target_screen_width = 640UL;
SGLulong target_screen_height = 480UL;
const SGLfloat ratio_x = 1.0F;
const SGLfloat ratio_y = 1.0F;

