/* Generated by SCADE Display */

/* ============================================================================
   (C) 2017 ESTEREL TECHNOLOGIES SAS.  ALL RIGHTS RESERVED
    This source file may be used and distributed without restriction provided
    that this copyright statement is not removed from the file and that any
    derivative work contains this copyright notice.
   Warranty
   ESTEREL TECHNOLOGIES SAS makes no warranty of any kind with regard to the
   use of this Software, either expressed or implied, including, but not
   limited to the fitness for a particular purpose.
 =========================================================================== */
#ifndef __TARGET_CONFIGURATION_H__
#define __TARGET_CONFIGURATION_H__

#include "sgl_types.h"

extern SGLulong target_screen_width;
extern SGLulong target_screen_height;
extern const SGLfloat ratio_x;
extern const SGLfloat ratio_y;

#define MAX_POINTERS 1
#define MAX_KEYBOARDS 1

#endif

