#ifndef USER_MACROS_H
#define USER_MACROS_H
/*generated by SCADE Code Generator*/
#include "libraries/libmathext/macro_libmathext.h"
#ifndef kcg_assume
#define kcg_assume(x)
#endif

#ifndef kcg_guarantee
#define kcg_guarantee(x)
#endif

#endif /*USER_MACROS_H*/
