/*********************************************************
 **
 ** File  SDY1_DMI_DMI_interface.h
 **
 ** Specification File:  C:\Users\Valerio\Desktop\DMI Funzionante\2014-09-02 RailDriverMachineInterface\RailDriverMachineInterface\SCADE Display\DMI.sgfx
 **
 ** Automatically generated by SCADE Display CG Simu
 ** Version 6.5.1 i28
 **
 ** Date of generation: 2015-01-20T14:34:54
 ** Command line: ScadeDisplayCGSimu.exe -interface -outdir C:\Users\Valerio\Desktop\DMI Funzionante\2014-09-02 RailDriverMachineInterface\RailDriverMachineInterface\Test\Simulation\SDY1_DMI\Code -prefix SDY1_DMI_ C:\Users\Valerio\Desktop\DMI Funzionante\2014-09-02 RailDriverMachineInterface\RailDriverMachineInterface\SCADE Display\DMI.sgfx C:\Program Files (x86)\Esterel Technologies\SCADE R15.1\SCADE Display\config\Workspace\environments\OpenGL\texture_table.stt C:\Users\Valerio\Desktop\DMI Funzionante\2014-09-02 RailDriverMachineInterface\RailDriverMachineInterface\SCADE Display\DMI.sct C:\Program Files (x86)\Esterel Technologies\SCADE R15.1\SCADE Display\config\Workspace\environments\OpenGL\line_width_table.swt C:\Program Files (x86)\Esterel Technologies\SCADE R15.1\SCADE Display\config\Workspace\environments\OpenGL\line_stipple_table.sst
 *********************************************************/

#ifndef _SDY1_DMI_DMI_INTERFACE_H
#define _SDY1_DMI_DMI_INTERFACE_H

#ifdef DLL_EXPORTS
#define DLL_API __declspec(dllexport)
#else /* DLL_EXPORTS */
#define DLL_API
#endif /* DLL_EXPORTS */

/* Set context function */
extern DLL_API void SDY1_DMI_C_DMI(void *pContext);

/* Input functions */
extern DLL_API void SDY1_DMI_I_DMI__TrainPosition(SGLfloat pValue);
extern DLL_API void SDY1_DMI_I_DMI__GradientsStart(SGLfloat (*pValue)[12]);
extern DLL_API void SDY1_DMI_I_DMI__GradientsEnd(SGLfloat (*pValue)[12]);
extern DLL_API void SDY1_DMI_I_DMI__GradientsValue(SGLfloat (*pValue)[12]);
extern DLL_API void SDY1_DMI_I_DMI__DistanceToTarget(SGLfloat pValue);
extern DLL_API void SDY1_DMI_I_DMI__DistanceToTargetVisible(SGLbool pValue);
extern DLL_API void SDY1_DMI_I_DMI__TrainSpeed(SGLfloat pValue);
extern DLL_API void SDY1_DMI_I_DMI__PointerColor(SGLlong pValue);
extern DLL_API void SDY1_DMI_I_DMI__SpeedDigitOne(SGLfloat pValue);
extern DLL_API void SDY1_DMI_I_DMI__SpeedDigitTwo(SGLfloat pValue);
extern DLL_API void SDY1_DMI_I_DMI__SpeedDigitThree(SGLfloat pValue);
extern DLL_API void SDY1_DMI_I_DMI__Vperm(SGLfloat pValue);
extern DLL_API void SDY1_DMI_I_DMI__Vtarget(SGLfloat pValue);
extern DLL_API void SDY1_DMI_I_DMI__Vrelease(SGLfloat pValue);
extern DLL_API void SDY1_DMI_I_DMI__VpermColor(SGLlong pValue);
extern DLL_API void SDY1_DMI_I_DMI__VtargetColor(SGLlong pValue);
extern DLL_API void SDY1_DMI_I_DMI__VreleaseColor(SGLlong pValue);
extern DLL_API void SDY1_DMI_I_DMI__ModeSymbol(SGLlong pValue);
extern DLL_API void SDY1_DMI_I_DMI__LevelSymbol(SGLlong pValue);
extern DLL_API void SDY1_DMI_I_DMI__StatusSymbolBrake(SGLbool pValue);
extern DLL_API void SDY1_DMI_I_DMI__LevelSymbolAnncouncement(SGLlong pValue);
extern DLL_API void SDY1_DMI_I_DMI__InterpolatedDistanceToTarget(SGLfloat pValue);
extern DLL_API void SDY1_DMI_I_DMI__showlala(SGLbool pValue);
extern DLL_API void SDY1_DMI_I_DMI__display_digit0(SGLlong (*pValue)[1]);
extern DLL_API void SDY1_DMI_I_DMI__display_digit1(SGLlong (*pValue)[1]);
extern DLL_API void SDY1_DMI_I_DMI__display_digit2(SGLlong (*pValue)[1]);
extern DLL_API void SDY1_DMI_I_DMI__display_digit3(SGLlong (*pValue)[1]);
extern DLL_API void SDY1_DMI_I_DMI__display_digit4(SGLlong (*pValue)[1]);

/* Output functions */
extern DLL_API void SDY1_DMI_O_DMI__OverA(SGLbool (*pVar));
extern DLL_API void SDY1_DMI_O_DMI__OverC2(SGLbool (*pVar));
extern DLL_API void SDY1_DMI_O_DMI__OverC3(SGLbool (*pVar));
extern DLL_API void SDY1_DMI_O_DMI__OverC4(SGLbool (*pVar));
extern DLL_API void SDY1_DMI_O_DMI__MousePressed(SGLbool (*pVar));
extern DLL_API void SDY1_DMI_O_DMI__VisibleGradients(SGLbool (*pVar)[12]);
extern DLL_API void SDY1_DMI_O_DMI__lala(SGLbool (*pVar));
extern DLL_API void SDY1_DMI_O_DMI__insideButton(SGLbool (*pVar));
extern DLL_API void SDY1_DMI_O_DMI__keyarray(SGLbool (*pVar)[12]);

#undef DLL_API

#endif /* _SDY1_DMI_DMI_INTERFACE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2015-01-20T14:34:54
 *********************************************************/

