#ifndef _ROOT_INTEGRATION_MACRO_H_
#define _ROOT_INTEGRATION_MACRO_H_


/*$************** SCADE Macro wrapper *********************
** Begin of file ROOT_Integration_macro.h
***********************************************************$*/


/*$**********************************************************
*                        INCLUDES
***********************************************************$*/

/* includes */
#include "ROOT_Integration_Testbench_Integration.h"

/*$**********************************************************
*                           CONTEXT
***********************************************************$*/

/* global_root_context option => no context definition is needed */
#define WU_CTX_TYPE_ROOT_Integration void

/*$**********************************************************
*                           SENSORS
***********************************************************$*/

#define DECLARE_SENSORS_ROOT_Integration() 

#define DECLARE_EXT_SENSORS_ROOT_Integration(MODE) 

/*$**********************************************************
*                           INPUTS
***********************************************************$*/

#define VARC_ROOT_Integration_GUI_reset(context) GUI_reset  /* Testbench_Integration::ROOT_Integration/GUI_reset */
#define VAR_ROOT_Integration_GUI_reset VARC_ROOT_Integration_GUI_reset(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_GUI_targetSpeed(context) GUI_targetSpeed  /* Testbench_Integration::ROOT_Integration/GUI_targetSpeed */
#define VAR_ROOT_Integration_GUI_targetSpeed VARC_ROOT_Integration_GUI_targetSpeed(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_GUI_traction(context) GUI_traction  /* Testbench_Integration::ROOT_Integration/GUI_traction */
#define VAR_ROOT_Integration_GUI_traction VARC_ROOT_Integration_GUI_traction(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_GUI_brake(context) GUI_brake  /* Testbench_Integration::ROOT_Integration/GUI_brake */
#define VAR_ROOT_Integration_GUI_brake VARC_ROOT_Integration_GUI_brake(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_GUI_initialPosition(context) GUI_initialPosition  /* Testbench_Integration::ROOT_Integration/GUI_initialPosition */
#define VAR_ROOT_Integration_GUI_initialPosition VARC_ROOT_Integration_GUI_initialPosition(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_GUI_initialVelocity(context) GUI_initialVelocity  /* Testbench_Integration::ROOT_Integration/GUI_initialVelocity */
#define VAR_ROOT_Integration_GUI_initialVelocity VARC_ROOT_Integration_GUI_initialVelocity(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_GUI_mode(context) GUI_mode  /* Testbench_Integration::ROOT_Integration/GUI_mode */
#define VAR_ROOT_Integration_GUI_mode VARC_ROOT_Integration_GUI_mode(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_GUI_level(context) GUI_level  /* Testbench_Integration::ROOT_Integration/GUI_level */
#define VAR_ROOT_Integration_GUI_level VARC_ROOT_Integration_GUI_level(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_GUI_mobileHWStatus(context) GUI_mobileHWStatus  /* Testbench_Integration::ROOT_Integration/GUI_mobileHWStatus */
#define VAR_ROOT_Integration_GUI_mobileHWStatus VARC_ROOT_Integration_GUI_mobileHWStatus(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_GUI_openDesk(context) GUI_openDesk  /* Testbench_Integration::ROOT_Integration/GUI_openDesk */
#define VAR_ROOT_Integration_GUI_openDesk VARC_ROOT_Integration_GUI_openDesk(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_MousePressed(context) DMI_MousePressed  /* Testbench_Integration::ROOT_Integration/DMI_MousePressed */
#define VAR_ROOT_Integration_DMI_MousePressed VARC_ROOT_Integration_DMI_MousePressed(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_startRequest(context) DMI_startRequest  /* Testbench_Integration::ROOT_Integration/DMI_startRequest */
#define VAR_ROOT_Integration_DMI_startRequest VARC_ROOT_Integration_DMI_startRequest(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_openTrainRN(context) DMI_openTrainRN  /* Testbench_Integration::ROOT_Integration/DMI_openTrainRN */
#define VAR_ROOT_Integration_DMI_openTrainRN VARC_ROOT_Integration_DMI_openTrainRN(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_traindataYesAck(context) DMI_traindataYesAck  /* Testbench_Integration::ROOT_Integration/DMI_traindataYesAck */
#define VAR_ROOT_Integration_DMI_traindataYesAck VARC_ROOT_Integration_DMI_traindataYesAck(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_TrainRN_Ack(context) DMI_TrainRN_Ack  /* Testbench_Integration::ROOT_Integration/DMI_TrainRN_Ack */
#define VAR_ROOT_Integration_DMI_TrainRN_Ack VARC_ROOT_Integration_DMI_TrainRN_Ack(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_keypad(context) DMI_keypad  /* Testbench_Integration::ROOT_Integration/DMI_keypad */
#define VAR_ROOT_Integration_DMI_keypad VARC_ROOT_Integration_DMI_keypad(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_openTrainDataWindow(context) DMI_openTrainDataWindow  /* Testbench_Integration::ROOT_Integration/DMI_openTrainDataWindow */
#define VAR_ROOT_Integration_DMI_openTrainDataWindow VARC_ROOT_Integration_DMI_openTrainDataWindow(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_openDriverID(context) DMI_openDriverID  /* Testbench_Integration::ROOT_Integration/DMI_openDriverID */
#define VAR_ROOT_Integration_DMI_openDriverID VARC_ROOT_Integration_DMI_openDriverID(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_DriverID_Ack(context) DMI_DriverID_Ack  /* Testbench_Integration::ROOT_Integration/DMI_DriverID_Ack */
#define VAR_ROOT_Integration_DMI_DriverID_Ack VARC_ROOT_Integration_DMI_DriverID_Ack(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_traindataNoAck(context) DMI_traindataNoAck  /* Testbench_Integration::ROOT_Integration/DMI_traindataNoAck */
#define VAR_ROOT_Integration_DMI_traindataNoAck VARC_ROOT_Integration_DMI_traindataNoAck(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_traindataAck(context) DMI_traindataAck  /* Testbench_Integration::ROOT_Integration/DMI_traindataAck */
#define VAR_ROOT_Integration_DMI_traindataAck VARC_ROOT_Integration_DMI_traindataAck(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_OverD9_fromDisplay(context) DMI_OverD9_fromDisplay  /* Testbench_Integration::ROOT_Integration/DMI_OverD9_fromDisplay */
#define VAR_ROOT_Integration_DMI_OverD9_fromDisplay VARC_ROOT_Integration_DMI_OverD9_fromDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_closeButton(context) DMI_closeButton  /* Testbench_Integration::ROOT_Integration/DMI_closeButton */
#define VAR_ROOT_Integration_DMI_closeButton VARC_ROOT_Integration_DMI_closeButton(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_confirmTrainData(context) DMI_confirmTrainData  /* Testbench_Integration::ROOT_Integration/DMI_confirmTrainData */
#define VAR_ROOT_Integration_DMI_confirmTrainData VARC_ROOT_Integration_DMI_confirmTrainData(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_textMsgAck(context) DMI_textMsgAck  /* Testbench_Integration::ROOT_Integration/DMI_textMsgAck */
#define VAR_ROOT_Integration_DMI_textMsgAck VARC_ROOT_Integration_DMI_textMsgAck(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_openLevelMenu(context) DMI_openLevelMenu  /* Testbench_Integration::ROOT_Integration/DMI_openLevelMenu */
#define VAR_ROOT_Integration_DMI_openLevelMenu VARC_ROOT_Integration_DMI_openLevelMenu(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_InputFieldAck(context) DMI_InputFieldAck  /* Testbench_Integration::ROOT_Integration/DMI_InputFieldAck */
#define VAR_ROOT_Integration_DMI_InputFieldAck VARC_ROOT_Integration_DMI_InputFieldAck(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_openMainMenu_fromDisplay(context) DMI_openMainMenu_fromDisplay  /* Testbench_Integration::ROOT_Integration/DMI_openMainMenu_fromDisplay */
#define VAR_ROOT_Integration_DMI_openMainMenu_fromDisplay VARC_ROOT_Integration_DMI_openMainMenu_fromDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_OverD12_frpmDisplay(context) DMI_OverD12_frpmDisplay  /* Testbench_Integration::ROOT_Integration/DMI_OverD12_frpmDisplay */
#define VAR_ROOT_Integration_DMI_OverD12_frpmDisplay VARC_ROOT_Integration_DMI_OverD12_frpmDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_HidePlanningArea_fromDisplay(context) DMI_HidePlanningArea_fromDisplay  /* Testbench_Integration::ROOT_Integration/DMI_HidePlanningArea_fromDisplay */
#define VAR_ROOT_Integration_DMI_HidePlanningArea_fromDisplay VARC_ROOT_Integration_DMI_HidePlanningArea_fromDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_ShowPlanningArea_fromDisplay(context) DMI_ShowPlanningArea_fromDisplay  /* Testbench_Integration::ROOT_Integration/DMI_ShowPlanningArea_fromDisplay */
#define VAR_ROOT_Integration_DMI_ShowPlanningArea_fromDisplay VARC_ROOT_Integration_DMI_ShowPlanningArea_fromDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_closeButtonMain(context) DMI_closeButtonMain  /* Testbench_Integration::ROOT_Integration/DMI_closeButtonMain */
#define VAR_ROOT_Integration_DMI_closeButtonMain VARC_ROOT_Integration_DMI_closeButtonMain(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_C1AreaAck(context) DMI_C1AreaAck  /* Testbench_Integration::ROOT_Integration/DMI_C1AreaAck */
#define VAR_ROOT_Integration_DMI_C1AreaAck VARC_ROOT_Integration_DMI_C1AreaAck(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_ScrollUp(context) DMI_ScrollUp  /* Testbench_Integration::ROOT_Integration/DMI_ScrollUp */
#define VAR_ROOT_Integration_DMI_ScrollUp VARC_ROOT_Integration_DMI_ScrollUp(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_ScrollDown(context) DMI_ScrollDown  /* Testbench_Integration::ROOT_Integration/DMI_ScrollDown */
#define VAR_ROOT_Integration_DMI_ScrollDown VARC_ROOT_Integration_DMI_ScrollDown(CTX_ROOT_Integration_Testbench_Integration)


/*$**********************************************************
*                           OUTPUTS
***********************************************************$*/

#define VARC_ROOT_Integration_DMI_icons_ack(context) DMI_icons_ack  /* Testbench_Integration::ROOT_Integration/DMI_icons_ack */
#define VAR_ROOT_Integration_DMI_icons_ack VARC_ROOT_Integration_DMI_icons_ack(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_openDesk_toDisplay(context) DMI_openDesk_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_openDesk_toDisplay */
#define VAR_ROOT_Integration_DMI_openDesk_toDisplay VARC_ROOT_Integration_DMI_openDesk_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_window_mask_visibility__toDisplay(context) DMI_window_mask_visibility__toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_window_mask_visibility__toDisplay */
#define VAR_ROOT_Integration_DMI_window_mask_visibility__toDisplay VARC_ROOT_Integration_DMI_window_mask_visibility__toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_SpeedTarget_toDisplay(context) DMI_SpeedTarget_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_SpeedTarget_toDisplay */
#define VAR_ROOT_Integration_DMI_SpeedTarget_toDisplay VARC_ROOT_Integration_DMI_SpeedTarget_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_VpermColor_toDisplay(context) DMI_VpermColor_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_VpermColor_toDisplay */
#define VAR_ROOT_Integration_DMI_VpermColor_toDisplay VARC_ROOT_Integration_DMI_VpermColor_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_trainLenght_toDisplay(context) DMI_trainLenght_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_trainLenght_toDisplay */
#define VAR_ROOT_Integration_DMI_trainLenght_toDisplay VARC_ROOT_Integration_DMI_trainLenght_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_GradientsValue_toDisplay(context) DMI_GradientsValue_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_GradientsValue_toDisplay */
#define VAR_ROOT_Integration_DMI_GradientsValue_toDisplay VARC_ROOT_Integration_DMI_GradientsValue_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_TrainPosition_toDisplay(context) DMI_TrainPosition_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_TrainPosition_toDisplay */
#define VAR_ROOT_Integration_DMI_TrainPosition_toDisplay VARC_ROOT_Integration_DMI_TrainPosition_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_Vinterv_Visibility_toDisplay(context) DMI_Vinterv_Visibility_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_Vinterv_Visibility_toDisplay */
#define VAR_ROOT_Integration_DMI_Vinterv_Visibility_toDisplay VARC_ROOT_Integration_DMI_Vinterv_Visibility_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_DistanceToTargetBarVisibility_toDisplay(context) DMI_DistanceToTargetBarVisibility_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_DistanceToTargetBarVisibility_toDisplay */
#define VAR_ROOT_Integration_DMI_DistanceToTargetBarVisibility_toDisplay VARC_ROOT_Integration_DMI_DistanceToTargetBarVisibility_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_SpeedDigitOne_toDisplay(context) DMI_SpeedDigitOne_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_SpeedDigitOne_toDisplay */
#define VAR_ROOT_Integration_DMI_SpeedDigitOne_toDisplay VARC_ROOT_Integration_DMI_SpeedDigitOne_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_hourGlassVisibility_toDisplay(context) DMI_hourGlassVisibility_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_hourGlassVisibility_toDisplay */
#define VAR_ROOT_Integration_DMI_hourGlassVisibility_toDisplay VARC_ROOT_Integration_DMI_hourGlassVisibility_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_trainAxleloadIndex_toDisplay(context) DMI_trainAxleloadIndex_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_trainAxleloadIndex_toDisplay */
#define VAR_ROOT_Integration_DMI_trainAxleloadIndex_toDisplay VARC_ROOT_Integration_DMI_trainAxleloadIndex_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_PointerColor_toDisplay(context) DMI_PointerColor_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_PointerColor_toDisplay */
#define VAR_ROOT_Integration_DMI_PointerColor_toDisplay VARC_ROOT_Integration_DMI_PointerColor_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_CloseButtonEnabler_toDisplay(context) DMI_CloseButtonEnabler_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_CloseButtonEnabler_toDisplay */
#define VAR_ROOT_Integration_DMI_CloseButtonEnabler_toDisplay VARC_ROOT_Integration_DMI_CloseButtonEnabler_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_SpeedRelease_toDisplay(context) DMI_SpeedRelease_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_SpeedRelease_toDisplay */
#define VAR_ROOT_Integration_DMI_SpeedRelease_toDisplay VARC_ROOT_Integration_DMI_SpeedRelease_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_VtargetColor_toDisplay(context) DMI_VtargetColor_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_VtargetColor_toDisplay */
#define VAR_ROOT_Integration_DMI_VtargetColor_toDisplay VARC_ROOT_Integration_DMI_VtargetColor_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_trainMaxspeed_toDisplay(context) DMI_trainMaxspeed_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_trainMaxspeed_toDisplay */
#define VAR_ROOT_Integration_DMI_trainMaxspeed_toDisplay VARC_ROOT_Integration_DMI_trainMaxspeed_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_DistanceToTargetVisible_toDisplay(context) DMI_DistanceToTargetVisible_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_DistanceToTargetVisible_toDisplay */
#define VAR_ROOT_Integration_DMI_DistanceToTargetVisible_toDisplay VARC_ROOT_Integration_DMI_DistanceToTargetVisible_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_LevelSymbolVisibility_toDisplay(context) DMI_LevelSymbolVisibility_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_LevelSymbolVisibility_toDisplay */
#define VAR_ROOT_Integration_DMI_LevelSymbolVisibility_toDisplay VARC_ROOT_Integration_DMI_LevelSymbolVisibility_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_SpeedIntervention_toDisplay(context) DMI_SpeedIntervention_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_SpeedIntervention_toDisplay */
#define VAR_ROOT_Integration_DMI_SpeedIntervention_toDisplay VARC_ROOT_Integration_DMI_SpeedIntervention_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_yellowBorderBrakeSymbol_toDisplay(context) DMI_yellowBorderBrakeSymbol_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_yellowBorderBrakeSymbol_toDisplay */
#define VAR_ROOT_Integration_DMI_yellowBorderBrakeSymbol_toDisplay VARC_ROOT_Integration_DMI_yellowBorderBrakeSymbol_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_closeButtonIndex_toDisplay(context) DMI_closeButtonIndex_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_closeButtonIndex_toDisplay */
#define VAR_ROOT_Integration_DMI_closeButtonIndex_toDisplay VARC_ROOT_Integration_DMI_closeButtonIndex_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_ModeSymbolVisibility_toDisplay(context) DMI_ModeSymbolVisibility_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_ModeSymbolVisibility_toDisplay */
#define VAR_ROOT_Integration_DMI_ModeSymbolVisibility_toDisplay VARC_ROOT_Integration_DMI_ModeSymbolVisibility_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_SpeedDigitThree_toDisplay(context) DMI_SpeedDigitThree_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_SpeedDigitThree_toDisplay */
#define VAR_ROOT_Integration_DMI_SpeedDigitThree_toDisplay VARC_ROOT_Integration_DMI_SpeedDigitThree_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_hourGlassCounter_toDisplay(context) DMI_hourGlassCounter_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_hourGlassCounter_toDisplay */
#define VAR_ROOT_Integration_DMI_hourGlassCounter_toDisplay VARC_ROOT_Integration_DMI_hourGlassCounter_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_trainLoadingGougeIndex_toDisplay(context) DMI_trainLoadingGougeIndex_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_trainLoadingGougeIndex_toDisplay */
#define VAR_ROOT_Integration_DMI_trainLoadingGougeIndex_toDisplay VARC_ROOT_Integration_DMI_trainLoadingGougeIndex_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_TrainRN_Display_toDisplay(context) DMI_TrainRN_Display_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_TrainRN_Display_toDisplay */
#define VAR_ROOT_Integration_DMI_TrainRN_Display_toDisplay VARC_ROOT_Integration_DMI_TrainRN_Display_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_RBC_status_symbol_toDisplay(context) DMI_RBC_status_symbol_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_RBC_status_symbol_toDisplay */
#define VAR_ROOT_Integration_DMI_RBC_status_symbol_toDisplay VARC_ROOT_Integration_DMI_RBC_status_symbol_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_GradientsEnd_toDisplay(context) DMI_GradientsEnd_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_GradientsEnd_toDisplay */
#define VAR_ROOT_Integration_DMI_GradientsEnd_toDisplay VARC_ROOT_Integration_DMI_GradientsEnd_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_vtarget_permColor_toDisplay(context) DMI_vtarget_permColor_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_vtarget_permColor_toDisplay */
#define VAR_ROOT_Integration_DMI_vtarget_permColor_toDisplay VARC_ROOT_Integration_DMI_vtarget_permColor_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_traindataYesNoIndex_toDisplay(context) DMI_traindataYesNoIndex_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_traindataYesNoIndex_toDisplay */
#define VAR_ROOT_Integration_DMI_traindataYesNoIndex_toDisplay VARC_ROOT_Integration_DMI_traindataYesNoIndex_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_StatusSymbolBrake_toDisplay(context) DMI_StatusSymbolBrake_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_StatusSymbolBrake_toDisplay */
#define VAR_ROOT_Integration_DMI_StatusSymbolBrake_toDisplay VARC_ROOT_Integration_DMI_StatusSymbolBrake_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_TrainDataWindowVisibility_toDisplay(context) DMI_TrainDataWindowVisibility_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_TrainDataWindowVisibility_toDisplay */
#define VAR_ROOT_Integration_DMI_TrainDataWindowVisibility_toDisplay VARC_ROOT_Integration_DMI_TrainDataWindowVisibility_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_levelSymbolAnnouncementIndex_toDisplay(context) DMI_levelSymbolAnnouncementIndex_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_levelSymbolAnnouncementIndex_toDisplay */
#define VAR_ROOT_Integration_DMI_levelSymbolAnnouncementIndex_toDisplay VARC_ROOT_Integration_DMI_levelSymbolAnnouncementIndex_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_trainCategoryIndex_toDisplay(context) DMI_trainCategoryIndex_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_trainCategoryIndex_toDisplay */
#define VAR_ROOT_Integration_DMI_trainCategoryIndex_toDisplay VARC_ROOT_Integration_DMI_trainCategoryIndex_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_SpeedPermitted_toDisplay(context) DMI_SpeedPermitted_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_SpeedPermitted_toDisplay */
#define VAR_ROOT_Integration_DMI_SpeedPermitted_toDisplay VARC_ROOT_Integration_DMI_SpeedPermitted_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_VreleaseColor_toDisplay(context) DMI_VreleaseColor_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_VreleaseColor_toDisplay */
#define VAR_ROOT_Integration_DMI_VreleaseColor_toDisplay VARC_ROOT_Integration_DMI_VreleaseColor_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_trainBrakePerc_toDisplay(context) DMI_trainBrakePerc_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_trainBrakePerc_toDisplay */
#define VAR_ROOT_Integration_DMI_trainBrakePerc_toDisplay VARC_ROOT_Integration_DMI_trainBrakePerc_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_ArrayButtonsEnabler_toDisplay(context) DMI_ArrayButtonsEnabler_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_ArrayButtonsEnabler_toDisplay */
#define VAR_ROOT_Integration_DMI_ArrayButtonsEnabler_toDisplay VARC_ROOT_Integration_DMI_ArrayButtonsEnabler_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_ETCS_LevelSymbol_toDisplay(context) DMI_ETCS_LevelSymbol_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_ETCS_LevelSymbol_toDisplay */
#define VAR_ROOT_Integration_DMI_ETCS_LevelSymbol_toDisplay VARC_ROOT_Integration_DMI_ETCS_LevelSymbol_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_modeSymbolAnnouncementIndex_toDisplay(context) DMI_modeSymbolAnnouncementIndex_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_modeSymbolAnnouncementIndex_toDisplay */
#define VAR_ROOT_Integration_DMI_modeSymbolAnnouncementIndex_toDisplay VARC_ROOT_Integration_DMI_modeSymbolAnnouncementIndex_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_ModeSymbol_toDisplay(context) DMI_ModeSymbol_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_ModeSymbol_toDisplay */
#define VAR_ROOT_Integration_DMI_ModeSymbol_toDisplay VARC_ROOT_Integration_DMI_ModeSymbol_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_DistanceToTarget_toDisplay(context) DMI_DistanceToTarget_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_DistanceToTarget_toDisplay */
#define VAR_ROOT_Integration_DMI_DistanceToTarget_toDisplay VARC_ROOT_Integration_DMI_DistanceToTarget_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_Vinterv_Color_toDisplay(context) DMI_Vinterv_Color_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_Vinterv_Color_toDisplay */
#define VAR_ROOT_Integration_DMI_Vinterv_Color_toDisplay VARC_ROOT_Integration_DMI_Vinterv_Color_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_yellowBorderMsg_toDisplay(context) DMI_yellowBorderMsg_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_yellowBorderMsg_toDisplay */
#define VAR_ROOT_Integration_DMI_yellowBorderMsg_toDisplay VARC_ROOT_Integration_DMI_yellowBorderMsg_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_DriverID_Display_toDisplay(context) DMI_DriverID_Display_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_DriverID_Display_toDisplay */
#define VAR_ROOT_Integration_DMI_DriverID_Display_toDisplay VARC_ROOT_Integration_DMI_DriverID_Display_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_SpeedDigitTwo_toDisplay(context) DMI_SpeedDigitTwo_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_SpeedDigitTwo_toDisplay */
#define VAR_ROOT_Integration_DMI_SpeedDigitTwo_toDisplay VARC_ROOT_Integration_DMI_SpeedDigitTwo_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_yellowBorderC1Area_toDisplay(context) DMI_yellowBorderC1Area_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_yellowBorderC1Area_toDisplay */
#define VAR_ROOT_Integration_DMI_yellowBorderC1Area_toDisplay VARC_ROOT_Integration_DMI_yellowBorderC1Area_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_trainAirtightIndex_toDisplay(context) DMI_trainAirtightIndex_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_trainAirtightIndex_toDisplay */
#define VAR_ROOT_Integration_DMI_trainAirtightIndex_toDisplay VARC_ROOT_Integration_DMI_trainAirtightIndex_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_GradientsStart_toDisplay(context) DMI_GradientsStart_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_GradientsStart_toDisplay */
#define VAR_ROOT_Integration_DMI_GradientsStart_toDisplay VARC_ROOT_Integration_DMI_GradientsStart_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_Vtarget_permVisibility_toDisplay(context) DMI_Vtarget_permVisibility_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_Vtarget_permVisibility_toDisplay */
#define VAR_ROOT_Integration_DMI_Vtarget_permVisibility_toDisplay VARC_ROOT_Integration_DMI_Vtarget_permVisibility_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_traindataValidWinVisibility_toDisplay(context) DMI_traindataValidWinVisibility_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_traindataValidWinVisibility_toDisplay */
#define VAR_ROOT_Integration_DMI_traindataValidWinVisibility_toDisplay VARC_ROOT_Integration_DMI_traindataValidWinVisibility_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_StatusSymbolVisibility_toDisplay(context) DMI_StatusSymbolVisibility_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_StatusSymbolVisibility_toDisplay */
#define VAR_ROOT_Integration_DMI_StatusSymbolVisibility_toDisplay VARC_ROOT_Integration_DMI_StatusSymbolVisibility_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_TrainSpeed_toDisplay(context) DMI_TrainSpeed_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_TrainSpeed_toDisplay */
#define VAR_ROOT_Integration_DMI_TrainSpeed_toDisplay VARC_ROOT_Integration_DMI_TrainSpeed_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_iconGroupIndex_toDisplay(context) DMI_iconGroupIndex_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_iconGroupIndex_toDisplay */
#define VAR_ROOT_Integration_DMI_iconGroupIndex_toDisplay VARC_ROOT_Integration_DMI_iconGroupIndex_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_ArrayOfMsgIndex_toDisplay(context) DMI_ArrayOfMsgIndex_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_ArrayOfMsgIndex_toDisplay */
#define VAR_ROOT_Integration_DMI_ArrayOfMsgIndex_toDisplay VARC_ROOT_Integration_DMI_ArrayOfMsgIndex_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_InterpolatedDistanceToTarget_toDisplay(context) DMI_InterpolatedDistanceToTarget_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_InterpolatedDistanceToTarget_toDisplay */
#define VAR_ROOT_Integration_DMI_InterpolatedDistanceToTarget_toDisplay VARC_ROOT_Integration_DMI_InterpolatedDistanceToTarget_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_SingleMsgAckRequiredVisibility_toDysplay(context) DMI_SingleMsgAckRequiredVisibility_toDysplay  /* Testbench_Integration::ROOT_Integration/DMI_SingleMsgAckRequiredVisibility_toDysplay */
#define VAR_ROOT_Integration_DMI_SingleMsgAckRequiredVisibility_toDysplay VARC_ROOT_Integration_DMI_SingleMsgAckRequiredVisibility_toDysplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_IndexFixedMsg_toDisplay(context) DMI_IndexFixedMsg_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_IndexFixedMsg_toDisplay */
#define VAR_ROOT_Integration_DMI_IndexFixedMsg_toDisplay VARC_ROOT_Integration_DMI_IndexFixedMsg_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_level_data(context) DMI_level_data  /* Testbench_Integration::ROOT_Integration/DMI_level_data */
#define VAR_ROOT_Integration_DMI_level_data VARC_ROOT_Integration_DMI_level_data(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_IndexLevel_toDisplay(context) DMI_IndexLevel_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_IndexLevel_toDisplay */
#define VAR_ROOT_Integration_DMI_IndexLevel_toDisplay VARC_ROOT_Integration_DMI_IndexLevel_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_ArrayLevelIndex_toDisplay(context) DMI_ArrayLevelIndex_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_ArrayLevelIndex_toDisplay */
#define VAR_ROOT_Integration_DMI_ArrayLevelIndex_toDisplay VARC_ROOT_Integration_DMI_ArrayLevelIndex_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_levelMenuVisibility_toDisplay(context) DMI_levelMenuVisibility_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_levelMenuVisibility_toDisplay */
#define VAR_ROOT_Integration_DMI_levelMenuVisibility_toDisplay VARC_ROOT_Integration_DMI_levelMenuVisibility_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_PlainText_toDisplay(context) DMI_PlainText_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_PlainText_toDisplay */
#define VAR_ROOT_Integration_DMI_PlainText_toDisplay VARC_ROOT_Integration_DMI_PlainText_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_Array_hh_toDisplay(context) DMI_Array_hh_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_Array_hh_toDisplay */
#define VAR_ROOT_Integration_DMI_Array_hh_toDisplay VARC_ROOT_Integration_DMI_Array_hh_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_Array_mm_toDisplay(context) DMI_Array_mm_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_Array_mm_toDisplay */
#define VAR_ROOT_Integration_DMI_Array_mm_toDisplay VARC_ROOT_Integration_DMI_Array_mm_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_isAuxiliarMsg_toDisplay(context) DMI_isAuxiliarMsg_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_isAuxiliarMsg_toDisplay */
#define VAR_ROOT_Integration_DMI_isAuxiliarMsg_toDisplay VARC_ROOT_Integration_DMI_isAuxiliarMsg_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_D_SPDI_SpeedChangeSymbolsVisible_toDisplay(context) DMI_D_SPDI_SpeedChangeSymbolsVisible_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_D_SPDI_SpeedChangeSymbolsVisible_toDisplay */
#define VAR_ROOT_Integration_DMI_D_SPDI_SpeedChangeSymbolsVisible_toDisplay VARC_ROOT_Integration_DMI_D_SPDI_SpeedChangeSymbolsVisible_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_D_PASP_IndicationMarker_toDisplay(context) DMI_D_PASP_IndicationMarker_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_D_PASP_IndicationMarker_toDisplay */
#define VAR_ROOT_Integration_DMI_D_PASP_IndicationMarker_toDisplay VARC_ROOT_Integration_DMI_D_PASP_IndicationMarker_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_D_SPDI_SpeedChangeIndex_toDisplay(context) DMI_D_SPDI_SpeedChangeIndex_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_D_SPDI_SpeedChangeIndex_toDisplay */
#define VAR_ROOT_Integration_DMI_D_SPDI_SpeedChangeIndex_toDisplay VARC_ROOT_Integration_DMI_D_SPDI_SpeedChangeIndex_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_D_SPDI_SpeedChangePosition_toDisplay(context) DMI_D_SPDI_SpeedChangePosition_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_D_SPDI_SpeedChangePosition_toDisplay */
#define VAR_ROOT_Integration_DMI_D_SPDI_SpeedChangePosition_toDisplay VARC_ROOT_Integration_DMI_D_SPDI_SpeedChangePosition_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_D_PASP_Speeds_toDisplay(context) DMI_D_PASP_Speeds_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_D_PASP_Speeds_toDisplay */
#define VAR_ROOT_Integration_DMI_D_PASP_Speeds_toDisplay VARC_ROOT_Integration_DMI_D_PASP_Speeds_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_D_PASP_Distances_toDisplay(context) DMI_D_PASP_Distances_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_D_PASP_Distances_toDisplay */
#define VAR_ROOT_Integration_DMI_D_PASP_Distances_toDisplay VARC_ROOT_Integration_DMI_D_PASP_Distances_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_D_GradientVisible_toDisplay(context) DMI_D_GradientVisible_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_D_GradientVisible_toDisplay */
#define VAR_ROOT_Integration_DMI_D_GradientVisible_toDisplay VARC_ROOT_Integration_DMI_D_GradientVisible_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_D_Scale_toDisplay(context) DMI_D_Scale_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_D_Scale_toDisplay */
#define VAR_ROOT_Integration_DMI_D_Scale_toDisplay VARC_ROOT_Integration_DMI_D_Scale_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_PlanningAreaVisibility_toDisplay(context) DMI_PlanningAreaVisibility_toDisplay  /* Testbench_Integration::ROOT_Integration/DMI_PlanningAreaVisibility_toDisplay */
#define VAR_ROOT_Integration_DMI_PlanningAreaVisibility_toDisplay VARC_ROOT_Integration_DMI_PlanningAreaVisibility_toDisplay(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_GUI_serviceBrake(context) GUI_serviceBrake  /* Testbench_Integration::ROOT_Integration/GUI_serviceBrake */
#define VAR_ROOT_Integration_GUI_serviceBrake VARC_ROOT_Integration_GUI_serviceBrake(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_GUI_TractionCutOff(context) GUI_TractionCutOff  /* Testbench_Integration::ROOT_Integration/GUI_TractionCutOff */
#define VAR_ROOT_Integration_GUI_TractionCutOff VARC_ROOT_Integration_GUI_TractionCutOff(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_GUI_currentPositionInCm(context) GUI_currentPositionInCm  /* Testbench_Integration::ROOT_Integration/GUI_currentPositionInCm */
#define VAR_ROOT_Integration_GUI_currentPositionInCm VARC_ROOT_Integration_GUI_currentPositionInCm(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_GUI_currentPositionInM(context) GUI_currentPositionInM  /* Testbench_Integration::ROOT_Integration/GUI_currentPositionInM */
#define VAR_ROOT_Integration_GUI_currentPositionInM VARC_ROOT_Integration_GUI_currentPositionInM(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_GUI_currentVelocityInKmH(context) GUI_currentVelocityInKmH  /* Testbench_Integration::ROOT_Integration/GUI_currentVelocityInKmH */
#define VAR_ROOT_Integration_GUI_currentVelocityInKmH VARC_ROOT_Integration_GUI_currentVelocityInKmH(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_GUI_TrainPositionDeltaMax(context) GUI_TrainPositionDeltaMax  /* Testbench_Integration::ROOT_Integration/GUI_TrainPositionDeltaMax */
#define VAR_ROOT_Integration_GUI_TrainPositionDeltaMax VARC_ROOT_Integration_GUI_TrainPositionDeltaMax(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_GUI_TrainPositionDeltaMin(context) GUI_TrainPositionDeltaMin  /* Testbench_Integration::ROOT_Integration/GUI_TrainPositionDeltaMin */
#define VAR_ROOT_Integration_GUI_TrainPositionDeltaMin VARC_ROOT_Integration_GUI_TrainPositionDeltaMin(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_GUI_timestamp(context) GUI_timestamp  /* Testbench_Integration::ROOT_Integration/GUI_timestamp */
#define VAR_ROOT_Integration_GUI_timestamp VARC_ROOT_Integration_GUI_timestamp(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_GUI_TrainPositionNominal(context) GUI_TrainPositionNominal  /* Testbench_Integration::ROOT_Integration/GUI_TrainPositionNominal */
#define VAR_ROOT_Integration_GUI_TrainPositionNominal VARC_ROOT_Integration_GUI_TrainPositionNominal(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_GUI_emergencyBrake(context) GUI_emergencyBrake  /* Testbench_Integration::ROOT_Integration/GUI_emergencyBrake */
#define VAR_ROOT_Integration_GUI_emergencyBrake VARC_ROOT_Integration_GUI_emergencyBrake(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_GUI_AFBActive(context) GUI_AFBActive  /* Testbench_Integration::ROOT_Integration/GUI_AFBActive */
#define VAR_ROOT_Integration_GUI_AFBActive VARC_ROOT_Integration_GUI_AFBActive(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_ScrollDownEnableIndex(context) DMI_ScrollDownEnableIndex  /* Testbench_Integration::ROOT_Integration/DMI_ScrollDownEnableIndex */
#define VAR_ROOT_Integration_DMI_ScrollDownEnableIndex VARC_ROOT_Integration_DMI_ScrollDownEnableIndex(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_ScrollUpEnableIndex(context) DMI_ScrollUpEnableIndex  /* Testbench_Integration::ROOT_Integration/DMI_ScrollUpEnableIndex */
#define VAR_ROOT_Integration_DMI_ScrollUpEnableIndex VARC_ROOT_Integration_DMI_ScrollUpEnableIndex(CTX_ROOT_Integration_Testbench_Integration)

#define VARC_ROOT_Integration_DMI_localTime(context) DMI_localTime  /* Testbench_Integration::ROOT_Integration/DMI_localTime */
#define VAR_ROOT_Integration_DMI_localTime VARC_ROOT_Integration_DMI_localTime(CTX_ROOT_Integration_Testbench_Integration)


/*$**********************************************************
*                           ELEMENT ACCESS
***********************************************************$*/

#define GET_ELEMENT_AT(VARIABLE, INDEX)  (VARIABLE)[INDEX]
#define GET_STRUCTURE_FIELD(VARIABLE, FIELD) (VARIABLE).FIELD

/*$**********************************************************
*                        VARIABLES TYPES
***********************************************************$*/

#define T_GUI_reset kcg_bool
#define CPY_GUI_reset(DST, SRC) DST = SRC
#define T_GUI_targetSpeed kcg_real
#define CPY_GUI_targetSpeed(DST, SRC) DST = SRC
#define T_GUI_traction kcg_real
#define CPY_GUI_traction(DST, SRC) DST = SRC
#define T_GUI_brake kcg_real
#define CPY_GUI_brake(DST, SRC) DST = SRC
#define T_GUI_initialPosition kcg_real
#define CPY_GUI_initialPosition(DST, SRC) DST = SRC
#define T_GUI_initialVelocity kcg_real
#define CPY_GUI_initialVelocity(DST, SRC) DST = SRC
#define T_GUI_mode kcg_int
#define CPY_GUI_mode(DST, SRC) DST = SRC
#define T_GUI_level kcg_int
#define CPY_GUI_level(DST, SRC) DST = SRC
#define T_GUI_mobileHWStatus kcg_int
#define CPY_GUI_mobileHWStatus(DST, SRC) DST = SRC
#define T_GUI_openDesk kcg_bool
#define CPY_GUI_openDesk(DST, SRC) DST = SRC
#define T_DMI_MousePressed kcg_bool
#define CPY_DMI_MousePressed(DST, SRC) DST = SRC
#define T_DMI_startRequest kcg_bool
#define CPY_DMI_startRequest(DST, SRC) DST = SRC
#define T_DMI_openTrainRN kcg_bool
#define CPY_DMI_openTrainRN(DST, SRC) DST = SRC
#define T_DMI_traindataYesAck kcg_bool
#define CPY_DMI_traindataYesAck(DST, SRC) DST = SRC
#define T_DMI_TrainRN_Ack kcg_bool
#define CPY_DMI_TrainRN_Ack(DST, SRC) DST = SRC
#define T_DMI_keypad array_bool_12
#define CPY_DMI_keypad(DST, SRC) kcg_copy_array_bool_12(DST, SRC)
#define T_DMI_openTrainDataWindow kcg_bool
#define CPY_DMI_openTrainDataWindow(DST, SRC) DST = SRC
#define T_DMI_openDriverID kcg_bool
#define CPY_DMI_openDriverID(DST, SRC) DST = SRC
#define T_DMI_DriverID_Ack kcg_bool
#define CPY_DMI_DriverID_Ack(DST, SRC) DST = SRC
#define T_DMI_traindataNoAck kcg_bool
#define CPY_DMI_traindataNoAck(DST, SRC) DST = SRC
#define T_DMI_traindataAck kcg_bool
#define CPY_DMI_traindataAck(DST, SRC) DST = SRC
#define T_DMI_OverD9_fromDisplay kcg_bool
#define CPY_DMI_OverD9_fromDisplay(DST, SRC) DST = SRC
#define T_DMI_closeButton kcg_bool
#define CPY_DMI_closeButton(DST, SRC) DST = SRC
#define T_DMI_confirmTrainData kcg_bool
#define CPY_DMI_confirmTrainData(DST, SRC) DST = SRC
#define T_DMI_textMsgAck kcg_bool
#define CPY_DMI_textMsgAck(DST, SRC) DST = SRC
#define T_DMI_openLevelMenu kcg_bool
#define CPY_DMI_openLevelMenu(DST, SRC) DST = SRC
#define T_DMI_InputFieldAck kcg_bool
#define CPY_DMI_InputFieldAck(DST, SRC) DST = SRC
#define T_DMI_openMainMenu_fromDisplay kcg_bool
#define CPY_DMI_openMainMenu_fromDisplay(DST, SRC) DST = SRC
#define T_DMI_OverD12_frpmDisplay kcg_bool
#define CPY_DMI_OverD12_frpmDisplay(DST, SRC) DST = SRC
#define T_DMI_HidePlanningArea_fromDisplay kcg_bool
#define CPY_DMI_HidePlanningArea_fromDisplay(DST, SRC) DST = SRC
#define T_DMI_ShowPlanningArea_fromDisplay kcg_bool
#define CPY_DMI_ShowPlanningArea_fromDisplay(DST, SRC) DST = SRC
#define T_DMI_closeButtonMain kcg_bool
#define CPY_DMI_closeButtonMain(DST, SRC) DST = SRC
#define T_DMI_C1AreaAck kcg_bool
#define CPY_DMI_C1AreaAck(DST, SRC) DST = SRC
#define T_DMI_ScrollUp kcg_bool
#define CPY_DMI_ScrollUp(DST, SRC) DST = SRC
#define T_DMI_ScrollDown kcg_bool
#define CPY_DMI_ScrollDown(DST, SRC) DST = SRC
#define T_DMI_icons_ack DMI_Icon_Ack_T_DMI_Messages_DMI_to_EVC_Pkg
#define CPY_DMI_icons_ack(DST, SRC) kcg_copy_DMI_Icon_Ack_T_DMI_Messages_DMI_to_EVC_Pkg(DST, SRC)
#define T_DMI_openDesk_toDisplay kcg_bool
#define CPY_DMI_openDesk_toDisplay(DST, SRC) DST = SRC
#define T_DMI_window_mask_visibility__toDisplay array_bool_15
#define CPY_DMI_window_mask_visibility__toDisplay(DST, SRC) kcg_copy_array_bool_15(DST, SRC)
#define T_DMI_SpeedTarget_toDisplay kcg_real
#define CPY_DMI_SpeedTarget_toDisplay(DST, SRC) DST = SRC
#define T_DMI_VpermColor_toDisplay kcg_int
#define CPY_DMI_VpermColor_toDisplay(DST, SRC) DST = SRC
#define T_DMI_trainLenght_toDisplay kcg_real
#define CPY_DMI_trainLenght_toDisplay(DST, SRC) DST = SRC
#define T_DMI_GradientsValue_toDisplay array_real_12
#define CPY_DMI_GradientsValue_toDisplay(DST, SRC) kcg_copy_array_real_12(DST, SRC)
#define T_DMI_TrainPosition_toDisplay kcg_real
#define CPY_DMI_TrainPosition_toDisplay(DST, SRC) DST = SRC
#define T_DMI_Vinterv_Visibility_toDisplay kcg_bool
#define CPY_DMI_Vinterv_Visibility_toDisplay(DST, SRC) DST = SRC
#define T_DMI_DistanceToTargetBarVisibility_toDisplay kcg_bool
#define CPY_DMI_DistanceToTargetBarVisibility_toDisplay(DST, SRC) DST = SRC
#define T_DMI_SpeedDigitOne_toDisplay kcg_real
#define CPY_DMI_SpeedDigitOne_toDisplay(DST, SRC) DST = SRC
#define T_DMI_hourGlassVisibility_toDisplay kcg_bool
#define CPY_DMI_hourGlassVisibility_toDisplay(DST, SRC) DST = SRC
#define T_DMI_trainAxleloadIndex_toDisplay kcg_int
#define CPY_DMI_trainAxleloadIndex_toDisplay(DST, SRC) DST = SRC
#define T_DMI_PointerColor_toDisplay kcg_int
#define CPY_DMI_PointerColor_toDisplay(DST, SRC) DST = SRC
#define T_DMI_CloseButtonEnabler_toDisplay kcg_int
#define CPY_DMI_CloseButtonEnabler_toDisplay(DST, SRC) DST = SRC
#define T_DMI_SpeedRelease_toDisplay kcg_real
#define CPY_DMI_SpeedRelease_toDisplay(DST, SRC) DST = SRC
#define T_DMI_VtargetColor_toDisplay kcg_int
#define CPY_DMI_VtargetColor_toDisplay(DST, SRC) DST = SRC
#define T_DMI_trainMaxspeed_toDisplay kcg_real
#define CPY_DMI_trainMaxspeed_toDisplay(DST, SRC) DST = SRC
#define T_DMI_DistanceToTargetVisible_toDisplay kcg_bool
#define CPY_DMI_DistanceToTargetVisible_toDisplay(DST, SRC) DST = SRC
#define T_DMI_LevelSymbolVisibility_toDisplay kcg_bool
#define CPY_DMI_LevelSymbolVisibility_toDisplay(DST, SRC) DST = SRC
#define T_DMI_SpeedIntervention_toDisplay kcg_real
#define CPY_DMI_SpeedIntervention_toDisplay(DST, SRC) DST = SRC
#define T_DMI_yellowBorderBrakeSymbol_toDisplay kcg_bool
#define CPY_DMI_yellowBorderBrakeSymbol_toDisplay(DST, SRC) DST = SRC
#define T_DMI_closeButtonIndex_toDisplay kcg_int
#define CPY_DMI_closeButtonIndex_toDisplay(DST, SRC) DST = SRC
#define T_DMI_ModeSymbolVisibility_toDisplay kcg_bool
#define CPY_DMI_ModeSymbolVisibility_toDisplay(DST, SRC) DST = SRC
#define T_DMI_SpeedDigitThree_toDisplay kcg_real
#define CPY_DMI_SpeedDigitThree_toDisplay(DST, SRC) DST = SRC
#define T_DMI_hourGlassCounter_toDisplay kcg_real
#define CPY_DMI_hourGlassCounter_toDisplay(DST, SRC) DST = SRC
#define T_DMI_trainLoadingGougeIndex_toDisplay kcg_int
#define CPY_DMI_trainLoadingGougeIndex_toDisplay(DST, SRC) DST = SRC
#define T_DMI_TrainRN_Display_toDisplay array_int_9
#define CPY_DMI_TrainRN_Display_toDisplay(DST, SRC) kcg_copy_array_int_9(DST, SRC)
#define T_DMI_RBC_status_symbol_toDisplay kcg_int
#define CPY_DMI_RBC_status_symbol_toDisplay(DST, SRC) DST = SRC
#define T_DMI_GradientsEnd_toDisplay array_real_12
#define CPY_DMI_GradientsEnd_toDisplay(DST, SRC) kcg_copy_array_real_12(DST, SRC)
#define T_DMI_vtarget_permColor_toDisplay kcg_int
#define CPY_DMI_vtarget_permColor_toDisplay(DST, SRC) DST = SRC
#define T_DMI_traindataYesNoIndex_toDisplay kcg_int
#define CPY_DMI_traindataYesNoIndex_toDisplay(DST, SRC) DST = SRC
#define T_DMI_StatusSymbolBrake_toDisplay kcg_bool
#define CPY_DMI_StatusSymbolBrake_toDisplay(DST, SRC) DST = SRC
#define T_DMI_TrainDataWindowVisibility_toDisplay kcg_bool
#define CPY_DMI_TrainDataWindowVisibility_toDisplay(DST, SRC) DST = SRC
#define T_DMI_levelSymbolAnnouncementIndex_toDisplay kcg_int
#define CPY_DMI_levelSymbolAnnouncementIndex_toDisplay(DST, SRC) DST = SRC
#define T_DMI_trainCategoryIndex_toDisplay kcg_int
#define CPY_DMI_trainCategoryIndex_toDisplay(DST, SRC) DST = SRC
#define T_DMI_SpeedPermitted_toDisplay kcg_real
#define CPY_DMI_SpeedPermitted_toDisplay(DST, SRC) DST = SRC
#define T_DMI_VreleaseColor_toDisplay kcg_int
#define CPY_DMI_VreleaseColor_toDisplay(DST, SRC) DST = SRC
#define T_DMI_trainBrakePerc_toDisplay kcg_real
#define CPY_DMI_trainBrakePerc_toDisplay(DST, SRC) DST = SRC
#define T_DMI_ArrayButtonsEnabler_toDisplay array_int_30
#define CPY_DMI_ArrayButtonsEnabler_toDisplay(DST, SRC) kcg_copy_array_int_30(DST, SRC)
#define T_DMI_ETCS_LevelSymbol_toDisplay kcg_int
#define CPY_DMI_ETCS_LevelSymbol_toDisplay(DST, SRC) DST = SRC
#define T_DMI_modeSymbolAnnouncementIndex_toDisplay kcg_int
#define CPY_DMI_modeSymbolAnnouncementIndex_toDisplay(DST, SRC) DST = SRC
#define T_DMI_ModeSymbol_toDisplay kcg_int
#define CPY_DMI_ModeSymbol_toDisplay(DST, SRC) DST = SRC
#define T_DMI_DistanceToTarget_toDisplay kcg_real
#define CPY_DMI_DistanceToTarget_toDisplay(DST, SRC) DST = SRC
#define T_DMI_Vinterv_Color_toDisplay kcg_int
#define CPY_DMI_Vinterv_Color_toDisplay(DST, SRC) DST = SRC
#define T_DMI_yellowBorderMsg_toDisplay kcg_bool
#define CPY_DMI_yellowBorderMsg_toDisplay(DST, SRC) DST = SRC
#define T_DMI_DriverID_Display_toDisplay array_int_9
#define CPY_DMI_DriverID_Display_toDisplay(DST, SRC) kcg_copy_array_int_9(DST, SRC)
#define T_DMI_SpeedDigitTwo_toDisplay kcg_real
#define CPY_DMI_SpeedDigitTwo_toDisplay(DST, SRC) DST = SRC
#define T_DMI_yellowBorderC1Area_toDisplay kcg_bool
#define CPY_DMI_yellowBorderC1Area_toDisplay(DST, SRC) DST = SRC
#define T_DMI_trainAirtightIndex_toDisplay kcg_int
#define CPY_DMI_trainAirtightIndex_toDisplay(DST, SRC) DST = SRC
#define T_DMI_GradientsStart_toDisplay array_real_12
#define CPY_DMI_GradientsStart_toDisplay(DST, SRC) kcg_copy_array_real_12(DST, SRC)
#define T_DMI_Vtarget_permVisibility_toDisplay kcg_bool
#define CPY_DMI_Vtarget_permVisibility_toDisplay(DST, SRC) DST = SRC
#define T_DMI_traindataValidWinVisibility_toDisplay kcg_bool
#define CPY_DMI_traindataValidWinVisibility_toDisplay(DST, SRC) DST = SRC
#define T_DMI_StatusSymbolVisibility_toDisplay kcg_bool
#define CPY_DMI_StatusSymbolVisibility_toDisplay(DST, SRC) DST = SRC
#define T_DMI_TrainSpeed_toDisplay kcg_real
#define CPY_DMI_TrainSpeed_toDisplay(DST, SRC) DST = SRC
#define T_DMI_iconGroupIndex_toDisplay kcg_int
#define CPY_DMI_iconGroupIndex_toDisplay(DST, SRC) DST = SRC
#define T_DMI_ArrayOfMsgIndex_toDisplay array_int_5
#define CPY_DMI_ArrayOfMsgIndex_toDisplay(DST, SRC) kcg_copy_array_int_5(DST, SRC)
#define T_DMI_InterpolatedDistanceToTarget_toDisplay kcg_real
#define CPY_DMI_InterpolatedDistanceToTarget_toDisplay(DST, SRC) DST = SRC
#define T_DMI_SingleMsgAckRequiredVisibility_toDysplay kcg_bool
#define CPY_DMI_SingleMsgAckRequiredVisibility_toDysplay(DST, SRC) DST = SRC
#define T_DMI_IndexFixedMsg_toDisplay array_int_5
#define CPY_DMI_IndexFixedMsg_toDisplay(DST, SRC) kcg_copy_array_int_5(DST, SRC)
#define T_DMI_level_data DMI_Level_Data_T_DMI_Messages_Bothways_Pkg
#define CPY_DMI_level_data(DST, SRC) kcg_copy_DMI_Level_Data_T_DMI_Messages_Bothways_Pkg(DST, SRC)
#define T_DMI_IndexLevel_toDisplay kcg_int
#define CPY_DMI_IndexLevel_toDisplay(DST, SRC) DST = SRC
#define T_DMI_ArrayLevelIndex_toDisplay array_int_12
#define CPY_DMI_ArrayLevelIndex_toDisplay(DST, SRC) kcg_copy_array_int_12(DST, SRC)
#define T_DMI_levelMenuVisibility_toDisplay kcg_bool
#define CPY_DMI_levelMenuVisibility_toDisplay(DST, SRC) DST = SRC
#define T_DMI_PlainText_toDisplay array_char_30_5
#define CPY_DMI_PlainText_toDisplay(DST, SRC) kcg_copy_array_char_30_5(DST, SRC)
#define T_DMI_Array_hh_toDisplay array_real_5
#define CPY_DMI_Array_hh_toDisplay(DST, SRC) kcg_copy_array_real_5(DST, SRC)
#define T_DMI_Array_mm_toDisplay array_real_5
#define CPY_DMI_Array_mm_toDisplay(DST, SRC) kcg_copy_array_real_5(DST, SRC)
#define T_DMI_isAuxiliarMsg_toDisplay kcg_bool
#define CPY_DMI_isAuxiliarMsg_toDisplay(DST, SRC) DST = SRC
#define T_DMI_D_SPDI_SpeedChangeSymbolsVisible_toDisplay array_bool_10
#define CPY_DMI_D_SPDI_SpeedChangeSymbolsVisible_toDisplay(DST, SRC) kcg_copy_array_bool_10(DST, SRC)
#define T_DMI_D_PASP_IndicationMarker_toDisplay array_real_1
#define CPY_DMI_D_PASP_IndicationMarker_toDisplay(DST, SRC) kcg_copy_array_real_1(DST, SRC)
#define T_DMI_D_SPDI_SpeedChangeIndex_toDisplay array_int_10
#define CPY_DMI_D_SPDI_SpeedChangeIndex_toDisplay(DST, SRC) kcg_copy_array_int_10(DST, SRC)
#define T_DMI_D_SPDI_SpeedChangePosition_toDisplay array_real_10
#define CPY_DMI_D_SPDI_SpeedChangePosition_toDisplay(DST, SRC) kcg_copy_array_real_10(DST, SRC)
#define T_DMI_D_PASP_Speeds_toDisplay array_real_4
#define CPY_DMI_D_PASP_Speeds_toDisplay(DST, SRC) kcg_copy_array_real_4(DST, SRC)
#define T_DMI_D_PASP_Distances_toDisplay array_real_4
#define CPY_DMI_D_PASP_Distances_toDisplay(DST, SRC) kcg_copy_array_real_4(DST, SRC)
#define T_DMI_D_GradientVisible_toDisplay array_bool_12
#define CPY_DMI_D_GradientVisible_toDisplay(DST, SRC) kcg_copy_array_bool_12(DST, SRC)
#define T_DMI_D_Scale_toDisplay tScale
#define CPY_DMI_D_Scale_toDisplay(DST, SRC) kcg_copy_tScale(DST, SRC)
#define T_DMI_PlanningAreaVisibility_toDisplay kcg_bool
#define CPY_DMI_PlanningAreaVisibility_toDisplay(DST, SRC) DST = SRC
#define T_GUI_serviceBrake kcg_bool
#define CPY_GUI_serviceBrake(DST, SRC) DST = SRC
#define T_GUI_TractionCutOff kcg_bool
#define CPY_GUI_TractionCutOff(DST, SRC) DST = SRC
#define T_GUI_currentPositionInCm L_internal_Type_Obu_BasicTypes_Pkg
#define CPY_GUI_currentPositionInCm(DST, SRC) DST = SRC
#define T_GUI_currentPositionInM kcg_real
#define CPY_GUI_currentPositionInM(DST, SRC) DST = SRC
#define T_GUI_currentVelocityInKmH kcg_real
#define CPY_GUI_currentVelocityInKmH(DST, SRC) DST = SRC
#define T_GUI_TrainPositionDeltaMax kcg_real
#define CPY_GUI_TrainPositionDeltaMax(DST, SRC) DST = SRC
#define T_GUI_TrainPositionDeltaMin kcg_real
#define CPY_GUI_TrainPositionDeltaMin(DST, SRC) DST = SRC
#define T_GUI_timestamp kcg_int
#define CPY_GUI_timestamp(DST, SRC) DST = SRC
#define T_GUI_TrainPositionNominal kcg_real
#define CPY_GUI_TrainPositionNominal(DST, SRC) DST = SRC
#define T_GUI_emergencyBrake kcg_bool
#define CPY_GUI_emergencyBrake(DST, SRC) DST = SRC
#define T_GUI_AFBActive kcg_bool
#define CPY_GUI_AFBActive(DST, SRC) DST = SRC
#define T_DMI_ScrollDownEnableIndex kcg_int
#define CPY_DMI_ScrollDownEnableIndex(DST, SRC) DST = SRC
#define T_DMI_ScrollUpEnableIndex kcg_int
#define CPY_DMI_ScrollUpEnableIndex(DST, SRC) DST = SRC
#define T_DMI_localTime array_real_4
#define CPY_DMI_localTime(DST, SRC) kcg_copy_array_real_4(DST, SRC)


/*$**********************************************************
*                      CREATION, INIT AND PERFORM
***********************************************************$*/

#define DECLAREC_CTXT_ROOT_Integration(context) /* global_root_context option => no context declaration is needed */
#define DECLARE_CTXT_ROOT_Integration() DECLAREC_CTXT_ROOT_Integration(CTX_ROOT_Integration_Testbench_Integration)

#define DECLAREC_EXT_CTXT_ROOT_Integration(MODE , context) /* global_root_context option => no context declaration is needed */
#define DECLARE_EXT_CTXT_ROOT_Integration(MODE) DECLAREC_EXT_CTXT_ROOT_Integration(MODE , CTX_ROOT_Integration_Testbench_Integration)

#define INITC_ROOT_Integration(context)     #ifndef KCG_USER_DEFINED_INIT\
        ROOT_Integration_init_Testbench_Integration();\
    #else\
        #ifndef KCG_NO_EXTERN_CALL_TO_RESET\
            ROOT_Integration_reset_Testbench_Integration();\
        #endif\
    #endif
#define INIT_ROOT_Integration() INITC_ROOT_Integration(CTX_ROOT_Integration_Testbench_Integration)

#define PERFORMC_ROOT_Integration(context)     ROOT_Integration_Testbench_Integration()
#define PERFORM_ROOT_Integration() PERFORMC_ROOT_Integration(CTX_ROOT_Integration_Testbench_Integration)

/*$************** SCADE Macro wrapper *********************
** End of file ROOT_Integration_macro.h
***********************************************************$*/

#endif /* _ROOT_INTEGRATION_MACRO_H_ */
