#include "Testbench_Integration_newinterface.h"
const int  rt_version = Srtv62;

const char* _SCSIM_CheckSum = "a891d496462816f6d80015ae6b804dc3";
const char* _SCSIM_SmuTypesCheckSum = "f79c40cc4a28a84eb05b013596813063";

/*******************************
 * Validity
 *******************************/
int valid(void * pHandle) {
	return 1;
}
int notvalid(void * pHandle) {
	return 0;
}

/*******************************
 * Simulation context
 *******************************/
static kcg_bool _ctx_GUI_reset_restore;
kcg_bool _ctx_GUI_reset_buffer;
static kcg_real _ctx_GUI_targetSpeed_restore;
kcg_real _ctx_GUI_targetSpeed_buffer;
static kcg_real _ctx_GUI_traction_restore;
kcg_real _ctx_GUI_traction_buffer;
static kcg_real _ctx_GUI_brake_restore;
kcg_real _ctx_GUI_brake_buffer;
static kcg_real _ctx_GUI_initialPosition_restore;
kcg_real _ctx_GUI_initialPosition_buffer;
static kcg_real _ctx_GUI_initialVelocity_restore;
kcg_real _ctx_GUI_initialVelocity_buffer;
static kcg_int _ctx_GUI_mode_restore;
kcg_int _ctx_GUI_mode_buffer;
static kcg_int _ctx_GUI_level_restore;
kcg_int _ctx_GUI_level_buffer;
static kcg_int _ctx_GUI_mobileHWStatus_restore;
kcg_int _ctx_GUI_mobileHWStatus_buffer;
static kcg_bool _ctx_GUI_openDesk_restore;
kcg_bool _ctx_GUI_openDesk_buffer;
static kcg_bool _ctx_DMI_MousePressed_restore;
kcg_bool _ctx_DMI_MousePressed_buffer;
static kcg_bool _ctx_DMI_startRequest_restore;
kcg_bool _ctx_DMI_startRequest_buffer;
static kcg_bool _ctx_DMI_openTrainRN_restore;
kcg_bool _ctx_DMI_openTrainRN_buffer;
static kcg_bool _ctx_DMI_traindataYesAck_restore;
kcg_bool _ctx_DMI_traindataYesAck_buffer;
static kcg_bool _ctx_DMI_TrainRN_Ack_restore;
kcg_bool _ctx_DMI_TrainRN_Ack_buffer;
static array_bool_12 _ctx_DMI_keypad_restore;
array_bool_12 _ctx_DMI_keypad_buffer;
static kcg_bool _ctx_DMI_openTrainDataWindow_restore;
kcg_bool _ctx_DMI_openTrainDataWindow_buffer;
static kcg_bool _ctx_DMI_openDriverID_restore;
kcg_bool _ctx_DMI_openDriverID_buffer;
static kcg_bool _ctx_DMI_DriverID_Ack_restore;
kcg_bool _ctx_DMI_DriverID_Ack_buffer;
static kcg_bool _ctx_DMI_traindataNoAck_restore;
kcg_bool _ctx_DMI_traindataNoAck_buffer;
static kcg_bool _ctx_DMI_traindataAck_restore;
kcg_bool _ctx_DMI_traindataAck_buffer;
static kcg_bool _ctx_DMI_OverD9_fromDisplay_restore;
kcg_bool _ctx_DMI_OverD9_fromDisplay_buffer;
static kcg_bool _ctx_DMI_closeButton_restore;
kcg_bool _ctx_DMI_closeButton_buffer;
static kcg_bool _ctx_DMI_confirmTrainData_restore;
kcg_bool _ctx_DMI_confirmTrainData_buffer;
static kcg_bool _ctx_DMI_textMsgAck_restore;
kcg_bool _ctx_DMI_textMsgAck_buffer;
static kcg_bool _ctx_DMI_openLevelMenu_restore;
kcg_bool _ctx_DMI_openLevelMenu_buffer;
static kcg_bool _ctx_DMI_InputFieldAck_restore;
kcg_bool _ctx_DMI_InputFieldAck_buffer;
static kcg_bool _ctx_DMI_openMainMenu_fromDisplay_restore;
kcg_bool _ctx_DMI_openMainMenu_fromDisplay_buffer;
static kcg_bool _ctx_DMI_OverD12_frpmDisplay_restore;
kcg_bool _ctx_DMI_OverD12_frpmDisplay_buffer;
static kcg_bool _ctx_DMI_HidePlanningArea_fromDisplay_restore;
kcg_bool _ctx_DMI_HidePlanningArea_fromDisplay_buffer;
static kcg_bool _ctx_DMI_ShowPlanningArea_fromDisplay_restore;
kcg_bool _ctx_DMI_ShowPlanningArea_fromDisplay_buffer;
static kcg_bool _ctx_DMI_closeButtonMain_restore;
kcg_bool _ctx_DMI_closeButtonMain_buffer;
static kcg_bool _ctx_DMI_C1AreaAck_restore;
kcg_bool _ctx_DMI_C1AreaAck_buffer;
static kcg_bool _ctx_DMI_ScrollUp_restore;
kcg_bool _ctx_DMI_ScrollUp_buffer;
static kcg_bool _ctx_DMI_ScrollDown_restore;
kcg_bool _ctx_DMI_ScrollDown_buffer;
static DMI_Icon_Ack_T_DMI_Messages_DMI_to_EVC_Pkg _ctx_DMI_icons_ack_restore;
static kcg_bool _ctx_DMI_openDesk_toDisplay_restore;
static array_bool_15 _ctx_DMI_window_mask_visibility__toDisplay_restore;
static kcg_real _ctx_DMI_SpeedTarget_toDisplay_restore;
static kcg_int _ctx_DMI_VpermColor_toDisplay_restore;
static kcg_real _ctx_DMI_trainLenght_toDisplay_restore;
static array_real_12 _ctx_DMI_GradientsValue_toDisplay_restore;
static kcg_real _ctx_DMI_TrainPosition_toDisplay_restore;
static kcg_bool _ctx_DMI_Vinterv_Visibility_toDisplay_restore;
static kcg_bool _ctx_DMI_DistanceToTargetBarVisibility_toDisplay_restore;
static kcg_real _ctx_DMI_SpeedDigitOne_toDisplay_restore;
static kcg_bool _ctx_DMI_hourGlassVisibility_toDisplay_restore;
static kcg_int _ctx_DMI_trainAxleloadIndex_toDisplay_restore;
static kcg_int _ctx_DMI_PointerColor_toDisplay_restore;
static kcg_int _ctx_DMI_CloseButtonEnabler_toDisplay_restore;
static kcg_real _ctx_DMI_SpeedRelease_toDisplay_restore;
static kcg_int _ctx_DMI_VtargetColor_toDisplay_restore;
static kcg_real _ctx_DMI_trainMaxspeed_toDisplay_restore;
static kcg_bool _ctx_DMI_DistanceToTargetVisible_toDisplay_restore;
static kcg_bool _ctx_DMI_LevelSymbolVisibility_toDisplay_restore;
static kcg_real _ctx_DMI_SpeedIntervention_toDisplay_restore;
static kcg_bool _ctx_DMI_yellowBorderBrakeSymbol_toDisplay_restore;
static kcg_int _ctx_DMI_closeButtonIndex_toDisplay_restore;
static kcg_bool _ctx_DMI_ModeSymbolVisibility_toDisplay_restore;
static kcg_real _ctx_DMI_SpeedDigitThree_toDisplay_restore;
static kcg_real _ctx_DMI_hourGlassCounter_toDisplay_restore;
static kcg_int _ctx_DMI_trainLoadingGougeIndex_toDisplay_restore;
static array_int_9 _ctx_DMI_TrainRN_Display_toDisplay_restore;
static kcg_int _ctx_DMI_RBC_status_symbol_toDisplay_restore;
static array_real_12 _ctx_DMI_GradientsEnd_toDisplay_restore;
static kcg_int _ctx_DMI_vtarget_permColor_toDisplay_restore;
static kcg_int _ctx_DMI_traindataYesNoIndex_toDisplay_restore;
static kcg_bool _ctx_DMI_StatusSymbolBrake_toDisplay_restore;
static kcg_bool _ctx_DMI_TrainDataWindowVisibility_toDisplay_restore;
static kcg_int _ctx_DMI_levelSymbolAnnouncementIndex_toDisplay_restore;
static kcg_int _ctx_DMI_trainCategoryIndex_toDisplay_restore;
static kcg_real _ctx_DMI_SpeedPermitted_toDisplay_restore;
static kcg_int _ctx_DMI_VreleaseColor_toDisplay_restore;
static kcg_real _ctx_DMI_trainBrakePerc_toDisplay_restore;
static array_int_30 _ctx_DMI_ArrayButtonsEnabler_toDisplay_restore;
static kcg_int _ctx_DMI_ETCS_LevelSymbol_toDisplay_restore;
static kcg_int _ctx_DMI_modeSymbolAnnouncementIndex_toDisplay_restore;
static kcg_int _ctx_DMI_ModeSymbol_toDisplay_restore;
static kcg_real _ctx_DMI_DistanceToTarget_toDisplay_restore;
static kcg_int _ctx_DMI_Vinterv_Color_toDisplay_restore;
static kcg_bool _ctx_DMI_yellowBorderMsg_toDisplay_restore;
static array_int_9 _ctx_DMI_DriverID_Display_toDisplay_restore;
static kcg_real _ctx_DMI_SpeedDigitTwo_toDisplay_restore;
static kcg_bool _ctx_DMI_yellowBorderC1Area_toDisplay_restore;
static kcg_int _ctx_DMI_trainAirtightIndex_toDisplay_restore;
static array_real_12 _ctx_DMI_GradientsStart_toDisplay_restore;
static kcg_bool _ctx_DMI_Vtarget_permVisibility_toDisplay_restore;
static kcg_bool _ctx_DMI_traindataValidWinVisibility_toDisplay_restore;
static kcg_bool _ctx_DMI_StatusSymbolVisibility_toDisplay_restore;
static kcg_real _ctx_DMI_TrainSpeed_toDisplay_restore;
static kcg_int _ctx_DMI_iconGroupIndex_toDisplay_restore;
static array_int_5 _ctx_DMI_ArrayOfMsgIndex_toDisplay_restore;
static kcg_real _ctx_DMI_InterpolatedDistanceToTarget_toDisplay_restore;
static kcg_bool _ctx_DMI_SingleMsgAckRequiredVisibility_toDysplay_restore;
static array_int_5 _ctx_DMI_IndexFixedMsg_toDisplay_restore;
static DMI_Level_Data_T_DMI_Messages_Bothways_Pkg _ctx_DMI_level_data_restore;
static kcg_int _ctx_DMI_IndexLevel_toDisplay_restore;
static array_int_12 _ctx_DMI_ArrayLevelIndex_toDisplay_restore;
static kcg_bool _ctx_DMI_levelMenuVisibility_toDisplay_restore;
static array_char_30_5 _ctx_DMI_PlainText_toDisplay_restore;
static array_real_5 _ctx_DMI_Array_hh_toDisplay_restore;
static array_real_5 _ctx_DMI_Array_mm_toDisplay_restore;
static kcg_bool _ctx_DMI_isAuxiliarMsg_toDisplay_restore;
static array_bool_10 _ctx_DMI_D_SPDI_SpeedChangeSymbolsVisible_toDisplay_restore;
static array_real_1 _ctx_DMI_D_PASP_IndicationMarker_toDisplay_restore;
static array_int_10 _ctx_DMI_D_SPDI_SpeedChangeIndex_toDisplay_restore;
static array_real_10 _ctx_DMI_D_SPDI_SpeedChangePosition_toDisplay_restore;
static array_real_4 _ctx_DMI_D_PASP_Speeds_toDisplay_restore;
static array_real_4 _ctx_DMI_D_PASP_Distances_toDisplay_restore;
static array_bool_12 _ctx_DMI_D_GradientVisible_toDisplay_restore;
static tScale _ctx_DMI_D_Scale_toDisplay_restore;
static kcg_bool _ctx_DMI_PlanningAreaVisibility_toDisplay_restore;
static kcg_bool _ctx_GUI_serviceBrake_restore;
static kcg_bool _ctx_GUI_TractionCutOff_restore;
static L_internal_Type_Obu_BasicTypes_Pkg _ctx_GUI_currentPositionInCm_restore;
static kcg_real _ctx_GUI_currentPositionInM_restore;
static kcg_real _ctx_GUI_currentVelocityInKmH_restore;
static kcg_real _ctx_GUI_TrainPositionDeltaMax_restore;
static kcg_real _ctx_GUI_TrainPositionDeltaMin_restore;
static kcg_int _ctx_GUI_timestamp_restore;
static kcg_real _ctx_GUI_TrainPositionNominal_restore;
static kcg_bool _ctx_GUI_emergencyBrake_restore;
static kcg_bool _ctx_GUI_AFBActive_restore;
static kcg_int _ctx_DMI_ScrollDownEnableIndex_restore;
static kcg_int _ctx_DMI_ScrollUpEnableIndex_restore;
static array_real_4 _ctx_DMI_localTime_restore;
static outC_ROOT_Integration_Testbench_Integration _ctx_mem_restore;

static void _SCSIM_RestoreInterface(void) {
	_ctx_GUI_reset_buffer = _ctx_GUI_reset_restore;
	_ctx_GUI_targetSpeed_buffer = _ctx_GUI_targetSpeed_restore;
	_ctx_GUI_traction_buffer = _ctx_GUI_traction_restore;
	_ctx_GUI_brake_buffer = _ctx_GUI_brake_restore;
	_ctx_GUI_initialPosition_buffer = _ctx_GUI_initialPosition_restore;
	_ctx_GUI_initialVelocity_buffer = _ctx_GUI_initialVelocity_restore;
	_ctx_GUI_mode_buffer = _ctx_GUI_mode_restore;
	_ctx_GUI_level_buffer = _ctx_GUI_level_restore;
	_ctx_GUI_mobileHWStatus_buffer = _ctx_GUI_mobileHWStatus_restore;
	_ctx_GUI_openDesk_buffer = _ctx_GUI_openDesk_restore;
	_ctx_DMI_MousePressed_buffer = _ctx_DMI_MousePressed_restore;
	_ctx_DMI_startRequest_buffer = _ctx_DMI_startRequest_restore;
	_ctx_DMI_openTrainRN_buffer = _ctx_DMI_openTrainRN_restore;
	_ctx_DMI_traindataYesAck_buffer = _ctx_DMI_traindataYesAck_restore;
	_ctx_DMI_TrainRN_Ack_buffer = _ctx_DMI_TrainRN_Ack_restore;
	kcg_copy_array_bool_12(&(_ctx_DMI_keypad_buffer), &(_ctx_DMI_keypad_restore));
	_ctx_DMI_openTrainDataWindow_buffer = _ctx_DMI_openTrainDataWindow_restore;
	_ctx_DMI_openDriverID_buffer = _ctx_DMI_openDriverID_restore;
	_ctx_DMI_DriverID_Ack_buffer = _ctx_DMI_DriverID_Ack_restore;
	_ctx_DMI_traindataNoAck_buffer = _ctx_DMI_traindataNoAck_restore;
	_ctx_DMI_traindataAck_buffer = _ctx_DMI_traindataAck_restore;
	_ctx_DMI_OverD9_fromDisplay_buffer = _ctx_DMI_OverD9_fromDisplay_restore;
	_ctx_DMI_closeButton_buffer = _ctx_DMI_closeButton_restore;
	_ctx_DMI_confirmTrainData_buffer = _ctx_DMI_confirmTrainData_restore;
	_ctx_DMI_textMsgAck_buffer = _ctx_DMI_textMsgAck_restore;
	_ctx_DMI_openLevelMenu_buffer = _ctx_DMI_openLevelMenu_restore;
	_ctx_DMI_InputFieldAck_buffer = _ctx_DMI_InputFieldAck_restore;
	_ctx_DMI_openMainMenu_fromDisplay_buffer = _ctx_DMI_openMainMenu_fromDisplay_restore;
	_ctx_DMI_OverD12_frpmDisplay_buffer = _ctx_DMI_OverD12_frpmDisplay_restore;
	_ctx_DMI_HidePlanningArea_fromDisplay_buffer = _ctx_DMI_HidePlanningArea_fromDisplay_restore;
	_ctx_DMI_ShowPlanningArea_fromDisplay_buffer = _ctx_DMI_ShowPlanningArea_fromDisplay_restore;
	_ctx_DMI_closeButtonMain_buffer = _ctx_DMI_closeButtonMain_restore;
	_ctx_DMI_C1AreaAck_buffer = _ctx_DMI_C1AreaAck_restore;
	_ctx_DMI_ScrollUp_buffer = _ctx_DMI_ScrollUp_restore;
	_ctx_DMI_ScrollDown_buffer = _ctx_DMI_ScrollDown_restore;
	kcg_copy_DMI_Icon_Ack_T_DMI_Messages_DMI_to_EVC_Pkg(&(DMI_icons_ack), &(_ctx_DMI_icons_ack_restore));
	DMI_openDesk_toDisplay = _ctx_DMI_openDesk_toDisplay_restore;
	kcg_copy_array_bool_15(&(DMI_window_mask_visibility__toDisplay), &(_ctx_DMI_window_mask_visibility__toDisplay_restore));
	DMI_SpeedTarget_toDisplay = _ctx_DMI_SpeedTarget_toDisplay_restore;
	DMI_VpermColor_toDisplay = _ctx_DMI_VpermColor_toDisplay_restore;
	DMI_trainLenght_toDisplay = _ctx_DMI_trainLenght_toDisplay_restore;
	kcg_copy_array_real_12(&(DMI_GradientsValue_toDisplay), &(_ctx_DMI_GradientsValue_toDisplay_restore));
	DMI_TrainPosition_toDisplay = _ctx_DMI_TrainPosition_toDisplay_restore;
	DMI_Vinterv_Visibility_toDisplay = _ctx_DMI_Vinterv_Visibility_toDisplay_restore;
	DMI_DistanceToTargetBarVisibility_toDisplay = _ctx_DMI_DistanceToTargetBarVisibility_toDisplay_restore;
	DMI_SpeedDigitOne_toDisplay = _ctx_DMI_SpeedDigitOne_toDisplay_restore;
	DMI_hourGlassVisibility_toDisplay = _ctx_DMI_hourGlassVisibility_toDisplay_restore;
	DMI_trainAxleloadIndex_toDisplay = _ctx_DMI_trainAxleloadIndex_toDisplay_restore;
	DMI_PointerColor_toDisplay = _ctx_DMI_PointerColor_toDisplay_restore;
	DMI_CloseButtonEnabler_toDisplay = _ctx_DMI_CloseButtonEnabler_toDisplay_restore;
	DMI_SpeedRelease_toDisplay = _ctx_DMI_SpeedRelease_toDisplay_restore;
	DMI_VtargetColor_toDisplay = _ctx_DMI_VtargetColor_toDisplay_restore;
	DMI_trainMaxspeed_toDisplay = _ctx_DMI_trainMaxspeed_toDisplay_restore;
	DMI_DistanceToTargetVisible_toDisplay = _ctx_DMI_DistanceToTargetVisible_toDisplay_restore;
	DMI_LevelSymbolVisibility_toDisplay = _ctx_DMI_LevelSymbolVisibility_toDisplay_restore;
	DMI_SpeedIntervention_toDisplay = _ctx_DMI_SpeedIntervention_toDisplay_restore;
	DMI_yellowBorderBrakeSymbol_toDisplay = _ctx_DMI_yellowBorderBrakeSymbol_toDisplay_restore;
	DMI_closeButtonIndex_toDisplay = _ctx_DMI_closeButtonIndex_toDisplay_restore;
	DMI_ModeSymbolVisibility_toDisplay = _ctx_DMI_ModeSymbolVisibility_toDisplay_restore;
	DMI_SpeedDigitThree_toDisplay = _ctx_DMI_SpeedDigitThree_toDisplay_restore;
	DMI_hourGlassCounter_toDisplay = _ctx_DMI_hourGlassCounter_toDisplay_restore;
	DMI_trainLoadingGougeIndex_toDisplay = _ctx_DMI_trainLoadingGougeIndex_toDisplay_restore;
	kcg_copy_array_int_9(&(DMI_TrainRN_Display_toDisplay), &(_ctx_DMI_TrainRN_Display_toDisplay_restore));
	DMI_RBC_status_symbol_toDisplay = _ctx_DMI_RBC_status_symbol_toDisplay_restore;
	kcg_copy_array_real_12(&(DMI_GradientsEnd_toDisplay), &(_ctx_DMI_GradientsEnd_toDisplay_restore));
	DMI_vtarget_permColor_toDisplay = _ctx_DMI_vtarget_permColor_toDisplay_restore;
	DMI_traindataYesNoIndex_toDisplay = _ctx_DMI_traindataYesNoIndex_toDisplay_restore;
	DMI_StatusSymbolBrake_toDisplay = _ctx_DMI_StatusSymbolBrake_toDisplay_restore;
	DMI_TrainDataWindowVisibility_toDisplay = _ctx_DMI_TrainDataWindowVisibility_toDisplay_restore;
	DMI_levelSymbolAnnouncementIndex_toDisplay = _ctx_DMI_levelSymbolAnnouncementIndex_toDisplay_restore;
	DMI_trainCategoryIndex_toDisplay = _ctx_DMI_trainCategoryIndex_toDisplay_restore;
	DMI_SpeedPermitted_toDisplay = _ctx_DMI_SpeedPermitted_toDisplay_restore;
	DMI_VreleaseColor_toDisplay = _ctx_DMI_VreleaseColor_toDisplay_restore;
	DMI_trainBrakePerc_toDisplay = _ctx_DMI_trainBrakePerc_toDisplay_restore;
	kcg_copy_array_int_30(&(DMI_ArrayButtonsEnabler_toDisplay), &(_ctx_DMI_ArrayButtonsEnabler_toDisplay_restore));
	DMI_ETCS_LevelSymbol_toDisplay = _ctx_DMI_ETCS_LevelSymbol_toDisplay_restore;
	DMI_modeSymbolAnnouncementIndex_toDisplay = _ctx_DMI_modeSymbolAnnouncementIndex_toDisplay_restore;
	DMI_ModeSymbol_toDisplay = _ctx_DMI_ModeSymbol_toDisplay_restore;
	DMI_DistanceToTarget_toDisplay = _ctx_DMI_DistanceToTarget_toDisplay_restore;
	DMI_Vinterv_Color_toDisplay = _ctx_DMI_Vinterv_Color_toDisplay_restore;
	DMI_yellowBorderMsg_toDisplay = _ctx_DMI_yellowBorderMsg_toDisplay_restore;
	kcg_copy_array_int_9(&(DMI_DriverID_Display_toDisplay), &(_ctx_DMI_DriverID_Display_toDisplay_restore));
	DMI_SpeedDigitTwo_toDisplay = _ctx_DMI_SpeedDigitTwo_toDisplay_restore;
	DMI_yellowBorderC1Area_toDisplay = _ctx_DMI_yellowBorderC1Area_toDisplay_restore;
	DMI_trainAirtightIndex_toDisplay = _ctx_DMI_trainAirtightIndex_toDisplay_restore;
	kcg_copy_array_real_12(&(DMI_GradientsStart_toDisplay), &(_ctx_DMI_GradientsStart_toDisplay_restore));
	DMI_Vtarget_permVisibility_toDisplay = _ctx_DMI_Vtarget_permVisibility_toDisplay_restore;
	DMI_traindataValidWinVisibility_toDisplay = _ctx_DMI_traindataValidWinVisibility_toDisplay_restore;
	DMI_StatusSymbolVisibility_toDisplay = _ctx_DMI_StatusSymbolVisibility_toDisplay_restore;
	DMI_TrainSpeed_toDisplay = _ctx_DMI_TrainSpeed_toDisplay_restore;
	DMI_iconGroupIndex_toDisplay = _ctx_DMI_iconGroupIndex_toDisplay_restore;
	kcg_copy_array_int_5(&(DMI_ArrayOfMsgIndex_toDisplay), &(_ctx_DMI_ArrayOfMsgIndex_toDisplay_restore));
	DMI_InterpolatedDistanceToTarget_toDisplay = _ctx_DMI_InterpolatedDistanceToTarget_toDisplay_restore;
	DMI_SingleMsgAckRequiredVisibility_toDysplay = _ctx_DMI_SingleMsgAckRequiredVisibility_toDysplay_restore;
	kcg_copy_array_int_5(&(DMI_IndexFixedMsg_toDisplay), &(_ctx_DMI_IndexFixedMsg_toDisplay_restore));
	kcg_copy_DMI_Level_Data_T_DMI_Messages_Bothways_Pkg(&(DMI_level_data), &(_ctx_DMI_level_data_restore));
	DMI_IndexLevel_toDisplay = _ctx_DMI_IndexLevel_toDisplay_restore;
	kcg_copy_array_int_12(&(DMI_ArrayLevelIndex_toDisplay), &(_ctx_DMI_ArrayLevelIndex_toDisplay_restore));
	DMI_levelMenuVisibility_toDisplay = _ctx_DMI_levelMenuVisibility_toDisplay_restore;
	kcg_copy_array_char_30_5(&(DMI_PlainText_toDisplay), &(_ctx_DMI_PlainText_toDisplay_restore));
	kcg_copy_array_real_5(&(DMI_Array_hh_toDisplay), &(_ctx_DMI_Array_hh_toDisplay_restore));
	kcg_copy_array_real_5(&(DMI_Array_mm_toDisplay), &(_ctx_DMI_Array_mm_toDisplay_restore));
	DMI_isAuxiliarMsg_toDisplay = _ctx_DMI_isAuxiliarMsg_toDisplay_restore;
	kcg_copy_array_bool_10(&(DMI_D_SPDI_SpeedChangeSymbolsVisible_toDisplay), &(_ctx_DMI_D_SPDI_SpeedChangeSymbolsVisible_toDisplay_restore));
	kcg_copy_array_real_1(&(DMI_D_PASP_IndicationMarker_toDisplay), &(_ctx_DMI_D_PASP_IndicationMarker_toDisplay_restore));
	kcg_copy_array_int_10(&(DMI_D_SPDI_SpeedChangeIndex_toDisplay), &(_ctx_DMI_D_SPDI_SpeedChangeIndex_toDisplay_restore));
	kcg_copy_array_real_10(&(DMI_D_SPDI_SpeedChangePosition_toDisplay), &(_ctx_DMI_D_SPDI_SpeedChangePosition_toDisplay_restore));
	kcg_copy_array_real_4(&(DMI_D_PASP_Speeds_toDisplay), &(_ctx_DMI_D_PASP_Speeds_toDisplay_restore));
	kcg_copy_array_real_4(&(DMI_D_PASP_Distances_toDisplay), &(_ctx_DMI_D_PASP_Distances_toDisplay_restore));
	kcg_copy_array_bool_12(&(DMI_D_GradientVisible_toDisplay), &(_ctx_DMI_D_GradientVisible_toDisplay_restore));
	kcg_copy_tScale(&(DMI_D_Scale_toDisplay), &(_ctx_DMI_D_Scale_toDisplay_restore));
	DMI_PlanningAreaVisibility_toDisplay = _ctx_DMI_PlanningAreaVisibility_toDisplay_restore;
	GUI_serviceBrake = _ctx_GUI_serviceBrake_restore;
	GUI_TractionCutOff = _ctx_GUI_TractionCutOff_restore;
	GUI_currentPositionInCm = _ctx_GUI_currentPositionInCm_restore;
	GUI_currentPositionInM = _ctx_GUI_currentPositionInM_restore;
	GUI_currentVelocityInKmH = _ctx_GUI_currentVelocityInKmH_restore;
	GUI_TrainPositionDeltaMax = _ctx_GUI_TrainPositionDeltaMax_restore;
	GUI_TrainPositionDeltaMin = _ctx_GUI_TrainPositionDeltaMin_restore;
	GUI_timestamp = _ctx_GUI_timestamp_restore;
	GUI_TrainPositionNominal = _ctx_GUI_TrainPositionNominal_restore;
	GUI_emergencyBrake = _ctx_GUI_emergencyBrake_restore;
	GUI_AFBActive = _ctx_GUI_AFBActive_restore;
	DMI_ScrollDownEnableIndex = _ctx_DMI_ScrollDownEnableIndex_restore;
	DMI_ScrollUpEnableIndex = _ctx_DMI_ScrollUpEnableIndex_restore;
	kcg_copy_array_real_4(&(DMI_localTime), &(_ctx_DMI_localTime_restore));
	Ctxt_ROOT_Integration_Testbench_Integration = _ctx_mem_restore;
}

static void _SCSIM_ExecuteInterface(void) {
	pSimulator->m_pfnAcquireValueMutex(pSimulator);
	GUI_reset = _ctx_GUI_reset_buffer;
	GUI_targetSpeed = _ctx_GUI_targetSpeed_buffer;
	GUI_traction = _ctx_GUI_traction_buffer;
	GUI_brake = _ctx_GUI_brake_buffer;
	GUI_initialPosition = _ctx_GUI_initialPosition_buffer;
	GUI_initialVelocity = _ctx_GUI_initialVelocity_buffer;
	GUI_mode = _ctx_GUI_mode_buffer;
	GUI_level = _ctx_GUI_level_buffer;
	GUI_mobileHWStatus = _ctx_GUI_mobileHWStatus_buffer;
	GUI_openDesk = _ctx_GUI_openDesk_buffer;
	DMI_MousePressed = _ctx_DMI_MousePressed_buffer;
	DMI_startRequest = _ctx_DMI_startRequest_buffer;
	DMI_openTrainRN = _ctx_DMI_openTrainRN_buffer;
	DMI_traindataYesAck = _ctx_DMI_traindataYesAck_buffer;
	DMI_TrainRN_Ack = _ctx_DMI_TrainRN_Ack_buffer;
	kcg_copy_array_bool_12(&(DMI_keypad), &(_ctx_DMI_keypad_buffer));
	DMI_openTrainDataWindow = _ctx_DMI_openTrainDataWindow_buffer;
	DMI_openDriverID = _ctx_DMI_openDriverID_buffer;
	DMI_DriverID_Ack = _ctx_DMI_DriverID_Ack_buffer;
	DMI_traindataNoAck = _ctx_DMI_traindataNoAck_buffer;
	DMI_traindataAck = _ctx_DMI_traindataAck_buffer;
	DMI_OverD9_fromDisplay = _ctx_DMI_OverD9_fromDisplay_buffer;
	DMI_closeButton = _ctx_DMI_closeButton_buffer;
	DMI_confirmTrainData = _ctx_DMI_confirmTrainData_buffer;
	DMI_textMsgAck = _ctx_DMI_textMsgAck_buffer;
	DMI_openLevelMenu = _ctx_DMI_openLevelMenu_buffer;
	DMI_InputFieldAck = _ctx_DMI_InputFieldAck_buffer;
	DMI_openMainMenu_fromDisplay = _ctx_DMI_openMainMenu_fromDisplay_buffer;
	DMI_OverD12_frpmDisplay = _ctx_DMI_OverD12_frpmDisplay_buffer;
	DMI_HidePlanningArea_fromDisplay = _ctx_DMI_HidePlanningArea_fromDisplay_buffer;
	DMI_ShowPlanningArea_fromDisplay = _ctx_DMI_ShowPlanningArea_fromDisplay_buffer;
	DMI_closeButtonMain = _ctx_DMI_closeButtonMain_buffer;
	DMI_C1AreaAck = _ctx_DMI_C1AreaAck_buffer;
	DMI_ScrollUp = _ctx_DMI_ScrollUp_buffer;
	DMI_ScrollDown = _ctx_DMI_ScrollDown_buffer;
	pSimulator->m_pfnReleaseValueMutex(pSimulator);
}

/*******************************
 * Init/Reset function encapsulation
 *******************************/
int SimInit(void) {
	int nRet=0;
	_SCSIM_RestoreInterface();
#ifdef EXTENDED_SIM
	BeforeSimInit();
#endif /* EXTENDED_SIM */
#ifndef KCG_USER_DEFINED_INIT
	ROOT_Integration_init_Testbench_Integration();
	nRet=1;
#else /* KCG_USER_DEFINED_INIT */
	nRet=0;
#endif /* KCG_USER_DEFINED_INIT */
#ifdef EXTENDED_SIM
	AfterSimInit();
#endif /* EXTENDED_SIM */
	return nRet;
}

int SimReset(void) {
	int nRet=0;
	_SCSIM_RestoreInterface();
#ifdef EXTENDED_SIM
	BeforeSimInit();
#endif /* EXTENDED_SIM */
#ifndef KCG_NO_EXTERN_CALL_TO_RESET
	ROOT_Integration_reset_Testbench_Integration();
	nRet=1;
#else /* KCG_NO_EXTERN_CALL_TO_RESET */
	nRet=0;
#endif /* KCG_NO_EXTERN_CALL_TO_RESET */
#ifdef EXTENDED_SIM
	AfterSimInit();
#endif /* EXTENDED_SIM */
	return nRet;
}

#ifdef EXTENDED_SIM
int GraphicalInputsConnected = 1;
#endif /* EXTENDED_SIM */
/*******************************
 * Cyclic function encapsulation
 *******************************/
int SimStep(void) {
#ifdef EXTENDED_SIM
	if (GraphicalInputsConnected)
		BeforeSimStep();
#endif /* EXTENDED_SIM */
	_SCSIM_ExecuteInterface();
	ROOT_Integration_Testbench_Integration();
#ifdef EXTENDED_SIM
	AfterSimStep();
#endif /* EXTENDED_SIM */
	return 1;
}

int SimStop(void) {
#ifdef EXTENDED_SIM
	ExtendedSimStop();
#endif /* EXTENDED_SIM */
	return 1;
}

int SsmGetDumpSize(void) {
	int nSize = 0;
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_int);
	nSize += sizeof(kcg_int);
	nSize += sizeof(kcg_int);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(array_bool_12);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(DMI_Icon_Ack_T_DMI_Messages_DMI_to_EVC_Pkg);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(array_bool_15);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_int);
	nSize += sizeof(kcg_real);
	nSize += sizeof(array_real_12);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_int);
	nSize += sizeof(kcg_int);
	nSize += sizeof(kcg_int);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_int);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_int);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_int);
	nSize += sizeof(array_int_9);
	nSize += sizeof(kcg_int);
	nSize += sizeof(array_real_12);
	nSize += sizeof(kcg_int);
	nSize += sizeof(kcg_int);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_int);
	nSize += sizeof(kcg_int);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_int);
	nSize += sizeof(kcg_real);
	nSize += sizeof(array_int_30);
	nSize += sizeof(kcg_int);
	nSize += sizeof(kcg_int);
	nSize += sizeof(kcg_int);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_int);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(array_int_9);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_int);
	nSize += sizeof(array_real_12);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_int);
	nSize += sizeof(array_int_5);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(array_int_5);
	nSize += sizeof(DMI_Level_Data_T_DMI_Messages_Bothways_Pkg);
	nSize += sizeof(kcg_int);
	nSize += sizeof(array_int_12);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(array_char_30_5);
	nSize += sizeof(array_real_5);
	nSize += sizeof(array_real_5);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(array_bool_10);
	nSize += sizeof(array_real_1);
	nSize += sizeof(array_int_10);
	nSize += sizeof(array_real_10);
	nSize += sizeof(array_real_4);
	nSize += sizeof(array_real_4);
	nSize += sizeof(array_bool_12);
	nSize += sizeof(tScale);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(L_internal_Type_Obu_BasicTypes_Pkg);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_int);
	nSize += sizeof(kcg_real);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_bool);
	nSize += sizeof(kcg_int);
	nSize += sizeof(kcg_int);
	nSize += sizeof(array_real_4);
	nSize += sizeof(outC_ROOT_Integration_Testbench_Integration);
#ifdef EXTENDED_SIM
	nSize += ExtendedGetDumpSize();
#endif /* EXTENDED_SIM */
	return nSize;
}

void SsmGatherDumpData(char * pData) {
	char* pCurrent = pData;
	memcpy(pCurrent, &GUI_reset, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &GUI_targetSpeed, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &GUI_traction, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &GUI_brake, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &GUI_initialPosition, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &GUI_initialVelocity, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &GUI_mode, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &GUI_level, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &GUI_mobileHWStatus, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &GUI_openDesk, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_MousePressed, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_startRequest, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_openTrainRN, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_traindataYesAck, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_TrainRN_Ack, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_keypad, sizeof(array_bool_12));
	pCurrent += sizeof(array_bool_12);
	memcpy(pCurrent, &DMI_openTrainDataWindow, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_openDriverID, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_DriverID_Ack, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_traindataNoAck, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_traindataAck, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_OverD9_fromDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_closeButton, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_confirmTrainData, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_textMsgAck, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_openLevelMenu, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_InputFieldAck, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_openMainMenu_fromDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_OverD12_frpmDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_HidePlanningArea_fromDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_ShowPlanningArea_fromDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_closeButtonMain, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_C1AreaAck, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_ScrollUp, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_ScrollDown, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_icons_ack, sizeof(DMI_Icon_Ack_T_DMI_Messages_DMI_to_EVC_Pkg));
	pCurrent += sizeof(DMI_Icon_Ack_T_DMI_Messages_DMI_to_EVC_Pkg);
	memcpy(pCurrent, &DMI_openDesk_toDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_window_mask_visibility__toDisplay, sizeof(array_bool_15));
	pCurrent += sizeof(array_bool_15);
	memcpy(pCurrent, &DMI_SpeedTarget_toDisplay, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &DMI_VpermColor_toDisplay, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_trainLenght_toDisplay, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &DMI_GradientsValue_toDisplay, sizeof(array_real_12));
	pCurrent += sizeof(array_real_12);
	memcpy(pCurrent, &DMI_TrainPosition_toDisplay, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &DMI_Vinterv_Visibility_toDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_DistanceToTargetBarVisibility_toDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_SpeedDigitOne_toDisplay, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &DMI_hourGlassVisibility_toDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_trainAxleloadIndex_toDisplay, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_PointerColor_toDisplay, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_CloseButtonEnabler_toDisplay, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_SpeedRelease_toDisplay, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &DMI_VtargetColor_toDisplay, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_trainMaxspeed_toDisplay, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &DMI_DistanceToTargetVisible_toDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_LevelSymbolVisibility_toDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_SpeedIntervention_toDisplay, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &DMI_yellowBorderBrakeSymbol_toDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_closeButtonIndex_toDisplay, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_ModeSymbolVisibility_toDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_SpeedDigitThree_toDisplay, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &DMI_hourGlassCounter_toDisplay, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &DMI_trainLoadingGougeIndex_toDisplay, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_TrainRN_Display_toDisplay, sizeof(array_int_9));
	pCurrent += sizeof(array_int_9);
	memcpy(pCurrent, &DMI_RBC_status_symbol_toDisplay, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_GradientsEnd_toDisplay, sizeof(array_real_12));
	pCurrent += sizeof(array_real_12);
	memcpy(pCurrent, &DMI_vtarget_permColor_toDisplay, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_traindataYesNoIndex_toDisplay, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_StatusSymbolBrake_toDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_TrainDataWindowVisibility_toDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_levelSymbolAnnouncementIndex_toDisplay, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_trainCategoryIndex_toDisplay, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_SpeedPermitted_toDisplay, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &DMI_VreleaseColor_toDisplay, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_trainBrakePerc_toDisplay, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &DMI_ArrayButtonsEnabler_toDisplay, sizeof(array_int_30));
	pCurrent += sizeof(array_int_30);
	memcpy(pCurrent, &DMI_ETCS_LevelSymbol_toDisplay, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_modeSymbolAnnouncementIndex_toDisplay, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_ModeSymbol_toDisplay, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_DistanceToTarget_toDisplay, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &DMI_Vinterv_Color_toDisplay, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_yellowBorderMsg_toDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_DriverID_Display_toDisplay, sizeof(array_int_9));
	pCurrent += sizeof(array_int_9);
	memcpy(pCurrent, &DMI_SpeedDigitTwo_toDisplay, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &DMI_yellowBorderC1Area_toDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_trainAirtightIndex_toDisplay, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_GradientsStart_toDisplay, sizeof(array_real_12));
	pCurrent += sizeof(array_real_12);
	memcpy(pCurrent, &DMI_Vtarget_permVisibility_toDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_traindataValidWinVisibility_toDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_StatusSymbolVisibility_toDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_TrainSpeed_toDisplay, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &DMI_iconGroupIndex_toDisplay, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_ArrayOfMsgIndex_toDisplay, sizeof(array_int_5));
	pCurrent += sizeof(array_int_5);
	memcpy(pCurrent, &DMI_InterpolatedDistanceToTarget_toDisplay, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &DMI_SingleMsgAckRequiredVisibility_toDysplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_IndexFixedMsg_toDisplay, sizeof(array_int_5));
	pCurrent += sizeof(array_int_5);
	memcpy(pCurrent, &DMI_level_data, sizeof(DMI_Level_Data_T_DMI_Messages_Bothways_Pkg));
	pCurrent += sizeof(DMI_Level_Data_T_DMI_Messages_Bothways_Pkg);
	memcpy(pCurrent, &DMI_IndexLevel_toDisplay, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_ArrayLevelIndex_toDisplay, sizeof(array_int_12));
	pCurrent += sizeof(array_int_12);
	memcpy(pCurrent, &DMI_levelMenuVisibility_toDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_PlainText_toDisplay, sizeof(array_char_30_5));
	pCurrent += sizeof(array_char_30_5);
	memcpy(pCurrent, &DMI_Array_hh_toDisplay, sizeof(array_real_5));
	pCurrent += sizeof(array_real_5);
	memcpy(pCurrent, &DMI_Array_mm_toDisplay, sizeof(array_real_5));
	pCurrent += sizeof(array_real_5);
	memcpy(pCurrent, &DMI_isAuxiliarMsg_toDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_D_SPDI_SpeedChangeSymbolsVisible_toDisplay, sizeof(array_bool_10));
	pCurrent += sizeof(array_bool_10);
	memcpy(pCurrent, &DMI_D_PASP_IndicationMarker_toDisplay, sizeof(array_real_1));
	pCurrent += sizeof(array_real_1);
	memcpy(pCurrent, &DMI_D_SPDI_SpeedChangeIndex_toDisplay, sizeof(array_int_10));
	pCurrent += sizeof(array_int_10);
	memcpy(pCurrent, &DMI_D_SPDI_SpeedChangePosition_toDisplay, sizeof(array_real_10));
	pCurrent += sizeof(array_real_10);
	memcpy(pCurrent, &DMI_D_PASP_Speeds_toDisplay, sizeof(array_real_4));
	pCurrent += sizeof(array_real_4);
	memcpy(pCurrent, &DMI_D_PASP_Distances_toDisplay, sizeof(array_real_4));
	pCurrent += sizeof(array_real_4);
	memcpy(pCurrent, &DMI_D_GradientVisible_toDisplay, sizeof(array_bool_12));
	pCurrent += sizeof(array_bool_12);
	memcpy(pCurrent, &DMI_D_Scale_toDisplay, sizeof(tScale));
	pCurrent += sizeof(tScale);
	memcpy(pCurrent, &DMI_PlanningAreaVisibility_toDisplay, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &GUI_serviceBrake, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &GUI_TractionCutOff, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &GUI_currentPositionInCm, sizeof(L_internal_Type_Obu_BasicTypes_Pkg));
	pCurrent += sizeof(L_internal_Type_Obu_BasicTypes_Pkg);
	memcpy(pCurrent, &GUI_currentPositionInM, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &GUI_currentVelocityInKmH, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &GUI_TrainPositionDeltaMax, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &GUI_TrainPositionDeltaMin, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &GUI_timestamp, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &GUI_TrainPositionNominal, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(pCurrent, &GUI_emergencyBrake, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &GUI_AFBActive, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(pCurrent, &DMI_ScrollDownEnableIndex, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_ScrollUpEnableIndex, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(pCurrent, &DMI_localTime, sizeof(array_real_4));
	pCurrent += sizeof(array_real_4);
	memcpy(pCurrent, &Ctxt_ROOT_Integration_Testbench_Integration, sizeof(outC_ROOT_Integration_Testbench_Integration));
	pCurrent += sizeof(outC_ROOT_Integration_Testbench_Integration);
#ifdef EXTENDED_SIM
	ExtendedGatherDumpData(pCurrent);
#endif /* EXTENDED_SIM */
}

void SsmRestoreDumpData(const char * pData) {
	const char* pCurrent = pData;
	memcpy(&GUI_reset, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&GUI_targetSpeed, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&GUI_traction, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&GUI_brake, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&GUI_initialPosition, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&GUI_initialVelocity, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&GUI_mode, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&GUI_level, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&GUI_mobileHWStatus, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&GUI_openDesk, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_MousePressed, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_startRequest, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_openTrainRN, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_traindataYesAck, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_TrainRN_Ack, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_keypad, pCurrent, sizeof(array_bool_12));
	pCurrent += sizeof(array_bool_12);
	memcpy(&DMI_openTrainDataWindow, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_openDriverID, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_DriverID_Ack, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_traindataNoAck, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_traindataAck, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_OverD9_fromDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_closeButton, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_confirmTrainData, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_textMsgAck, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_openLevelMenu, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_InputFieldAck, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_openMainMenu_fromDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_OverD12_frpmDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_HidePlanningArea_fromDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_ShowPlanningArea_fromDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_closeButtonMain, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_C1AreaAck, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_ScrollUp, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_ScrollDown, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_icons_ack, pCurrent, sizeof(DMI_Icon_Ack_T_DMI_Messages_DMI_to_EVC_Pkg));
	pCurrent += sizeof(DMI_Icon_Ack_T_DMI_Messages_DMI_to_EVC_Pkg);
	memcpy(&DMI_openDesk_toDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_window_mask_visibility__toDisplay, pCurrent, sizeof(array_bool_15));
	pCurrent += sizeof(array_bool_15);
	memcpy(&DMI_SpeedTarget_toDisplay, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&DMI_VpermColor_toDisplay, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_trainLenght_toDisplay, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&DMI_GradientsValue_toDisplay, pCurrent, sizeof(array_real_12));
	pCurrent += sizeof(array_real_12);
	memcpy(&DMI_TrainPosition_toDisplay, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&DMI_Vinterv_Visibility_toDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_DistanceToTargetBarVisibility_toDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_SpeedDigitOne_toDisplay, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&DMI_hourGlassVisibility_toDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_trainAxleloadIndex_toDisplay, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_PointerColor_toDisplay, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_CloseButtonEnabler_toDisplay, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_SpeedRelease_toDisplay, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&DMI_VtargetColor_toDisplay, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_trainMaxspeed_toDisplay, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&DMI_DistanceToTargetVisible_toDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_LevelSymbolVisibility_toDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_SpeedIntervention_toDisplay, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&DMI_yellowBorderBrakeSymbol_toDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_closeButtonIndex_toDisplay, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_ModeSymbolVisibility_toDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_SpeedDigitThree_toDisplay, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&DMI_hourGlassCounter_toDisplay, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&DMI_trainLoadingGougeIndex_toDisplay, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_TrainRN_Display_toDisplay, pCurrent, sizeof(array_int_9));
	pCurrent += sizeof(array_int_9);
	memcpy(&DMI_RBC_status_symbol_toDisplay, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_GradientsEnd_toDisplay, pCurrent, sizeof(array_real_12));
	pCurrent += sizeof(array_real_12);
	memcpy(&DMI_vtarget_permColor_toDisplay, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_traindataYesNoIndex_toDisplay, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_StatusSymbolBrake_toDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_TrainDataWindowVisibility_toDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_levelSymbolAnnouncementIndex_toDisplay, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_trainCategoryIndex_toDisplay, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_SpeedPermitted_toDisplay, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&DMI_VreleaseColor_toDisplay, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_trainBrakePerc_toDisplay, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&DMI_ArrayButtonsEnabler_toDisplay, pCurrent, sizeof(array_int_30));
	pCurrent += sizeof(array_int_30);
	memcpy(&DMI_ETCS_LevelSymbol_toDisplay, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_modeSymbolAnnouncementIndex_toDisplay, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_ModeSymbol_toDisplay, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_DistanceToTarget_toDisplay, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&DMI_Vinterv_Color_toDisplay, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_yellowBorderMsg_toDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_DriverID_Display_toDisplay, pCurrent, sizeof(array_int_9));
	pCurrent += sizeof(array_int_9);
	memcpy(&DMI_SpeedDigitTwo_toDisplay, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&DMI_yellowBorderC1Area_toDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_trainAirtightIndex_toDisplay, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_GradientsStart_toDisplay, pCurrent, sizeof(array_real_12));
	pCurrent += sizeof(array_real_12);
	memcpy(&DMI_Vtarget_permVisibility_toDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_traindataValidWinVisibility_toDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_StatusSymbolVisibility_toDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_TrainSpeed_toDisplay, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&DMI_iconGroupIndex_toDisplay, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_ArrayOfMsgIndex_toDisplay, pCurrent, sizeof(array_int_5));
	pCurrent += sizeof(array_int_5);
	memcpy(&DMI_InterpolatedDistanceToTarget_toDisplay, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&DMI_SingleMsgAckRequiredVisibility_toDysplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_IndexFixedMsg_toDisplay, pCurrent, sizeof(array_int_5));
	pCurrent += sizeof(array_int_5);
	memcpy(&DMI_level_data, pCurrent, sizeof(DMI_Level_Data_T_DMI_Messages_Bothways_Pkg));
	pCurrent += sizeof(DMI_Level_Data_T_DMI_Messages_Bothways_Pkg);
	memcpy(&DMI_IndexLevel_toDisplay, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_ArrayLevelIndex_toDisplay, pCurrent, sizeof(array_int_12));
	pCurrent += sizeof(array_int_12);
	memcpy(&DMI_levelMenuVisibility_toDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_PlainText_toDisplay, pCurrent, sizeof(array_char_30_5));
	pCurrent += sizeof(array_char_30_5);
	memcpy(&DMI_Array_hh_toDisplay, pCurrent, sizeof(array_real_5));
	pCurrent += sizeof(array_real_5);
	memcpy(&DMI_Array_mm_toDisplay, pCurrent, sizeof(array_real_5));
	pCurrent += sizeof(array_real_5);
	memcpy(&DMI_isAuxiliarMsg_toDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_D_SPDI_SpeedChangeSymbolsVisible_toDisplay, pCurrent, sizeof(array_bool_10));
	pCurrent += sizeof(array_bool_10);
	memcpy(&DMI_D_PASP_IndicationMarker_toDisplay, pCurrent, sizeof(array_real_1));
	pCurrent += sizeof(array_real_1);
	memcpy(&DMI_D_SPDI_SpeedChangeIndex_toDisplay, pCurrent, sizeof(array_int_10));
	pCurrent += sizeof(array_int_10);
	memcpy(&DMI_D_SPDI_SpeedChangePosition_toDisplay, pCurrent, sizeof(array_real_10));
	pCurrent += sizeof(array_real_10);
	memcpy(&DMI_D_PASP_Speeds_toDisplay, pCurrent, sizeof(array_real_4));
	pCurrent += sizeof(array_real_4);
	memcpy(&DMI_D_PASP_Distances_toDisplay, pCurrent, sizeof(array_real_4));
	pCurrent += sizeof(array_real_4);
	memcpy(&DMI_D_GradientVisible_toDisplay, pCurrent, sizeof(array_bool_12));
	pCurrent += sizeof(array_bool_12);
	memcpy(&DMI_D_Scale_toDisplay, pCurrent, sizeof(tScale));
	pCurrent += sizeof(tScale);
	memcpy(&DMI_PlanningAreaVisibility_toDisplay, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&GUI_serviceBrake, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&GUI_TractionCutOff, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&GUI_currentPositionInCm, pCurrent, sizeof(L_internal_Type_Obu_BasicTypes_Pkg));
	pCurrent += sizeof(L_internal_Type_Obu_BasicTypes_Pkg);
	memcpy(&GUI_currentPositionInM, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&GUI_currentVelocityInKmH, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&GUI_TrainPositionDeltaMax, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&GUI_TrainPositionDeltaMin, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&GUI_timestamp, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&GUI_TrainPositionNominal, pCurrent, sizeof(kcg_real));
	pCurrent += sizeof(kcg_real);
	memcpy(&GUI_emergencyBrake, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&GUI_AFBActive, pCurrent, sizeof(kcg_bool));
	pCurrent += sizeof(kcg_bool);
	memcpy(&DMI_ScrollDownEnableIndex, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_ScrollUpEnableIndex, pCurrent, sizeof(kcg_int));
	pCurrent += sizeof(kcg_int);
	memcpy(&DMI_localTime, pCurrent, sizeof(array_real_4));
	pCurrent += sizeof(array_real_4);
	memcpy(&Ctxt_ROOT_Integration_Testbench_Integration, pCurrent, sizeof(outC_ROOT_Integration_Testbench_Integration));
	pCurrent += sizeof(outC_ROOT_Integration_Testbench_Integration);
#ifdef EXTENDED_SIM
	ExtendedRestoreDumpData(pCurrent);
#endif /* EXTENDED_SIM */
}

const char * SsmGetCheckSum() {
	return _SCSIM_CheckSum;
}

const char * SsmGetSmuTypesCheckSum() {
	return _SCSIM_SmuTypesCheckSum;
}

void SsmUpdateValues(void) {
#ifdef EXTENDED_SIM
	UpdateValues();
#endif /* EXTENDED_SIM */
}

void SsmConnectExternalInputs(int bConnect) {
#ifdef EXTENDED_SIM
	GraphicalInputsConnected = bConnect;
#endif /* EXTENDED_SIM */
}

